.include "macro.inc"

.section .sdata

/* Generated by spimdisasm 1.27.0 */

.align 2
dlabel D_80075580
/* 65D80 80075580 */ .asciz "HAK"
.align 2
.size D_80075580, . - D_80075580

.align 2
dlabel D_80075584
/* 65D84 80075584 */ .asciz "AMOS"
.align 2
.size D_80075584, . - D_80075584

.align 2
dlabel D_8007558C
/* 65D8C 8007558C */ .asciz "CRAY"
.align 2
.size D_8007558C, . - D_8007558C

.align 2
dlabel D_80075594
/* 65D94 80075594 */ .asciz "TUCO"
.align 2
.size D_80075594, . - D_80075594

.align 2
dlabel D_8007559C
/* 65D9C 8007559C */ .asciz "GOSNOLD"
.align 2
.size D_8007559C, . - D_8007559C
