.include "macro.inc"

.section .sdata

/* Generated by spimdisasm 1.27.0 */

dlabel D_80075264
/* 65A64 80075264 */ .byte 0x00
/* 65A65 80075265 */ .byte 0x02
/* 65A66 80075266 */ .byte 0x01
.size D_80075264, . - D_80075264

dlabel D_80075267
/* 65A67 80075267 */ .byte 0x02
.size D_80075267, . - D_80075267

dlabel D_80075268
/* 65A68 80075268 00070000 */ .word 0x00000700
.size D_80075268, . - D_80075268

dlabel D_8007526C
/* 65A6C 8007526C */ .byte 0x00
/* 65A6D 8007526D */ .byte 0x00
/* 65A6E 8007526E */ .byte 0x00
.size D_8007526C, . - D_8007526C

dlabel D_8007526F
/* 65A6F 8007526F */ .byte 0x00
.size D_8007526F, . - D_8007526F

dlabel D_80075270
/* 65A70 80075270 00000000 */ .word 0x00000000
.size D_80075270, . - D_80075270

dlabel D_80075274
/* 65A74 80075274 08101808 */ .word 0x08181008
.size D_80075274, . - D_80075274

dlabel D_80075278
/* 65A78 80075278 10080810 */ .word 0x10080810
.size D_80075278, . - D_80075278

dlabel D_8007527C
/* 65A7C 8007527C 08000000 */ .word 0x00000008
.size D_8007527C, . - D_8007527C

dlabel D_80075280
/* 65A80 80075280 5501AB02 */ .word 0x02AB0155
.size D_80075280, . - D_80075280

dlabel D_80075284
/* 65A84 80075284 AB025501 */ .word 0x015502AB
.size D_80075284, . - D_80075284

dlabel D_80075288
/* 65A88 80075288 A0A0004C */ .word 0x4C00A0A0
.size D_80075288, . - D_80075288

dlabel D_8007528C
/* 65A8C 8007528C C020204C */ .word 0x4C2020C0
.size D_8007528C, . - D_8007528C

.align 2
dlabel D_80075290
/* 65A90 80075290 */ .asciz "COPTERS"
.align 2
.size D_80075290, . - D_80075290

.align 2
dlabel D_80075298
/* 65A98 80075298 */ .asciz "BOATS"
.align 2
.size D_80075298, . - D_80075298

.align 2
dlabel D_800752A0
/* 65AA0 800752A0 */ .asciz "LIGHTS"
.align 2
.size D_800752A0, . - D_800752A0

.align 2
dlabel D_800752A8
/* 65AA8 800752A8 */ .asciz "RINGS"
.align 2
.size D_800752A8, . - D_800752A8

.align 2
dlabel D_800752B0
/* 65AB0 800752B0 */ .asciz "CHESTS"
.align 2
.size D_800752B0, . - D_800752B0

.align 2
dlabel D_800752B8
/* 65AB8 800752B8 */ .asciz "PLANES"
.align 2
.size D_800752B8, . - D_800752B8

.align 2
dlabel D_800752C0
/* 65AC0 800752C0 */ .asciz "ARCHES"
.align 2
.size D_800752C0, . - D_800752C0

.align 2
dlabel D_800752C8
/* 65AC8 800752C8 */ .asciz "BARRELS"
.align 2
.size D_800752C8, . - D_800752C8

dlabel g_GameOverTextRot
/* 65AD0 800752D0 */ .byte 0x6B
/* 65AD1 800752D1 */ .byte 0x60
/* 65AD2 800752D2 */ .byte 0x55
/* 65AD3 800752D3 */ .byte 0x4E
/* 65AD4 800752D4 */ .byte 0x32
/* 65AD5 800752D5 */ .byte 0x2B
/* 65AD6 800752D6 */ .byte 0x20
/* 65AD7 800752D7 */ .byte 0x15
.size g_GameOverTextRot, . - g_GameOverTextRot

dlabel g_GameOverRotY
/* 65AD8 800752D8 */ .short 0x00B0
.size g_GameOverRotY, . - g_GameOverRotY

dlabel g_GameOverRotZ
/* 65ADA 800752DA */ .short 0x0400
.size g_GameOverRotZ, . - g_GameOverRotZ

dlabel g_GameOverSkyboxRotY
/* 65ADC g_GameOverSkyboxRotY */ .short 0x0F50
.size g_GameOverSkyboxRotY, . - g_GameOverSkyboxRotY

dlabel g_GameOverSkyboxRotZ
/* 65ADE 800752DE */ .short 0x0884
.size g_GameOverSkyboxRotZ, . - g_GameOverSkyboxRotZ

dlabel g_GameOverLetterDisplayTicks
/* 65AE0 800752E0 */ .byte 0x00
/* 65AE1 800752E1 */ .byte 0x08
/* 65AE2 800752E2 */ .byte 0x10
/* 65AE3 800752E3 */ .byte 0x18
/* 65AE4 800752E4 */ .byte 0x48
/* 65AE5 800752E5 */ .byte 0x50
/* 65AE6 800752E6 */ .byte 0x58
/* 65AE7 800752E7 */ .byte 0x60
.size g_GameOverLetterDisplayTicks, . - g_GameOverLetterDisplayTicks
