.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.27.0 */

dlabel D_80010000
/* 800 80010000 44524147 */ .word 0x47415244
/* 804 80010004 4F4E2058 */ .word 0x58204E4F
/* 808 80010008 00000000 */ .word 0x00000000
.size D_80010000, . - D_80010000

.align 2
dlabel homeworldThighMasters
/* 80C 8001000C */ .asciz "THIGH MASTERS"
.align 2
.size homeworldThighMasters, . - homeworldThighMasters

.align 2
dlabel homeworldGnastysWorld
/* 81C 8001001C */ .asciz "GNASTY'S WORLD"
.align 2
.size homeworldGnastysWorld, . - homeworldGnastysWorld

.align 2
dlabel homeworldDreamWeavers
/* 82C 8001002C */ .asciz "DREAM WEAVERS"
.align 2
.size homeworldDreamWeavers, . - homeworldDreamWeavers

.align 2
dlabel homeworldBeastMakers
/* 83C 8001003C */ .asciz "BEAST MAKERS"
.align 2
.size homeworldBeastMakers, . - homeworldBeastMakers

.align 2
dlabel homeworldMagicCrafters
/* 84C 8001004C */ .asciz "MAGIC CRAFTERS"
.align 2
.size homeworldMagicCrafters, . - homeworldMagicCrafters

.align 2
dlabel homeworldPeaceKeepers
/* 85C 8001005C */ .asciz "PEACE KEEPERS"
.align 2
.size homeworldPeaceKeepers, . - homeworldPeaceKeepers

.align 2
dlabel homeworldArtisans
/* 86C 8001006C */ .asciz "ARTISANS"
.align 2
.align 2
dlabel returnHome
/* 878 80010078 */ .asciz "RETURN HOME"
.align 2

/* I HAD TO ASSIGN THESE LABELS MANUALLY */

.align 2
dlabel D_80010084
/* 884 80010084 */ .asciz "GNASTY'S LOOT"
.align 2

.align 2
dlabel D_80010094
/* 894 80010094 */ .asciz "GNASTY GNORC"
.align 2

.align 2
dlabel D_800100A4
/* 8A4 800100A4 */ .asciz "TWILIGHT HARBOR"
.align 2

.align 2
dlabel D_800100B4
/* 8B4 800100B4 */ .asciz "GNORC COVE"
.align 2

.align 2
dlabel D_800100C0
/* 8C0 800100C0 */ .asciz "GNORC GNEXUS"
.align 2

.align 2
dlabel D_800100D0
/* 8D0 800100D0 */ .asciz "ICY FLIGHT"
.align 2

.align 2
dlabel D_800100DC
/* 8DC 800100DC */ .asciz "HAUNTED TOWERS"
.align 2

.align 2
dlabel D_800100EC
/* 8EC 800100EC */ .asciz "LOFTY CASTLE"
.align 2

.align 2
dlabel D_800100FC
/* 8FC 800100FC */ .asciz "DARK PASSAGE"
.align 2

.align 2
dlabel D_8001010C
/* 90C 8001010C */ .asciz "WILD FLIGHT"
.align 2

.align 2
dlabel D_80010118
/* 918 80010118 */ .asciz "METALHEAD"
.align 2

.align 2
dlabel D_80010124
/* 924 80010124 */ .asciz "TREE TOPS"
.align 2

.align 2
dlabel D_80010130
/* 930 80010130 */ .asciz "MISTY BOG"
.align 2

.align 2
dlabel D_8001013C
/* 93C 8001013C */ .asciz "TERRACE VILLAGE"
.align 2

.align 2
dlabel D_8001014C
/* 94C 8001014C */ .asciz "CRYSTAL FLIGHT"
.align 2

.align 2
dlabel D_8001015C
/* 95C 8001015C */ .asciz "BLOWHARD"
.align 2
.align 2
dlabel D_80010168
/* 968 80010168 */ .asciz "WIZARD PEAK"
.align 2
.align 2
dlabel D_80010174
/* 974 80010174 */ .asciz "HIGH CAVES"
.align 2
.align 2
dlabel D_80010180
/* 980 80010180 */ .asciz "ALPINE RIDGE"
.align 2
.align 2
dlabel D_80010190
/* 990 80010190 */ .asciz "NIGHT FLIGHT"
.align 2
.align 2
dlabel D_800101A0
/* 9A0 800101A0 */ .asciz "DOCTOR SHEMP"
.align 2
.align 2
dlabel D_800101B0
/* 9B0 800101B0 */ .asciz "ICE CAVERN"
.align 2
.align 2
dlabel D_800101BC
/* 9BC 800101BC */ .asciz "CLIFF TOWN"
.align 2
.align 2
dlabel D_800101C8
/* 9C8 800101C8 */ .asciz "DRY CANYON"
.align 2
.align 2
dlabel D_800101D4
/* 9D4 800101D4 */ .asciz "SUNNY FLIGHT"
.align 2
.align 2
dlabel D_800101E4
/* 9E4 800101E4 */ .asciz "TOWN SQUARE"
.align 2
.align 2
dlabel D_800101F0
/* 9F0 800101F0 */ .asciz "DARK HOLLOW"
.align 2
.align 2
dlabel D_800101FC
/* 9FC 800101FC */ .asciz "STONE HILL"
.align 2
.size homeworldArtisans, . - homeworldArtisans
