.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.27.0 */

dlabel g_OverlaySpacePointer
/* 1BA0 800113A0 38AA0780 */ .word main_BSS_END
.size g_OverlaySpacePointer, . - g_OverlaySpacePointer
