.include "macro.inc"

.section .sbss

/* Generated by spimdisasm 1.27.0 */

dlabel D_80075640
/* 65E40 80075640 */ .space 0x08

dlabel D_80075648
/* 65E48 80075648 */ .space 0x10

dlabel D_80075658
/* 65E58 80075658 */ .space 0x10
