.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 2
dlabel D_80010BA8
/* 13A8 80010BA8 */ .asciz "HI SPYRO,"
.align 2
.size D_80010BA8, . - D_80010BA8

.align 2
dlabel D_80010BB4
/* 13B4 80010BB4 */ .asciz "SAVE GAME"
.align 2
.size D_80010BB4, . - D_80010BB4

.align 2
dlabel D_80010BC0
/* 13C0 80010BC0 */ .asciz "REPLAY DRAGON"
.align 2
.size D_80010BC0, . - D_80010BC0

.align 2
dlabel D_80010BD0
/* 13D0 80010BD0 */ .asciz "NO SAVE FILE"
.align 2
.size D_80010BD0, . - D_80010BD0

.align 2
dlabel D_80010BE0
/* 13E0 80010BE0 */ .asciz "PLEASE RESTART WITH"
.align 2
.size D_80010BE0, . - D_80010BE0

.align 2
dlabel D_80010BF4
/* 13F4 80010BF4 */ .asciz "A MEMORY CARD TO"
.align 2
.size D_80010BF4, . - D_80010BF4

.align 2
dlabel D_80010C08
/* 1408 80010C08 */ .asciz "ENABLE GAME SAVES."
.align 2
.size D_80010C08, . - D_80010C08

.align 2
dlabel D_80010C1C
/* 141C 80010C1C */ .asciz "SAVING..."
.align 2
.size D_80010C1C, . - D_80010C1C

.align 2
dlabel D_80010C28
/* 1428 80010C28 */ .asciz "NO MEMORY CARD"
.align 2
.size D_80010C28, . - D_80010C28

.align 2
dlabel D_80010C38
/* 1438 80010C38 */ .asciz "PLEASE INSERT THE"
.align 2
.size D_80010C38, . - D_80010C38

.align 2
dlabel D_80010C4C
/* 144C 80010C4C */ .asciz "MEMORY CARD WITH"
.align 2
.size D_80010C4C, . - D_80010C4C

.align 2
dlabel D_80010C60
/* 1460 80010C60 */ .asciz "THIS GAME SAVE FILE"
.align 2
.size D_80010C60, . - D_80010C60

.align 2
dlabel D_80010C74
/* 1474 80010C74 */ .asciz "SAVE ERROR"
.align 2
.size D_80010C74, . - D_80010C74

.align 2
dlabel D_80010C80
/* 1480 80010C80 */ .asciz "PLEASE CHECK THAT"
.align 2
.size D_80010C80, . - D_80010C80

.align 2
dlabel D_80010C94
/* 1494 80010C94 */ .asciz "THE MEMORY CARD"
.align 2
.size D_80010C94, . - D_80010C94

.align 2
dlabel D_80010CA4
/* 14A4 80010CA4 */ .asciz "IS STILL IN PLACE."
.align 2
.size D_80010CA4, . - D_80010CA4

.align 2
dlabel D_80010CB8
/* 14B8 80010CB8 */ .asciz "SAVE FAILED"
.align 2
.size D_80010CB8, . - D_80010CB8

.align 2
dlabel D_80010CC4
/* 14C4 80010CC4 */ .asciz "GAME SAVED"
.align 2
.size D_80010CC4, . - D_80010CC4
.section .rodata.jtbl
.align 3
dlabel jtbl_80010D58
/* 1558 80010D58 18D80180 */ .word .L8001D818
/* 155C 80010D5C A8D90180 */ .word .L8001D9A8
/* 1560 80010D60 00DB0180 */ .word .L8001DB00
/* 1564 80010D64 A0DB0180 */ .word .L8001DBA0
/* 1568 80010D68 A0DB0180 */ .word .L8001DBA0
/* 156C 80010D6C 38DD0180 */ .word .L8001DD38
/* 1570 80010D70 A4DE0180 */ .word .L8001DEA4
/* 1574 80010D74 E0DF0180 */ .word .L8001DFE0
.size jtbl_80010D58, . - jtbl_80010D58


.section .text
/* Generated by spimdisasm 1.27.0 */

glabel func_8001D718
/* DF18 8001D718 0780033C */  lui        $v1, %hi(D_800756FC)
/* DF1C 8001D71C FC56638C */  lw         $v1, %lo(D_800756FC)($v1)
/* DF20 8001D720 0880023C */  lui        $v0, %hi(D_800785F0)
/* DF24 8001D724 F085428C */  lw         $v0, %lo(D_800785F0)($v0)
/* DF28 8001D728 98FFBD27 */  addiu      $sp, $sp, -0x68
/* DF2C 8001D72C 6400BFAF */  sw         $ra, 0x64($sp)
/* DF30 8001D730 6000B4AF */  sw         $s4, 0x60($sp)
/* DF34 8001D734 5C00B3AF */  sw         $s3, 0x5C($sp)
/* DF38 8001D738 5800B2AF */  sw         $s2, 0x58($sp)
/* DF3C 8001D73C 5400B1AF */  sw         $s1, 0x54($sp)
/* DF40 8001D740 0A006214 */  bne        $v1, $v0, .L8001D76C
/* DF44 8001D744 5000B0AF */   sw        $s0, 0x50($sp)
/* DF48 8001D748 0100033C */  lui        $v1, (0x1BA00 >> 16)
/* DF4C 8001D74C 0780023C */  lui        $v0, %hi(D_800757B0)
/* DF50 8001D750 B057428C */  lw         $v0, %lo(D_800757B0)($v0)
/* DF54 8001D754 00BA6334 */  ori        $v1, $v1, (0x1BA00 & 0xFFFF)
/* DF58 8001D758 21104300 */  addu       $v0, $v0, $v1
/* DF5C 8001D75C 0780013C */  lui        $at, %hi(D_800756FC)
/* DF60 8001D760 FC5622AC */  sw         $v0, %lo(D_800756FC)($at)
/* DF64 8001D764 0780013C */  lui        $at, %hi(g_HudMobys)
/* DF68 8001D768 105722AC */  sw         $v0, %lo(g_HudMobys)($at)
.L8001D76C:
/* DF6C 8001D76C 0880103C */  lui        $s0, %hi(D_80078D00)
/* DF70 8001D770 008D108E */  lw         $s0, %lo(D_80078D00)($s0)
/* DF74 8001D774 01000224 */  addiu      $v0, $zero, 0x1
/* DF78 8001D778 64020216 */  bne        $s0, $v0, .L8001E10C
/* DF7C 8001D77C 00000000 */   nop
/* DF80 8001D780 0880023C */  lui        $v0, %hi(D_80078D0C)
/* DF84 8001D784 0C8D428C */  lw         $v0, %lo(D_80078D0C)($v0)
/* DF88 8001D788 0880033C */  lui        $v1, %hi(D_80078D10)
/* DF8C 8001D78C 108D638C */  lw         $v1, %lo(D_80078D10)($v1)
/* DF90 8001D790 C0100200 */  sll        $v0, $v0, 3
/* DF94 8001D794 0780013C */  lui        $at, %hi(D_8006F354)
/* DF98 8001D798 21082200 */  addu       $at, $at, $v0
/* DF9C 8001D79C 54F32684 */  lh         $a2, %lo(D_8006F354)($at)
/* DFA0 8001D7A0 0780013C */  lui        $at, %hi(D_8006F356)
/* DFA4 8001D7A4 21082200 */  addu       $at, $at, $v0
/* DFA8 8001D7A8 56F32784 */  lh         $a3, %lo(D_8006F356)($at)
/* DFAC 8001D7AC 0780013C */  lui        $at, %hi(D_8006F350)
/* DFB0 8001D7B0 21082200 */  addu       $at, $at, $v0
/* DFB4 8001D7B4 50F32484 */  lh         $a0, %lo(D_8006F350)($at)
/* DFB8 8001D7B8 0780013C */  lui        $at, %hi(D_8006F352)
/* DFBC 8001D7BC 21082200 */  addu       $at, $at, $v0
/* DFC0 8001D7C0 52F32584 */  lh         $a1, %lo(D_8006F352)($at)
/* DFC4 8001D7C4 21206400 */  addu       $a0, $v1, $a0
/* DFC8 8001D7C8 8361000C */  jal        func_8001860C
/* DFCC 8001D7CC 21286500 */   addu      $a1, $v1, $a1
/* DFD0 8001D7D0 0880033C */  lui        $v1, %hi(D_80078D0C)
/* DFD4 8001D7D4 0C8D638C */  lw         $v1, %lo(D_80078D0C)($v1)
/* DFD8 8001D7D8 10000224 */  addiu      $v0, $zero, 0x10
/* DFDC 8001D7DC 2800A2AF */  sw         $v0, 0x28($sp)
/* DFE0 8001D7E0 00140224 */  addiu      $v0, $zero, 0x1400
/* DFE4 8001D7E4 3000A2AF */  sw         $v0, 0x30($sp)
/* DFE8 8001D7E8 00110224 */  addiu      $v0, $zero, 0x1100
/* DFEC 8001D7EC 2C00B0AF */  sw         $s0, 0x2C($sp)
/* DFF0 8001D7F0 2000A2AF */  sw         $v0, 0x20($sp)
/* DFF4 8001D7F4 0800622C */  sltiu      $v0, $v1, 0x8
/* DFF8 8001D7F8 1F024010 */  beqz       $v0, .L8001E078
/* DFFC 8001D7FC 80100300 */   sll       $v0, $v1, 2
/* E000 8001D800 0180013C */  lui        $at, %hi(jtbl_80010D58)
/* E004 8001D804 21082200 */  addu       $at, $at, $v0
/* E008 8001D808 580D228C */  lw         $v0, %lo(jtbl_80010D58)($at)
/* E00C 8001D80C 00000000 */  nop
/* E010 8001D810 08004000 */  jr         $v0
/* E014 8001D814 00000000 */   nop
.L8001D818:
/* E018 8001D818 0180043C */  lui        $a0, %hi(D_80010BA8)
/* E01C 8001D81C A80B8424 */  addiu      $a0, $a0, %lo(D_80010BA8)
/* E020 8001D820 1800A527 */  addiu      $a1, $sp, 0x18
/* E024 8001D824 2800B227 */  addiu      $s2, $sp, 0x28
/* E028 8001D828 21304002 */  addu       $a2, $s2, $zero
/* E02C 8001D82C 12000724 */  addiu      $a3, $zero, 0x12
/* E030 8001D830 0880103C */  lui        $s0, %hi(D_80078D10)
/* E034 8001D834 108D1026 */  addiu      $s0, $s0, %lo(D_80078D10)
/* E038 8001D838 32000324 */  addiu      $v1, $zero, 0x32
/* E03C 8001D83C 0000028E */  lw         $v0, 0x0($s0)
/* E040 8001D840 0B001424 */  addiu      $s4, $zero, 0xB
/* E044 8001D844 1C00A3AF */  sw         $v1, 0x1C($sp)
/* E048 8001D848 40004224 */  addiu      $v0, $v0, 0x40
/* E04C 8001D84C 1800A2AF */  sw         $v0, 0x18($sp)
/* E050 8001D850 6B60000C */  jal        func_800181AC
/* E054 8001D854 1000B4AF */   sw        $s4, 0x10($sp)
/* E058 8001D858 0180043C */  lui        $a0, %hi(D_80010BB4)
/* E05C 8001D85C B40B8424 */  addiu      $a0, $a0, %lo(D_80010BB4)
/* E060 8001D860 1800A527 */  addiu      $a1, $sp, 0x18
/* E064 8001D864 21304002 */  addu       $a2, $s2, $zero
/* E068 8001D868 12000724 */  addiu      $a3, $zero, 0x12
/* E06C 8001D86C 1C00A28F */  lw         $v0, 0x1C($sp)
/* E070 8001D870 0000038E */  lw         $v1, 0x0($s0)
/* E074 8001D874 18004224 */  addiu      $v0, $v0, 0x18
/* E078 8001D878 4C006324 */  addiu      $v1, $v1, 0x4C
/* E07C 8001D87C 1C00A2AF */  sw         $v0, 0x1C($sp)
/* E080 8001D880 1800A3AF */  sw         $v1, 0x18($sp)
/* E084 8001D884 6B60000C */  jal        func_800181AC
/* E088 8001D888 1000B4AF */   sw        $s4, 0x10($sp)
/* E08C 8001D88C 1C00A28F */  lw         $v0, 0x1C($sp)
/* E090 8001D890 F8FF038E */  lw         $v1, -0x8($s0)
/* E094 8001D894 13004224 */  addiu      $v0, $v0, 0x13
/* E098 8001D898 04006014 */  bnez       $v1, .L8001D8AC
/* E09C 8001D89C 1C00A2AF */   sw        $v0, 0x1C($sp)
/* E0A0 8001D8A0 0780113C */  lui        $s1, %hi(g_HudMobys)
/* E0A4 8001D8A4 1057318E */  lw         $s1, %lo(g_HudMobys)($s1)
/* E0A8 8001D8A8 08001324 */  addiu      $s3, $zero, 0x8
.L8001D8AC:
/* E0AC 8001D8AC 0180043C */  lui        $a0, %hi(D_80010BC0)
/* E0B0 8001D8B0 C00B8424 */  addiu      $a0, $a0, %lo(D_80010BC0)
/* E0B4 8001D8B4 1800A527 */  addiu      $a1, $sp, 0x18
/* E0B8 8001D8B8 21304002 */  addu       $a2, $s2, $zero
/* E0BC 8001D8BC 0000028E */  lw         $v0, 0x0($s0)
/* E0C0 8001D8C0 12000724 */  addiu      $a3, $zero, 0x12
/* E0C4 8001D8C4 4C004224 */  addiu      $v0, $v0, 0x4C
/* E0C8 8001D8C8 1800A2AF */  sw         $v0, 0x18($sp)
/* E0CC 8001D8CC 6B60000C */  jal        func_800181AC
/* E0D0 8001D8D0 1000B4AF */   sw        $s4, 0x10($sp)
/* E0D4 8001D8D4 1C00A28F */  lw         $v0, 0x1C($sp)
/* E0D8 8001D8D8 00000000 */  nop
/* E0DC 8001D8DC 13004224 */  addiu      $v0, $v0, 0x13
/* E0E0 8001D8E0 1C00A2AF */  sw         $v0, 0x1C($sp)
/* E0E4 8001D8E4 F8FF038E */  lw         $v1, -0x8($s0)
/* E0E8 8001D8E8 01000224 */  addiu      $v0, $zero, 0x1
/* E0EC 8001D8EC 04006214 */  bne        $v1, $v0, .L8001D900
/* E0F0 8001D8F0 00000000 */   nop
/* E0F4 8001D8F4 0780113C */  lui        $s1, %hi(g_HudMobys)
/* E0F8 8001D8F8 1057318E */  lw         $s1, %lo(g_HudMobys)($s1)
/* E0FC 8001D8FC 0C001324 */  addiu      $s3, $zero, 0xC
.L8001D900:
/* E100 8001D900 0180043C */  lui        $a0, %hi(D_80010B6C)
/* E104 8001D904 6C0B8424 */  addiu      $a0, $a0, %lo(D_80010B6C)
/* E108 8001D908 1800A527 */  addiu      $a1, $sp, 0x18
/* E10C 8001D90C 21304002 */  addu       $a2, $s2, $zero
/* E110 8001D910 0000028E */  lw         $v0, 0x0($s0)
/* E114 8001D914 12000724 */  addiu      $a3, $zero, 0x12
/* E118 8001D918 4C004224 */  addiu      $v0, $v0, 0x4C
/* E11C 8001D91C 1800A2AF */  sw         $v0, 0x18($sp)
/* E120 8001D920 6B60000C */  jal        func_800181AC
/* E124 8001D924 1000B4AF */   sw        $s4, 0x10($sp)
/* E128 8001D928 F8FF038E */  lw         $v1, -0x8($s0)
/* E12C 8001D92C 02000224 */  addiu      $v0, $zero, 0x2
/* E130 8001D930 05006214 */  bne        $v1, $v0, .L8001D948
/* E134 8001D934 FF006632 */   andi      $a2, $s3, 0xFF
/* E138 8001D938 0780113C */  lui        $s1, %hi(g_HudMobys)
/* E13C 8001D93C 1057318E */  lw         $s1, %lo(g_HudMobys)($s1)
/* E140 8001D940 08001324 */  addiu      $s3, $zero, 0x8
/* E144 8001D944 FF006632 */  andi       $a2, $s3, 0xFF
.L8001D948:
/* E148 8001D948 CB01C018 */  blez       $a2, .L8001E078
/* E14C 8001D94C 21200000 */   addu      $a0, $zero, $zero
/* E150 8001D950 F4FF0826 */  addiu      $t0, $s0, -0xC
/* E154 8001D954 0780073C */  lui        $a3, %hi(D_8006CC78)
/* E158 8001D958 78CCE724 */  addiu      $a3, $a3, %lo(D_8006CC78)
/* E15C 8001D95C 21280000 */  addu       $a1, $zero, $zero
.L8001D960:
/* E160 8001D960 0000028D */  lw         $v0, 0x0($t0)
/* E164 8001D964 01008424 */  addiu      $a0, $a0, 0x1
/* E168 8001D968 80100200 */  sll        $v0, $v0, 2
/* E16C 8001D96C 21104500 */  addu       $v0, $v0, $a1
/* E170 8001D970 FF004230 */  andi       $v0, $v0, 0xFF
/* E174 8001D974 40100200 */  sll        $v0, $v0, 1
/* E178 8001D978 21104700 */  addu       $v0, $v0, $a3
/* E17C 8001D97C 00004384 */  lh         $v1, 0x0($v0)
/* E180 8001D980 0C00A524 */  addiu      $a1, $a1, 0xC
/* E184 8001D984 40100300 */  sll        $v0, $v1, 1
/* E188 8001D988 21104300 */  addu       $v0, $v0, $v1
/* E18C 8001D98C 43120200 */  sra        $v0, $v0, 9
/* E190 8001D990 460022A2 */  sb         $v0, 0x46($s1)
/* E194 8001D994 2A108600 */  slt        $v0, $a0, $a2
/* E198 8001D998 F1FF4014 */  bnez       $v0, .L8001D960
/* E19C 8001D99C 58003126 */   addiu     $s1, $s1, 0x58
/* E1A0 8001D9A0 1E780008 */  j          .L8001E078
/* E1A4 8001D9A4 00000000 */   nop
.L8001D9A8:
/* E1A8 8001D9A8 0180043C */  lui        $a0, %hi(D_80010BD0)
/* E1AC 8001D9AC D00B8424 */  addiu      $a0, $a0, %lo(D_80010BD0)
/* E1B0 8001D9B0 1800A527 */  addiu      $a1, $sp, 0x18
/* E1B4 8001D9B4 2800A627 */  addiu      $a2, $sp, 0x28
/* E1B8 8001D9B8 12000724 */  addiu      $a3, $zero, 0x12
/* E1BC 8001D9BC 0880103C */  lui        $s0, %hi(D_80078D10)
/* E1C0 8001D9C0 108D1026 */  addiu      $s0, $s0, %lo(D_80078D10)
/* E1C4 8001D9C4 0000028E */  lw         $v0, 0x0($s0)
/* E1C8 8001D9C8 32000324 */  addiu      $v1, $zero, 0x32
/* E1CC 8001D9CC 1C00A3AF */  sw         $v1, 0x1C($sp)
/* E1D0 8001D9D0 52004224 */  addiu      $v0, $v0, 0x52
/* E1D4 8001D9D4 1800A2AF */  sw         $v0, 0x18($sp)
/* E1D8 8001D9D8 0B000224 */  addiu      $v0, $zero, 0xB
/* E1DC 8001D9DC 6B60000C */  jal        func_800181AC
/* E1E0 8001D9E0 1000A2AF */   sw        $v0, 0x10($sp)
/* E1E4 8001D9E4 21200000 */  addu       $a0, $zero, $zero
/* E1E8 8001D9E8 F4FF1026 */  addiu      $s0, $s0, -0xC
/* E1EC 8001D9EC 0780063C */  lui        $a2, %hi(D_8006CC78)
/* E1F0 8001D9F0 78CCC624 */  addiu      $a2, $a2, %lo(D_8006CC78)
/* E1F4 8001D9F4 21280000 */  addu       $a1, $zero, $zero
/* E1F8 8001D9F8 1C00A28F */  lw         $v0, 0x1C($sp)
/* E1FC 8001D9FC 0780113C */  lui        $s1, %hi(g_HudMobys)
/* E200 8001DA00 1057318E */  lw         $s1, %lo(g_HudMobys)($s1)
/* E204 8001DA04 1A004224 */  addiu      $v0, $v0, 0x1A
/* E208 8001DA08 1C00A2AF */  sw         $v0, 0x1C($sp)
.L8001DA0C:
/* E20C 8001DA0C 0000028E */  lw         $v0, 0x0($s0)
/* E210 8001DA10 01008424 */  addiu      $a0, $a0, 0x1
/* E214 8001DA14 80100200 */  sll        $v0, $v0, 2
/* E218 8001DA18 21104500 */  addu       $v0, $v0, $a1
/* E21C 8001DA1C FF004230 */  andi       $v0, $v0, 0xFF
/* E220 8001DA20 40100200 */  sll        $v0, $v0, 1
/* E224 8001DA24 21104600 */  addu       $v0, $v0, $a2
/* E228 8001DA28 00004384 */  lh         $v1, 0x0($v0)
/* E22C 8001DA2C 0C00A524 */  addiu      $a1, $a1, 0xC
/* E230 8001DA30 40100300 */  sll        $v0, $v1, 1
/* E234 8001DA34 21104300 */  addu       $v0, $v0, $v1
/* E238 8001DA38 43120200 */  sra        $v0, $v0, 9
/* E23C 8001DA3C 460022A2 */  sb         $v0, 0x46($s1)
/* E240 8001DA40 0A008228 */  slti       $v0, $a0, 0xA
/* E244 8001DA44 F1FF4014 */  bnez       $v0, .L8001DA0C
/* E248 8001DA48 58003126 */   addiu     $s1, $s1, 0x58
/* E24C 8001DA4C 0180043C */  lui        $a0, %hi(D_80010BE0)
/* E250 8001DA50 E00B8424 */  addiu      $a0, $a0, %lo(D_80010BE0)
/* E254 8001DA54 1800A527 */  addiu      $a1, $sp, 0x18
/* E258 8001DA58 2800B227 */  addiu      $s2, $sp, 0x28
/* E25C 8001DA5C 21304002 */  addu       $a2, $s2, $zero
/* E260 8001DA60 10000724 */  addiu      $a3, $zero, 0x10
/* E264 8001DA64 0E000224 */  addiu      $v0, $zero, 0xE
/* E268 8001DA68 2800A2AF */  sw         $v0, 0x28($sp)
/* E26C 8001DA6C 01000224 */  addiu      $v0, $zero, 0x1
/* E270 8001DA70 2C00A2AF */  sw         $v0, 0x2C($sp)
/* E274 8001DA74 00160224 */  addiu      $v0, $zero, 0x1600
/* E278 8001DA78 0880113C */  lui        $s1, %hi(D_80078D10)
/* E27C 8001DA7C 108D3126 */  addiu      $s1, $s1, %lo(D_80078D10)
/* E280 8001DA80 00140324 */  addiu      $v1, $zero, 0x1400
/* E284 8001DA84 3000A2AF */  sw         $v0, 0x30($sp)
/* E288 8001DA88 0000228E */  lw         $v0, 0x0($s1)
/* E28C 8001DA8C 0B001024 */  addiu      $s0, $zero, 0xB
/* E290 8001DA90 2000A3AF */  sw         $v1, 0x20($sp)
/* E294 8001DA94 2D004224 */  addiu      $v0, $v0, 0x2D
/* E298 8001DA98 1800A2AF */  sw         $v0, 0x18($sp)
/* E29C 8001DA9C 6B60000C */  jal        func_800181AC
/* E2A0 8001DAA0 1000B0AF */   sw        $s0, 0x10($sp)
/* E2A4 8001DAA4 0180043C */  lui        $a0, %hi(D_80010BF4)
/* E2A8 8001DAA8 F40B8424 */  addiu      $a0, $a0, %lo(D_80010BF4)
/* E2AC 8001DAAC 1800A527 */  addiu      $a1, $sp, 0x18
/* E2B0 8001DAB0 21304002 */  addu       $a2, $s2, $zero
/* E2B4 8001DAB4 10000724 */  addiu      $a3, $zero, 0x10
/* E2B8 8001DAB8 1C00A28F */  lw         $v0, 0x1C($sp)
/* E2BC 8001DABC 0000238E */  lw         $v1, 0x0($s1)
/* E2C0 8001DAC0 11004224 */  addiu      $v0, $v0, 0x11
/* E2C4 8001DAC4 43006324 */  addiu      $v1, $v1, 0x43
/* E2C8 8001DAC8 1C00A2AF */  sw         $v0, 0x1C($sp)
/* E2CC 8001DACC 1800A3AF */  sw         $v1, 0x18($sp)
/* E2D0 8001DAD0 6B60000C */  jal        func_800181AC
/* E2D4 8001DAD4 1000B0AF */   sw        $s0, 0x10($sp)
/* E2D8 8001DAD8 0180043C */  lui        $a0, %hi(D_80010C08)
/* E2DC 8001DADC 080C8424 */  addiu      $a0, $a0, %lo(D_80010C08)
/* E2E0 8001DAE0 1800A527 */  addiu      $a1, $sp, 0x18
/* E2E4 8001DAE4 21304002 */  addu       $a2, $s2, $zero
/* E2E8 8001DAE8 10000724 */  addiu      $a3, $zero, 0x10
/* E2EC 8001DAEC 1C00A28F */  lw         $v0, 0x1C($sp)
/* E2F0 8001DAF0 0000238E */  lw         $v1, 0x0($s1)
/* E2F4 8001DAF4 11004224 */  addiu      $v0, $v0, 0x11
/* E2F8 8001DAF8 A3770008 */  j          .L8001DE8C
/* E2FC 8001DAFC 38006324 */   addiu     $v1, $v1, 0x38
.L8001DB00:
/* E300 8001DB00 0180043C */  lui        $a0, %hi(D_80010C1C)
/* E304 8001DB04 1C0C8424 */  addiu      $a0, $a0, %lo(D_80010C1C)
/* E308 8001DB08 1800A527 */  addiu      $a1, $sp, 0x18
/* E30C 8001DB0C 2800A627 */  addiu      $a2, $sp, 0x28
/* E310 8001DB10 12000724 */  addiu      $a3, $zero, 0x12
/* E314 8001DB14 0880103C */  lui        $s0, %hi(D_80078D10)
/* E318 8001DB18 108D1026 */  addiu      $s0, $s0, %lo(D_80078D10)
/* E31C 8001DB1C 0000028E */  lw         $v0, 0x0($s0)
/* E320 8001DB20 52000324 */  addiu      $v1, $zero, 0x52
/* E324 8001DB24 1C00A3AF */  sw         $v1, 0x1C($sp)
/* E328 8001DB28 6A004224 */  addiu      $v0, $v0, 0x6A
/* E32C 8001DB2C 1800A2AF */  sw         $v0, 0x18($sp)
/* E330 8001DB30 0B000224 */  addiu      $v0, $zero, 0xB
/* E334 8001DB34 6B60000C */  jal        func_800181AC
/* E338 8001DB38 1000A2AF */   sw        $v0, 0x10($sp)
/* E33C 8001DB3C 21200000 */  addu       $a0, $zero, $zero
/* E340 8001DB40 F4FF1026 */  addiu      $s0, $s0, -0xC
/* E344 8001DB44 0780063C */  lui        $a2, %hi(D_8006CC78)
/* E348 8001DB48 78CCC624 */  addiu      $a2, $a2, %lo(D_8006CC78)
/* E34C 8001DB4C 21280000 */  addu       $a1, $zero, $zero
/* E350 8001DB50 0780113C */  lui        $s1, %hi(g_HudMobys)
/* E354 8001DB54 1057318E */  lw         $s1, %lo(g_HudMobys)($s1)
.L8001DB58:
/* E358 8001DB58 0000028E */  lw         $v0, 0x0($s0)
/* E35C 8001DB5C 01008424 */  addiu      $a0, $a0, 0x1
/* E360 8001DB60 80100200 */  sll        $v0, $v0, 2
/* E364 8001DB64 21104500 */  addu       $v0, $v0, $a1
/* E368 8001DB68 FF004230 */  andi       $v0, $v0, 0xFF
/* E36C 8001DB6C 40100200 */  sll        $v0, $v0, 1
/* E370 8001DB70 21104600 */  addu       $v0, $v0, $a2
/* E374 8001DB74 00004384 */  lh         $v1, 0x0($v0)
/* E378 8001DB78 0C00A524 */  addiu      $a1, $a1, 0xC
/* E37C 8001DB7C 40100300 */  sll        $v0, $v1, 1
/* E380 8001DB80 21104300 */  addu       $v0, $v0, $v1
/* E384 8001DB84 43120200 */  sra        $v0, $v0, 9
/* E388 8001DB88 460022A2 */  sb         $v0, 0x46($s1)
/* E38C 8001DB8C 09008228 */  slti       $v0, $a0, 0x9
/* E390 8001DB90 F1FF4014 */  bnez       $v0, .L8001DB58
/* E394 8001DB94 58003126 */   addiu     $s1, $s1, 0x58
/* E398 8001DB98 1E780008 */  j          .L8001E078
/* E39C 8001DB9C 00000000 */   nop
.L8001DBA0:
/* E3A0 8001DBA0 0880033C */  lui        $v1, %hi(D_80078D0C)
/* E3A4 8001DBA4 0C8D638C */  lw         $v1, %lo(D_80078D0C)($v1)
/* E3A8 8001DBA8 32000224 */  addiu      $v0, $zero, 0x32
/* E3AC 8001DBAC 1C00A2AF */  sw         $v0, 0x1C($sp)
/* E3B0 8001DBB0 03000224 */  addiu      $v0, $zero, 0x3
/* E3B4 8001DBB4 0A006214 */  bne        $v1, $v0, .L8001DBE0
/* E3B8 8001DBB8 1800A527 */   addiu     $a1, $sp, 0x18
/* E3BC 8001DBBC 0180043C */  lui        $a0, %hi(D_80010C28)
/* E3C0 8001DBC0 280C8424 */  addiu      $a0, $a0, %lo(D_80010C28)
/* E3C4 8001DBC4 2800A627 */  addiu      $a2, $sp, 0x28
/* E3C8 8001DBC8 12000724 */  addiu      $a3, $zero, 0x12
/* E3CC 8001DBCC 0880023C */  lui        $v0, %hi(D_80078D10)
/* E3D0 8001DBD0 108D428C */  lw         $v0, %lo(D_80078D10)($v0)
/* E3D4 8001DBD4 0C001324 */  addiu      $s3, $zero, 0xC
/* E3D8 8001DBD8 00770008 */  j          .L8001DC00
/* E3DC 8001DBDC 42004224 */   addiu     $v0, $v0, 0x42
.L8001DBE0:
/* E3E0 8001DBE0 0180043C */  lui        $a0, %hi(D_80010BD0)
/* E3E4 8001DBE4 D00B8424 */  addiu      $a0, $a0, %lo(D_80010BD0)
/* E3E8 8001DBE8 2800A627 */  addiu      $a2, $sp, 0x28
/* E3EC 8001DBEC 12000724 */  addiu      $a3, $zero, 0x12
/* E3F0 8001DBF0 0880023C */  lui        $v0, %hi(D_80078D10)
/* E3F4 8001DBF4 108D428C */  lw         $v0, %lo(D_80078D10)($v0)
/* E3F8 8001DBF8 0A001324 */  addiu      $s3, $zero, 0xA
/* E3FC 8001DBFC 54004224 */  addiu      $v0, $v0, 0x54
.L8001DC00:
/* E400 8001DC00 1800A2AF */  sw         $v0, 0x18($sp)
/* E404 8001DC04 0B000224 */  addiu      $v0, $zero, 0xB
/* E408 8001DC08 6B60000C */  jal        func_800181AC
/* E40C 8001DC0C 1000A2AF */   sw        $v0, 0x10($sp)
/* E410 8001DC10 21200000 */  addu       $a0, $zero, $zero
/* E414 8001DC14 FF006632 */  andi       $a2, $s3, 0xFF
/* E418 8001DC18 1C00A28F */  lw         $v0, 0x1C($sp)
/* E41C 8001DC1C 0780113C */  lui        $s1, %hi(g_HudMobys)
/* E420 8001DC20 1057318E */  lw         $s1, %lo(g_HudMobys)($s1)
/* E424 8001DC24 1A004224 */  addiu      $v0, $v0, 0x1A
/* E428 8001DC28 1600C018 */  blez       $a2, .L8001DC84
/* E42C 8001DC2C 1C00A2AF */   sw        $v0, 0x1C($sp)
/* E430 8001DC30 0880083C */  lui        $t0, %hi(D_80078D04)
/* E434 8001DC34 048D0825 */  addiu      $t0, $t0, %lo(D_80078D04)
/* E438 8001DC38 0780073C */  lui        $a3, %hi(D_8006CC78)
/* E43C 8001DC3C 78CCE724 */  addiu      $a3, $a3, %lo(D_8006CC78)
/* E440 8001DC40 21280000 */  addu       $a1, $zero, $zero
.L8001DC44:
/* E444 8001DC44 0000028D */  lw         $v0, 0x0($t0)
/* E448 8001DC48 01008424 */  addiu      $a0, $a0, 0x1
/* E44C 8001DC4C 80100200 */  sll        $v0, $v0, 2
/* E450 8001DC50 21104500 */  addu       $v0, $v0, $a1
/* E454 8001DC54 FF004230 */  andi       $v0, $v0, 0xFF
/* E458 8001DC58 40100200 */  sll        $v0, $v0, 1
/* E45C 8001DC5C 21104700 */  addu       $v0, $v0, $a3
/* E460 8001DC60 00004384 */  lh         $v1, 0x0($v0)
/* E464 8001DC64 0C00A524 */  addiu      $a1, $a1, 0xC
/* E468 8001DC68 40100300 */  sll        $v0, $v1, 1
/* E46C 8001DC6C 21104300 */  addu       $v0, $v0, $v1
/* E470 8001DC70 43120200 */  sra        $v0, $v0, 9
/* E474 8001DC74 460022A2 */  sb         $v0, 0x46($s1)
/* E478 8001DC78 2A108600 */  slt        $v0, $a0, $a2
/* E47C 8001DC7C F1FF4014 */  bnez       $v0, .L8001DC44
/* E480 8001DC80 58003126 */   addiu     $s1, $s1, 0x58
.L8001DC84:
/* E484 8001DC84 0180043C */  lui        $a0, %hi(D_80010C38)
/* E488 8001DC88 380C8424 */  addiu      $a0, $a0, %lo(D_80010C38)
/* E48C 8001DC8C 1800A527 */  addiu      $a1, $sp, 0x18
/* E490 8001DC90 2800B227 */  addiu      $s2, $sp, 0x28
/* E494 8001DC94 21304002 */  addu       $a2, $s2, $zero
/* E498 8001DC98 10000724 */  addiu      $a3, $zero, 0x10
/* E49C 8001DC9C 0E000224 */  addiu      $v0, $zero, 0xE
/* E4A0 8001DCA0 2800A2AF */  sw         $v0, 0x28($sp)
/* E4A4 8001DCA4 01000224 */  addiu      $v0, $zero, 0x1
/* E4A8 8001DCA8 2C00A2AF */  sw         $v0, 0x2C($sp)
/* E4AC 8001DCAC 00160224 */  addiu      $v0, $zero, 0x1600
/* E4B0 8001DCB0 0880113C */  lui        $s1, %hi(D_80078D10)
/* E4B4 8001DCB4 108D3126 */  addiu      $s1, $s1, %lo(D_80078D10)
/* E4B8 8001DCB8 00140324 */  addiu      $v1, $zero, 0x1400
/* E4BC 8001DCBC 3000A2AF */  sw         $v0, 0x30($sp)
/* E4C0 8001DCC0 0000228E */  lw         $v0, 0x0($s1)
/* E4C4 8001DCC4 0B001024 */  addiu      $s0, $zero, 0xB
/* E4C8 8001DCC8 2000A3AF */  sw         $v1, 0x20($sp)
/* E4CC 8001DCCC 3B004224 */  addiu      $v0, $v0, 0x3B
/* E4D0 8001DCD0 1800A2AF */  sw         $v0, 0x18($sp)
/* E4D4 8001DCD4 6B60000C */  jal        func_800181AC
/* E4D8 8001DCD8 1000B0AF */   sw        $s0, 0x10($sp)
/* E4DC 8001DCDC 0180043C */  lui        $a0, %hi(D_80010C4C)
/* E4E0 8001DCE0 4C0C8424 */  addiu      $a0, $a0, %lo(D_80010C4C)
/* E4E4 8001DCE4 1800A527 */  addiu      $a1, $sp, 0x18
/* E4E8 8001DCE8 21304002 */  addu       $a2, $s2, $zero
/* E4EC 8001DCEC 10000724 */  addiu      $a3, $zero, 0x10
/* E4F0 8001DCF0 1C00A28F */  lw         $v0, 0x1C($sp)
/* E4F4 8001DCF4 0000238E */  lw         $v1, 0x0($s1)
/* E4F8 8001DCF8 11004224 */  addiu      $v0, $v0, 0x11
/* E4FC 8001DCFC 43006324 */  addiu      $v1, $v1, 0x43
/* E500 8001DD00 1C00A2AF */  sw         $v0, 0x1C($sp)
/* E504 8001DD04 1800A3AF */  sw         $v1, 0x18($sp)
/* E508 8001DD08 6B60000C */  jal        func_800181AC
/* E50C 8001DD0C 1000B0AF */   sw        $s0, 0x10($sp)
/* E510 8001DD10 0180043C */  lui        $a0, %hi(D_80010C60)
/* E514 8001DD14 600C8424 */  addiu      $a0, $a0, %lo(D_80010C60)
/* E518 8001DD18 1800A527 */  addiu      $a1, $sp, 0x18
/* E51C 8001DD1C 21304002 */  addu       $a2, $s2, $zero
/* E520 8001DD20 10000724 */  addiu      $a3, $zero, 0x10
/* E524 8001DD24 1C00A28F */  lw         $v0, 0x1C($sp)
/* E528 8001DD28 0000238E */  lw         $v1, 0x0($s1)
/* E52C 8001DD2C 11004224 */  addiu      $v0, $v0, 0x11
/* E530 8001DD30 A3770008 */  j          .L8001DE8C
/* E534 8001DD34 2D006324 */   addiu     $v1, $v1, 0x2D
.L8001DD38:
/* E538 8001DD38 0180043C */  lui        $a0, %hi(D_80010C74)
/* E53C 8001DD3C 740C8424 */  addiu      $a0, $a0, %lo(D_80010C74)
/* E540 8001DD40 1800A527 */  addiu      $a1, $sp, 0x18
/* E544 8001DD44 2800A627 */  addiu      $a2, $sp, 0x28
/* E548 8001DD48 12000724 */  addiu      $a3, $zero, 0x12
/* E54C 8001DD4C 0880103C */  lui        $s0, %hi(D_80078D10)
/* E550 8001DD50 108D1026 */  addiu      $s0, $s0, %lo(D_80078D10)
/* E554 8001DD54 0000028E */  lw         $v0, 0x0($s0)
/* E558 8001DD58 32000324 */  addiu      $v1, $zero, 0x32
/* E55C 8001DD5C 1C00A3AF */  sw         $v1, 0x1C($sp)
/* E560 8001DD60 5E004224 */  addiu      $v0, $v0, 0x5E
/* E564 8001DD64 1800A2AF */  sw         $v0, 0x18($sp)
/* E568 8001DD68 0B000224 */  addiu      $v0, $zero, 0xB
/* E56C 8001DD6C 6B60000C */  jal        func_800181AC
/* E570 8001DD70 1000A2AF */   sw        $v0, 0x10($sp)
/* E574 8001DD74 21200000 */  addu       $a0, $zero, $zero
/* E578 8001DD78 F4FF1026 */  addiu      $s0, $s0, -0xC
/* E57C 8001DD7C 0780063C */  lui        $a2, %hi(D_8006CC78)
/* E580 8001DD80 78CCC624 */  addiu      $a2, $a2, %lo(D_8006CC78)
/* E584 8001DD84 21280000 */  addu       $a1, $zero, $zero
/* E588 8001DD88 1C00A28F */  lw         $v0, 0x1C($sp)
/* E58C 8001DD8C 0780113C */  lui        $s1, %hi(g_HudMobys)
/* E590 8001DD90 1057318E */  lw         $s1, %lo(g_HudMobys)($s1)
/* E594 8001DD94 1A004224 */  addiu      $v0, $v0, 0x1A
/* E598 8001DD98 1C00A2AF */  sw         $v0, 0x1C($sp)
.L8001DD9C:
/* E59C 8001DD9C 0000028E */  lw         $v0, 0x0($s0)
/* E5A0 8001DDA0 01008424 */  addiu      $a0, $a0, 0x1
/* E5A4 8001DDA4 80100200 */  sll        $v0, $v0, 2
/* E5A8 8001DDA8 21104500 */  addu       $v0, $v0, $a1
/* E5AC 8001DDAC FF004230 */  andi       $v0, $v0, 0xFF
/* E5B0 8001DDB0 40100200 */  sll        $v0, $v0, 1
/* E5B4 8001DDB4 21104600 */  addu       $v0, $v0, $a2
/* E5B8 8001DDB8 00004384 */  lh         $v1, 0x0($v0)
/* E5BC 8001DDBC 0C00A524 */  addiu      $a1, $a1, 0xC
/* E5C0 8001DDC0 40100300 */  sll        $v0, $v1, 1
/* E5C4 8001DDC4 21104300 */  addu       $v0, $v0, $v1
/* E5C8 8001DDC8 43120200 */  sra        $v0, $v0, 9
/* E5CC 8001DDCC 460022A2 */  sb         $v0, 0x46($s1)
/* E5D0 8001DDD0 09008228 */  slti       $v0, $a0, 0x9
/* E5D4 8001DDD4 F1FF4014 */  bnez       $v0, .L8001DD9C
/* E5D8 8001DDD8 58003126 */   addiu     $s1, $s1, 0x58
/* E5DC 8001DDDC 0180043C */  lui        $a0, %hi(D_80010C80)
/* E5E0 8001DDE0 800C8424 */  addiu      $a0, $a0, %lo(D_80010C80)
/* E5E4 8001DDE4 1800A527 */  addiu      $a1, $sp, 0x18
/* E5E8 8001DDE8 2800B227 */  addiu      $s2, $sp, 0x28
/* E5EC 8001DDEC 21304002 */  addu       $a2, $s2, $zero
/* E5F0 8001DDF0 10000724 */  addiu      $a3, $zero, 0x10
/* E5F4 8001DDF4 0E000224 */  addiu      $v0, $zero, 0xE
/* E5F8 8001DDF8 2800A2AF */  sw         $v0, 0x28($sp)
/* E5FC 8001DDFC 01000224 */  addiu      $v0, $zero, 0x1
/* E600 8001DE00 2C00A2AF */  sw         $v0, 0x2C($sp)
/* E604 8001DE04 00160224 */  addiu      $v0, $zero, 0x1600
/* E608 8001DE08 0880113C */  lui        $s1, %hi(D_80078D10)
/* E60C 8001DE0C 108D3126 */  addiu      $s1, $s1, %lo(D_80078D10)
/* E610 8001DE10 00140324 */  addiu      $v1, $zero, 0x1400
/* E614 8001DE14 3000A2AF */  sw         $v0, 0x30($sp)
/* E618 8001DE18 0000228E */  lw         $v0, 0x0($s1)
/* E61C 8001DE1C 0B001024 */  addiu      $s0, $zero, 0xB
/* E620 8001DE20 2000A3AF */  sw         $v1, 0x20($sp)
/* E624 8001DE24 3B004224 */  addiu      $v0, $v0, 0x3B
/* E628 8001DE28 1800A2AF */  sw         $v0, 0x18($sp)
/* E62C 8001DE2C 6B60000C */  jal        func_800181AC
/* E630 8001DE30 1000B0AF */   sw        $s0, 0x10($sp)
/* E634 8001DE34 0180043C */  lui        $a0, %hi(D_80010C94)
/* E638 8001DE38 940C8424 */  addiu      $a0, $a0, %lo(D_80010C94)
/* E63C 8001DE3C 1800A527 */  addiu      $a1, $sp, 0x18
/* E640 8001DE40 21304002 */  addu       $a2, $s2, $zero
/* E644 8001DE44 10000724 */  addiu      $a3, $zero, 0x10
/* E648 8001DE48 1C00A28F */  lw         $v0, 0x1C($sp)
/* E64C 8001DE4C 0000238E */  lw         $v1, 0x0($s1)
/* E650 8001DE50 11004224 */  addiu      $v0, $v0, 0x11
/* E654 8001DE54 49006324 */  addiu      $v1, $v1, 0x49
/* E658 8001DE58 1C00A2AF */  sw         $v0, 0x1C($sp)
/* E65C 8001DE5C 1800A3AF */  sw         $v1, 0x18($sp)
/* E660 8001DE60 6B60000C */  jal        func_800181AC
/* E664 8001DE64 1000B0AF */   sw        $s0, 0x10($sp)
/* E668 8001DE68 0180043C */  lui        $a0, %hi(D_80010CA4)
/* E66C 8001DE6C A40C8424 */  addiu      $a0, $a0, %lo(D_80010CA4)
/* E670 8001DE70 1800A527 */  addiu      $a1, $sp, 0x18
/* E674 8001DE74 21304002 */  addu       $a2, $s2, $zero
/* E678 8001DE78 10000724 */  addiu      $a3, $zero, 0x10
/* E67C 8001DE7C 1C00A28F */  lw         $v0, 0x1C($sp)
/* E680 8001DE80 0000238E */  lw         $v1, 0x0($s1)
/* E684 8001DE84 11004224 */  addiu      $v0, $v0, 0x11
/* E688 8001DE88 36006324 */  addiu      $v1, $v1, 0x36
.L8001DE8C:
/* E68C 8001DE8C 1C00A2AF */  sw         $v0, 0x1C($sp)
/* E690 8001DE90 1800A3AF */  sw         $v1, 0x18($sp)
/* E694 8001DE94 6B60000C */  jal        func_800181AC
/* E698 8001DE98 1000B0AF */   sw        $s0, 0x10($sp)
/* E69C 8001DE9C 1E780008 */  j          .L8001E078
/* E6A0 8001DEA0 00000000 */   nop
.L8001DEA4:
/* E6A4 8001DEA4 0180043C */  lui        $a0, %hi(D_80010CB8)
/* E6A8 8001DEA8 B80C8424 */  addiu      $a0, $a0, %lo(D_80010CB8)
/* E6AC 8001DEAC 1800A527 */  addiu      $a1, $sp, 0x18
/* E6B0 8001DEB0 2800B027 */  addiu      $s0, $sp, 0x28
/* E6B4 8001DEB4 21300002 */  addu       $a2, $s0, $zero
/* E6B8 8001DEB8 12000724 */  addiu      $a3, $zero, 0x12
/* E6BC 8001DEBC 0880123C */  lui        $s2, %hi(D_80078D10)
/* E6C0 8001DEC0 108D5226 */  addiu      $s2, $s2, %lo(D_80078D10)
/* E6C4 8001DEC4 35000324 */  addiu      $v1, $zero, 0x35
/* E6C8 8001DEC8 0000428E */  lw         $v0, 0x0($s2)
/* E6CC 8001DECC 0B001424 */  addiu      $s4, $zero, 0xB
/* E6D0 8001DED0 1C00A3AF */  sw         $v1, 0x1C($sp)
/* E6D4 8001DED4 56004224 */  addiu      $v0, $v0, 0x56
/* E6D8 8001DED8 1800A2AF */  sw         $v0, 0x18($sp)
/* E6DC 8001DEDC 6B60000C */  jal        func_800181AC
/* E6E0 8001DEE0 1000B4AF */   sw        $s4, 0x10($sp)
/* E6E4 8001DEE4 0780043C */  lui        $a0, %hi(D_80075620)
/* E6E8 8001DEE8 20568424 */  addiu      $a0, $a0, %lo(D_80075620)
/* E6EC 8001DEEC 1800A527 */  addiu      $a1, $sp, 0x18
/* E6F0 8001DEF0 21300002 */  addu       $a2, $s0, $zero
/* E6F4 8001DEF4 12000724 */  addiu      $a3, $zero, 0x12
/* E6F8 8001DEF8 1C00A28F */  lw         $v0, 0x1C($sp)
/* E6FC 8001DEFC 0000438E */  lw         $v1, 0x0($s2)
/* E700 8001DF00 28004224 */  addiu      $v0, $v0, 0x28
/* E704 8001DF04 87006324 */  addiu      $v1, $v1, 0x87
/* E708 8001DF08 1C00A2AF */  sw         $v0, 0x1C($sp)
/* E70C 8001DF0C 1800A3AF */  sw         $v1, 0x18($sp)
/* E710 8001DF10 6B60000C */  jal        func_800181AC
/* E714 8001DF14 1000B4AF */   sw        $s4, 0x10($sp)
/* E718 8001DF18 1C00A28F */  lw         $v0, 0x1C($sp)
/* E71C 8001DF1C F8FF438E */  lw         $v1, -0x8($s2)
/* E720 8001DF20 13004224 */  addiu      $v0, $v0, 0x13
/* E724 8001DF24 04006014 */  bnez       $v1, .L8001DF38
/* E728 8001DF28 1C00A2AF */   sw        $v0, 0x1C($sp)
/* E72C 8001DF2C 0780113C */  lui        $s1, %hi(g_HudMobys)
/* E730 8001DF30 1057318E */  lw         $s1, %lo(g_HudMobys)($s1)
/* E734 8001DF34 05001324 */  addiu      $s3, $zero, 0x5
.L8001DF38:
/* E738 8001DF38 0780043C */  lui        $a0, %hi(D_80075628)
/* E73C 8001DF3C 28568424 */  addiu      $a0, $a0, %lo(D_80075628)
/* E740 8001DF40 1800A527 */  addiu      $a1, $sp, 0x18
/* E744 8001DF44 21300002 */  addu       $a2, $s0, $zero
/* E748 8001DF48 0000428E */  lw         $v0, 0x0($s2)
/* E74C 8001DF4C 12000724 */  addiu      $a3, $zero, 0x12
/* E750 8001DF50 87004224 */  addiu      $v0, $v0, 0x87
/* E754 8001DF54 1800A2AF */  sw         $v0, 0x18($sp)
/* E758 8001DF58 6B60000C */  jal        func_800181AC
/* E75C 8001DF5C 1000B4AF */   sw        $s4, 0x10($sp)
/* E760 8001DF60 F8FF438E */  lw         $v1, -0x8($s2)
/* E764 8001DF64 01000224 */  addiu      $v0, $zero, 0x1
/* E768 8001DF68 05006214 */  bne        $v1, $v0, .L8001DF80
/* E76C 8001DF6C FF006632 */   andi      $a2, $s3, 0xFF
/* E770 8001DF70 0780113C */  lui        $s1, %hi(g_HudMobys)
/* E774 8001DF74 1057318E */  lw         $s1, %lo(g_HudMobys)($s1)
/* E778 8001DF78 05001324 */  addiu      $s3, $zero, 0x5
/* E77C 8001DF7C FF006632 */  andi       $a2, $s3, 0xFF
.L8001DF80:
/* E780 8001DF80 3D00C018 */  blez       $a2, .L8001E078
/* E784 8001DF84 21200000 */   addu      $a0, $zero, $zero
/* E788 8001DF88 F4FF4826 */  addiu      $t0, $s2, -0xC
/* E78C 8001DF8C 0780073C */  lui        $a3, %hi(D_8006CC78)
/* E790 8001DF90 78CCE724 */  addiu      $a3, $a3, %lo(D_8006CC78)
/* E794 8001DF94 21280000 */  addu       $a1, $zero, $zero
.L8001DF98:
/* E798 8001DF98 0000028D */  lw         $v0, 0x0($t0)
/* E79C 8001DF9C 01008424 */  addiu      $a0, $a0, 0x1
/* E7A0 8001DFA0 80100200 */  sll        $v0, $v0, 2
/* E7A4 8001DFA4 21104500 */  addu       $v0, $v0, $a1
/* E7A8 8001DFA8 FF004230 */  andi       $v0, $v0, 0xFF
/* E7AC 8001DFAC 40100200 */  sll        $v0, $v0, 1
/* E7B0 8001DFB0 21104700 */  addu       $v0, $v0, $a3
/* E7B4 8001DFB4 00004384 */  lh         $v1, 0x0($v0)
/* E7B8 8001DFB8 0C00A524 */  addiu      $a1, $a1, 0xC
/* E7BC 8001DFBC 40100300 */  sll        $v0, $v1, 1
/* E7C0 8001DFC0 21104300 */  addu       $v0, $v0, $v1
/* E7C4 8001DFC4 43120200 */  sra        $v0, $v0, 9
/* E7C8 8001DFC8 460022A2 */  sb         $v0, 0x46($s1)
/* E7CC 8001DFCC 2A108600 */  slt        $v0, $a0, $a2
/* E7D0 8001DFD0 F1FF4014 */  bnez       $v0, .L8001DF98
/* E7D4 8001DFD4 58003126 */   addiu     $s1, $s1, 0x58
/* E7D8 8001DFD8 1E780008 */  j          .L8001E078
/* E7DC 8001DFDC 00000000 */   nop
.L8001DFE0:
/* E7E0 8001DFE0 0180043C */  lui        $a0, %hi(D_80010CC4)
/* E7E4 8001DFE4 C40C8424 */  addiu      $a0, $a0, %lo(D_80010CC4)
/* E7E8 8001DFE8 1800A527 */  addiu      $a1, $sp, 0x18
/* E7EC 8001DFEC 2800A627 */  addiu      $a2, $sp, 0x28
/* E7F0 8001DFF0 12000724 */  addiu      $a3, $zero, 0x12
/* E7F4 8001DFF4 0880103C */  lui        $s0, %hi(D_80078D10)
/* E7F8 8001DFF8 108D1026 */  addiu      $s0, $s0, %lo(D_80078D10)
/* E7FC 8001DFFC 0000028E */  lw         $v0, 0x0($s0)
/* E800 8001E000 52000324 */  addiu      $v1, $zero, 0x52
/* E804 8001E004 1C00A3AF */  sw         $v1, 0x1C($sp)
/* E808 8001E008 5E004224 */  addiu      $v0, $v0, 0x5E
/* E80C 8001E00C 1800A2AF */  sw         $v0, 0x18($sp)
/* E810 8001E010 0B000224 */  addiu      $v0, $zero, 0xB
/* E814 8001E014 6B60000C */  jal        func_800181AC
/* E818 8001E018 1000A2AF */   sw        $v0, 0x10($sp)
/* E81C 8001E01C 21200000 */  addu       $a0, $zero, $zero
/* E820 8001E020 F4FF1026 */  addiu      $s0, $s0, -0xC
/* E824 8001E024 0780063C */  lui        $a2, %hi(D_8006CC78)
/* E828 8001E028 78CCC624 */  addiu      $a2, $a2, %lo(D_8006CC78)
/* E82C 8001E02C 21280000 */  addu       $a1, $zero, $zero
/* E830 8001E030 0780113C */  lui        $s1, %hi(g_HudMobys)
/* E834 8001E034 1057318E */  lw         $s1, %lo(g_HudMobys)($s1)
.L8001E038:
/* E838 8001E038 0000028E */  lw         $v0, 0x0($s0)
/* E83C 8001E03C 01008424 */  addiu      $a0, $a0, 0x1
/* E840 8001E040 80100200 */  sll        $v0, $v0, 2
/* E844 8001E044 21104500 */  addu       $v0, $v0, $a1
/* E848 8001E048 FF004230 */  andi       $v0, $v0, 0xFF
/* E84C 8001E04C 40100200 */  sll        $v0, $v0, 1
/* E850 8001E050 21104600 */  addu       $v0, $v0, $a2
/* E854 8001E054 00004384 */  lh         $v1, 0x0($v0)
/* E858 8001E058 0C00A524 */  addiu      $a1, $a1, 0xC
/* E85C 8001E05C 40100300 */  sll        $v0, $v1, 1
/* E860 8001E060 21104300 */  addu       $v0, $v0, $v1
/* E864 8001E064 43120200 */  sra        $v0, $v0, 9
/* E868 8001E068 460022A2 */  sb         $v0, 0x46($s1)
/* E86C 8001E06C 09008228 */  slti       $v0, $a0, 0x9
/* E870 8001E070 F1FF4014 */  bnez       $v0, .L8001E038
/* E874 8001E074 58003126 */   addiu     $s1, $s1, 0x58
.L8001E078:
/* E878 8001E078 0880023C */  lui        $v0, %hi(D_80078D0C)
/* E87C 8001E07C 0C8D428C */  lw         $v0, %lo(D_80078D0C)($v0)
/* E880 8001E080 00000000 */  nop
/* E884 8001E084 02004228 */  slti       $v0, $v0, 0x2
/* E888 8001E088 20004014 */  bnez       $v0, .L8001E10C
/* E88C 8001E08C 0D000224 */   addiu     $v0, $zero, 0xD
/* E890 8001E090 0880033C */  lui        $v1, %hi(D_80078D18)
/* E894 8001E094 188D638C */  lw         $v1, %lo(D_80078D18)($v1)
/* E898 8001E098 2800A2AF */  sw         $v0, 0x28($sp)
/* E89C 8001E09C 01000224 */  addiu      $v0, $zero, 0x1
/* E8A0 8001E0A0 2C00A2AF */  sw         $v0, 0x2C($sp)
/* E8A4 8001E0A4 001A0224 */  addiu      $v0, $zero, 0x1A00
/* E8A8 8001E0A8 3000A2AF */  sw         $v0, 0x30($sp)
/* E8AC 8001E0AC 1D000224 */  addiu      $v0, $zero, 0x1D
/* E8B0 8001E0B0 1C00A2AF */  sw         $v0, 0x1C($sp)
/* E8B4 8001E0B4 00160224 */  addiu      $v0, $zero, 0x1600
/* E8B8 8001E0B8 0A006014 */  bnez       $v1, .L8001E0E4
/* E8BC 8001E0BC 2000A2AF */   sw        $v0, 0x20($sp)
/* E8C0 8001E0C0 0780043C */  lui        $a0, %hi(D_80075630)
/* E8C4 8001E0C4 30568424 */  addiu      $a0, $a0, %lo(D_80075630)
/* E8C8 8001E0C8 1800A527 */  addiu      $a1, $sp, 0x18
/* E8CC 8001E0CC 2800A627 */  addiu      $a2, $sp, 0x28
/* E8D0 8001E0D0 0880023C */  lui        $v0, %hi(D_80078D10)
/* E8D4 8001E0D4 108D428C */  lw         $v0, %lo(D_80078D10)($v0)
/* E8D8 8001E0D8 0E000724 */  addiu      $a3, $zero, 0xE
/* E8DC 8001E0DC 3F780008 */  j          .L8001E0FC
/* E8E0 8001E0E0 30004224 */   addiu     $v0, $v0, 0x30
.L8001E0E4:
/* E8E4 8001E0E4 0780043C */  lui        $a0, %hi(D_80075638)
/* E8E8 8001E0E8 38568424 */  addiu      $a0, $a0, %lo(D_80075638)
/* E8EC 8001E0EC 1800A527 */  addiu      $a1, $sp, 0x18
/* E8F0 8001E0F0 2800A627 */  addiu      $a2, $sp, 0x28
/* E8F4 8001E0F4 0E000724 */  addiu      $a3, $zero, 0xE
/* E8F8 8001E0F8 E6000224 */  addiu      $v0, $zero, 0xE6
.L8001E0FC:
/* E8FC 8001E0FC 1800A2AF */  sw         $v0, 0x18($sp)
/* E900 8001E100 0B000224 */  addiu      $v0, $zero, 0xB
/* E904 8001E104 6B60000C */  jal        func_800181AC
/* E908 8001E108 1000A2AF */   sw        $v0, 0x10($sp)
.L8001E10C:
/* E90C 8001E10C 7048010C */  jal        func_800521C0
/* E910 8001E110 00000000 */   nop
/* E914 8001E114 A665000C */  jal        func_80019698
/* E918 8001E118 00000000 */   nop
/* E91C 8001E11C 0880033C */  lui        $v1, %hi(D_80078D00)
/* E920 8001E120 008D638C */  lw         $v1, %lo(D_80078D00)($v1)
/* E924 8001E124 01000224 */  addiu      $v0, $zero, 0x1
/* E928 8001E128 07006214 */  bne        $v1, $v0, .L8001E148
/* E92C 8001E12C 00000000 */   nop
/* E930 8001E130 0780013C */  lui        $at, %hi(D_8006FCF4 + 0x2400)
/* E934 8001E134 F42020AC */  sw         $zero, %lo(D_8006FCF4 + 0x2400)($at)
/* E938 8001E138 2062000C */  jal        func_80018880
/* E93C 8001E13C 00000000 */   nop
/* E940 8001E140 8B8A000C */  jal        func_80022A2C
/* E944 8001E144 00000000 */   nop
.L8001E148:
/* E948 8001E148 73AE000C */  jal        func_8002B9CC
/* E94C 8001E14C 00000000 */   nop
/* E950 8001E150 F442010C */  jal        func_80050BD0
/* E954 8001E154 00000000 */   nop
/* E958 8001E158 F25C010C */  jal        func_800573C8
/* E95C 8001E15C 00000000 */   nop
/* E960 8001E160 CC63000C */  jal        func_80018F30
/* E964 8001E164 00000000 */   nop
/* E968 8001E168 D97D010C */  jal        DrawSync
/* E96C 8001E16C 21200000 */   addu      $a0, $zero, $zero
/* E970 8001E170 0780023C */  lui        $v0, %hi(D_80075784)
/* E974 8001E174 8457428C */  lw         $v0, %lo(D_80075784)($v0)
/* E978 8001E178 00000000 */  nop
/* E97C 8001E17C 03004010 */  beqz       $v0, .L8001E18C
/* E980 8001E180 00000000 */   nop
/* E984 8001E184 F176010C */  jal        VSync
/* E988 8001E188 21200000 */   addu      $a0, $zero, $zero
.L8001E18C:
/* E98C 8001E18C F176010C */  jal        VSync
/* E990 8001E190 FFFF0424 */   addiu     $a0, $zero, -0x1
/* E994 8001E194 0780033C */  lui        $v1, %hi(D_80075950)
/* E998 8001E198 5059638C */  lw         $v1, %lo(D_80075950)($v1)
/* E99C 8001E19C 0780013C */  lui        $at, %hi(D_80075954)
/* E9A0 8001E1A0 545922AC */  sw         $v0, %lo(D_80075954)($at)
/* E9A4 8001E1A4 23104300 */  subu       $v0, $v0, $v1
/* E9A8 8001E1A8 02004228 */  slti       $v0, $v0, 0x2
/* E9AC 8001E1AC 0E004010 */  beqz       $v0, .L8001E1E8
/* E9B0 8001E1B0 00000000 */   nop
/* E9B4 8001E1B4 0780103C */  lui        $s0, %hi(D_80075954)
/* E9B8 8001E1B8 54591026 */  addiu      $s0, $s0, %lo(D_80075954)
.L8001E1BC:
/* E9BC 8001E1BC F176010C */  jal        VSync
/* E9C0 8001E1C0 21200000 */   addu      $a0, $zero, $zero
/* E9C4 8001E1C4 F176010C */  jal        VSync
/* E9C8 8001E1C8 FFFF0424 */   addiu     $a0, $zero, -0x1
/* E9CC 8001E1CC FCFF038E */  lw         $v1, -0x4($s0)
/* E9D0 8001E1D0 0780013C */  lui        $at, %hi(D_80075954)
/* E9D4 8001E1D4 545922AC */  sw         $v0, %lo(D_80075954)($at)
/* E9D8 8001E1D8 23104300 */  subu       $v0, $v0, $v1
/* E9DC 8001E1DC 02004228 */  slti       $v0, $v0, 0x2
/* E9E0 8001E1E0 F6FF4014 */  bnez       $v0, .L8001E1BC
/* E9E4 8001E1E4 00000000 */   nop
.L8001E1E8:
/* E9E8 8001E1E8 F176010C */  jal        VSync
/* E9EC 8001E1EC FFFF0424 */   addiu     $a0, $zero, -0x1
/* E9F0 8001E1F0 0780043C */  lui        $a0, %hi(g_CurDB)
/* E9F4 8001E1F4 8858848C */  lw         $a0, %lo(g_CurDB)($a0)
/* E9F8 8001E1F8 0780013C */  lui        $at, %hi(D_80075950)
/* E9FC 8001E1FC 505922AC */  sw         $v0, %lo(D_80075950)($at)
/* EA00 8001E200 0C80010C */  jal        PutDispEnv
/* EA04 8001E204 5C008424 */   addiu     $a0, $a0, 0x5C
/* EA08 8001E208 0780043C */  lui        $a0, %hi(g_CurDB)
/* EA0C 8001E20C 8858848C */  lw         $a0, %lo(g_CurDB)($a0)
/* EA10 8001E210 767F010C */  jal        PutDrawEnv
/* EA14 8001E214 00000000 */   nop
/* EA18 8001E218 E159000C */  jal        func_80016784
/* EA1C 8001E21C 00080424 */   addiu     $a0, $zero, 0x800
/* EA20 8001E220 597F010C */  jal        DrawOTag
/* EA24 8001E224 21204000 */   addu      $a0, $v0, $zero
/* EA28 8001E228 6400BF8F */  lw         $ra, 0x64($sp)
/* EA2C 8001E22C 6000B48F */  lw         $s4, 0x60($sp)
/* EA30 8001E230 5C00B38F */  lw         $s3, 0x5C($sp)
/* EA34 8001E234 5800B28F */  lw         $s2, 0x58($sp)
/* EA38 8001E238 5400B18F */  lw         $s1, 0x54($sp)
/* EA3C 8001E23C 5000B08F */  lw         $s0, 0x50($sp)
/* EA40 8001E240 6800BD27 */  addiu      $sp, $sp, 0x68
/* EA44 8001E244 0800E003 */  jr         $ra
/* EA48 8001E248 00000000 */   nop
.size func_8001D718, . - func_8001D718
