.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 2
dlabel D_80010B9C
/* 139C 80010B9C */ .asciz "PRESS START"
.align 2
.size D_80010B9C, . - D_80010B9C


.section .text
/* Generated by spimdisasm 1.27.0 */

glabel func_8001CA38
/* D238 8001CA38 0780023C */  lui        $v0, %hi(D_80075940)
/* D23C 8001CA3C 4059428C */  lw         $v0, %lo(D_80075940)($v0)
/* D240 8001CA40 A8FFBD27 */  addiu      $sp, $sp, -0x58
/* D244 8001CA44 5000BFAF */  sw         $ra, 0x50($sp)
/* D248 8001CA48 4C00B3AF */  sw         $s3, 0x4C($sp)
/* D24C 8001CA4C 4800B2AF */  sw         $s2, 0x48($sp)
/* D250 8001CA50 4400B1AF */  sw         $s1, 0x44($sp)
/* D254 8001CA54 2E004014 */  bnez       $v0, .L8001CB10
/* D258 8001CA58 4000B0AF */   sw        $s0, 0x40($sp)
/* D25C 8001CA5C 0780033C */  lui        $v1, %hi(D_8007593C)
/* D260 8001CA60 3C59638C */  lw         $v1, %lo(D_8007593C)($v1)
/* D264 8001CA64 00000000 */  nop
/* D268 8001CA68 21006014 */  bnez       $v1, .L8001CAF0
/* D26C 8001CA6C 10006228 */   slti      $v0, $v1, 0x10
/* D270 8001CA70 7048010C */  jal        func_800521C0
/* D274 8001CA74 00000000 */   nop
/* D278 8001CA78 A665000C */  jal        func_80019698
/* D27C 8001CA7C 00000000 */   nop
/* D280 8001CA80 F25C010C */  jal        func_800573C8
/* D284 8001CA84 00000000 */   nop
/* D288 8001CA88 F442010C */  jal        func_80050BD0
/* D28C 8001CA8C 00000000 */   nop
/* D290 8001CA90 73AE000C */  jal        func_8002B9CC
/* D294 8001CA94 00000000 */   nop
/* D298 8001CA98 D97D010C */  jal        DrawSync
/* D29C 8001CA9C 21200000 */   addu      $a0, $zero, $zero
/* D2A0 8001CAA0 F176010C */  jal        VSync
/* D2A4 8001CAA4 21200000 */   addu      $a0, $zero, $zero
/* D2A8 8001CAA8 0780043C */  lui        $a0, %hi(g_CurDB)
/* D2AC 8001CAAC 8858848C */  lw         $a0, %lo(g_CurDB)($a0)
/* D2B0 8001CAB0 0C80010C */  jal        PutDispEnv
/* D2B4 8001CAB4 5C008424 */   addiu     $a0, $a0, 0x5C
/* D2B8 8001CAB8 0780043C */  lui        $a0, %hi(g_CurDB)
/* D2BC 8001CABC 8858848C */  lw         $a0, %lo(g_CurDB)($a0)
/* D2C0 8001CAC0 767F010C */  jal        PutDrawEnv
/* D2C4 8001CAC4 00000000 */   nop
/* D2C8 8001CAC8 E159000C */  jal        func_80016784
/* D2CC 8001CACC 00080424 */   addiu     $a0, $zero, 0x800
/* D2D0 8001CAD0 597F010C */  jal        DrawOTag
/* D2D4 8001CAD4 21204000 */   addu      $a0, $v0, $zero
/* D2D8 8001CAD8 D97D010C */  jal        DrawSync
/* D2DC 8001CADC 21200000 */   addu      $a0, $zero, $zero
/* D2E0 8001CAE0 F176010C */  jal        VSync
/* D2E4 8001CAE4 21200000 */   addu      $a0, $zero, $zero
/* D2E8 8001CAE8 96730008 */  j          .L8001CE58
/* D2EC 8001CAEC 08000724 */   addiu     $a3, $zero, 0x8
.L8001CAF0:
/* D2F0 8001CAF0 32014010 */  beqz       $v0, .L8001CFBC
/* D2F4 8001CAF4 01000224 */   addiu     $v0, $zero, 0x1
/* D2F8 8001CAF8 F8006214 */  bne        $v1, $v0, .L8001CEDC
/* D2FC 8001CAFC 10000524 */   addiu     $a1, $zero, 0x10
/* D300 8001CB00 02000424 */  addiu      $a0, $zero, 0x2
/* D304 8001CB04 10000624 */  addiu      $a2, $zero, 0x10
/* D308 8001CB08 BB730008 */  j          .L8001CEEC
/* D30C 8001CB0C 10000724 */   addiu     $a3, $zero, 0x10
.L8001CB10:
/* D310 8001CB10 01000424 */  addiu      $a0, $zero, 0x1
/* D314 8001CB14 CA004414 */  bne        $v0, $a0, .L8001CE40
/* D318 8001CB18 00000000 */   nop
/* D31C 8001CB1C 0780023C */  lui        $v0, %hi(D_8007593C)
/* D320 8001CB20 3C59428C */  lw         $v0, %lo(D_8007593C)($v0)
/* D324 8001CB24 00000000 */  nop
/* D328 8001CB28 3C004228 */  slti       $v0, $v0, 0x3C
/* D32C 8001CB2C 91004014 */  bnez       $v0, .L8001CD74
/* D330 8001CB30 00000000 */   nop
/* D334 8001CB34 21880000 */  addu       $s1, $zero, $zero
/* D338 8001CB38 0780133C */  lui        $s3, %hi(D_8006F2D4)
/* D33C 8001CB3C D4F27326 */  addiu      $s3, $s3, %lo(D_8006F2D4)
/* D340 8001CB40 21900000 */  addu       $s2, $zero, $zero
.L8001CB44:
/* D344 8001CB44 0780013C */  lui        $at, %hi(D_800752E0)
/* D348 8001CB48 21083100 */  addu       $at, $at, $s1
/* D34C 8001CB4C E0522290 */  lbu        $v0, %lo(D_800752E0)($at)
/* D350 8001CB50 0780033C */  lui        $v1, %hi(D_8007593C)
/* D354 8001CB54 3C59638C */  lw         $v1, %lo(D_8007593C)($v1)
/* D358 8001CB58 3C004224 */  addiu      $v0, $v0, 0x3C
/* D35C 8001CB5C 23806200 */  subu       $s0, $v1, $v0
/* D360 8001CB60 38000006 */  bltz       $s0, .L8001CC44
/* D364 8001CB64 21280000 */   addu      $a1, $zero, $zero
/* D368 8001CB68 0780043C */  lui        $a0, %hi(g_HudMobys)
/* D36C 8001CB6C 1057848C */  lw         $a0, %lo(g_HudMobys)($a0)
/* D370 8001CB70 00000000 */  nop
/* D374 8001CB74 A8FF8424 */  addiu      $a0, $a0, -0x58
/* D378 8001CB78 0780013C */  lui        $at, %hi(g_HudMobys)
/* D37C 8001CB7C 105724AC */  sw         $a0, %lo(g_HudMobys)($at)
/* D380 8001CB80 455A000C */  jal        Memset
/* D384 8001CB84 58000624 */   addiu     $a2, $zero, 0x58
/* D388 8001CB88 1800022A */  slti       $v0, $s0, 0x18
/* D38C 8001CB8C 07004010 */  beqz       $v0, .L8001CBAC
/* D390 8001CB90 40101000 */   sll       $v0, $s0, 1
/* D394 8001CB94 21105300 */  addu       $v0, $v0, $s3
/* D398 8001CB98 0780033C */  lui        $v1, %hi(g_HudMobys)
/* D39C 8001CB9C 1057638C */  lw         $v1, %lo(g_HudMobys)($v1)
/* D3A0 8001CBA0 00004284 */  lh         $v0, 0x0($v0)
/* D3A4 8001CBA4 EF720008 */  j          .L8001CBBC
/* D3A8 8001CBA8 140062AC */   sw        $v0, 0x14($v1)
.L8001CBAC:
/* D3AC 8001CBAC 0780033C */  lui        $v1, %hi(g_HudMobys)
/* D3B0 8001CBB0 1057638C */  lw         $v1, %lo(g_HudMobys)($v1)
/* D3B4 8001CBB4 00040224 */  addiu      $v0, $zero, 0x400
/* D3B8 8001CBB8 140062AC */  sw         $v0, 0x14($v1)
.L8001CBBC:
/* D3BC 8001CBBC 0780013C */  lui        $at, %hi(D_8006F304)
/* D3C0 8001CBC0 21083100 */  addu       $at, $at, $s1
/* D3C4 8001CBC4 04F32290 */  lbu        $v0, %lo(D_8006F304)($at)
/* D3C8 8001CBC8 0780033C */  lui        $v1, %hi(g_HudMobys)
/* D3CC 8001CBCC 1057638C */  lw         $v1, %lo(g_HudMobys)($v1)
/* D3D0 8001CBD0 69014224 */  addiu      $v0, $v0, 0x169
/* D3D4 8001CBD4 360062A4 */  sh         $v0, 0x36($v1)
/* D3D8 8001CBD8 0780013C */  lui        $at, %hi(D_8006F2B4)
/* D3DC 8001CBDC 21083200 */  addu       $at, $at, $s2
/* D3E0 8001CBE0 B4F22284 */  lh         $v0, %lo(D_8006F2B4)($at)
/* D3E4 8001CBE4 00000000 */  nop
/* D3E8 8001CBE8 0C0062AC */  sw         $v0, 0xC($v1)
/* D3EC 8001CBEC 0780013C */  lui        $at, %hi(D_8006F2B6)
/* D3F0 8001CBF0 21083200 */  addu       $at, $at, $s2
/* D3F4 8001CBF4 B6F22284 */  lh         $v0, %lo(D_8006F2B6)($at)
/* D3F8 8001CBF8 00000000 */  nop
/* D3FC 8001CBFC 100062AC */  sw         $v0, 0x10($v1)
/* D400 8001CC00 0780013C */  lui        $at, %hi(D_800752D0)
/* D404 8001CC04 21083100 */  addu       $at, $at, $s1
/* D408 8001CC08 D0522290 */  lbu        $v0, %lo(D_800752D0)($at)
/* D40C 8001CC0C 00000000 */  nop
/* D410 8001CC10 460062A0 */  sb         $v0, 0x46($v1)
/* D414 8001CC14 0780033C */  lui        $v1, %hi(g_HudMobys)
/* D418 8001CC18 1057638C */  lw         $v1, %lo(g_HudMobys)($v1)
/* D41C 8001CC1C 04000224 */  addiu      $v0, $zero, 0x4
/* D420 8001CC20 470062A0 */  sb         $v0, 0x47($v1)
/* D424 8001CC24 0780033C */  lui        $v1, %hi(g_HudMobys)
/* D428 8001CC28 1057638C */  lw         $v1, %lo(g_HudMobys)($v1)
/* D42C 8001CC2C 0B000224 */  addiu      $v0, $zero, 0xB
/* D430 8001CC30 4F0062A0 */  sb         $v0, 0x4F($v1)
/* D434 8001CC34 0780033C */  lui        $v1, %hi(g_HudMobys)
/* D438 8001CC38 1057638C */  lw         $v1, %lo(g_HudMobys)($v1)
/* D43C 8001CC3C 20000224 */  addiu      $v0, $zero, 0x20
/* D440 8001CC40 500062A0 */  sb         $v0, 0x50($v1)
.L8001CC44:
/* D444 8001CC44 01003126 */  addiu      $s1, $s1, 0x1
/* D448 8001CC48 0800222A */  slti       $v0, $s1, 0x8
/* D44C 8001CC4C BDFF4014 */  bnez       $v0, .L8001CB44
/* D450 8001CC50 04005226 */   addiu     $s2, $s2, 0x4
/* D454 8001CC54 0780023C */  lui        $v0, %hi(g_LoadStage)
/* D458 8001CC58 6458428C */  lw         $v0, %lo(g_LoadStage)($v0)
/* D45C 8001CC5C 00000000 */  nop
/* D460 8001CC60 0B004228 */  slti       $v0, $v0, 0xB
/* D464 8001CC64 31004014 */  bnez       $v0, .L8001CD2C
/* D468 8001CC68 00000000 */   nop
/* D46C 8001CC6C 0780023C */  lui        $v0, %hi(D_8007593C)
/* D470 8001CC70 3C59428C */  lw         $v0, %lo(D_8007593C)($v0)
/* D474 8001CC74 00000000 */  nop
/* D478 8001CC78 A5014228 */  slti       $v0, $v0, 0x1A5
/* D47C 8001CC7C 2B004014 */  bnez       $v0, .L8001CD2C
/* D480 8001CC80 2000A527 */   addiu     $a1, $sp, 0x20
/* D484 8001CC84 0180043C */  lui        $a0, %hi(D_80010B9C)
/* D488 8001CC88 9C0B8424 */  addiu      $a0, $a0, %lo(D_80010B9C)
/* D48C 8001CC8C 3000A627 */  addiu      $a2, $sp, 0x30
/* D490 8001CC90 12000724 */  addiu      $a3, $zero, 0x12
/* D494 8001CC94 10000224 */  addiu      $v0, $zero, 0x10
/* D498 8001CC98 3000A2AF */  sw         $v0, 0x30($sp)
/* D49C 8001CC9C 01000224 */  addiu      $v0, $zero, 0x1
/* D4A0 8001CCA0 3400A2AF */  sw         $v0, 0x34($sp)
/* D4A4 8001CCA4 00140224 */  addiu      $v0, $zero, 0x1400
/* D4A8 8001CCA8 3800A2AF */  sw         $v0, 0x38($sp)
/* D4AC 8001CCAC AE000224 */  addiu      $v0, $zero, 0xAE
/* D4B0 8001CCB0 2000A2AF */  sw         $v0, 0x20($sp)
/* D4B4 8001CCB4 D0000224 */  addiu      $v0, $zero, 0xD0
/* D4B8 8001CCB8 2400A2AF */  sw         $v0, 0x24($sp)
/* D4BC 8001CCBC 00110224 */  addiu      $v0, $zero, 0x1100
/* D4C0 8001CCC0 2800A2AF */  sw         $v0, 0x28($sp)
/* D4C4 8001CCC4 0B000224 */  addiu      $v0, $zero, 0xB
/* D4C8 8001CCC8 6B60000C */  jal        func_800181AC
/* D4CC 8001CCCC 1000A2AF */   sw        $v0, 0x10($sp)
/* D4D0 8001CCD0 21880000 */  addu       $s1, $zero, $zero
/* D4D4 8001CCD4 0780063C */  lui        $a2, %hi(D_8006CC78)
/* D4D8 8001CCD8 78CCC624 */  addiu      $a2, $a2, %lo(D_8006CC78)
/* D4DC 8001CCDC 21280000 */  addu       $a1, $zero, $zero
/* D4E0 8001CCE0 0780043C */  lui        $a0, %hi(g_HudMobys)
/* D4E4 8001CCE4 1057848C */  lw         $a0, %lo(g_HudMobys)($a0)
.L8001CCE8:
/* D4E8 8001CCE8 0780023C */  lui        $v0, %hi(D_8007593C)
/* D4EC 8001CCEC 3C59428C */  lw         $v0, %lo(D_8007593C)($v0)
/* D4F0 8001CCF0 01003126 */  addiu      $s1, $s1, 0x1
/* D4F4 8001CCF4 80100200 */  sll        $v0, $v0, 2
/* D4F8 8001CCF8 21104500 */  addu       $v0, $v0, $a1
/* D4FC 8001CCFC FF004230 */  andi       $v0, $v0, 0xFF
/* D500 8001CD00 40100200 */  sll        $v0, $v0, 1
/* D504 8001CD04 21104600 */  addu       $v0, $v0, $a2
/* D508 8001CD08 00004384 */  lh         $v1, 0x0($v0)
/* D50C 8001CD0C 0C00A524 */  addiu      $a1, $a1, 0xC
/* D510 8001CD10 40100300 */  sll        $v0, $v1, 1
/* D514 8001CD14 21104300 */  addu       $v0, $v0, $v1
/* D518 8001CD18 43120200 */  sra        $v0, $v0, 9
/* D51C 8001CD1C 460082A0 */  sb         $v0, 0x46($a0)
/* D520 8001CD20 0A00222A */  slti       $v0, $s1, 0xA
/* D524 8001CD24 F0FF4014 */  bnez       $v0, .L8001CCE8
/* D528 8001CD28 58008424 */   addiu     $a0, $a0, 0x58
.L8001CD2C:
/* D52C 8001CD2C 0780103C */  lui        $s0, %hi(D_8006FCF4 + 0x2400)
/* D530 8001CD30 F4201026 */  addiu      $s0, $s0, %lo(D_8006FCF4 + 0x2400)
/* D534 8001CD34 2062000C */  jal        func_80018880
/* D538 8001CD38 000000AE */   sw        $zero, 0x0($s0)
/* D53C 8001CD3C 00DC0426 */  addiu      $a0, $s0, -0x2400
/* D540 8001CD40 21280000 */  addu       $a1, $zero, $zero
/* D544 8001CD44 455A000C */  jal        Memset
/* D548 8001CD48 00090624 */   addiu     $a2, $zero, 0x900
/* D54C 8001CD4C 8B8A000C */  jal        func_80022A2C
/* D550 8001CD50 00000000 */   nop
/* D554 8001CD54 0780023C */  lui        $v0, %hi(D_8007593C)
/* D558 8001CD58 3C59428C */  lw         $v0, %lo(D_8007593C)($v0)
/* D55C 8001CD5C 00000000 */  nop
/* D560 8001CD60 B5004228 */  slti       $v0, $v0, 0xB5
/* D564 8001CD64 03004014 */  bnez       $v0, .L8001CD74
/* D568 8001CD68 00000000 */   nop
/* D56C 8001CD6C B18E000C */  jal        func_80023AC4
/* D570 8001CD70 00000000 */   nop
.L8001CD74:
/* D574 8001CD74 0780023C */  lui        $v0, %hi(D_800752DC)
/* D578 8001CD78 DC524294 */  lhu        $v0, %lo(D_800752DC)($v0)
/* D57C 8001CD7C 0780033C */  lui        $v1, %hi(D_800752DE)
/* D580 8001CD80 DE526394 */  lhu        $v1, %lo(D_800752DE)($v1)
/* D584 8001CD84 0780103C */  lui        $s0, %hi(g_Camera + 0x4E)
/* D588 8001CD88 1E6E1026 */  addiu      $s0, $s0, %lo(g_Camera + 0x4E)
/* D58C 8001CD8C 000002A6 */  sh         $v0, 0x0($s0)
/* D590 8001CD90 0780013C */  lui        $at, %hi(g_Camera + 0x50)
/* D594 8001CD94 206E23A4 */  sh         $v1, %lo(g_Camera + 0x50)($at)
/* D598 8001CD98 14CF000C */  jal        CameraUpdateMatrices
/* D59C 8001CD9C 00000000 */   nop
/* D5A0 8001CDA0 FFFF0424 */  addiu      $a0, $zero, -0x1
/* D5A4 8001CDA4 C6FF0526 */  addiu      $a1, $s0, -0x3A
/* D5A8 8001CDA8 EA3A010C */  jal        func_8004EBA8
/* D5AC 8001CDAC B2FF0626 */   addiu     $a2, $s0, -0x4E
/* D5B0 8001CDB0 0780023C */  lui        $v0, %hi(D_800752D8)
/* D5B4 8001CDB4 D8524294 */  lhu        $v0, %lo(D_800752D8)($v0)
/* D5B8 8001CDB8 0780033C */  lui        $v1, %hi(D_800752DA)
/* D5BC 8001CDBC DA526394 */  lhu        $v1, %lo(D_800752DA)($v1)
/* D5C0 8001CDC0 0780063C */  lui        $a2, %hi(D_8007593C)
/* D5C4 8001CDC4 3C59C68C */  lw         $a2, %lo(D_8007593C)($a2)
/* D5C8 8001CDC8 000002A6 */  sh         $v0, 0x0($s0)
/* D5CC 8001CDCC 2000C228 */  slti       $v0, $a2, 0x20
/* D5D0 8001CDD0 0780013C */  lui        $at, %hi(g_Camera + 0x50)
/* D5D4 8001CDD4 206E23A4 */  sh         $v1, %lo(g_Camera + 0x50)($at)
/* D5D8 8001CDD8 07004010 */  beqz       $v0, .L8001CDF8
/* D5DC 8001CDDC 02000424 */   addiu     $a0, $zero, 0x2
/* D5E0 8001CDE0 1F000524 */  addiu      $a1, $zero, 0x1F
/* D5E4 8001CDE4 2328A600 */  subu       $a1, $a1, $a2
/* D5E8 8001CDE8 C0280500 */  sll        $a1, $a1, 3
/* D5EC 8001CDEC 2130A000 */  addu       $a2, $a1, $zero
/* D5F0 8001CDF0 3564000C */  jal        func_800190D4
/* D5F4 8001CDF4 2138A000 */   addu      $a3, $a1, $zero
.L8001CDF8:
/* D5F8 8001CDF8 D97D010C */  jal        DrawSync
/* D5FC 8001CDFC 21200000 */   addu      $a0, $zero, $zero
/* D600 8001CE00 F176010C */  jal        VSync
/* D604 8001CE04 21200000 */   addu      $a0, $zero, $zero
/* D608 8001CE08 0780043C */  lui        $a0, %hi(g_CurDB)
/* D60C 8001CE0C 8858848C */  lw         $a0, %lo(g_CurDB)($a0)
/* D610 8001CE10 0C80010C */  jal        PutDispEnv
/* D614 8001CE14 5C008424 */   addiu     $a0, $a0, 0x5C
/* D618 8001CE18 0780043C */  lui        $a0, %hi(g_CurDB)
/* D61C 8001CE1C 8858848C */  lw         $a0, %lo(g_CurDB)($a0)
/* D620 8001CE20 767F010C */  jal        PutDrawEnv
/* D624 8001CE24 00000000 */   nop
/* D628 8001CE28 E159000C */  jal        func_80016784
/* D62C 8001CE2C 00080424 */   addiu     $a0, $zero, 0x800
/* D630 8001CE30 597F010C */  jal        DrawOTag
/* D634 8001CE34 21204000 */   addu      $a0, $v0, $zero
/* D638 8001CE38 EF730008 */  j          .L8001CFBC
/* D63C 8001CE3C 00000000 */   nop
.L8001CE40:
/* D640 8001CE40 0780033C */  lui        $v1, %hi(D_8007593C)
/* D644 8001CE44 3C59638C */  lw         $v1, %lo(D_8007593C)($v1)
/* D648 8001CE48 00000000 */  nop
/* D64C 8001CE4C 1B006014 */  bnez       $v1, .L8001CEBC
/* D650 8001CE50 10006228 */   slti      $v0, $v1, 0x10
/* D654 8001CE54 08000724 */  addiu      $a3, $zero, 0x8
.L8001CE58:
/* D658 8001CE58 0780033C */  lui        $v1, %hi(g_CurDB)
/* D65C 8001CE5C 8858638C */  lw         $v1, %lo(g_CurDB)($v1)
/* D660 8001CE60 0780023C */  lui        $v0, %hi(g_DB)
/* D664 8001CE64 E06E4224 */  addiu      $v0, $v0, %lo(g_DB)
/* D668 8001CE68 02006210 */  beq        $v1, $v0, .L8001CE74
/* D66C 8001CE6C 1800A0A7 */   sh        $zero, 0x18($sp)
/* D670 8001CE70 F8000724 */  addiu      $a3, $zero, 0xF8
.L8001CE74:
/* D674 8001CE74 1800A427 */  addiu      $a0, $sp, 0x18
/* D678 8001CE78 21280000 */  addu       $a1, $zero, $zero
/* D67C 8001CE7C 00010624 */  addiu      $a2, $zero, 0x100
/* D680 8001CE80 2330C700 */  subu       $a2, $a2, $a3
/* D684 8001CE84 00020224 */  addiu      $v0, $zero, 0x200
/* D688 8001CE88 1C00A2A7 */  sh         $v0, 0x1C($sp)
/* D68C 8001CE8C E0000224 */  addiu      $v0, $zero, 0xE0
/* D690 8001CE90 1A00A7A7 */  sh         $a3, 0x1A($sp)
/* D694 8001CE94 BC7E010C */  jal        MoveImage
/* D698 8001CE98 1E00A2A7 */   sh        $v0, 0x1E($sp)
/* D69C 8001CE9C D97D010C */  jal        DrawSync
/* D6A0 8001CEA0 21200000 */   addu      $a0, $zero, $zero
/* D6A4 8001CEA4 0780013C */  lui        $at, %hi(g_DB + 0x18)
/* D6A8 8001CEA8 F86E20A0 */  sb         $zero, %lo(g_DB + 0x18)($at)
/* D6AC 8001CEAC 0780013C */  lui        $at, %hi(g_DB + 0x9C)
/* D6B0 8001CEB0 7C6F20A0 */  sb         $zero, %lo(g_DB + 0x9C)($at)
/* D6B4 8001CEB4 EF730008 */  j          .L8001CFBC
/* D6B8 8001CEB8 00000000 */   nop
.L8001CEBC:
/* D6BC 8001CEBC 3F004010 */  beqz       $v0, .L8001CFBC
/* D6C0 8001CEC0 00000000 */   nop
/* D6C4 8001CEC4 05006414 */  bne        $v1, $a0, .L8001CEDC
/* D6C8 8001CEC8 10000524 */   addiu     $a1, $zero, 0x10
/* D6CC 8001CECC 02000424 */  addiu      $a0, $zero, 0x2
/* D6D0 8001CED0 10000624 */  addiu      $a2, $zero, 0x10
/* D6D4 8001CED4 BB730008 */  j          .L8001CEEC
/* D6D8 8001CED8 10000724 */   addiu     $a3, $zero, 0x10
.L8001CEDC:
/* D6DC 8001CEDC 02000424 */  addiu      $a0, $zero, 0x2
/* D6E0 8001CEE0 20000524 */  addiu      $a1, $zero, 0x20
/* D6E4 8001CEE4 20000624 */  addiu      $a2, $zero, 0x20
/* D6E8 8001CEE8 20000724 */  addiu      $a3, $zero, 0x20
.L8001CEEC:
/* D6EC 8001CEEC 3564000C */  jal        func_800190D4
/* D6F0 8001CEF0 00000000 */   nop
/* D6F4 8001CEF4 D97D010C */  jal        DrawSync
/* D6F8 8001CEF8 21200000 */   addu      $a0, $zero, $zero
/* D6FC 8001CEFC F176010C */  jal        VSync
/* D700 8001CF00 21200000 */   addu      $a0, $zero, $zero
/* D704 8001CF04 0780043C */  lui        $a0, %hi(g_CurDB)
/* D708 8001CF08 8858848C */  lw         $a0, %lo(g_CurDB)($a0)
/* D70C 8001CF0C 0C80010C */  jal        PutDispEnv
/* D710 8001CF10 5C008424 */   addiu     $a0, $a0, 0x5C
/* D714 8001CF14 0780043C */  lui        $a0, %hi(g_CurDB)
/* D718 8001CF18 8858848C */  lw         $a0, %lo(g_CurDB)($a0)
/* D71C 8001CF1C 767F010C */  jal        PutDrawEnv
/* D720 8001CF20 00000000 */   nop
/* D724 8001CF24 E159000C */  jal        func_80016784
/* D728 8001CF28 00080424 */   addiu     $a0, $zero, 0x800
/* D72C 8001CF2C 597F010C */  jal        DrawOTag
/* D730 8001CF30 21204000 */   addu      $a0, $v0, $zero
/* D734 8001CF34 0780033C */  lui        $v1, %hi(D_8007593C)
/* D738 8001CF38 3C59638C */  lw         $v1, %lo(D_8007593C)($v1)
/* D73C 8001CF3C 0F000224 */  addiu      $v0, $zero, 0xF
/* D740 8001CF40 1E006214 */  bne        $v1, $v0, .L8001CFBC
/* D744 8001CF44 21200000 */   addu      $a0, $zero, $zero
/* D748 8001CF48 0780033C */  lui        $v1, %hi(g_DB + 0x18)
/* D74C 8001CF4C F86E6324 */  addiu      $v1, $v1, %lo(g_DB + 0x18)
/* D750 8001CF50 01000224 */  addiu      $v0, $zero, 0x1
/* D754 8001CF54 000062A0 */  sb         $v0, 0x0($v1)
/* D758 8001CF58 0780013C */  lui        $at, %hi(g_DB + 0x9C)
/* D75C 8001CF5C 7C6F22A0 */  sb         $v0, %lo(g_DB + 0x9C)($at)
/* D760 8001CF60 0780013C */  lui        $at, %hi(g_DB + 0x19)
/* D764 8001CF64 F96E20A0 */  sb         $zero, %lo(g_DB + 0x19)($at)
/* D768 8001CF68 0780013C */  lui        $at, %hi(g_DB + 0x1A)
/* D76C 8001CF6C FA6E20A0 */  sb         $zero, %lo(g_DB + 0x1A)($at)
/* D770 8001CF70 0780013C */  lui        $at, %hi(g_DB + 0x1B)
/* D774 8001CF74 FB6E20A0 */  sb         $zero, %lo(g_DB + 0x1B)($at)
/* D778 8001CF78 850060A0 */  sb         $zero, 0x85($v1)
/* D77C 8001CF7C 860060A0 */  sb         $zero, 0x86($v1)
/* D780 8001CF80 D97D010C */  jal        DrawSync
/* D784 8001CF84 870060A0 */   sb        $zero, 0x87($v1)
/* D788 8001CF88 F176010C */  jal        VSync
/* D78C 8001CF8C 21200000 */   addu      $a0, $zero, $zero
/* D790 8001CF90 1800A427 */  addiu      $a0, $sp, 0x18
/* D794 8001CF94 21280000 */  addu       $a1, $zero, $zero
/* D798 8001CF98 21300000 */  addu       $a2, $zero, $zero
/* D79C 8001CF9C 21380000 */  addu       $a3, $zero, $zero
/* D7A0 8001CFA0 00020224 */  addiu      $v0, $zero, 0x200
/* D7A4 8001CFA4 1C00A2A7 */  sh         $v0, 0x1C($sp)
/* D7A8 8001CFA8 E0010224 */  addiu      $v0, $zero, 0x1E0
/* D7AC 8001CFAC 1800A0A7 */  sh         $zero, 0x18($sp)
/* D7B0 8001CFB0 1A00A0A7 */  sh         $zero, 0x1A($sp)
/* D7B4 8001CFB4 3E7E010C */  jal        ClearImage
/* D7B8 8001CFB8 1E00A2A7 */   sh        $v0, 0x1E($sp)
.L8001CFBC:
/* D7BC 8001CFBC 5000BF8F */  lw         $ra, 0x50($sp)
/* D7C0 8001CFC0 4C00B38F */  lw         $s3, 0x4C($sp)
/* D7C4 8001CFC4 4800B28F */  lw         $s2, 0x48($sp)
/* D7C8 8001CFC8 4400B18F */  lw         $s1, 0x44($sp)
/* D7CC 8001CFCC 4000B08F */  lw         $s0, 0x40($sp)
/* D7D0 8001CFD0 5800BD27 */  addiu      $sp, $sp, 0x58
/* D7D4 8001CFD4 0800E003 */  jr         $ra
/* D7D8 8001CFD8 00000000 */   nop
.size func_8001CA38, . - func_8001CA38
