.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.27.0 */

/* Handwritten function */
glabel func_800524C4
/* 42CC4 800524C4 0780013C */  lui        $at, %hi(D_800756A4)
/* 42CC8 800524C8 A4562124 */  addiu      $at, $at, %lo(D_800756A4)
/* 42CCC 800524CC 0000228C */  lw         $v0, 0x0($at)
/* 42CD0 800524D0 00000000 */  nop
/* 42CD4 800524D4 01004220 */  addi       $v0, $v0, 0x1 /* handwritten instruction */
/* 42CD8 800524D8 000022AC */  sw         $v0, 0x0($at)
/* 42CDC 800524DC 0780013C */  lui        $at, %hi(D_8007573C)
/* 42CE0 800524E0 3C572124 */  addiu      $at, $at, %lo(D_8007573C)
/* 42CE4 800524E4 0000228C */  lw         $v0, 0x0($at)
/* 42CE8 800524E8 FFFF0320 */  addi       $v1, $zero, -0x1 /* handwritten instruction */
/* 42CEC 800524EC 48004480 */  lb         $a0, 0x48($v0)
/* 42CF0 800524F0 480040A0 */  sb         $zero, 0x48($v0)
/* 42CF4 800524F4 03008314 */  bne        $a0, $v1, .L80052504
/* 42CF8 800524F8 58004320 */   addi      $v1, $v0, 0x58 /* handwritten instruction */
/* 42CFC 800524FC 46490108 */  j          .L80052518
/* 42D00 80052500 480064A0 */   sb        $a0, 0x48($v1)
.L80052504:
/* 42D04 80052504 48006480 */  lb         $a0, 0x48($v1)
/* 42D08 80052508 00000000 */  nop
/* 42D0C 8005250C FDFF8104 */  bgez       $a0, .L80052504
/* 42D10 80052510 58006320 */   addi      $v1, $v1, 0x58 /* handwritten instruction */
/* 42D14 80052514 A8FF6320 */  addi       $v1, $v1, -0x58 /* handwritten instruction */
.L80052518:
/* 42D18 80052518 000023AC */  sw         $v1, 0x0($at)
/* 42D1C 8005251C 0780013C */  lui        $at, %hi(D_80075930)
/* 42D20 80052520 30592124 */  addiu      $at, $at, %lo(D_80075930)
/* 42D24 80052524 0000238C */  lw         $v1, 0x0($at)
/* 42D28 80052528 FFFF0420 */  addi       $a0, $zero, -0x1 /* handwritten instruction */
/* 42D2C 8005252C FFFF6580 */  lb         $a1, -0x1($v1)
/* 42D30 80052530 FFFF60A0 */  sb         $zero, -0x1($v1)
/* 42D34 80052534 0300A414 */  bne        $a1, $a0, .L80052544
/* 42D38 80052538 E8FF6420 */   addi      $a0, $v1, -0x18 /* handwritten instruction */
/* 42D3C 8005253C 56490108 */  j          .L80052558
/* 42D40 80052540 FFFF85A0 */   sb        $a1, -0x1($a0)
.L80052544:
/* 42D44 80052544 FFFF8580 */  lb         $a1, -0x1($a0)
/* 42D48 80052548 00000000 */  nop
/* 42D4C 8005254C FDFFA104 */  bgez       $a1, .L80052544
/* 42D50 80052550 E8FF8420 */   addi      $a0, $a0, -0x18 /* handwritten instruction */
/* 42D54 80052554 18008420 */  addi       $a0, $a0, 0x18 /* handwritten instruction */
.L80052558:
/* 42D58 80052558 E8FF6320 */  addi       $v1, $v1, -0x18 /* handwritten instruction */
/* 42D5C 8005255C 000043AC */  sw         $v1, 0x0($v0)
/* 42D60 80052560 0800E003 */  jr         $ra
/* 42D64 80052564 000024AC */   sw        $a0, 0x0($at)
.size func_800524C4, . - func_800524C4

/* Handwritten function */
glabel func_80052568
/* 42D68 80052568 34008584 */  lh         $a1, 0x34($a0)
/* 42D6C 8005256C 0780013C */  lui        $at, %hi(D_80075778)
/* 42D70 80052570 78572124 */  addiu      $at, $at, %lo(D_80075778)
/* 42D74 80052574 0C00A004 */  bltz       $a1, .L800525A8
/* 42D78 80052578 0000218C */   lw        $at, 0x0($at)
/* 42D7C 8005257C 80280500 */  sll        $a1, $a1, 2
/* 42D80 80052580 2028A100 */  add        $a1, $a1, $at /* handwritten instruction */
/* 42D84 80052584 FCFFA220 */  addi       $v0, $a1, -0x4 /* handwritten instruction */
.L80052588:
/* 42D88 80052588 04004520 */  addi       $a1, $v0, 0x4 /* handwritten instruction */
/* 42D8C 8005258C 0000A28C */  lw         $v0, 0x0($a1)
/* 42D90 80052590 00000000 */  nop
/* 42D94 80052594 FCFF4414 */  bne        $v0, $a0, .L80052588
/* 42D98 80052598 00000000 */   nop
/* 42D9C 8005259C 0400828C */  lw         $v0, 0x4($a0)
/* 42DA0 800525A0 00000000 */  nop
/* 42DA4 800525A4 0000A2AC */  sw         $v0, 0x0($a1)
.L800525A8:
/* 42DA8 800525A8 0780013C */  lui        $at, %hi(D_80075890)
/* 42DAC 800525AC 90582124 */  addiu      $at, $at, %lo(D_80075890)
/* 42DB0 800525B0 0000218C */  lw         $at, 0x0($at)
/* 42DB4 800525B4 00000000 */  nop
/* 42DB8 800525B8 22082400 */  sub        $at, $at, $a0 /* handwritten instruction */
/* 42DBC 800525BC 03002018 */  blez       $at, .L800525CC
/* 42DC0 800525C0 FDFF0220 */   addi      $v0, $zero, -0x3 /* handwritten instruction */
/* 42DC4 800525C4 0800E003 */  jr         $ra
/* 42DC8 800525C8 480082A0 */   sb        $v0, 0x48($a0)
.L800525CC:
/* 42DCC 800525CC 0780013C */  lui        $at, %hi(D_800756A4)
/* 42DD0 800525D0 A4562124 */  addiu      $at, $at, %lo(D_800756A4)
/* 42DD4 800525D4 0000228C */  lw         $v0, 0x0($at)
/* 42DD8 800525D8 00000000 */  nop
/* 42DDC 800525DC FFFF4220 */  addi       $v0, $v0, -0x1 /* handwritten instruction */
/* 42DE0 800525E0 000022AC */  sw         $v0, 0x0($at)
/* 42DE4 800525E4 58008120 */  addi       $at, $a0, 0x58 /* handwritten instruction */
/* 42DE8 800525E8 48002280 */  lb         $v0, 0x48($at)
/* 42DEC 800525EC FFFF0320 */  addi       $v1, $zero, -0x1 /* handwritten instruction */
/* 42DF0 800525F0 00008120 */  addi       $at, $a0, 0x0 /* handwritten instruction */
/* 42DF4 800525F4 09004314 */  bne        $v0, $v1, .L8005261C
/* 42DF8 800525F8 FEFF0320 */   addi      $v1, $zero, -0x2 /* handwritten instruction */
/* 42DFC 800525FC A8FF2120 */  addi       $at, $at, -0x58 /* handwritten instruction */
.L80052600:
/* 42E00 80052600 48002280 */  lb         $v0, 0x48($at)
/* 42E04 80052604 FEFF0320 */  addi       $v1, $zero, -0x2 /* handwritten instruction */
/* 42E08 80052608 FDFF4310 */  beq        $v0, $v1, .L80052600
/* 42E0C 8005260C A8FF2120 */   addi      $at, $at, -0x58 /* handwritten instruction */
/* 42E10 80052610 58002120 */  addi       $at, $at, 0x58 /* handwritten instruction */
/* 42E14 80052614 58002120 */  addi       $at, $at, 0x58 /* handwritten instruction */
/* 42E18 80052618 FFFF0320 */  addi       $v1, $zero, -0x1 /* handwritten instruction */
.L8005261C:
/* 42E1C 8005261C 480023A0 */  sb         $v1, 0x48($at)
/* 42E20 80052620 0780023C */  lui        $v0, %hi(D_8007573C)
/* 42E24 80052624 3C574224 */  addiu      $v0, $v0, %lo(D_8007573C)
/* 42E28 80052628 0000438C */  lw         $v1, 0x0($v0)
/* 42E2C 8005262C 00000000 */  nop
/* 42E30 80052630 22186100 */  sub        $v1, $v1, $at /* handwritten instruction */
/* 42E34 80052634 02006004 */  bltz       $v1, .L80052640
/* 42E38 80052638 00000000 */   nop
/* 42E3C 8005263C 000041AC */  sw         $at, 0x0($v0)
.L80052640:
/* 42E40 80052640 0000848C */  lw         $a0, 0x0($a0)
/* 42E44 80052644 00000000 */  nop
/* 42E48 80052648 FFFF8280 */  lb         $v0, -0x1($a0)
/* 42E4C 8005264C FFFF0320 */  addi       $v1, $zero, -0x1 /* handwritten instruction */
/* 42E50 80052650 18008120 */  addi       $at, $a0, 0x18 /* handwritten instruction */
/* 42E54 80052654 09004314 */  bne        $v0, $v1, .L8005267C
/* 42E58 80052658 FEFF0320 */   addi      $v1, $zero, -0x2 /* handwritten instruction */
/* 42E5C 8005265C 18002120 */  addi       $at, $at, 0x18 /* handwritten instruction */
.L80052660:
/* 42E60 80052660 FFFF2280 */  lb         $v0, -0x1($at)
/* 42E64 80052664 FEFF0320 */  addi       $v1, $zero, -0x2 /* handwritten instruction */
/* 42E68 80052668 FDFF4310 */  beq        $v0, $v1, .L80052660
/* 42E6C 8005266C 18002120 */   addi      $at, $at, 0x18 /* handwritten instruction */
/* 42E70 80052670 E8FF2120 */  addi       $at, $at, -0x18 /* handwritten instruction */
/* 42E74 80052674 E8FF2120 */  addi       $at, $at, -0x18 /* handwritten instruction */
/* 42E78 80052678 FFFF0320 */  addi       $v1, $zero, -0x1 /* handwritten instruction */
.L8005267C:
/* 42E7C 8005267C FFFF23A0 */  sb         $v1, -0x1($at)
/* 42E80 80052680 0780023C */  lui        $v0, %hi(D_80075930)
/* 42E84 80052684 30594224 */  addiu      $v0, $v0, %lo(D_80075930)
/* 42E88 80052688 0000438C */  lw         $v1, 0x0($v0)
/* 42E8C 8005268C 00000000 */  nop
/* 42E90 80052690 22186100 */  sub        $v1, $v1, $at /* handwritten instruction */
/* 42E94 80052694 0200601C */  bgtz       $v1, .L800526A0
/* 42E98 80052698 00000000 */   nop
/* 42E9C 8005269C 000041AC */  sw         $at, 0x0($v0)
.L800526A0:
/* 42EA0 800526A0 0800E003 */  jr         $ra
/* 42EA4 800526A4 00000000 */   nop
.size func_80052568, . - func_80052568

/* Handwritten function */
glabel func_800526A8
/* 42EA8 800526A8 36008194 */  lhu        $at, 0x36($a0)
/* 42EAC 800526AC 0780023C */  lui        $v0, %hi(D_80076378)
/* 42EB0 800526B0 78634224 */  addiu      $v0, $v0, %lo(D_80076378)
/* 42EB4 800526B4 80080100 */  sll        $at, $at, 2
/* 42EB8 800526B8 20082200 */  add        $at, $at, $v0 /* handwritten instruction */
/* 42EBC 800526BC 3C008290 */  lbu        $v0, 0x3C($a0)
/* 42EC0 800526C0 0000218C */  lw         $at, 0x0($at)
/* 42EC4 800526C4 80100200 */  sll        $v0, $v0, 2
/* 42EC8 800526C8 20104100 */  add        $v0, $v0, $at /* handwritten instruction */
/* 42ECC 800526CC 3E008390 */  lbu        $v1, 0x3E($a0)
/* 42ED0 800526D0 3800428C */  lw         $v0, 0x38($v0)
/* 42ED4 800526D4 C0180300 */  sll        $v1, $v1, 3
/* 42ED8 800526D8 0C004590 */  lbu        $a1, 0xC($v0)
/* 42EDC 800526DC 20104300 */  add        $v0, $v0, $v1 /* handwritten instruction */
/* 42EE0 800526E0 2400438C */  lw         $v1, 0x24($v0)
/* 42EE4 800526E4 410085A0 */  sb         $a1, 0x41($a0)
/* 42EE8 800526E8 C21C0300 */  srl        $v1, $v1, 19
/* 42EEC 800526EC 1C006330 */  andi       $v1, $v1, 0x1C
/* 42EF0 800526F0 20102300 */  add        $v0, $at, $v1 /* handwritten instruction */
/* 42EF4 800526F4 1400428C */  lw         $v0, 0x14($v0)
/* 42EF8 800526F8 1400218C */  lw         $at, 0x14($at)
/* 42EFC 800526FC 080082AC */  sw         $v0, 0x8($a0)
/* 42F00 80052700 FFFF0220 */  addi       $v0, $zero, -0x1 /* handwritten instruction */
/* 42F04 80052704 14002010 */  beqz       $at, .L80052758
/* 42F08 80052708 340082A4 */   sh        $v0, 0x34($a0)
/* 42F0C 8005270C 0C00828C */  lw         $v0, 0xC($a0)
/* 42F10 80052710 1000838C */  lw         $v1, 0x10($a0)
/* 42F14 80052714 0780053C */  lui        $a1, %hi(D_80075778)
/* 42F18 80052718 7857A524 */  addiu      $a1, $a1, %lo(D_80075778)
/* 42F1C 8005271C 0000A58C */  lw         $a1, 0x0($a1)
/* 42F20 80052720 42130200 */  srl        $v0, $v0, 13
/* 42F24 80052724 421B0300 */  srl        $v1, $v1, 13
/* 42F28 80052728 40190300 */  sll        $v1, $v1, 5
/* 42F2C 8005272C 20104300 */  add        $v0, $v0, $v1 /* handwritten instruction */
/* 42F30 80052730 02002004 */  bltz       $at, .L8005273C
/* 42F34 80052734 00000620 */   addi      $a2, $zero, 0x0 /* handwritten instruction */
/* 42F38 80052738 00040620 */  addi       $a2, $zero, 0x400 /* handwritten instruction */
.L8005273C:
/* 42F3C 8005273C 20104600 */  add        $v0, $v0, $a2 /* handwritten instruction */
/* 42F40 80052740 340082A4 */  sh         $v0, 0x34($a0)
/* 42F44 80052744 80100200 */  sll        $v0, $v0, 2
/* 42F48 80052748 20104500 */  add        $v0, $v0, $a1 /* handwritten instruction */
/* 42F4C 8005274C 0000438C */  lw         $v1, 0x0($v0)
/* 42F50 80052750 000044AC */  sw         $a0, 0x0($v0)
/* 42F54 80052754 040083AC */  sw         $v1, 0x4($a0)
.L80052758:
/* 42F58 80052758 00008F20 */  addi       $t7, $a0, 0x0 /* handwritten instruction */
/* 42F5C 8005275C 4400E18D */  lw         $at, 0x44($t7)
/* 42F60 80052760 0780023C */  lui        $v0, %hi(D_8006CBF8)
/* 42F64 80052764 F8CB4224 */  addiu      $v0, $v0, %lo(D_8006CBF8)
/* 42F68 80052768 0780033C */  lui        $v1, %hi(D_8006CC78)
/* 42F6C 8005276C 78CC6324 */  addiu      $v1, $v1, %lo(D_8006CC78)
/* 42F70 80052770 00100A20 */  addi       $t2, $zero, 0x1000 /* handwritten instruction */
/* 42F74 80052774 00000B20 */  addi       $t3, $zero, 0x0 /* handwritten instruction */
/* 42F78 80052778 00100C20 */  addi       $t4, $zero, 0x1000 /* handwritten instruction */
/* 42F7C 8005277C 00000D20 */  addi       $t5, $zero, 0x0 /* handwritten instruction */
/* 42F80 80052780 00100E20 */  addi       $t6, $zero, 0x1000 /* handwritten instruction */
/* 42F84 80052784 0000CA48 */  ctc2       $t2, $0 /* handwritten instruction */
/* 42F88 80052788 0008CB48 */  ctc2       $t3, $1 /* handwritten instruction */
/* 42F8C 8005278C 0010CC48 */  ctc2       $t4, $2 /* handwritten instruction */
/* 42F90 80052790 0018CD48 */  ctc2       $t5, $3 /* handwritten instruction */
/* 42F94 80052794 0020CE48 */  ctc2       $t6, $4 /* handwritten instruction */
/* 42F98 80052798 0028C048 */  ctc2       $zero, $5 /* handwritten instruction */
/* 42F9C 8005279C 0030C048 */  ctc2       $zero, $6 /* handwritten instruction */
/* 42FA0 800527A0 0038C048 */  ctc2       $zero, $7 /* handwritten instruction */
/* 42FA4 800527A4 C2230100 */  srl        $a0, $at, 15
/* 42FA8 800527A8 FE018430 */  andi       $a0, $a0, 0x1FE
/* 42FAC 800527AC 2A008010 */  beqz       $a0, .L80052858
/* 42FB0 800527B0 20288300 */   add       $a1, $a0, $v1 /* handwritten instruction */
/* 42FB4 800527B4 20208200 */  add        $a0, $a0, $v0 /* handwritten instruction */
/* 42FB8 800527B8 0000A594 */  lhu        $a1, 0x0($a1)
/* 42FBC 800527BC 00008494 */  lhu        $a0, 0x0($a0)
/* 42FC0 800527C0 FFFFA530 */  andi       $a1, $a1, 0xFFFF
/* 42FC4 800527C4 00008548 */  mtc2       $a1, $0 /* handwritten instruction */
/* 42FC8 800527C8 00088448 */  mtc2       $a0, $1 /* handwritten instruction */
/* 42FCC 800527CC 00000000 */  nop
/* 42FD0 800527D0 00000000 */  nop
/* 42FD4 800527D4 1260484A */  MVMVA      1, 0, 0, 3, 0
/* 42FD8 800527D8 22200400 */  neg        $a0, $a0 /* handwritten instruction */
/* 42FDC 800527DC FFFF8430 */  andi       $a0, $a0, 0xFFFF
/* 42FE0 800527E0 FFFFA530 */  andi       $a1, $a1, 0xFFFF
/* 42FE4 800527E4 00480748 */  mfc2       $a3, $9 /* handwritten instruction */
/* 42FE8 800527E8 00500848 */  mfc2       $t0, $10 /* handwritten instruction */
/* 42FEC 800527EC 00580948 */  mfc2       $t1, $11 /* handwritten instruction */
/* 42FF0 800527F0 00008448 */  mtc2       $a0, $0 /* handwritten instruction */
/* 42FF4 800527F4 00088548 */  mtc2       $a1, $1 /* handwritten instruction */
/* 42FF8 800527F8 00000000 */  nop
/* 42FFC 800527FC FFFF063C */  lui        $a2, (0xFFFF0000 >> 16)
/* 43000 80052800 1260484A */  MVMVA      1, 0, 0, 3, 0
/* 43004 80052804 24504601 */  and        $t2, $t2, $a2
/* 43008 80052808 FFFFE730 */  andi       $a3, $a3, 0xFFFF
/* 4300C 8005280C 20504701 */  add        $t2, $t2, $a3 /* handwritten instruction */
/* 43010 80052810 2468A601 */  and        $t5, $t5, $a2
/* 43014 80052814 FFFF2931 */  andi       $t1, $t1, 0xFFFF
/* 43018 80052818 2068A901 */  add        $t5, $t5, $t1 /* handwritten instruction */
/* 4301C 8005281C 00440800 */  sll        $t0, $t0, 16
/* 43020 80052820 FFFF8C31 */  andi       $t4, $t4, 0xFFFF
/* 43024 80052824 00480448 */  mfc2       $a0, $9 /* handwritten instruction */
/* 43028 80052828 00500548 */  mfc2       $a1, $10 /* handwritten instruction */
/* 4302C 8005282C 00580648 */  mfc2       $a2, $11 /* handwritten instruction */
/* 43030 80052830 FFFF8430 */  andi       $a0, $a0, 0xFFFF
/* 43034 80052834 20588800 */  add        $t3, $a0, $t0 /* handwritten instruction */
/* 43038 80052838 002C0500 */  sll        $a1, $a1, 16
/* 4303C 8005283C 20608501 */  add        $t4, $t4, $a1 /* handwritten instruction */
/* 43040 80052840 FFFFCE30 */  andi       $t6, $a2, 0xFFFF
/* 43044 80052844 0000CA48 */  ctc2       $t2, $0 /* handwritten instruction */
/* 43048 80052848 0008CB48 */  ctc2       $t3, $1 /* handwritten instruction */
/* 4304C 8005284C 0010CC48 */  ctc2       $t4, $2 /* handwritten instruction */
/* 43050 80052850 0018CD48 */  ctc2       $t5, $3 /* handwritten instruction */
/* 43054 80052854 0020CE48 */  ctc2       $t6, $4 /* handwritten instruction */
.L80052858:
/* 43058 80052858 00FF2430 */  andi       $a0, $at, 0xFF00
/* 4305C 8005285C 2B008010 */  beqz       $a0, .L8005290C
/* 43060 80052860 02220400 */   srl       $a0, $a0, 8
/* 43064 80052864 40200400 */  sll        $a0, $a0, 1
/* 43068 80052868 20288300 */  add        $a1, $a0, $v1 /* handwritten instruction */
/* 4306C 8005286C 20208200 */  add        $a0, $a0, $v0 /* handwritten instruction */
/* 43070 80052870 0000A594 */  lhu        $a1, 0x0($a1)
/* 43074 80052874 00008494 */  lhu        $a0, 0x0($a0)
/* 43078 80052878 00340500 */  sll        $a2, $a1, 16
/* 4307C 8005287C 00008648 */  mtc2       $a2, $0 /* handwritten instruction */
/* 43080 80052880 00088448 */  mtc2       $a0, $1 /* handwritten instruction */
/* 43084 80052884 00000000 */  nop
/* 43088 80052888 00000000 */  nop
/* 4308C 8005288C 1260484A */  MVMVA      1, 0, 0, 3, 0
/* 43090 80052890 00340400 */  sll        $a2, $a0, 16
/* 43094 80052894 22300600 */  neg        $a2, $a2 /* handwritten instruction */
/* 43098 80052898 00480748 */  mfc2       $a3, $9 /* handwritten instruction */
/* 4309C 8005289C 00500848 */  mfc2       $t0, $10 /* handwritten instruction */
/* 430A0 800528A0 00580948 */  mfc2       $t1, $11 /* handwritten instruction */
/* 430A4 800528A4 00008648 */  mtc2       $a2, $0 /* handwritten instruction */
/* 430A8 800528A8 00088548 */  mtc2       $a1, $1 /* handwritten instruction */
/* 430AC 800528AC 00000000 */  nop
/* 430B0 800528B0 FFFF063C */  lui        $a2, (0xFFFF0000 >> 16)
/* 430B4 800528B4 1260484A */  MVMVA      1, 0, 0, 3, 0
/* 430B8 800528B8 FFFF4A31 */  andi       $t2, $t2, 0xFFFF
/* 430BC 800528BC 003C0700 */  sll        $a3, $a3, 16
/* 430C0 800528C0 20504701 */  add        $t2, $t2, $a3 /* handwritten instruction */
/* 430C4 800528C4 FFFFAD31 */  andi       $t5, $t5, 0xFFFF
/* 430C8 800528C8 004C0900 */  sll        $t1, $t1, 16
/* 430CC 800528CC 2068A901 */  add        $t5, $t5, $t1 /* handwritten instruction */
/* 430D0 800528D0 FFFF0831 */  andi       $t0, $t0, 0xFFFF
/* 430D4 800528D4 24586601 */  and        $t3, $t3, $a2
/* 430D8 800528D8 00480448 */  mfc2       $a0, $9 /* handwritten instruction */
/* 430DC 800528DC 00500548 */  mfc2       $a1, $10 /* handwritten instruction */
/* 430E0 800528E0 00580648 */  mfc2       $a2, $11 /* handwritten instruction */
/* 430E4 800528E4 FFFF8430 */  andi       $a0, $a0, 0xFFFF
/* 430E8 800528E8 20586401 */  add        $t3, $t3, $a0 /* handwritten instruction */
/* 430EC 800528EC 002C0500 */  sll        $a1, $a1, 16
/* 430F0 800528F0 2060A800 */  add        $t4, $a1, $t0 /* handwritten instruction */
/* 430F4 800528F4 FFFFCE30 */  andi       $t6, $a2, 0xFFFF
/* 430F8 800528F8 0000CA48 */  ctc2       $t2, $0 /* handwritten instruction */
/* 430FC 800528FC 0008CB48 */  ctc2       $t3, $1 /* handwritten instruction */
/* 43100 80052900 0010CC48 */  ctc2       $t4, $2 /* handwritten instruction */
/* 43104 80052904 0018CD48 */  ctc2       $t5, $3 /* handwritten instruction */
/* 43108 80052908 0020CE48 */  ctc2       $t6, $4 /* handwritten instruction */
.L8005290C:
/* 4310C 8005290C FF002430 */  andi       $a0, $at, 0xFF
/* 43110 80052910 27008010 */  beqz       $a0, .L800529B0
/* 43114 80052914 40200400 */   sll       $a0, $a0, 1
/* 43118 80052918 20288300 */  add        $a1, $a0, $v1 /* handwritten instruction */
/* 4311C 8005291C 20208200 */  add        $a0, $a0, $v0 /* handwritten instruction */
/* 43120 80052920 0000A594 */  lhu        $a1, 0x0($a1)
/* 43124 80052924 00008494 */  lhu        $a0, 0x0($a0)
/* 43128 80052928 00088048 */  mtc2       $zero, $1 /* handwritten instruction */
/* 4312C 8005292C 00340400 */  sll        $a2, $a0, 16
/* 43130 80052930 2030C500 */  add        $a2, $a2, $a1 /* handwritten instruction */
/* 43134 80052934 00008648 */  mtc2       $a2, $0 /* handwritten instruction */
/* 43138 80052938 00000000 */  nop
/* 4313C 8005293C 00000000 */  nop
/* 43140 80052940 1260484A */  MVMVA      1, 0, 0, 3, 0
/* 43144 80052944 22200400 */  neg        $a0, $a0 /* handwritten instruction */
/* 43148 80052948 FFFF8430 */  andi       $a0, $a0, 0xFFFF
/* 4314C 8005294C 002C0500 */  sll        $a1, $a1, 16
/* 43150 80052950 20208500 */  add        $a0, $a0, $a1 /* handwritten instruction */
/* 43154 80052954 00480748 */  mfc2       $a3, $9 /* handwritten instruction */
/* 43158 80052958 00500848 */  mfc2       $t0, $10 /* handwritten instruction */
/* 4315C 8005295C 00580948 */  mfc2       $t1, $11 /* handwritten instruction */
/* 43160 80052960 00008448 */  mtc2       $a0, $0 /* handwritten instruction */
/* 43164 80052964 00088048 */  mtc2       $zero, $1 /* handwritten instruction */
/* 43168 80052968 00000000 */  nop
/* 4316C 8005296C FFFF063C */  lui        $a2, (0xFFFF0000 >> 16)
/* 43170 80052970 1260484A */  MVMVA      1, 0, 0, 3, 0
/* 43174 80052974 00440800 */  sll        $t0, $t0, 16
/* 43178 80052978 FFFF6B31 */  andi       $t3, $t3, 0xFFFF
/* 4317C 8005297C 20586801 */  add        $t3, $t3, $t0 /* handwritten instruction */
/* 43180 80052980 FFFFE730 */  andi       $a3, $a3, 0xFFFF
/* 43184 80052984 FFFF2931 */  andi       $t1, $t1, 0xFFFF
/* 43188 80052988 24608601 */  and        $t4, $t4, $a2
/* 4318C 8005298C 00480448 */  mfc2       $a0, $9 /* handwritten instruction */
/* 43190 80052990 00500548 */  mfc2       $a1, $10 /* handwritten instruction */
/* 43194 80052994 00580648 */  mfc2       $a2, $11 /* handwritten instruction */
/* 43198 80052998 00240400 */  sll        $a0, $a0, 16
/* 4319C 8005299C 20508700 */  add        $t2, $a0, $a3 /* handwritten instruction */
/* 431A0 800529A0 00340600 */  sll        $a2, $a2, 16
/* 431A4 800529A4 2068C900 */  add        $t5, $a2, $t1 /* handwritten instruction */
/* 431A8 800529A8 FFFFA530 */  andi       $a1, $a1, 0xFFFF
/* 431AC 800529AC 20608501 */  add        $t4, $t4, $a1 /* handwritten instruction */
.L800529B0:
/* 431B0 800529B0 2000EAAD */  sw         $t2, 0x20($t7)
/* 431B4 800529B4 2400EBAD */  sw         $t3, 0x24($t7)
/* 431B8 800529B8 2800ECAD */  sw         $t4, 0x28($t7)
/* 431BC 800529BC 2C00EDAD */  sw         $t5, 0x2C($t7)
/* 431C0 800529C0 3000EEAD */  sw         $t6, 0x30($t7)
/* 431C4 800529C4 0800E003 */  jr         $ra
/* 431C8 800529C8 00000000 */   nop
.size func_800526A8, . - func_800526A8

/* Handwritten function */
glabel func_800529CC
/* 431CC 800529CC 4B0080A0 */  sb         $zero, 0x4B($a0)
/* 431D0 800529D0 410080A0 */  sb         $zero, 0x41($a0)
/* 431D4 800529D4 080080AC */  sw         $zero, 0x8($a0)
/* 431D8 800529D8 FFFF0120 */  addi       $at, $zero, -0x1 /* handwritten instruction */
/* 431DC 800529DC 0800E003 */  jr         $ra
/* 431E0 800529E0 340081A4 */   sh        $at, 0x34($a0)
.size func_800529CC, . - func_800529CC

/* Handwritten function */
glabel func_800529E4
/* 431E4 800529E4 0100A130 */  andi       $at, $a1, 0x1
/* 431E8 800529E8 1E002010 */  beqz       $at, .L80052A64
/* 431EC 800529EC 00000000 */   nop
/* 431F0 800529F0 36008194 */  lhu        $at, 0x36($a0)
/* 431F4 800529F4 0780023C */  lui        $v0, %hi(D_80076378)
/* 431F8 800529F8 78634224 */  addiu      $v0, $v0, %lo(D_80076378)
/* 431FC 800529FC 80080100 */  sll        $at, $at, 2
/* 43200 80052A00 20082200 */  add        $at, $at, $v0 /* handwritten instruction */
/* 43204 80052A04 40008290 */  lbu        $v0, 0x40($a0)
/* 43208 80052A08 3C00838C */  lw         $v1, 0x3C($a0)
/* 4320C 80052A0C 0000218C */  lw         $at, 0x0($at)
/* 43210 80052A10 0400401C */  bgtz       $v0, .L80052A24
/* 43214 80052A14 FF006230 */   andi      $v0, $v1, 0xFF
/* 43218 80052A18 021C0300 */  srl        $v1, $v1, 16
/* 4321C 80052A1C 8C4A0108 */  j          .L80052A30
/* 43220 80052A20 FF006330 */   andi      $v1, $v1, 0xFF
.L80052A24:
/* 43224 80052A24 02120300 */  srl        $v0, $v1, 8
/* 43228 80052A28 FF004230 */  andi       $v0, $v0, 0xFF
/* 4322C 80052A2C 021E0300 */  srl        $v1, $v1, 24
.L80052A30:
/* 43230 80052A30 80100200 */  sll        $v0, $v0, 2
/* 43234 80052A34 20104100 */  add        $v0, $v0, $at /* handwritten instruction */
/* 43238 80052A38 3800428C */  lw         $v0, 0x38($v0)
/* 4323C 80052A3C C0180300 */  sll        $v1, $v1, 3
/* 43240 80052A40 20104300 */  add        $v0, $v0, $v1 /* handwritten instruction */
/* 43244 80052A44 2400438C */  lw         $v1, 0x24($v0)
/* 43248 80052A48 00000000 */  nop
/* 4324C 80052A4C C21C0300 */  srl        $v1, $v1, 19
/* 43250 80052A50 1C006330 */  andi       $v1, $v1, 0x1C
/* 43254 80052A54 20102300 */  add        $v0, $at, $v1 /* handwritten instruction */
/* 43258 80052A58 1400428C */  lw         $v0, 0x14($v0)
/* 4325C 80052A5C 00000000 */  nop
/* 43260 80052A60 080082AC */  sw         $v0, 0x8($a0)
.L80052A64:
/* 43264 80052A64 0200A130 */  andi       $at, $a1, 0x2
/* 43268 80052A68 20002010 */  beqz       $at, .L80052AEC
/* 4326C 80052A6C 00000000 */   nop
/* 43270 80052A70 0C00818C */  lw         $at, 0xC($a0)
/* 43274 80052A74 1000828C */  lw         $v0, 0x10($a0)
/* 43278 80052A78 0780033C */  lui        $v1, %hi(D_80075778)
/* 4327C 80052A7C 78576324 */  addiu      $v1, $v1, %lo(D_80075778)
/* 43280 80052A80 0000638C */  lw         $v1, 0x0($v1)
/* 43284 80052A84 420B0100 */  srl        $at, $at, 13
/* 43288 80052A88 42130200 */  srl        $v0, $v0, 13
/* 4328C 80052A8C 40110200 */  sll        $v0, $v0, 5
/* 43290 80052A90 34008684 */  lh         $a2, 0x34($a0)
/* 43294 80052A94 20082200 */  add        $at, $at, $v0 /* handwritten instruction */
/* 43298 80052A98 0004C730 */  andi       $a3, $a2, 0x400
/* 4329C 80052A9C 25082700 */  or         $at, $at, $a3
/* 432A0 80052AA0 12002610 */  beq        $at, $a2, .L80052AEC
/* 432A4 80052AA4 80300600 */   sll       $a2, $a2, 2
/* 432A8 80052AA8 1000C004 */  bltz       $a2, .L80052AEC
/* 432AC 80052AAC 2030C300 */   add       $a2, $a2, $v1 /* handwritten instruction */
/* 432B0 80052AB0 FCFFC220 */  addi       $v0, $a2, -0x4 /* handwritten instruction */
.L80052AB4:
/* 432B4 80052AB4 04004620 */  addi       $a2, $v0, 0x4 /* handwritten instruction */
/* 432B8 80052AB8 0000C28C */  lw         $v0, 0x0($a2)
/* 432BC 80052ABC 00000000 */  nop
/* 432C0 80052AC0 FCFF4414 */  bne        $v0, $a0, .L80052AB4
/* 432C4 80052AC4 00000000 */   nop
/* 432C8 80052AC8 0400828C */  lw         $v0, 0x4($a0)
/* 432CC 80052ACC 00000000 */  nop
/* 432D0 80052AD0 0000C2AC */  sw         $v0, 0x0($a2)
/* 432D4 80052AD4 340081A4 */  sh         $at, 0x34($a0)
/* 432D8 80052AD8 80080100 */  sll        $at, $at, 2
/* 432DC 80052ADC 20082300 */  add        $at, $at, $v1 /* handwritten instruction */
/* 432E0 80052AE0 0000228C */  lw         $v0, 0x0($at)
/* 432E4 80052AE4 000024AC */  sw         $a0, 0x0($at)
/* 432E8 80052AE8 040082AC */  sw         $v0, 0x4($a0)
.L80052AEC:
/* 432EC 80052AEC 0400A130 */  andi       $at, $a1, 0x4
/* 432F0 80052AF0 9A002010 */  beqz       $at, .L80052D5C
/* 432F4 80052AF4 00008F20 */   addi      $t7, $a0, 0x0 /* handwritten instruction */
/* 432F8 80052AF8 4400EC8D */  lw         $t4, 0x44($t7)
/* 432FC 80052AFC 07800D3C */  lui        $t5, %hi(D_8006CBF8)
/* 43300 80052B00 F8CBAD25 */  addiu      $t5, $t5, %lo(D_8006CBF8)
/* 43304 80052B04 07800E3C */  lui        $t6, %hi(D_8006CC78)
/* 43308 80052B08 78CCCE25 */  addiu      $t6, $t6, %lo(D_8006CC78)
/* 4330C 80052B0C 00100720 */  addi       $a3, $zero, 0x1000 /* handwritten instruction */
/* 43310 80052B10 00000820 */  addi       $t0, $zero, 0x0 /* handwritten instruction */
/* 43314 80052B14 00100920 */  addi       $t1, $zero, 0x1000 /* handwritten instruction */
/* 43318 80052B18 00000A20 */  addi       $t2, $zero, 0x0 /* handwritten instruction */
/* 4331C 80052B1C 00100B20 */  addi       $t3, $zero, 0x1000 /* handwritten instruction */
/* 43320 80052B20 0000C748 */  ctc2       $a3, $0 /* handwritten instruction */
/* 43324 80052B24 0008C848 */  ctc2       $t0, $1 /* handwritten instruction */
/* 43328 80052B28 0010C948 */  ctc2       $t1, $2 /* handwritten instruction */
/* 4332C 80052B2C 0018CA48 */  ctc2       $t2, $3 /* handwritten instruction */
/* 43330 80052B30 0020CB48 */  ctc2       $t3, $4 /* handwritten instruction */
/* 43334 80052B34 0028C048 */  ctc2       $zero, $5 /* handwritten instruction */
/* 43338 80052B38 0030C048 */  ctc2       $zero, $6 /* handwritten instruction */
/* 4333C 80052B3C 0038C048 */  ctc2       $zero, $7 /* handwritten instruction */
/* 43340 80052B40 C20B0C00 */  srl        $at, $t4, 15
/* 43344 80052B44 FE012130 */  andi       $at, $at, 0x1FE
/* 43348 80052B48 29002010 */  beqz       $at, .L80052BF0
/* 4334C 80052B4C 20102E00 */   add       $v0, $at, $t6 /* handwritten instruction */
/* 43350 80052B50 20082D00 */  add        $at, $at, $t5 /* handwritten instruction */
/* 43354 80052B54 00004294 */  lhu        $v0, 0x0($v0)
/* 43358 80052B58 00002194 */  lhu        $at, 0x0($at)
/* 4335C 80052B5C FFFF4230 */  andi       $v0, $v0, 0xFFFF
/* 43360 80052B60 00008248 */  mtc2       $v0, $0 /* handwritten instruction */
/* 43364 80052B64 00088148 */  mtc2       $at, $1 /* handwritten instruction */
/* 43368 80052B68 00000000 */  nop
/* 4336C 80052B6C 00000000 */  nop
/* 43370 80052B70 1260484A */  MVMVA      1, 0, 0, 3, 0
/* 43374 80052B74 22080100 */  neg        $at, $at /* handwritten instruction */
/* 43378 80052B78 FFFF2130 */  andi       $at, $at, 0xFFFF
/* 4337C 80052B7C 00480448 */  mfc2       $a0, $9 /* handwritten instruction */
/* 43380 80052B80 00500548 */  mfc2       $a1, $10 /* handwritten instruction */
/* 43384 80052B84 00580648 */  mfc2       $a2, $11 /* handwritten instruction */
/* 43388 80052B88 00008148 */  mtc2       $at, $0 /* handwritten instruction */
/* 4338C 80052B8C 00088248 */  mtc2       $v0, $1 /* handwritten instruction */
/* 43390 80052B90 00000000 */  nop
/* 43394 80052B94 FFFF033C */  lui        $v1, (0xFFFF0000 >> 16)
/* 43398 80052B98 1260484A */  MVMVA      1, 0, 0, 3, 0
/* 4339C 80052B9C 2438E300 */  and        $a3, $a3, $v1
/* 433A0 80052BA0 FFFF8430 */  andi       $a0, $a0, 0xFFFF
/* 433A4 80052BA4 2038E400 */  add        $a3, $a3, $a0 /* handwritten instruction */
/* 433A8 80052BA8 24504301 */  and        $t2, $t2, $v1
/* 433AC 80052BAC FFFFC630 */  andi       $a2, $a2, 0xFFFF
/* 433B0 80052BB0 20504601 */  add        $t2, $t2, $a2 /* handwritten instruction */
/* 433B4 80052BB4 002C0500 */  sll        $a1, $a1, 16
/* 433B8 80052BB8 FFFF2931 */  andi       $t1, $t1, 0xFFFF
/* 433BC 80052BBC 00480148 */  mfc2       $at, $9 /* handwritten instruction */
/* 433C0 80052BC0 00500248 */  mfc2       $v0, $10 /* handwritten instruction */
/* 433C4 80052BC4 00580348 */  mfc2       $v1, $11 /* handwritten instruction */
/* 433C8 80052BC8 FFFF2130 */  andi       $at, $at, 0xFFFF
/* 433CC 80052BCC 20402500 */  add        $t0, $at, $a1 /* handwritten instruction */
/* 433D0 80052BD0 00140200 */  sll        $v0, $v0, 16
/* 433D4 80052BD4 20482201 */  add        $t1, $t1, $v0 /* handwritten instruction */
/* 433D8 80052BD8 FFFF6B30 */  andi       $t3, $v1, 0xFFFF
/* 433DC 80052BDC 0000C748 */  ctc2       $a3, $0 /* handwritten instruction */
/* 433E0 80052BE0 0008C848 */  ctc2       $t0, $1 /* handwritten instruction */
/* 433E4 80052BE4 0010C948 */  ctc2       $t1, $2 /* handwritten instruction */
/* 433E8 80052BE8 0018CA48 */  ctc2       $t2, $3 /* handwritten instruction */
/* 433EC 80052BEC 0020CB48 */  ctc2       $t3, $4 /* handwritten instruction */
.L80052BF0:
/* 433F0 80052BF0 00FF8131 */  andi       $at, $t4, 0xFF00
/* 433F4 80052BF4 2B002010 */  beqz       $at, .L80052CA4
/* 433F8 80052BF8 020A0100 */   srl       $at, $at, 8
/* 433FC 80052BFC 40080100 */  sll        $at, $at, 1
/* 43400 80052C00 20102E00 */  add        $v0, $at, $t6 /* handwritten instruction */
/* 43404 80052C04 20082D00 */  add        $at, $at, $t5 /* handwritten instruction */
/* 43408 80052C08 00004294 */  lhu        $v0, 0x0($v0)
/* 4340C 80052C0C 00002194 */  lhu        $at, 0x0($at)
/* 43410 80052C10 001C0200 */  sll        $v1, $v0, 16
/* 43414 80052C14 00008348 */  mtc2       $v1, $0 /* handwritten instruction */
/* 43418 80052C18 00088148 */  mtc2       $at, $1 /* handwritten instruction */
/* 4341C 80052C1C 00000000 */  nop
/* 43420 80052C20 00000000 */  nop
/* 43424 80052C24 1260484A */  MVMVA      1, 0, 0, 3, 0
/* 43428 80052C28 001C0100 */  sll        $v1, $at, 16
/* 4342C 80052C2C 22180300 */  neg        $v1, $v1 /* handwritten instruction */
/* 43430 80052C30 00480448 */  mfc2       $a0, $9 /* handwritten instruction */
/* 43434 80052C34 00500548 */  mfc2       $a1, $10 /* handwritten instruction */
/* 43438 80052C38 00580648 */  mfc2       $a2, $11 /* handwritten instruction */
/* 4343C 80052C3C 00008348 */  mtc2       $v1, $0 /* handwritten instruction */
/* 43440 80052C40 00088248 */  mtc2       $v0, $1 /* handwritten instruction */
/* 43444 80052C44 00000000 */  nop
/* 43448 80052C48 FFFF033C */  lui        $v1, (0xFFFF0000 >> 16)
/* 4344C 80052C4C 1260484A */  MVMVA      1, 0, 0, 3, 0
/* 43450 80052C50 FFFFE730 */  andi       $a3, $a3, 0xFFFF
/* 43454 80052C54 00240400 */  sll        $a0, $a0, 16
/* 43458 80052C58 2038E400 */  add        $a3, $a3, $a0 /* handwritten instruction */
/* 4345C 80052C5C FFFF4A31 */  andi       $t2, $t2, 0xFFFF
/* 43460 80052C60 00340600 */  sll        $a2, $a2, 16
/* 43464 80052C64 20504601 */  add        $t2, $t2, $a2 /* handwritten instruction */
/* 43468 80052C68 FFFFA530 */  andi       $a1, $a1, 0xFFFF
/* 4346C 80052C6C 24400301 */  and        $t0, $t0, $v1
/* 43470 80052C70 00480148 */  mfc2       $at, $9 /* handwritten instruction */
/* 43474 80052C74 00500248 */  mfc2       $v0, $10 /* handwritten instruction */
/* 43478 80052C78 00580348 */  mfc2       $v1, $11 /* handwritten instruction */
/* 4347C 80052C7C FFFF2130 */  andi       $at, $at, 0xFFFF
/* 43480 80052C80 20400101 */  add        $t0, $t0, $at /* handwritten instruction */
/* 43484 80052C84 00140200 */  sll        $v0, $v0, 16
/* 43488 80052C88 20484500 */  add        $t1, $v0, $a1 /* handwritten instruction */
/* 4348C 80052C8C FFFF6B30 */  andi       $t3, $v1, 0xFFFF
/* 43490 80052C90 0000C748 */  ctc2       $a3, $0 /* handwritten instruction */
/* 43494 80052C94 0008C848 */  ctc2       $t0, $1 /* handwritten instruction */
/* 43498 80052C98 0010C948 */  ctc2       $t1, $2 /* handwritten instruction */
/* 4349C 80052C9C 0018CA48 */  ctc2       $t2, $3 /* handwritten instruction */
/* 434A0 80052CA0 0020CB48 */  ctc2       $t3, $4 /* handwritten instruction */
.L80052CA4:
/* 434A4 80052CA4 FF008131 */  andi       $at, $t4, 0xFF
/* 434A8 80052CA8 27002010 */  beqz       $at, .L80052D48
/* 434AC 80052CAC 40080100 */   sll       $at, $at, 1
/* 434B0 80052CB0 20102E00 */  add        $v0, $at, $t6 /* handwritten instruction */
/* 434B4 80052CB4 20082D00 */  add        $at, $at, $t5 /* handwritten instruction */
/* 434B8 80052CB8 00004294 */  lhu        $v0, 0x0($v0)
/* 434BC 80052CBC 00002194 */  lhu        $at, 0x0($at)
/* 434C0 80052CC0 00088048 */  mtc2       $zero, $1 /* handwritten instruction */
/* 434C4 80052CC4 001C0100 */  sll        $v1, $at, 16
/* 434C8 80052CC8 20186200 */  add        $v1, $v1, $v0 /* handwritten instruction */
/* 434CC 80052CCC 00008348 */  mtc2       $v1, $0 /* handwritten instruction */
/* 434D0 80052CD0 00000000 */  nop
/* 434D4 80052CD4 00000000 */  nop
/* 434D8 80052CD8 1260484A */  MVMVA      1, 0, 0, 3, 0
/* 434DC 80052CDC 22080100 */  neg        $at, $at /* handwritten instruction */
/* 434E0 80052CE0 FFFF2130 */  andi       $at, $at, 0xFFFF
/* 434E4 80052CE4 00140200 */  sll        $v0, $v0, 16
/* 434E8 80052CE8 20082200 */  add        $at, $at, $v0 /* handwritten instruction */
/* 434EC 80052CEC 00480448 */  mfc2       $a0, $9 /* handwritten instruction */
/* 434F0 80052CF0 00500548 */  mfc2       $a1, $10 /* handwritten instruction */
/* 434F4 80052CF4 00580648 */  mfc2       $a2, $11 /* handwritten instruction */
/* 434F8 80052CF8 00008148 */  mtc2       $at, $0 /* handwritten instruction */
/* 434FC 80052CFC 00088048 */  mtc2       $zero, $1 /* handwritten instruction */
/* 43500 80052D00 00000000 */  nop
/* 43504 80052D04 FFFF033C */  lui        $v1, (0xFFFF0000 >> 16)
/* 43508 80052D08 1260484A */  MVMVA      1, 0, 0, 3, 0
/* 4350C 80052D0C 002C0500 */  sll        $a1, $a1, 16
/* 43510 80052D10 FFFF0831 */  andi       $t0, $t0, 0xFFFF
/* 43514 80052D14 20400501 */  add        $t0, $t0, $a1 /* handwritten instruction */
/* 43518 80052D18 FFFF8430 */  andi       $a0, $a0, 0xFFFF
/* 4351C 80052D1C FFFFC630 */  andi       $a2, $a2, 0xFFFF
/* 43520 80052D20 24482301 */  and        $t1, $t1, $v1
/* 43524 80052D24 00480148 */  mfc2       $at, $9 /* handwritten instruction */
/* 43528 80052D28 00500248 */  mfc2       $v0, $10 /* handwritten instruction */
/* 4352C 80052D2C 00580348 */  mfc2       $v1, $11 /* handwritten instruction */
/* 43530 80052D30 000C0100 */  sll        $at, $at, 16
/* 43534 80052D34 20382400 */  add        $a3, $at, $a0 /* handwritten instruction */
/* 43538 80052D38 001C0300 */  sll        $v1, $v1, 16
/* 4353C 80052D3C 20506600 */  add        $t2, $v1, $a2 /* handwritten instruction */
/* 43540 80052D40 FFFF4230 */  andi       $v0, $v0, 0xFFFF
/* 43544 80052D44 20482201 */  add        $t1, $t1, $v0 /* handwritten instruction */
.L80052D48:
/* 43548 80052D48 2000E7AD */  sw         $a3, 0x20($t7)
/* 4354C 80052D4C 2400E8AD */  sw         $t0, 0x24($t7)
/* 43550 80052D50 2800E9AD */  sw         $t1, 0x28($t7)
/* 43554 80052D54 2C00EAAD */  sw         $t2, 0x2C($t7)
/* 43558 80052D58 3000EBAD */  sw         $t3, 0x30($t7)
.L80052D5C:
/* 4355C 80052D5C 0800E003 */  jr         $ra
/* 43560 80052D60 00000000 */   nop
.size func_800529E4, . - func_800529E4

/* Handwritten function */
glabel func_80052D64
/* 43564 80052D64 00009820 */  addi       $t8, $a0, 0x0 /* handwritten instruction */
/* 43568 80052D68 0000AF20 */  addi       $t7, $a1, 0x0 /* handwritten instruction */
/* 4356C 80052D6C 0000D920 */  addi       $t9, $a2, 0x0 /* handwritten instruction */
/* 43570 80052D70 2000018F */  lw         $at, 0x20($t8)
/* 43574 80052D74 2400028F */  lw         $v0, 0x24($t8)
/* 43578 80052D78 2800038F */  lw         $v1, 0x28($t8)
/* 4357C 80052D7C 2C00048F */  lw         $a0, 0x2C($t8)
/* 43580 80052D80 3000058F */  lw         $a1, 0x30($t8)
/* 43584 80052D84 0000C148 */  ctc2       $at, $0 /* handwritten instruction */
/* 43588 80052D88 0008C248 */  ctc2       $v0, $1 /* handwritten instruction */
/* 4358C 80052D8C 0010C348 */  ctc2       $v1, $2 /* handwritten instruction */
/* 43590 80052D90 0018C448 */  ctc2       $a0, $3 /* handwritten instruction */
/* 43594 80052D94 0020C548 */  ctc2       $a1, $4 /* handwritten instruction */
/* 43598 80052D98 0028C048 */  ctc2       $zero, $5 /* handwritten instruction */
/* 4359C 80052D9C 0030C048 */  ctc2       $zero, $6 /* handwritten instruction */
/* 435A0 80052DA0 0038C048 */  ctc2       $zero, $7 /* handwritten instruction */
/* 435A4 80052DA4 36000197 */  lhu        $at, 0x36($t8)
/* 435A8 80052DA8 3C00058F */  lw         $a1, 0x3C($t8)
/* 435AC 80052DAC 0780023C */  lui        $v0, %hi(D_80076378)
/* 435B0 80052DB0 78634224 */  addiu      $v0, $v0, %lo(D_80076378)
/* 435B4 80052DB4 80080100 */  sll        $at, $at, 2
/* 435B8 80052DB8 20082200 */  add        $at, $at, $v0 /* handwritten instruction */
/* 435BC 80052DBC 0000218C */  lw         $at, 0x0($at)
/* 435C0 80052DC0 40000693 */  lbu        $a2, 0x40($t8)
/* 435C4 80052DC4 80100500 */  sll        $v0, $a1, 2
/* 435C8 80052DC8 FC034230 */  andi       $v0, $v0, 0x3FC
/* 435CC 80052DCC 20102200 */  add        $v0, $at, $v0 /* handwritten instruction */
/* 435D0 80052DD0 82190500 */  srl        $v1, $a1, 6
/* 435D4 80052DD4 FC036330 */  andi       $v1, $v1, 0x3FC
/* 435D8 80052DD8 20182300 */  add        $v1, $at, $v1 /* handwritten instruction */
/* 435DC 80052DDC 3800428C */  lw         $v0, 0x38($v0)
/* 435E0 80052DE0 42230500 */  srl        $a0, $a1, 13
/* 435E4 80052DE4 F8078430 */  andi       $a0, $a0, 0x7F8
/* 435E8 80052DE8 422D0500 */  srl        $a1, $a1, 21
/* 435EC 80052DEC F807A530 */  andi       $a1, $a1, 0x7F8
/* 435F0 80052DF0 20204400 */  add        $a0, $v0, $a0 /* handwritten instruction */
/* 435F4 80052DF4 2400848C */  lw         $a0, 0x24($a0)
/* 435F8 80052DF8 05004180 */  lb         $at, 0x5($v0)
/* 435FC 80052DFC C0220400 */  sll        $a0, $a0, 11
/* 43600 80052E00 C2220400 */  srl        $a0, $a0, 11
/* 43604 80052E04 80780F00 */  sll        $t7, $t7, 2
/* 43608 80052E08 20208F00 */  add        $a0, $a0, $t7 /* handwritten instruction */
/* 4360C 80052E0C 0B00C01C */  bgtz       $a2, .L80052E3C
/* 43610 80052E10 0000828C */   lw        $v0, 0x0($a0)
/* 43614 80052E14 00000000 */  nop
/* 43618 80052E18 002D0200 */  sll        $a1, $v0, 20
/* 4361C 80052E1C C32C0500 */  sra        $a1, $a1, 19
/* 43620 80052E20 80220200 */  sll        $a0, $v0, 10
/* 43624 80052E24 43250400 */  sra        $a0, $a0, 21
/* 43628 80052E28 431D0200 */  sra        $v1, $v0, 21
/* 4362C 80052E2C 04182300 */  sllv       $v1, $v1, $at
/* 43630 80052E30 04202400 */  sllv       $a0, $a0, $at
/* 43634 80052E34 BA4B0108 */  j          .L80052EE8
/* 43638 80052E38 04282500 */   sllv      $a1, $a1, $at
.L80052E3C:
/* 4363C 80052E3C 3800638C */  lw         $v1, 0x38($v1)
/* 43640 80052E40 004D0200 */  sll        $t1, $v0, 20
/* 43644 80052E44 C34C0900 */  sra        $t1, $t1, 19
/* 43648 80052E48 80420200 */  sll        $t0, $v0, 10
/* 4364C 80052E4C 43450800 */  sra        $t0, $t0, 21
/* 43650 80052E50 433D0200 */  sra        $a3, $v0, 21
/* 43654 80052E54 20286500 */  add        $a1, $v1, $a1 /* handwritten instruction */
/* 43658 80052E58 2400A58C */  lw         $a1, 0x24($a1)
/* 4365C 80052E5C 04382700 */  sllv       $a3, $a3, $at
/* 43660 80052E60 04402800 */  sllv       $t0, $t0, $at
/* 43664 80052E64 04482900 */  sllv       $t1, $t1, $at
/* 43668 80052E68 40000320 */  addi       $v1, $zero, 0x40 /* handwritten instruction */
/* 4366C 80052E6C 22186600 */  sub        $v1, $v1, $a2 /* handwritten instruction */
/* 43670 80052E70 C02A0500 */  sll        $a1, $a1, 11
/* 43674 80052E74 C22A0500 */  srl        $a1, $a1, 11
/* 43678 80052E78 00408348 */  mtc2       $v1, $8 /* handwritten instruction */
/* 4367C 80052E7C 00488748 */  mtc2       $a3, $9 /* handwritten instruction */
/* 43680 80052E80 00508848 */  mtc2       $t0, $10 /* handwritten instruction */
/* 43684 80052E84 00588948 */  mtc2       $t1, $11 /* handwritten instruction */
/* 43688 80052E88 2028AF00 */  add        $a1, $a1, $t7 /* handwritten instruction */
/* 4368C 80052E8C 0000A38C */  lw         $v1, 0x0($a1)
/* 43690 80052E90 3D00904B */  GPF        0
/* 43694 80052E94 002D0300 */  sll        $a1, $v1, 20
/* 43698 80052E98 C32C0500 */  sra        $a1, $a1, 19
/* 4369C 80052E9C 80220300 */  sll        $a0, $v1, 10
/* 436A0 80052EA0 43250400 */  sra        $a0, $a0, 21
/* 436A4 80052EA4 431D0300 */  sra        $v1, $v1, 21
/* 436A8 80052EA8 04182300 */  sllv       $v1, $v1, $at
/* 436AC 80052EAC 04202400 */  sllv       $a0, $a0, $at
/* 436B0 80052EB0 04282500 */  sllv       $a1, $a1, $at
/* 436B4 80052EB4 00408648 */  mtc2       $a2, $8 /* handwritten instruction */
/* 436B8 80052EB8 00488348 */  mtc2       $v1, $9 /* handwritten instruction */
/* 436BC 80052EBC 00508448 */  mtc2       $a0, $10 /* handwritten instruction */
/* 436C0 80052EC0 00588548 */  mtc2       $a1, $11 /* handwritten instruction */
/* 436C4 80052EC4 00000000 */  nop
/* 436C8 80052EC8 00000000 */  nop
/* 436CC 80052ECC 3E00A04B */  GPL        0
/* 436D0 80052ED0 00C80348 */  mfc2       $v1, $25 /* handwritten instruction */
/* 436D4 80052ED4 00D00448 */  mfc2       $a0, $26 /* handwritten instruction */
/* 436D8 80052ED8 00D80548 */  mfc2       $a1, $27 /* handwritten instruction */
/* 436DC 80052EDC 83190300 */  sra        $v1, $v1, 6
/* 436E0 80052EE0 83210400 */  sra        $a0, $a0, 6
/* 436E4 80052EE4 83290500 */  sra        $a1, $a1, 6
.L80052EE8:
/* 436E8 80052EE8 002C0500 */  sll        $a1, $a1, 16
/* 436EC 80052EEC 20208500 */  add        $a0, $a0, $a1 /* handwritten instruction */
/* 436F0 80052EF0 00088348 */  mtc2       $v1, $1 /* handwritten instruction */
/* 436F4 80052EF4 00008448 */  mtc2       $a0, $0 /* handwritten instruction */
/* 436F8 80052EF8 00000000 */  nop
/* 436FC 80052EFC 00000000 */  nop
/* 43700 80052F00 0100184A */  RTPS
/* 43704 80052F04 0C00018F */  lw         $at, 0xC($t8)
/* 43708 80052F08 1000028F */  lw         $v0, 0x10($t8)
/* 4370C 80052F0C 1400038F */  lw         $v1, 0x14($t8)
/* 43710 80052F10 00580448 */  mfc2       $a0, $11 /* handwritten instruction */
/* 43714 80052F14 00480548 */  mfc2       $a1, $9 /* handwritten instruction */
/* 43718 80052F18 00500648 */  mfc2       $a2, $10 /* handwritten instruction */
/* 4371C 80052F1C 20208100 */  add        $a0, $a0, $at /* handwritten instruction */
/* 43720 80052F20 22284500 */  sub        $a1, $v0, $a1 /* handwritten instruction */
/* 43724 80052F24 22306600 */  sub        $a2, $v1, $a2 /* handwritten instruction */
/* 43728 80052F28 000024AF */  sw         $a0, 0x0($t9)
/* 4372C 80052F2C 040025AF */  sw         $a1, 0x4($t9)
/* 43730 80052F30 0800E003 */  jr         $ra
/* 43734 80052F34 080026AF */   sw        $a2, 0x8($t9)
.size func_80052D64, . - func_80052D64

/* Handwritten function */
glabel func_80052F38
/* 43738 80052F38 00009820 */  addi       $t8, $a0, 0x0 /* handwritten instruction */
/* 4373C 80052F3C 0000B920 */  addi       $t9, $a1, 0x0 /* handwritten instruction */
/* 43740 80052F40 0000C120 */  addi       $at, $a2, 0x0 /* handwritten instruction */
/* 43744 80052F44 0000E220 */  addi       $v0, $a3, 0x0 /* handwritten instruction */
/* 43748 80052F48 08800F3C */  lui        $t7, %hi(g_Spyro)
/* 4374C 80052F4C 588AEF25 */  addiu      $t7, $t7, %lo(g_Spyro)
/* 43750 80052F50 07800E3C */  lui        $t6, %hi(D_80076378)
/* 43754 80052F54 7863CE25 */  addiu      $t6, $t6, %lo(D_80076378)
/* 43758 80052F58 0000CE8D */  lw         $t6, 0x0($t6)
/* 4375C 80052F5C 80080100 */  sll        $at, $at, 2
/* 43760 80052F60 20082E00 */  add        $at, $at, $t6 /* handwritten instruction */
/* 43764 80052F64 3800218C */  lw         $at, 0x38($at)
/* 43768 80052F68 80100200 */  sll        $v0, $v0, 2
/* 4376C 80052F6C 20104100 */  add        $v0, $v0, $at /* handwritten instruction */
/* 43770 80052F70 2400428C */  lw         $v0, 0x24($v0)
/* 43774 80052F74 00000000 */  nop
/* 43778 80052F78 423D0200 */  srl        $a3, $v0, 21
/* 4377C 80052F7C 0100E730 */  andi       $a3, $a3, 0x1
/* 43780 80052F80 C0120200 */  sll        $v0, $v0, 11
/* 43784 80052F84 82120200 */  srl        $v0, $v0, 10
/* 43788 80052F88 1000248C */  lw         $a0, 0x10($at)
/* 4378C 80052F8C 0800458C */  lw         $a1, 0x8($v0)
/* 43790 80052F90 18004620 */  addi       $a2, $v0, 0x18 /* handwritten instruction */
/* 43794 80052F94 022D0500 */  srl        $a1, $a1, 20
/* 43798 80052F98 2028A600 */  add        $a1, $a1, $a2 /* handwritten instruction */
/* 4379C 80052F9C 00000120 */  addi       $at, $zero, 0x0 /* handwritten instruction */
/* 437A0 80052FA0 00000220 */  addi       $v0, $zero, 0x0 /* handwritten instruction */
/* 437A4 80052FA4 00000320 */  addi       $v1, $zero, 0x0 /* handwritten instruction */
/* 437A8 80052FA8 07800E3C */  lui        $t6, %hi(D_8006D614)
/* 437AC 80052FAC 14D6CE25 */  addiu      $t6, $t6, %lo(D_8006D614)
.L80052FB0:
/* 437B0 80052FB0 1700E01C */  bgtz       $a3, .L80053010
/* 437B4 80052FB4 FFFF1823 */   addi      $t8, $t8, -0x1 /* handwritten instruction */
/* 437B8 80052FB8 0000A890 */  lbu        $t0, 0x0($a1)
/* 437BC 80052FBC 0000898C */  lw         $t1, 0x0($a0)
/* 437C0 80052FC0 0100A520 */  addi       $a1, $a1, 0x1 /* handwritten instruction */
/* 437C4 80052FC4 04008420 */  addi       $a0, $a0, 0x4 /* handwritten instruction */
/* 437C8 80052FC8 01000731 */  andi       $a3, $t0, 0x1
/* 437CC 80052FCC 40400800 */  sll        $t0, $t0, 1
/* 437D0 80052FD0 FC010831 */  andi       $t0, $t0, 0x1FC
/* 437D4 80052FD4 20400E01 */  add        $t0, $t0, $t6 /* handwritten instruction */
/* 437D8 80052FD8 0000088D */  lw         $t0, 0x0($t0)
/* 437DC 80052FDC 00000000 */  nop
/* 437E0 80052FE0 20400901 */  add        $t0, $t0, $t1 /* handwritten instruction */
/* 437E4 80052FE4 434D0800 */  sra        $t1, $t0, 21
/* 437E8 80052FE8 20082900 */  add        $at, $at, $t1 /* handwritten instruction */
/* 437EC 80052FEC C04A0800 */  sll        $t1, $t0, 11
/* 437F0 80052FF0 434D0900 */  sra        $t1, $t1, 21
/* 437F4 80052FF4 20104900 */  add        $v0, $v0, $t1 /* handwritten instruction */
/* 437F8 80052FF8 804D0800 */  sll        $t1, $t0, 22
/* 437FC 80052FFC 434D0900 */  sra        $t1, $t1, 21
/* 43800 80053000 EBFF0017 */  bnez       $t8, .L80052FB0
/* 43804 80053004 20186900 */   add       $v1, $v1, $t1 /* handwritten instruction */
/* 43808 80053008 2C4C0108 */  j          .L800530B0
/* 4380C 8005300C 00000000 */   nop
.L80053010:
/* 43810 80053010 0000C884 */  lh         $t0, 0x0($a2)
/* 43814 80053014 0200C620 */  addi       $a2, $a2, 0x2 /* handwritten instruction */
/* 43818 80053018 17000005 */  bltz       $t0, .L80053078
/* 4381C 8005301C 00400731 */   andi      $a3, $t0, 0x4000
/* 43820 80053020 0000898C */  lw         $t1, 0x0($a0)
/* 43824 80053024 04008420 */  addi       $a0, $a0, 0x4 /* handwritten instruction */
/* 43828 80053028 80540800 */  sll        $t2, $t0, 18
/* 4382C 8005302C 43560A00 */  sra        $t2, $t2, 25
/* 43830 80053030 20082A00 */  add        $at, $at, $t2 /* handwritten instruction */
/* 43834 80053034 C0550800 */  sll        $t2, $t0, 23
/* 43838 80053038 43560A00 */  sra        $t2, $t2, 25
/* 4383C 8005303C 20104A00 */  add        $v0, $v0, $t2 /* handwritten instruction */
/* 43840 80053040 00570800 */  sll        $t2, $t0, 28
/* 43844 80053044 43560A00 */  sra        $t2, $t2, 25
/* 43848 80053048 20186A00 */  add        $v1, $v1, $t2 /* handwritten instruction */
/* 4384C 8005304C 43450900 */  sra        $t0, $t1, 21
/* 43850 80053050 20082800 */  add        $at, $at, $t0 /* handwritten instruction */
/* 43854 80053054 C0420900 */  sll        $t0, $t1, 11
/* 43858 80053058 43450800 */  sra        $t0, $t0, 21
/* 4385C 8005305C 20104800 */  add        $v0, $v0, $t0 /* handwritten instruction */
/* 43860 80053060 80450900 */  sll        $t0, $t1, 22
/* 43864 80053064 43450800 */  sra        $t0, $t0, 21
/* 43868 80053068 D1FF0017 */  bnez       $t8, .L80052FB0
/* 4386C 8005306C 20186800 */   add       $v1, $v1, $t0 /* handwritten instruction */
/* 43870 80053070 2C4C0108 */  j          .L800530B0
/* 43874 80053074 00000000 */   nop
.L80053078:
/* 43878 80053078 0000C994 */  lhu        $t1, 0x0($a2)
/* 4387C 8005307C 0200C620 */  addi       $a2, $a2, 0x2 /* handwritten instruction */
/* 43880 80053080 04008420 */  addi       $a0, $a0, 0x4 /* handwritten instruction */
/* 43884 80053084 80540800 */  sll        $t2, $t0, 18
/* 43888 80053088 430D0A00 */  sra        $at, $t2, 21
/* 4388C 8005308C 00570800 */  sll        $t2, $t0, 28
/* 43890 80053090 00430900 */  sll        $t0, $t1, 12
/* 43894 80053094 25400A01 */  or         $t0, $t0, $t2
/* 43898 80053098 43150800 */  sra        $v0, $t0, 21
/* 4389C 8005309C 80550900 */  sll        $t2, $t1, 22
/* 438A0 800530A0 C3FF0017 */  bnez       $t8, .L80052FB0
/* 438A4 800530A4 431D0A00 */   sra       $v1, $t2, 21
/* 438A8 800530A8 2C4C0108 */  j          .L800530B0
/* 438AC 800530AC 00000000 */   nop
.L800530B0:
/* 438B0 800530B0 000021AF */  sw         $at, 0x0($t9)
/* 438B4 800530B4 040022AF */  sw         $v0, 0x4($t9)
/* 438B8 800530B8 0800E003 */  jr         $ra
/* 438BC 800530BC 080023AF */   sw        $v1, 0x8($t9)
.size func_80052F38, . - func_80052F38

/* Handwritten function */
glabel func_800530C0
/* 438C0 800530C0 00008F20 */  addi       $t7, $a0, 0x0 /* handwritten instruction */
/* 438C4 800530C4 0068C548 */  ctc2       $a1, $13 /* handwritten instruction */
/* 438C8 800530C8 2000E18D */  lw         $at, 0x20($t7)
/* 438CC 800530CC 2400E28D */  lw         $v0, 0x24($t7)
/* 438D0 800530D0 2800E38D */  lw         $v1, 0x28($t7)
/* 438D4 800530D4 2C00E48D */  lw         $a0, 0x2C($t7)
/* 438D8 800530D8 3000E58D */  lw         $a1, 0x30($t7)
/* 438DC 800530DC 0000C148 */  ctc2       $at, $0 /* handwritten instruction */
/* 438E0 800530E0 0008C248 */  ctc2       $v0, $1 /* handwritten instruction */
/* 438E4 800530E4 0010C348 */  ctc2       $v1, $2 /* handwritten instruction */
/* 438E8 800530E8 0018C448 */  ctc2       $a0, $3 /* handwritten instruction */
/* 438EC 800530EC 0020C548 */  ctc2       $a1, $4 /* handwritten instruction */
/* 438F0 800530F0 0C00E18D */  lw         $at, 0xC($t7)
/* 438F4 800530F4 1000E28D */  lw         $v0, 0x10($t7)
/* 438F8 800530F8 1400E38D */  lw         $v1, 0x14($t7)
/* 438FC 800530FC 82080100 */  srl        $at, $at, 2
/* 43900 80053100 82100200 */  srl        $v0, $v0, 2
/* 43904 80053104 82180300 */  srl        $v1, $v1, 2
/* 43908 80053108 0028C148 */  ctc2       $at, $5 /* handwritten instruction */
/* 4390C 8005310C 0030C248 */  ctc2       $v0, $6 /* handwritten instruction */
/* 43910 80053110 0038C348 */  ctc2       $v1, $7 /* handwritten instruction */
/* 43914 80053114 3600E195 */  lhu        $at, 0x36($t7)
/* 43918 80053118 3C00E38D */  lw         $v1, 0x3C($t7)
/* 4391C 8005311C 0780023C */  lui        $v0, %hi(D_80076378)
/* 43920 80053120 78634224 */  addiu      $v0, $v0, %lo(D_80076378)
/* 43924 80053124 80080100 */  sll        $at, $at, 2
/* 43928 80053128 20082200 */  add        $at, $at, $v0 /* handwritten instruction */
/* 4392C 8005312C 0000218C */  lw         $at, 0x0($at)
/* 43930 80053130 80100300 */  sll        $v0, $v1, 2
/* 43934 80053134 FC034230 */  andi       $v0, $v0, 0x3FC
/* 43938 80053138 20104100 */  add        $v0, $v0, $at /* handwritten instruction */
/* 4393C 8005313C 3800428C */  lw         $v0, 0x38($v0)
/* 43940 80053140 421B0300 */  srl        $v1, $v1, 13
/* 43944 80053144 F8076330 */  andi       $v1, $v1, 0x7F8
/* 43948 80053148 24006320 */  addi       $v1, $v1, 0x24 /* handwritten instruction */
/* 4394C 8005314C 20186200 */  add        $v1, $v1, $v0 /* handwritten instruction */
/* 43950 80053150 0000618C */  lw         $at, 0x0($v1)
/* 43954 80053154 0400638C */  lw         $v1, 0x4($v1)
/* 43958 80053158 08004490 */  lbu        $a0, 0x8($v0)
/* 4395C 8005315C 05004590 */  lbu        $a1, 0x5($v0)
/* 43960 80053160 06004690 */  lbu        $a2, 0x6($v0)
/* 43964 80053164 1400588C */  lw         $t8, 0x14($v0)
/* 43968 80053168 1800598C */  lw         $t9, 0x18($v0)
/* 4396C 8005316C C00A0100 */  sll        $at, $at, 11
/* 43970 80053170 C20A0100 */  srl        $at, $at, 11
/* 43974 80053174 021E0300 */  srl        $v1, $v1, 24
/* 43978 80053178 80180300 */  sll        $v1, $v1, 2
/* 4397C 8005317C 20102300 */  add        $v0, $at, $v1 /* handwritten instruction */
/* 43980 80053180 801F033C */  lui        $v1, (0x1F800008 >> 16)
/* 43984 80053184 01000B20 */  addi       $t3, $zero, 0x1 /* handwritten instruction */
/* 43988 80053188 42200400 */  srl        $a0, $a0, 1
/* 4398C 8005318C C0200400 */  sll        $a0, $a0, 3
/* 43990 80053190 20208300 */  add        $a0, $a0, $v1 /* handwritten instruction */
/* 43994 80053194 00000A20 */  addi       $t2, $zero, 0x0 /* handwritten instruction */
/* 43998 80053198 0100C620 */  addi       $a2, $a2, 0x1 /* handwritten instruction */
/* 4399C 8005319C 2030C500 */  add        $a2, $a2, $a1 /* handwritten instruction */
.L800531A0:
/* 439A0 800531A0 0D004015 */  bnez       $t2, .L800531D8
/* 439A4 800531A4 00000000 */   nop
/* 439A8 800531A8 0000298C */  lw         $t1, 0x0($at)
/* 439AC 800531AC 04002120 */  addi       $at, $at, 0x4 /* handwritten instruction */
/* 439B0 800531B0 01002A31 */  andi       $t2, $t1, 0x1
/* 439B4 800531B4 433D0900 */  sra        $a3, $t1, 21
/* 439B8 800531B8 80420900 */  sll        $t0, $t1, 10
/* 439BC 800531BC 43450800 */  sra        $t0, $t0, 21
/* 439C0 800531C0 004D0900 */  sll        $t1, $t1, 20
/* 439C4 800531C4 C34C0900 */  sra        $t1, $t1, 19
/* 439C8 800531C8 0438A700 */  sllv       $a3, $a3, $a1
/* 439CC 800531CC 0440A800 */  sllv       $t0, $t0, $a1
/* 439D0 800531D0 844C0108 */  j          .L80053210
/* 439D4 800531D4 0448A900 */   sllv      $t1, $t1, $a1
.L800531D8:
/* 439D8 800531D8 00004C84 */  lh         $t4, 0x0($v0)
/* 439DC 800531DC 02004220 */  addi       $v0, $v0, 0x2 /* handwritten instruction */
/* 439E0 800531E0 C36A0C00 */  sra        $t5, $t4, 11
/* 439E4 800531E4 0468CD00 */  sllv       $t5, $t5, $a2
/* 439E8 800531E8 2038ED00 */  add        $a3, $a3, $t5 /* handwritten instruction */
/* 439EC 800531EC 406D0C00 */  sll        $t5, $t4, 21
/* 439F0 800531F0 C36E0D00 */  sra        $t5, $t5, 27
/* 439F4 800531F4 0468CD00 */  sllv       $t5, $t5, $a2
/* 439F8 800531F8 22400D01 */  sub        $t0, $t0, $t5 /* handwritten instruction */
/* 439FC 800531FC 806E0C00 */  sll        $t5, $t4, 26
/* 43A00 80053200 C36E0D00 */  sra        $t5, $t5, 27
/* 43A04 80053204 0468CD00 */  sllv       $t5, $t5, $a2
/* 43A08 80053208 22482D01 */  sub        $t1, $t1, $t5 /* handwritten instruction */
/* 43A0C 8005320C 01008A31 */  andi       $t2, $t4, 0x1
.L80053210:
/* 43A10 80053210 E3FF6005 */  bltz       $t3, .L800531A0
/* 43A14 80053214 22580B00 */   neg       $t3, $t3 /* handwritten instruction */
/* 43A18 80053218 00588748 */  mtc2       $a3, $11 /* handwritten instruction */
/* 43A1C 8005321C 00488848 */  mtc2       $t0, $9 /* handwritten instruction */
/* 43A20 80053220 00508948 */  mtc2       $t1, $10 /* handwritten instruction */
/* 43A24 80053224 08006320 */  addi       $v1, $v1, (0x1F800008 & 0xFFFF) /* handwritten instruction */
/* 43A28 80053228 00000000 */  nop
/* 43A2C 8005322C 12E0494A */  MVMVA      1, 0, 3, 3, 0
/* 43A30 80053230 00D80C48 */  mfc2       $t4, $27 /* handwritten instruction */
/* 43A34 80053234 00C80D48 */  mfc2       $t5, $25 /* handwritten instruction */
/* 43A38 80053238 00D00E48 */  mfc2       $t6, $26 /* handwritten instruction */
/* 43A3C 8005323C 22680D00 */  neg        $t5, $t5 /* handwritten instruction */
/* 43A40 80053240 22700E00 */  neg        $t6, $t6 /* handwritten instruction */
/* 43A44 80053244 F8FF6CA4 */  sh         $t4, -0x8($v1)
/* 43A48 80053248 FAFF6DA4 */  sh         $t5, -0x6($v1)
/* 43A4C 8005324C D4FF6414 */  bne        $v1, $a0, .L800531A0
/* 43A50 80053250 FCFF6EA4 */   sh        $t6, -0x4($v1)
/* 43A54 80053254 801F183C */  lui        $t8, (0x1F800000 >> 16)
/* 43A58 80053258 F8FF9920 */  addi       $t9, $a0, -0x8 /* handwritten instruction */
/* 43A5C 8005325C 0000EF23 */  addi       $t7, $ra, 0x0 /* handwritten instruction */
.L80053260:
/* 43A60 80053260 CB89010C */  jal        rand
/* 43A64 80053264 00000000 */   nop
/* 43A68 80053268 00004E20 */  addi       $t6, $v0, 0x0 /* handwritten instruction */
/* 43A6C 8005326C 5C4D010C */  jal        func_80053570
/* 43A70 80053270 02000420 */   addi      $a0, $zero, 0x2 /* handwritten instruction */
/* 43A74 80053274 00000387 */  lh         $v1, 0x0($t8)
/* 43A78 80053278 02000487 */  lh         $a0, 0x2($t8)
/* 43A7C 8005327C 04000587 */  lh         $a1, 0x4($t8)
/* 43A80 80053280 83180300 */  sra        $v1, $v1, 2
/* 43A84 80053284 83200400 */  sra        $a0, $a0, 2
/* 43A88 80053288 83280500 */  sra        $a1, $a1, 2
/* 43A8C 8005328C 00284648 */  cfc2       $a2, $5 /* handwritten instruction */
/* 43A90 80053290 00304748 */  cfc2       $a3, $6 /* handwritten instruction */
/* 43A94 80053294 00384848 */  cfc2       $t0, $7 /* handwritten instruction */
/* 43A98 80053298 20186600 */  add        $v1, $v1, $a2 /* handwritten instruction */
/* 43A9C 8005329C 20208700 */  add        $a0, $a0, $a3 /* handwritten instruction */
/* 43AA0 800532A0 2028A800 */  add        $a1, $a1, $t0 /* handwritten instruction */
/* 43AA4 800532A4 040043A4 */  sh         $v1, 0x4($v0)
/* 43AA8 800532A8 060044A4 */  sh         $a0, 0x6($v0)
/* 43AAC 800532AC 0300C131 */  andi       $at, $t6, 0x3
/* 43AB0 800532B0 27002010 */  beqz       $at, .L80053350
/* 43AB4 800532B4 080045A4 */   sh        $a1, 0x8($v0)
/* 43AB8 800532B8 00684348 */  cfc2       $v1, $13 /* handwritten instruction */
/* 43ABC 800532BC 0300C131 */  andi       $at, $t6, 0x3
/* 43AC0 800532C0 20082300 */  add        $at, $at, $v1 /* handwritten instruction */
/* 43AC4 800532C4 0A0041A0 */  sb         $at, 0xA($v0)
/* 43AC8 800532C8 FF00C131 */  andi       $at, $t6, 0xFF
/* 43ACC 800532CC 0B0041A0 */  sb         $at, 0xB($v0)
/* 43AD0 800532D0 0700C131 */  andi       $at, $t6, 0x7
/* 43AD4 800532D4 C0080100 */  sll        $at, $at, 3
/* 43AD8 800532D8 30002120 */  addi       $at, $at, 0x30 /* handwritten instruction */
/* 43ADC 800532DC 0C0041A0 */  sb         $at, 0xC($v0)
/* 43AE0 800532E0 0D0041A0 */  sb         $at, 0xD($v0)
/* 43AE4 800532E4 0E0041A0 */  sb         $at, 0xE($v0)
/* 43AE8 800532E8 2E000120 */  addi       $at, $zero, 0x2E /* handwritten instruction */
/* 43AEC 800532EC 0F0041A0 */  sb         $at, 0xF($v0)
/* 43AF0 800532F0 00000120 */  addi       $at, $zero, 0x0 /* handwritten instruction */
/* 43AF4 800532F4 100041A0 */  sb         $at, 0x10($v0)
/* 43AF8 800532F8 04000120 */  addi       $at, $zero, 0x4 /* handwritten instruction */
/* 43AFC 800532FC 110041A0 */  sb         $at, 0x11($v0)
/* 43B00 80053300 400C0E00 */  sll        $at, $t6, 17
/* 43B04 80053304 430F0100 */  sra        $at, $at, 29
/* 43B08 80053308 120041A4 */  sh         $at, 0x12($v0)
/* 43B0C 8005330C 800B0E00 */  sll        $at, $t6, 14
/* 43B10 80053310 430F0100 */  sra        $at, $at, 29
/* 43B14 80053314 140041A4 */  sh         $at, 0x14($v0)
/* 43B18 80053318 C00A0E00 */  sll        $at, $t6, 11
/* 43B1C 8005331C 430F0100 */  sra        $at, $at, 29
/* 43B20 80053320 02002120 */  addi       $at, $at, 0x2 /* handwritten instruction */
/* 43B24 80053324 160041A4 */  sh         $at, 0x16($v0)
/* 43B28 80053328 0B000120 */  addi       $at, $zero, 0xB /* handwritten instruction */
/* 43B2C 8005332C 000041A0 */  sb         $at, 0x0($v0)
/* 43B30 80053330 00000120 */  addi       $at, $zero, 0x0 /* handwritten instruction */
/* 43B34 80053334 020041A0 */  sb         $at, 0x2($v0)
/* 43B38 80053338 01000120 */  addi       $at, $zero, 0x1 /* handwritten instruction */
/* 43B3C 8005333C 030041A0 */  sb         $at, 0x3($v0)
/* 43B40 80053340 C7FF1917 */  bne        $t8, $t9, .L80053260
/* 43B44 80053344 08001823 */   addi      $t8, $t8, 0x8 /* handwritten instruction */
/* 43B48 80053348 0800E001 */  jr         $t7
/* 43B4C 8005334C 00000000 */   nop
.L80053350:
/* 43B50 80053350 400C0E00 */  sll        $at, $t6, 17
/* 43B54 80053354 C30E0100 */  sra        $at, $at, 27
/* 43B58 80053358 20186100 */  add        $v1, $v1, $at /* handwritten instruction */
/* 43B5C 8005335C 0A0043A4 */  sh         $v1, 0xA($v0)
/* 43B60 80053360 000D0E00 */  sll        $at, $t6, 20
/* 43B64 80053364 C30E0100 */  sra        $at, $at, 27
/* 43B68 80053368 20208100 */  add        $a0, $a0, $at /* handwritten instruction */
/* 43B6C 8005336C 0C0044A4 */  sh         $a0, 0xC($v0)
/* 43B70 80053370 C00D0E00 */  sll        $at, $t6, 23
/* 43B74 80053374 420F0100 */  srl        $at, $at, 29
/* 43B78 80053378 06002120 */  addi       $at, $at, 0x6 /* handwritten instruction */
/* 43B7C 8005337C 2228A100 */  sub        $a1, $a1, $at /* handwritten instruction */
/* 43B80 80053380 0E0045A4 */  sh         $a1, 0xE($v0)
/* 43B84 80053384 48000120 */  addi       $at, $zero, 0x48 /* handwritten instruction */
/* 43B88 80053388 000041A0 */  sb         $at, 0x0($v0)
/* 43B8C 8005338C 01000120 */  addi       $at, $zero, 0x1 /* handwritten instruction */
/* 43B90 80053390 010041A0 */  sb         $at, 0x1($v0)
/* 43B94 80053394 820A0E00 */  srl        $at, $t6, 10
/* 43B98 80053398 1F002130 */  andi       $at, $at, 0x1F
/* 43B9C 8005339C 020041A0 */  sb         $at, 0x2($v0)
/* 43BA0 800533A0 01000120 */  addi       $at, $zero, 0x1 /* handwritten instruction */
/* 43BA4 800533A4 030041A0 */  sb         $at, 0x3($v0)
/* 43BA8 800533A8 8050013C */  lui        $at, (0x5080F0F0 >> 16)
/* 43BAC 800533AC F0F02134 */  ori        $at, $at, (0x5080F0F0 & 0xFFFF)
/* 43BB0 800533B0 100041AC */  sw         $at, 0x10($v0)
/* 43BB4 800533B4 4002013C */  lui        $at, (0x24080C0 >> 16)
/* 43BB8 800533B8 C0802134 */  ori        $at, $at, (0x24080C0 & 0xFFFF)
/* 43BBC 800533BC 140041AC */  sw         $at, 0x14($v0)
/* 43BC0 800533C0 A7FF1917 */  bne        $t8, $t9, .L80053260
/* 43BC4 800533C4 08001823 */   addi      $t8, $t8, 0x8 /* handwritten instruction */
/* 43BC8 800533C8 0800E001 */  jr         $t7
/* 43BCC 800533CC 00000000 */   nop
.size func_800530C0, . - func_800530C0

/* Handwritten function */
glabel func_800533D0
/* 43BD0 800533D0 0780033C */  lui        $v1, %hi(D_80077368)
/* 43BD4 800533D4 68736324 */  addiu      $v1, $v1, %lo(D_80077368)
/* 43BD8 800533D8 0000618C */  lw         $at, 0x0($v1)
/* 43BDC 800533DC 0400628C */  lw         $v0, 0x4($v1)
/* 43BE0 800533E0 0800638C */  lw         $v1, 0x8($v1)
/* 43BE4 800533E4 00488148 */  mtc2       $at, $9 /* handwritten instruction */
/* 43BE8 800533E8 00588348 */  mtc2       $v1, $11 /* handwritten instruction */
/* 43BEC 800533EC 00000000 */  nop
/* 43BF0 800533F0 00000000 */  nop
/* 43BF4 800533F4 2804A04A */  SQR        0
/* 43BF8 800533F8 1C00878C */  lw         $a3, 0x1C($a0)
/* 43BFC 800533FC 00C80548 */  mfc2       $a1, $25 /* handwritten instruction */
/* 43C00 80053400 00D80648 */  mfc2       $a2, $27 /* handwritten instruction */
/* 43C04 80053404 5800E104 */  bgez       $a3, .L80053568
/* 43C08 80053408 2028A600 */   add       $a1, $a1, $a2 /* handwritten instruction */
/* 43C0C 8005340C 00F08548 */  mtc2       $a1, $30 /* handwritten instruction */
/* 43C10 80053410 1500A010 */  beqz       $a1, .L80053468
/* 43C14 80053414 00000000 */   nop
/* 43C18 80053418 00F80648 */  mfc2       $a2, $31 /* handwritten instruction */
/* 43C1C 8005341C FEFF0720 */  addi       $a3, $zero, -0x2 /* handwritten instruction */
/* 43C20 80053420 2438C700 */  and        $a3, $a2, $a3
/* 43C24 80053424 1F000620 */  addi       $a2, $zero, 0x1F /* handwritten instruction */
/* 43C28 80053428 2230C700 */  sub        $a2, $a2, $a3 /* handwritten instruction */
/* 43C2C 8005342C 43300600 */  sra        $a2, $a2, 1
/* 43C30 80053430 E8FFE720 */  addi       $a3, $a3, -0x18 /* handwritten instruction */
/* 43C34 80053434 0300E104 */  bgez       $a3, .L80053444
/* 43C38 80053438 0440E500 */   sllv      $t0, $a1, $a3
/* 43C3C 8005343C 22380700 */  neg        $a3, $a3 /* handwritten instruction */
/* 43C40 80053440 0740E500 */  srav       $t0, $a1, $a3
.L80053444:
/* 43C44 80053444 C0FF0821 */  addi       $t0, $t0, -0x40 /* handwritten instruction */
/* 43C48 80053448 40400800 */  sll        $t0, $t0, 1
/* 43C4C 8005344C 0780073C */  lui        $a3, %hi(D_80074B84)
/* 43C50 80053450 844BE724 */  addiu      $a3, $a3, %lo(D_80074B84)
/* 43C54 80053454 2038E800 */  add        $a3, $a3, $t0 /* handwritten instruction */
/* 43C58 80053458 0000E784 */  lh         $a3, 0x0($a3)
/* 43C5C 8005345C 00000000 */  nop
/* 43C60 80053460 0438C700 */  sllv       $a3, $a3, $a2
/* 43C64 80053464 022B0700 */  srl        $a1, $a3, 12
.L80053468:
/* 43C68 80053468 2230A200 */  sub        $a2, $a1, $v0 /* handwritten instruction */
/* 43C6C 8005346C 0B00C004 */  bltz       $a2, .L8005349C
/* 43C70 80053470 2030A200 */   add       $a2, $a1, $v0 /* handwritten instruction */
/* 43C74 80053474 0400C004 */  bltz       $a2, .L80053488
/* 43C78 80053478 40310200 */   sll       $a2, $v0, 5
/* 43C7C 8005347C 1A00C500 */  div        $zero, $a2, $a1
/* 43C80 80053480 304D0108 */  j          .L800534C0
/* 43C84 80053484 00000720 */   addi      $a3, $zero, 0x0 /* handwritten instruction */
.L80053488:
/* 43C88 80053488 40310500 */  sll        $a2, $a1, 5
/* 43C8C 8005348C 22380200 */  neg        $a3, $v0 /* handwritten instruction */
/* 43C90 80053490 1A00C700 */  div        $zero, $a2, $a3
/* 43C94 80053494 304D0108 */  j          .L800534C0
/* 43C98 80053498 C0000720 */   addi      $a3, $zero, 0xC0 /* handwritten instruction */
.L8005349C:
/* 43C9C 8005349C 0500C004 */  bltz       $a2, .L800534B4
/* 43CA0 800534A0 40310500 */   sll       $a2, $a1, 5
/* 43CA4 800534A4 22380200 */  neg        $a3, $v0 /* handwritten instruction */
/* 43CA8 800534A8 1A00C700 */  div        $zero, $a2, $a3
/* 43CAC 800534AC 304D0108 */  j          .L800534C0
/* 43CB0 800534B0 40000720 */   addi      $a3, $zero, 0x40 /* handwritten instruction */
.L800534B4:
/* 43CB4 800534B4 40310200 */  sll        $a2, $v0, 5
/* 43CB8 800534B8 1A00C500 */  div        $zero, $a2, $a1
/* 43CBC 800534BC 80000720 */  addi       $a3, $zero, 0x80 /* handwritten instruction */
.L800534C0:
/* 43CC0 800534C0 12100000 */  mflo       $v0
/* 43CC4 800534C4 20104700 */  add        $v0, $v0, $a3 /* handwritten instruction */
/* 43CC8 800534C8 22306100 */  sub        $a2, $v1, $at /* handwritten instruction */
/* 43CCC 800534CC 0B00C004 */  bltz       $a2, .L800534FC
/* 43CD0 800534D0 20306100 */   add       $a2, $v1, $at /* handwritten instruction */
/* 43CD4 800534D4 0400C004 */  bltz       $a2, .L800534E8
/* 43CD8 800534D8 40310100 */   sll       $a2, $at, 5
/* 43CDC 800534DC 1A00C300 */  div        $zero, $a2, $v1
/* 43CE0 800534E0 484D0108 */  j          .L80053520
/* 43CE4 800534E4 00000720 */   addi      $a3, $zero, 0x0 /* handwritten instruction */
.L800534E8:
/* 43CE8 800534E8 40310300 */  sll        $a2, $v1, 5
/* 43CEC 800534EC 22380100 */  neg        $a3, $at /* handwritten instruction */
/* 43CF0 800534F0 1A00C700 */  div        $zero, $a2, $a3
/* 43CF4 800534F4 484D0108 */  j          .L80053520
/* 43CF8 800534F8 C0000720 */   addi      $a3, $zero, 0xC0 /* handwritten instruction */
.L800534FC:
/* 43CFC 800534FC 0500C004 */  bltz       $a2, .L80053514
/* 43D00 80053500 40310300 */   sll       $a2, $v1, 5
/* 43D04 80053504 22380100 */  neg        $a3, $at /* handwritten instruction */
/* 43D08 80053508 1A00C700 */  div        $zero, $a2, $a3
/* 43D0C 8005350C 484D0108 */  j          .L80053520
/* 43D10 80053510 40000720 */   addi      $a3, $zero, 0x40 /* handwritten instruction */
.L80053514:
/* 43D14 80053514 40310100 */  sll        $a2, $at, 5
/* 43D18 80053518 1A00C300 */  div        $zero, $a2, $v1
/* 43D1C 8005351C 80000720 */  addi       $a3, $zero, 0x80 /* handwritten instruction */
.L80053520:
/* 43D20 80053520 0780053C */  lui        $a1, %hi(D_80076B80)
/* 43D24 80053524 806BA524 */  addiu      $a1, $a1, %lo(D_80076B80)
/* 43D28 80053528 0800A58C */  lw         $a1, 0x8($a1)
/* 43D2C 8005352C 12080000 */  mflo       $at
/* 43D30 80053530 20082700 */  add        $at, $at, $a3 /* handwritten instruction */
/* 43D34 80053534 22080100 */  neg        $at, $at /* handwritten instruction */
/* 43D38 80053538 22100200 */  neg        $v0, $v0 /* handwritten instruction */
/* 43D3C 8005353C 82080100 */  srl        $at, $at, 2
/* 43D40 80053540 82100200 */  srl        $v0, $v0, 2
/* 43D44 80053544 3F002130 */  andi       $at, $at, 0x3F
/* 43D48 80053548 3F004230 */  andi       $v0, $v0, 0x3F
/* 43D4C 8005354C 000C0100 */  sll        $at, $at, 16
/* 43D50 80053550 80150200 */  sll        $v0, $v0, 22
/* 43D54 80053554 0080033C */  lui        $v1, (0x80000000 >> 16)
/* 43D58 80053558 25186100 */  or         $v1, $v1, $at
/* 43D5C 8005355C 25186200 */  or         $v1, $v1, $v0
/* 43D60 80053560 82280500 */  srl        $a1, $a1, 2
/* 43D64 80053564 25386500 */  or         $a3, $v1, $a1
.L80053568:
/* 43D68 80053568 0800E003 */  jr         $ra
/* 43D6C 8005356C 1C0087AC */   sw        $a3, 0x1C($a0)
.size func_800533D0, . - func_800533D0
