.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata.jtbl
.align 3
dlabel jtbl_80010DD0
/* 15D0 80010DD0 C4E40280 */ .word .L8002E4C4
/* 15D4 80010DD4 E0E50280 */ .word .L8002E5E0
/* 15D8 80010DD8 D4E60280 */ .word .L8002E6D4
/* 15DC 80010DDC 88E70280 */ .word .L8002E788
/* 15E0 80010DE0 24E80280 */ .word .L8002E824
/* 15E4 80010DE4 88E80280 */ .word .L8002E888
.size jtbl_80010DD0, . - jtbl_80010DD0


.section .text
/* Generated by spimdisasm 1.27.0 */

glabel func_8002E12C
/* 1E92C 8002E12C 0780023C */  lui        $v0, %hi(g_IsFlightLevel)
/* 1E930 8002E130 9056428C */  lw         $v0, %lo(g_IsFlightLevel)($v0)
/* 1E934 8002E134 D0FFBD27 */  addiu      $sp, $sp, -0x30
/* 1E938 8002E138 2800BFAF */  sw         $ra, 0x28($sp)
/* 1E93C 8002E13C 2400B1AF */  sw         $s1, 0x24($sp)
/* 1E940 8002E140 03004014 */  bnez       $v0, .L8002E150
/* 1E944 8002E144 2000B0AF */   sw        $s0, 0x20($sp)
/* 1E948 8002E148 6252010C */  jal        HudTick
/* 1E94C 8002E14C 00000000 */   nop
.L8002E150:
/* 1E950 8002E150 0780023C */  lui        $v0, %hi(D_8007568C)
/* 1E954 8002E154 8C56428C */  lw         $v0, %lo(D_8007568C)($v0)
/* 1E958 8002E158 0780013C */  lui        $at, %hi(g_Hud + 0x0C)
/* 1E95C 8002E15C B47F20AC */  sw         $zero, %lo(g_Hud + 0x0C)($at)
/* 1E960 8002E160 0780013C */  lui        $at, %hi(g_Hud + 0x10)
/* 1E964 8002E164 B87F20AC */  sw         $zero, %lo(g_Hud + 0x10)($at)
/* 1E968 8002E168 0780013C */  lui        $at, %hi(g_Hud + 0x14)
/* 1E96C 8002E16C BC7F20AC */  sw         $zero, %lo(g_Hud + 0x14)($at)
/* 1E970 8002E170 0780013C */  lui        $at, %hi(g_Hud + 0x18)
/* 1E974 8002E174 C07F20AC */  sw         $zero, %lo(g_Hud + 0x18)($at)
/* 1E978 8002E178 0780013C */  lui        $at, %hi(g_Hud + 0x1C)
/* 1E97C 8002E17C C47F20AC */  sw         $zero, %lo(g_Hud + 0x1C)($at)
/* 1E980 8002E180 01004224 */  addiu      $v0, $v0, 0x1
/* 1E984 8002E184 0780013C */  lui        $at, %hi(D_8007568C)
/* 1E988 8002E188 8C5622AC */  sw         $v0, %lo(D_8007568C)($at)
/* 1E98C 8002E18C 3063010C */  jal        SpecularUpdate
/* 1E990 8002E190 03000424 */   addiu     $a0, $zero, 0x3
/* 1E994 8002E194 0780023C */  lui        $v0, %hi(D_800758B8)
/* 1E998 8002E198 B858428C */  lw         $v0, %lo(D_800758B8)($v0)
/* 1E99C 8002E19C 00000000 */  nop
/* 1E9A0 8002E1A0 05004228 */  slti       $v0, $v0, 0x5
/* 1E9A4 8002E1A4 5B024014 */  bnez       $v0, .L8002EB14
/* 1E9A8 8002E1A8 00000000 */   nop
/* 1E9AC 8002E1AC 0780043C */  lui        $a0, %hi(g_Pad)
/* 1E9B0 8002E1B0 7873848C */  lw         $a0, %lo(g_Pad)($a0)
/* 1E9B4 8002E1B4 00000000 */  nop
/* 1E9B8 8002E1B8 00018230 */  andi       $v0, $a0, 0x100
/* 1E9BC 8002E1BC 1D024014 */  bnez       $v0, .L8002EA34
/* 1E9C0 8002E1C0 02000224 */   addiu     $v0, $zero, 0x2
/* 1E9C4 8002E1C4 0780033C */  lui        $v1, %hi(D_800757C8)
/* 1E9C8 8002E1C8 C857638C */  lw         $v1, %lo(D_800757C8)($v1)
/* 1E9CC 8002E1CC 00000000 */  nop
/* 1E9D0 8002E1D0 6C006214 */  bne        $v1, $v0, .L8002E384
/* 1E9D4 8002E1D4 01000224 */   addiu     $v0, $zero, 0x1
/* 1E9D8 8002E1D8 00A08230 */  andi       $v0, $a0, 0xA000
/* 1E9DC 8002E1DC 0F004010 */  beqz       $v0, .L8002E21C
/* 1E9E0 8002E1E0 21280000 */   addu      $a1, $zero, $zero
/* 1E9E4 8002E1E4 0780023C */  lui        $v0, %hi(g_Spu + 0x2CC)
/* 1E9E8 8002E1E8 D461428C */  lw         $v0, %lo(g_Spu + 0x2CC)($v0)
/* 1E9EC 8002E1EC 10000624 */  addiu      $a2, $zero, 0x10
/* 1E9F0 8002E1F0 2E004490 */  lbu        $a0, 0x2E($v0)
/* 1E9F4 8002E1F4 9E56010C */  jal        PlaySound
/* 1E9F8 8002E1F8 21380000 */   addu      $a3, $zero, $zero
/* 1E9FC 8002E1FC 0780033C */  lui        $v1, %hi(D_80075720)
/* 1EA00 8002E200 2057638C */  lw         $v1, %lo(D_80075720)($v1)
/* 1EA04 8002E204 01000224 */  addiu      $v0, $zero, 0x1
/* 1EA08 8002E208 23104300 */  subu       $v0, $v0, $v1
/* 1EA0C 8002E20C 0780013C */  lui        $at, %hi(D_80075720)
/* 1EA10 8002E210 205722AC */  sw         $v0, %lo(D_80075720)($at)
/* 1EA14 8002E214 C5BA0008 */  j          .L8002EB14
/* 1EA18 8002E218 00000000 */   nop
.L8002E21C:
/* 1EA1C 8002E21C 50008230 */  andi       $v0, $a0, 0x50
/* 1EA20 8002E220 3C024010 */  beqz       $v0, .L8002EB14
/* 1EA24 8002E224 01000224 */   addiu     $v0, $zero, 0x1
/* 1EA28 8002E228 0780033C */  lui        $v1, %hi(D_80075720)
/* 1EA2C 8002E22C 2057638C */  lw         $v1, %lo(D_80075720)($v1)
/* 1EA30 8002E230 00000000 */  nop
/* 1EA34 8002E234 03006210 */  beq        $v1, $v0, .L8002E244
/* 1EA38 8002E238 10008230 */   andi      $v0, $a0, 0x10
/* 1EA3C 8002E23C 0F004010 */  beqz       $v0, .L8002E27C
/* 1EA40 8002E240 00000000 */   nop
.L8002E244:
/* 1EA44 8002E244 21280000 */  addu       $a1, $zero, $zero
/* 1EA48 8002E248 0780023C */  lui        $v0, %hi(g_Spu + 0x2CC)
/* 1EA4C 8002E24C D461428C */  lw         $v0, %lo(g_Spu + 0x2CC)($v0)
/* 1EA50 8002E250 10000624 */  addiu      $a2, $zero, 0x10
/* 1EA54 8002E254 2D004490 */  lbu        $a0, 0x2D($v0)
/* 1EA58 8002E258 9E56010C */  jal        PlaySound
/* 1EA5C 8002E25C 21380000 */   addu      $a3, $zero, $zero
/* 1EA60 8002E260 03000224 */  addiu      $v0, $zero, 0x3
/* 1EA64 8002E264 0780013C */  lui        $at, %hi(D_800757C8)
/* 1EA68 8002E268 C85720AC */  sw         $zero, %lo(D_800757C8)($at)
/* 1EA6C 8002E26C 0780013C */  lui        $at, %hi(D_80075720)
/* 1EA70 8002E270 205722AC */  sw         $v0, %lo(D_80075720)($at)
/* 1EA74 8002E274 C5BA0008 */  j          .L8002EB14
/* 1EA78 8002E278 00000000 */   nop
.L8002E27C:
/* 1EA7C 8002E27C CA5A010C */  jal        func_80056B28
/* 1EA80 8002E280 21200000 */   addu      $a0, $zero, $zero
/* 1EA84 8002E284 21280000 */  addu       $a1, $zero, $zero
/* 1EA88 8002E288 0780023C */  lui        $v0, %hi(g_Spu + 0x2CC)
/* 1EA8C 8002E28C D461428C */  lw         $v0, %lo(g_Spu + 0x2CC)($v0)
/* 1EA90 8002E290 10000624 */  addiu      $a2, $zero, 0x10
/* 1EA94 8002E294 2D004490 */  lbu        $a0, 0x2D($v0)
/* 1EA98 8002E298 9E56010C */  jal        PlaySound
/* 1EA9C 8002E29C 21380000 */   addu      $a3, $zero, $zero
/* 1EAA0 8002E2A0 B55B010C */  jal        SpuUpdate
/* 1EAA4 8002E2A4 00000000 */   nop
/* 1EAA8 8002E2A8 1800A427 */  addiu      $a0, $sp, 0x18
/* 1EAAC 8002E2AC 21280000 */  addu       $a1, $zero, $zero
/* 1EAB0 8002E2B0 21300000 */  addu       $a2, $zero, $zero
/* 1EAB4 8002E2B4 21380000 */  addu       $a3, $zero, $zero
/* 1EAB8 8002E2B8 00020224 */  addiu      $v0, $zero, 0x200
/* 1EABC 8002E2BC 1C00A2A7 */  sh         $v0, 0x1C($sp)
/* 1EAC0 8002E2C0 E0010224 */  addiu      $v0, $zero, 0x1E0
/* 1EAC4 8002E2C4 1800A0A7 */  sh         $zero, 0x18($sp)
/* 1EAC8 8002E2C8 1A00A0A7 */  sh         $zero, 0x1A($sp)
/* 1EACC 8002E2CC 3E7E010C */  jal        ClearImage
/* 1EAD0 8002E2D0 1E00A2A7 */   sh        $v0, 0x1E($sp)
/* 1EAD4 8002E2D4 D97D010C */  jal        DrawSync
/* 1EAD8 8002E2D8 21200000 */   addu      $a0, $zero, $zero
/* 1EADC 8002E2DC 0780043C */  lui        $a0, %hi(g_CdState)
/* 1EAE0 8002E2E0 906B848C */  lw         $a0, %lo(g_CdState)($a0)
/* 1EAE4 8002E2E4 0880063C */  lui        $a2, %hi(g_WadHeader + 0x14)
/* 1EAE8 8002E2E8 E4A6C68C */  lw         $a2, %lo(g_WadHeader + 0x14)($a2)
/* 1EAEC 8002E2EC 0880073C */  lui        $a3, %hi(g_WadHeader + 0x10)
/* 1EAF0 8002E2F0 E0A6E78C */  lw         $a3, %lo(g_WadHeader + 0x10)($a3)
/* 1EAF4 8002E2F4 0180053C */  lui        $a1, %hi(g_OverlaySpacePointer)
/* 1EAF8 8002E2F8 A013A58C */  lw         $a1, %lo(g_OverlaySpacePointer)($a1)
/* 1EAFC 8002E2FC 0880023C */  lui        $v0, %hi(func_titlescreen_8007DDE8)
/* 1EB00 8002E300 E8DD4224 */  addiu      $v0, $v0, %lo(func_titlescreen_8007DDE8)
/* 1EB04 8002E304 0880013C */  lui        $at, %hi(D_800785D8)
/* 1EB08 8002E308 D88522AC */  sw         $v0, %lo(D_800785D8)($at)
/* 1EB0C 8002E30C 0880013C */  lui        $at, %hi(D_800785D8 + 0x4)
/* 1EB10 8002E310 DC8522AC */  sw         $v0, %lo(D_800785D8 + 0x4)($at)
/* 1EB14 8002E314 58020224 */  addiu      $v0, $zero, 0x258
/* 1EB18 8002E318 0780013C */  lui        $at, %hi(g_LoadStage)
/* 1EB1C 8002E31C 645820AC */  sw         $zero, %lo(g_LoadStage)($at)
/* 1EB20 8002E320 0780013C */  lui        $at, %hi(g_CutsceneIdx)
/* 1EB24 8002E324 6C5620AC */  sw         $zero, %lo(g_CutsceneIdx)($at)
/* 1EB28 8002E328 4059000C */  jal        CDLoadSync
/* 1EB2C 8002E32C 1000A2AF */   sw        $v0, 0x10($sp)
/* 1EB30 8002E330 D2B80008 */  j          .L8002E348
/* 1EB34 8002E334 00000000 */   nop
.L8002E338:
/* 1EB38 8002E338 5951000C */  jal        LoadCutscene
/* 1EB3C 8002E33C 00000000 */   nop
/* 1EB40 8002E340 F8AE000C */  jal        CDMusicUpdate
/* 1EB44 8002E344 00000000 */   nop
.L8002E348:
/* 1EB48 8002E348 0780023C */  lui        $v0, %hi(g_LoadStage)
/* 1EB4C 8002E34C 6458428C */  lw         $v0, %lo(g_LoadStage)($v0)
/* 1EB50 8002E350 00000000 */  nop
/* 1EB54 8002E354 0A004228 */  slti       $v0, $v0, 0xA
/* 1EB58 8002E358 F7FF4014 */  bnez       $v0, .L8002E338
/* 1EB5C 8002E35C 00000000 */   nop
/* 1EB60 8002E360 CEB4000C */  jal        StartCutscenePlayback
/* 1EB64 8002E364 00000000 */   nop
/* 1EB68 8002E368 5CB4000C */  jal        func_8002D170
/* 1EB6C 8002E36C 00000000 */   nop
/* 1EB70 8002E370 01000224 */  addiu      $v0, $zero, 0x1
/* 1EB74 8002E374 0780013C */  lui        $at, %hi(g_StateSwitch)
/* 1EB78 8002E378 9C5722AC */  sw         $v0, %lo(g_StateSwitch)($at)
/* 1EB7C 8002E37C C5BA0008 */  j          .L8002EB14
/* 1EB80 8002E380 00000000 */   nop
.L8002E384:
/* 1EB84 8002E384 52016214 */  bne        $v1, $v0, .L8002E8D0
/* 1EB88 8002E388 00408230 */   andi      $v0, $a0, 0x4000
/* 1EB8C 8002E38C 1E004010 */  beqz       $v0, .L8002E408
/* 1EB90 8002E390 21280000 */   addu      $a1, $zero, $zero
/* 1EB94 8002E394 0780023C */  lui        $v0, %hi(g_Spu + 0x2CC)
/* 1EB98 8002E398 D461428C */  lw         $v0, %lo(g_Spu + 0x2CC)($v0)
/* 1EB9C 8002E39C 10000624 */  addiu      $a2, $zero, 0x10
/* 1EBA0 8002E3A0 2D004490 */  lbu        $a0, 0x2D($v0)
/* 1EBA4 8002E3A4 9E56010C */  jal        PlaySound
/* 1EBA8 8002E3A8 21380000 */   addu      $a3, $zero, $zero
/* 1EBAC 8002E3AC 0780043C */  lui        $a0, %hi(D_80075720)
/* 1EBB0 8002E3B0 2057848C */  lw         $a0, %lo(D_80075720)($a0)
/* 1EBB4 8002E3B4 0780013C */  lui        $at, %hi(D_8007568C)
/* 1EBB8 8002E3B8 8C5620AC */  sw         $zero, %lo(D_8007568C)($at)
/* 1EBBC 8002E3BC 01008324 */  addiu      $v1, $a0, 0x1
/* 1EBC0 8002E3C0 06006228 */  slti       $v0, $v1, 0x6
/* 1EBC4 8002E3C4 0780013C */  lui        $at, %hi(D_80075720)
/* 1EBC8 8002E3C8 205723AC */  sw         $v1, %lo(D_80075720)($at)
/* 1EBCC 8002E3CC 05004014 */  bnez       $v0, .L8002E3E4
/* 1EBD0 8002E3D0 03000224 */   addiu     $v0, $zero, 0x3
/* 1EBD4 8002E3D4 0780013C */  lui        $at, %hi(D_80075720)
/* 1EBD8 8002E3D8 205720AC */  sw         $zero, %lo(D_80075720)($at)
/* 1EBDC 8002E3DC 1FB90008 */  j          .L8002E47C
/* 1EBE0 8002E3E0 00000000 */   nop
.L8002E3E4:
/* 1EBE4 8002E3E4 25006214 */  bne        $v1, $v0, .L8002E47C
/* 1EBE8 8002E3E8 00000000 */   nop
/* 1EBEC 8002E3EC 0780023C */  lui        $v0, %hi(g_ActAvailable)
/* 1EBF0 8002E3F0 D856428C */  lw         $v0, %lo(g_ActAvailable)($v0)
/* 1EBF4 8002E3F4 00000000 */  nop
/* 1EBF8 8002E3F8 20004014 */  bnez       $v0, .L8002E47C
/* 1EBFC 8002E3FC 02008224 */   addiu     $v0, $a0, 0x2
/* 1EC00 8002E400 1DB90008 */  j          .L8002E474
/* 1EC04 8002E404 00000000 */   nop
.L8002E408:
/* 1EC08 8002E408 00108230 */  andi       $v0, $a0, 0x1000
/* 1EC0C 8002E40C 1B004010 */  beqz       $v0, .L8002E47C
/* 1EC10 8002E410 10000624 */   addiu     $a2, $zero, 0x10
/* 1EC14 8002E414 0780023C */  lui        $v0, %hi(g_Spu + 0x2CC)
/* 1EC18 8002E418 D461428C */  lw         $v0, %lo(g_Spu + 0x2CC)($v0)
/* 1EC1C 8002E41C 00000000 */  nop
/* 1EC20 8002E420 2D004490 */  lbu        $a0, 0x2D($v0)
/* 1EC24 8002E424 9E56010C */  jal        PlaySound
/* 1EC28 8002E428 21380000 */   addu      $a3, $zero, $zero
/* 1EC2C 8002E42C 0780043C */  lui        $a0, %hi(D_80075720)
/* 1EC30 8002E430 2057848C */  lw         $a0, %lo(D_80075720)($a0)
/* 1EC34 8002E434 0780013C */  lui        $at, %hi(D_8007568C)
/* 1EC38 8002E438 8C5620AC */  sw         $zero, %lo(D_8007568C)($at)
/* 1EC3C 8002E43C FFFF8324 */  addiu      $v1, $a0, -0x1
/* 1EC40 8002E440 0780013C */  lui        $at, %hi(D_80075720)
/* 1EC44 8002E444 205723AC */  sw         $v1, %lo(D_80075720)($at)
/* 1EC48 8002E448 03006104 */  bgez       $v1, .L8002E458
/* 1EC4C 8002E44C 03000224 */   addiu     $v0, $zero, 0x3
/* 1EC50 8002E450 1DB90008 */  j          .L8002E474
/* 1EC54 8002E454 05000224 */   addiu     $v0, $zero, 0x5
.L8002E458:
/* 1EC58 8002E458 08006214 */  bne        $v1, $v0, .L8002E47C
/* 1EC5C 8002E45C 00000000 */   nop
/* 1EC60 8002E460 0780023C */  lui        $v0, %hi(g_ActAvailable)
/* 1EC64 8002E464 D856428C */  lw         $v0, %lo(g_ActAvailable)($v0)
/* 1EC68 8002E468 00000000 */  nop
/* 1EC6C 8002E46C 03004014 */  bnez       $v0, .L8002E47C
/* 1EC70 8002E470 FEFF8224 */   addiu     $v0, $a0, -0x2
.L8002E474:
/* 1EC74 8002E474 0780013C */  lui        $at, %hi(D_80075720)
/* 1EC78 8002E478 205722AC */  sw         $v0, %lo(D_80075720)($at)
.L8002E47C:
/* 1EC7C 8002E47C 0780023C */  lui        $v0, %hi(g_Pad)
/* 1EC80 8002E480 7873428C */  lw         $v0, %lo(g_Pad)($v0)
/* 1EC84 8002E484 00000000 */  nop
/* 1EC88 8002E488 10004230 */  andi       $v0, $v0, 0x10
/* 1EC8C 8002E48C 04014014 */  bnez       $v0, .L8002E8A0
/* 1EC90 8002E490 21280000 */   addu      $a1, $zero, $zero
/* 1EC94 8002E494 0780033C */  lui        $v1, %hi(D_80075720)
/* 1EC98 8002E498 2057638C */  lw         $v1, %lo(D_80075720)($v1)
/* 1EC9C 8002E49C 00000000 */  nop
/* 1ECA0 8002E4A0 0600622C */  sltiu      $v0, $v1, 0x6
/* 1ECA4 8002E4A4 9B014010 */  beqz       $v0, .L8002EB14
/* 1ECA8 8002E4A8 80100300 */   sll       $v0, $v1, 2
/* 1ECAC 8002E4AC 0180013C */  lui        $at, %hi(jtbl_80010DD0)
/* 1ECB0 8002E4B0 21082200 */  addu       $at, $at, $v0
/* 1ECB4 8002E4B4 D00D228C */  lw         $v0, %lo(jtbl_80010DD0)($at)
/* 1ECB8 8002E4B8 00000000 */  nop
/* 1ECBC 8002E4BC 08004000 */  jr         $v0
/* 1ECC0 8002E4C0 00000000 */   nop
.L8002E4C4:
/* 1ECC4 8002E4C4 0780023C */  lui        $v0, %hi(g_Pad)
/* 1ECC8 8002E4C8 7873428C */  lw         $v0, %lo(g_Pad)($v0)
/* 1ECCC 8002E4CC 00000000 */  nop
/* 1ECD0 8002E4D0 00804230 */  andi       $v0, $v0, 0x8000
/* 1ECD4 8002E4D4 10004010 */  beqz       $v0, .L8002E518
/* 1ECD8 8002E4D8 00000000 */   nop
/* 1ECDC 8002E4DC 0780023C */  lui        $v0, %hi(D_80075754)
/* 1ECE0 8002E4E0 5457428C */  lw         $v0, %lo(D_80075754)($v0)
/* 1ECE4 8002E4E4 00000000 */  nop
/* 1ECE8 8002E4E8 0B004018 */  blez       $v0, .L8002E518
/* 1ECEC 8002E4EC 21280000 */   addu      $a1, $zero, $zero
/* 1ECF0 8002E4F0 0780023C */  lui        $v0, %hi(g_Spu + 0x2CC)
/* 1ECF4 8002E4F4 D461428C */  lw         $v0, %lo(g_Spu + 0x2CC)($v0)
/* 1ECF8 8002E4F8 10000624 */  addiu      $a2, $zero, 0x10
/* 1ECFC 8002E4FC 2E004490 */  lbu        $a0, 0x2E($v0)
/* 1ED00 8002E500 9E56010C */  jal        PlaySound
/* 1ED04 8002E504 21380000 */   addu      $a3, $zero, $zero
/* 1ED08 8002E508 0780023C */  lui        $v0, %hi(D_80075754)
/* 1ED0C 8002E50C 5457428C */  lw         $v0, %lo(D_80075754)($v0)
/* 1ED10 8002E510 5CB90008 */  j          .L8002E570
/* 1ED14 8002E514 FFFF4224 */   addiu     $v0, $v0, -0x1
.L8002E518:
/* 1ED18 8002E518 0780023C */  lui        $v0, %hi(g_Pad)
/* 1ED1C 8002E51C 7873428C */  lw         $v0, %lo(g_Pad)($v0)
/* 1ED20 8002E520 00000000 */  nop
/* 1ED24 8002E524 00204230 */  andi       $v0, $v0, 0x2000
/* 1ED28 8002E528 14004010 */  beqz       $v0, .L8002E57C
/* 1ED2C 8002E52C 6666043C */   lui       $a0, (0x66666667 >> 16)
/* 1ED30 8002E530 0780023C */  lui        $v0, %hi(D_80075754)
/* 1ED34 8002E534 5457428C */  lw         $v0, %lo(D_80075754)($v0)
/* 1ED38 8002E538 00000000 */  nop
/* 1ED3C 8002E53C 0A004228 */  slti       $v0, $v0, 0xA
/* 1ED40 8002E540 0E004010 */  beqz       $v0, .L8002E57C
/* 1ED44 8002E544 21280000 */   addu      $a1, $zero, $zero
/* 1ED48 8002E548 0780023C */  lui        $v0, %hi(g_Spu + 0x2CC)
/* 1ED4C 8002E54C D461428C */  lw         $v0, %lo(g_Spu + 0x2CC)($v0)
/* 1ED50 8002E550 10000624 */  addiu      $a2, $zero, 0x10
/* 1ED54 8002E554 2E004490 */  lbu        $a0, 0x2E($v0)
/* 1ED58 8002E558 9E56010C */  jal        PlaySound
/* 1ED5C 8002E55C 21380000 */   addu      $a3, $zero, $zero
/* 1ED60 8002E560 0780023C */  lui        $v0, %hi(D_80075754)
/* 1ED64 8002E564 5457428C */  lw         $v0, %lo(D_80075754)($v0)
/* 1ED68 8002E568 00000000 */  nop
/* 1ED6C 8002E56C 01004224 */  addiu      $v0, $v0, 0x1
.L8002E570:
/* 1ED70 8002E570 0780013C */  lui        $at, %hi(D_80075754)
/* 1ED74 8002E574 545722AC */  sw         $v0, %lo(D_80075754)($at)
/* 1ED78 8002E578 6666043C */  lui        $a0, (0x66666667 >> 16)
.L8002E57C:
/* 1ED7C 8002E57C 0780033C */  lui        $v1, %hi(D_80075754)
/* 1ED80 8002E580 5457638C */  lw         $v1, %lo(D_80075754)($v1)
/* 1ED84 8002E584 67668434 */  ori        $a0, $a0, (0x66666667 & 0xFFFF)
/* 1ED88 8002E588 80130300 */  sll        $v0, $v1, 14
/* 1ED8C 8002E58C 23104300 */  subu       $v0, $v0, $v1
/* 1ED90 8002E590 18004400 */  mult       $v0, $a0
/* 1ED94 8002E594 0280053C */  lui        $a1, (0x80020009 >> 16)
/* 1ED98 8002E598 0900A534 */  ori        $a1, $a1, (0x80020009 & 0xFFFF)
/* 1ED9C 8002E59C C3170200 */  sra        $v0, $v0, 31
/* 1EDA0 8002E5A0 10400000 */  mfhi       $t0
/* 1EDA4 8002E5A4 83180800 */  sra        $v1, $t0, 2
/* 1EDA8 8002E5A8 23186200 */  subu       $v1, $v1, $v0
/* 1EDAC 8002E5AC 00230300 */  sll        $a0, $v1, 12
/* 1EDB0 8002E5B0 18008500 */  mult       $a0, $a1
/* 1EDB4 8002E5B4 0780013C */  lui        $at, %hi(g_Spu + 0x320)
/* 1EDB8 8002E5B8 286223AC */  sw         $v1, %lo(g_Spu + 0x320)($at)
/* 1EDBC 8002E5BC 10400000 */  mfhi       $t0
/* 1EDC0 8002E5C0 21100401 */  addu       $v0, $t0, $a0
/* 1EDC4 8002E5C4 43130200 */  sra        $v0, $v0, 13
/* 1EDC8 8002E5C8 C3270400 */  sra        $a0, $a0, 31
/* 1EDCC 8002E5CC 23104400 */  subu       $v0, $v0, $a0
/* 1EDD0 8002E5D0 0780013C */  lui        $at, %hi(g_Spu + 0x324)
/* 1EDD4 8002E5D4 2C6222AC */  sw         $v0, %lo(g_Spu + 0x324)($at)
/* 1EDD8 8002E5D8 C5BA0008 */  j          .L8002EB14
/* 1EDDC 8002E5DC 00000000 */   nop
.L8002E5E0:
/* 1EDE0 8002E5E0 0780023C */  lui        $v0, %hi(g_Pad)
/* 1EDE4 8002E5E4 7873428C */  lw         $v0, %lo(g_Pad)($v0)
/* 1EDE8 8002E5E8 00000000 */  nop
/* 1EDEC 8002E5EC 00804230 */  andi       $v0, $v0, 0x8000
/* 1EDF0 8002E5F0 10004010 */  beqz       $v0, .L8002E634
/* 1EDF4 8002E5F4 00000000 */   nop
/* 1EDF8 8002E5F8 0780023C */  lui        $v0, %hi(D_80075748)
/* 1EDFC 8002E5FC 4857428C */  lw         $v0, %lo(D_80075748)($v0)
/* 1EE00 8002E600 00000000 */  nop
/* 1EE04 8002E604 0B004018 */  blez       $v0, .L8002E634
/* 1EE08 8002E608 21280000 */   addu      $a1, $zero, $zero
/* 1EE0C 8002E60C 0780023C */  lui        $v0, %hi(g_Spu + 0x2CC)
/* 1EE10 8002E610 D461428C */  lw         $v0, %lo(g_Spu + 0x2CC)($v0)
/* 1EE14 8002E614 10000624 */  addiu      $a2, $zero, 0x10
/* 1EE18 8002E618 2E004490 */  lbu        $a0, 0x2E($v0)
/* 1EE1C 8002E61C 9E56010C */  jal        PlaySound
/* 1EE20 8002E620 21380000 */   addu      $a3, $zero, $zero
/* 1EE24 8002E624 0780023C */  lui        $v0, %hi(D_80075748)
/* 1EE28 8002E628 4857428C */  lw         $v0, %lo(D_80075748)($v0)
/* 1EE2C 8002E62C A3B90008 */  j          .L8002E68C
/* 1EE30 8002E630 FFFF4224 */   addiu     $v0, $v0, -0x1
.L8002E634:
/* 1EE34 8002E634 0780023C */  lui        $v0, %hi(g_Pad)
/* 1EE38 8002E638 7873428C */  lw         $v0, %lo(g_Pad)($v0)
/* 1EE3C 8002E63C 00000000 */  nop
/* 1EE40 8002E640 00204230 */  andi       $v0, $v0, 0x2000
/* 1EE44 8002E644 13004010 */  beqz       $v0, .L8002E694
/* 1EE48 8002E648 00000000 */   nop
/* 1EE4C 8002E64C 0780023C */  lui        $v0, %hi(D_80075748)
/* 1EE50 8002E650 4857428C */  lw         $v0, %lo(D_80075748)($v0)
/* 1EE54 8002E654 00000000 */  nop
/* 1EE58 8002E658 0A004228 */  slti       $v0, $v0, 0xA
/* 1EE5C 8002E65C 0D004010 */  beqz       $v0, .L8002E694
/* 1EE60 8002E660 21280000 */   addu      $a1, $zero, $zero
/* 1EE64 8002E664 0780023C */  lui        $v0, %hi(g_Spu + 0x2CC)
/* 1EE68 8002E668 D461428C */  lw         $v0, %lo(g_Spu + 0x2CC)($v0)
/* 1EE6C 8002E66C 10000624 */  addiu      $a2, $zero, 0x10
/* 1EE70 8002E670 2E004490 */  lbu        $a0, 0x2E($v0)
/* 1EE74 8002E674 9E56010C */  jal        PlaySound
/* 1EE78 8002E678 21380000 */   addu      $a3, $zero, $zero
/* 1EE7C 8002E67C 0780023C */  lui        $v0, %hi(D_80075748)
/* 1EE80 8002E680 4857428C */  lw         $v0, %lo(D_80075748)($v0)
/* 1EE84 8002E684 00000000 */  nop
/* 1EE88 8002E688 01004224 */  addiu      $v0, $v0, 0x1
.L8002E68C:
/* 1EE8C 8002E68C 0780013C */  lui        $at, %hi(D_80075748)
/* 1EE90 8002E690 485722AC */  sw         $v0, %lo(D_80075748)($at)
.L8002E694:
/* 1EE94 8002E694 0780023C */  lui        $v0, %hi(g_Spu + 0x31C)
/* 1EE98 8002E698 24624224 */  addiu      $v0, $v0, %lo(g_Spu + 0x31C)
/* 1EE9C 8002E69C 0780033C */  lui        $v1, %hi(D_80075748)
/* 1EEA0 8002E6A0 4857638C */  lw         $v1, %lo(D_80075748)($v1)
/* 1EEA4 8002E6A4 C0000524 */  addiu      $a1, $zero, 0xC0
/* 1EEA8 8002E6A8 E4FC45AC */  sw         $a1, -0x31C($v0)
/* 1EEAC 8002E6AC C01A0300 */  sll        $v1, $v1, 11
/* 1EEB0 8002E6B0 000043AC */  sw         $v1, 0x0($v0)
/* 1EEB4 8002E6B4 0780013C */  lui        $at, %hi(g_Spu + 0x10)
/* 1EEB8 8002E6B8 185F23A4 */  sh         $v1, %lo(g_Spu + 0x10)($at)
/* 1EEBC 8002E6BC 0780013C */  lui        $at, %hi(g_Spu + 0x12)
/* 1EEC0 8002E6C0 1A5F23A4 */  sh         $v1, %lo(g_Spu + 0x12)($at)
/* 1EEC4 8002E6C4 1673010C */  jal        SpuSetCommonAttr
/* 1EEC8 8002E6C8 E4FC4424 */   addiu     $a0, $v0, -0x31C
/* 1EECC 8002E6CC C5BA0008 */  j          .L8002EB14
/* 1EED0 8002E6D0 00000000 */   nop
.L8002E6D4:
/* 1EED4 8002E6D4 0780023C */  lui        $v0, %hi(g_Pad)
/* 1EED8 8002E6D8 7873428C */  lw         $v0, %lo(g_Pad)($v0)
/* 1EEDC 8002E6DC 00000000 */  nop
/* 1EEE0 8002E6E0 40A04230 */  andi       $v0, $v0, 0xA040
/* 1EEE4 8002E6E4 0B014010 */  beqz       $v0, .L8002EB14
/* 1EEE8 8002E6E8 21280000 */   addu      $a1, $zero, $zero
/* 1EEEC 8002E6EC 0780023C */  lui        $v0, %hi(g_Spu + 0x2CC)
/* 1EEF0 8002E6F0 D461428C */  lw         $v0, %lo(g_Spu + 0x2CC)($v0)
/* 1EEF4 8002E6F4 10000624 */  addiu      $a2, $zero, 0x10
/* 1EEF8 8002E6F8 2E004490 */  lbu        $a0, 0x2E($v0)
/* 1EEFC 8002E6FC 9E56010C */  jal        PlaySound
/* 1EF00 8002E700 21380000 */   addu      $a3, $zero, $zero
/* 1EF04 8002E704 0780043C */  lui        $a0, %hi(g_Spu + 0x338)
/* 1EF08 8002E708 40628424 */  addiu      $a0, $a0, %lo(g_Spu + 0x338)
/* 1EF0C 8002E70C 0000838C */  lw         $v1, 0x0($a0)
/* 1EF10 8002E710 01000224 */  addiu      $v0, $zero, 0x1
/* 1EF14 8002E714 23104300 */  subu       $v0, $v0, $v1
/* 1EF18 8002E718 0C004010 */  beqz       $v0, .L8002E74C
/* 1EF1C 8002E71C 000082AC */   sw        $v0, 0x0($a0)
/* 1EF20 8002E720 3F000224 */  addiu      $v0, $zero, 0x3F
/* 1EF24 8002E724 0780013C */  lui        $at, %hi(g_CdMusic + 0x223)
/* 1EF28 8002E728 D37622A0 */  sb         $v0, %lo(g_CdMusic + 0x223)($at)
/* 1EF2C 8002E72C 0780013C */  lui        $at, %hi(g_CdMusic + 0x222)
/* 1EF30 8002E730 D27622A0 */  sb         $v0, %lo(g_CdMusic + 0x222)($at)
/* 1EF34 8002E734 0780013C */  lui        $at, %hi(g_CdMusic + 0x221)
/* 1EF38 8002E738 D17622A0 */  sb         $v0, %lo(g_CdMusic + 0x221)($at)
/* 1EF3C 8002E73C 0780013C */  lui        $at, %hi(g_CdMusic + 0x220)
/* 1EF40 8002E740 D07622A0 */  sb         $v0, %lo(g_CdMusic + 0x220)($at)
/* 1EF44 8002E744 DCB90008 */  j          .L8002E770
/* 1EF48 8002E748 00000000 */   nop
.L8002E74C:
/* 1EF4C 8002E74C 7F000224 */  addiu      $v0, $zero, 0x7F
/* 1EF50 8002E750 0780013C */  lui        $at, %hi(g_CdMusic + 0x222)
/* 1EF54 8002E754 D27622A0 */  sb         $v0, %lo(g_CdMusic + 0x222)($at)
/* 1EF58 8002E758 0780013C */  lui        $at, %hi(g_CdMusic + 0x220)
/* 1EF5C 8002E75C D07622A0 */  sb         $v0, %lo(g_CdMusic + 0x220)($at)
/* 1EF60 8002E760 0780013C */  lui        $at, %hi(g_CdMusic + 0x223)
/* 1EF64 8002E764 D37620A0 */  sb         $zero, %lo(g_CdMusic + 0x223)($at)
/* 1EF68 8002E768 0780013C */  lui        $at, %hi(g_CdMusic + 0x221)
/* 1EF6C 8002E76C D17620A0 */  sb         $zero, %lo(g_CdMusic + 0x221)($at)
.L8002E770:
/* 1EF70 8002E770 0780043C */  lui        $a0, %hi(g_CdMusic + 0x220)
/* 1EF74 8002E774 D0768424 */  addiu      $a0, $a0, %lo(g_CdMusic + 0x220)
/* 1EF78 8002E778 FC8F010C */  jal        CdMix
/* 1EF7C 8002E77C 00000000 */   nop
/* 1EF80 8002E780 C5BA0008 */  j          .L8002EB14
/* 1EF84 8002E784 00000000 */   nop
.L8002E788:
/* 1EF88 8002E788 0780023C */  lui        $v0, %hi(g_ActAvailable)
/* 1EF8C 8002E78C D856428C */  lw         $v0, %lo(g_ActAvailable)($v0)
/* 1EF90 8002E790 00000000 */  nop
/* 1EF94 8002E794 1F004010 */  beqz       $v0, .L8002E814
/* 1EF98 8002E798 04000224 */   addiu     $v0, $zero, 0x4
/* 1EF9C 8002E79C 0780023C */  lui        $v0, %hi(g_Pad)
/* 1EFA0 8002E7A0 7873428C */  lw         $v0, %lo(g_Pad)($v0)
/* 1EFA4 8002E7A4 00000000 */  nop
/* 1EFA8 8002E7A8 40A04230 */  andi       $v0, $v0, 0xA040
/* 1EFAC 8002E7AC D9004010 */  beqz       $v0, .L8002EB14
/* 1EFB0 8002E7B0 21280000 */   addu      $a1, $zero, $zero
/* 1EFB4 8002E7B4 0780023C */  lui        $v0, %hi(g_Spu + 0x2CC)
/* 1EFB8 8002E7B8 D461428C */  lw         $v0, %lo(g_Spu + 0x2CC)($v0)
/* 1EFBC 8002E7BC 10000624 */  addiu      $a2, $zero, 0x10
/* 1EFC0 8002E7C0 2E004490 */  lbu        $a0, 0x2E($v0)
/* 1EFC4 8002E7C4 9E56010C */  jal        PlaySound
/* 1EFC8 8002E7C8 21380000 */   addu      $a3, $zero, $zero
/* 1EFCC 8002E7CC 0780033C */  lui        $v1, %hi(g_ActEnabled)
/* 1EFD0 8002E7D0 A457638C */  lw         $v1, %lo(g_ActEnabled)($v1)
/* 1EFD4 8002E7D4 01000224 */  addiu      $v0, $zero, 0x1
/* 1EFD8 8002E7D8 23104300 */  subu       $v0, $v0, $v1
/* 1EFDC 8002E7DC 0780013C */  lui        $at, %hi(g_ActEnabled)
/* 1EFE0 8002E7E0 A45722AC */  sw         $v0, %lo(g_ActEnabled)($at)
/* 1EFE4 8002E7E4 CB004010 */  beqz       $v0, .L8002EB14
/* 1EFE8 8002E7E8 00000000 */   nop
/* 1EFEC 8002E7EC 0780023C */  lui        $v0, %hi(D_80075764)
/* 1EFF0 8002E7F0 6457428C */  lw         $v0, %lo(D_80075764)($v0)
/* 1EFF4 8002E7F4 00000000 */  nop
/* 1EFF8 8002E7F8 0A004228 */  slti       $v0, $v0, 0xA
/* 1EFFC 8002E7FC C5004010 */  beqz       $v0, .L8002EB14
/* 1F000 8002E800 0A000224 */   addiu     $v0, $zero, 0xA
/* 1F004 8002E804 0780013C */  lui        $at, %hi(D_80075764)
/* 1F008 8002E808 645722AC */  sw         $v0, %lo(D_80075764)($at)
/* 1F00C 8002E80C C5BA0008 */  j          .L8002EB14
/* 1F010 8002E810 00000000 */   nop
.L8002E814:
/* 1F014 8002E814 0780013C */  lui        $at, %hi(D_80075720)
/* 1F018 8002E818 205722AC */  sw         $v0, %lo(D_80075720)($at)
/* 1F01C 8002E81C C5BA0008 */  j          .L8002EB14
/* 1F020 8002E820 00000000 */   nop
.L8002E824:
/* 1F024 8002E824 0780023C */  lui        $v0, %hi(g_Pad)
/* 1F028 8002E828 7873428C */  lw         $v0, %lo(g_Pad)($v0)
/* 1F02C 8002E82C 00000000 */  nop
/* 1F030 8002E830 40A04230 */  andi       $v0, $v0, 0xA040
/* 1F034 8002E834 B7004010 */  beqz       $v0, .L8002EB14
/* 1F038 8002E838 21280000 */   addu      $a1, $zero, $zero
/* 1F03C 8002E83C 0780023C */  lui        $v0, %hi(g_Spu + 0x2CC)
/* 1F040 8002E840 D461428C */  lw         $v0, %lo(g_Spu + 0x2CC)($v0)
/* 1F044 8002E844 10000624 */  addiu      $a2, $zero, 0x10
/* 1F048 8002E848 2E004490 */  lbu        $a0, 0x2E($v0)
/* 1F04C 8002E84C 9E56010C */  jal        PlaySound
/* 1F050 8002E850 21380000 */   addu      $a3, $zero, $zero
/* 1F054 8002E854 0780023C */  lui        $v0, %hi(D_80075914)
/* 1F058 8002E858 1459428C */  lw         $v0, %lo(D_80075914)($v0)
/* 1F05C 8002E85C 02000324 */  addiu      $v1, $zero, 0x2
/* 1F060 8002E860 05004314 */  bne        $v0, $v1, .L8002E878
/* 1F064 8002E864 52000224 */   addiu     $v0, $zero, 0x52
/* 1F068 8002E868 0780013C */  lui        $at, %hi(D_80075914)
/* 1F06C 8002E86C 145922AC */  sw         $v0, %lo(D_80075914)($at)
/* 1F070 8002E870 C5BA0008 */  j          .L8002EB14
/* 1F074 8002E874 00000000 */   nop
.L8002E878:
/* 1F078 8002E878 0780013C */  lui        $at, %hi(D_80075914)
/* 1F07C 8002E87C 145923AC */  sw         $v1, %lo(D_80075914)($at)
/* 1F080 8002E880 C5BA0008 */  j          .L8002EB14
/* 1F084 8002E884 00000000 */   nop
.L8002E888:
/* 1F088 8002E888 0780023C */  lui        $v0, %hi(g_Pad)
/* 1F08C 8002E88C 7873428C */  lw         $v0, %lo(g_Pad)($v0)
/* 1F090 8002E890 00000000 */  nop
/* 1F094 8002E894 40004230 */  andi       $v0, $v0, 0x40
/* 1F098 8002E898 9E004010 */  beqz       $v0, .L8002EB14
/* 1F09C 8002E89C 21280000 */   addu      $a1, $zero, $zero
.L8002E8A0:
/* 1F0A0 8002E8A0 0780023C */  lui        $v0, %hi(g_Spu + 0x2CC)
/* 1F0A4 8002E8A4 D461428C */  lw         $v0, %lo(g_Spu + 0x2CC)($v0)
/* 1F0A8 8002E8A8 10000624 */  addiu      $a2, $zero, 0x10
/* 1F0AC 8002E8AC 2E004490 */  lbu        $a0, 0x2E($v0)
/* 1F0B0 8002E8B0 9E56010C */  jal        PlaySound
/* 1F0B4 8002E8B4 21380000 */   addu      $a3, $zero, $zero
/* 1F0B8 8002E8B8 0780013C */  lui        $at, %hi(D_800757C8)
/* 1F0BC 8002E8BC C85720AC */  sw         $zero, %lo(D_800757C8)($at)
/* 1F0C0 8002E8C0 0780013C */  lui        $at, %hi(D_80075720)
/* 1F0C4 8002E8C4 205720AC */  sw         $zero, %lo(D_80075720)($at)
/* 1F0C8 8002E8C8 C5BA0008 */  j          .L8002EB14
/* 1F0CC 8002E8CC 00000000 */   nop
.L8002E8D0:
/* 1F0D0 8002E8D0 16004010 */  beqz       $v0, .L8002E92C
/* 1F0D4 8002E8D4 03001024 */   addiu     $s0, $zero, 0x3
/* 1F0D8 8002E8D8 21280000 */  addu       $a1, $zero, $zero
/* 1F0DC 8002E8DC 0780023C */  lui        $v0, %hi(g_Spu + 0x2CC)
/* 1F0E0 8002E8E0 D461428C */  lw         $v0, %lo(g_Spu + 0x2CC)($v0)
/* 1F0E4 8002E8E4 10000624 */  addiu      $a2, $zero, 0x10
/* 1F0E8 8002E8E8 2D004490 */  lbu        $a0, 0x2D($v0)
/* 1F0EC 8002E8EC 9E56010C */  jal        PlaySound
/* 1F0F0 8002E8F0 21380000 */   addu      $a3, $zero, $zero
/* 1F0F4 8002E8F4 0780023C */  lui        $v0, %hi(D_80075720)
/* 1F0F8 8002E8F8 2057428C */  lw         $v0, %lo(D_80075720)($v0)
/* 1F0FC 8002E8FC 0780013C */  lui        $at, %hi(D_8007568C)
/* 1F100 8002E900 8C5620AC */  sw         $zero, %lo(D_8007568C)($at)
/* 1F104 8002E904 01004224 */  addiu      $v0, $v0, 0x1
/* 1F108 8002E908 0780013C */  lui        $at, %hi(D_80075720)
/* 1F10C 8002E90C 205722AC */  sw         $v0, %lo(D_80075720)($at)
/* 1F110 8002E910 2A100202 */  slt        $v0, $s0, $v0
/* 1F114 8002E914 19004010 */  beqz       $v0, .L8002E97C
/* 1F118 8002E918 00000000 */   nop
/* 1F11C 8002E91C 0780013C */  lui        $at, %hi(D_80075720)
/* 1F120 8002E920 205720AC */  sw         $zero, %lo(D_80075720)($at)
/* 1F124 8002E924 5FBA0008 */  j          .L8002E97C
/* 1F128 8002E928 00000000 */   nop
.L8002E92C:
/* 1F12C 8002E92C 00108230 */  andi       $v0, $a0, 0x1000
/* 1F130 8002E930 12004010 */  beqz       $v0, .L8002E97C
/* 1F134 8002E934 21280000 */   addu      $a1, $zero, $zero
/* 1F138 8002E938 0780023C */  lui        $v0, %hi(g_Spu + 0x2CC)
/* 1F13C 8002E93C D461428C */  lw         $v0, %lo(g_Spu + 0x2CC)($v0)
/* 1F140 8002E940 10000624 */  addiu      $a2, $zero, 0x10
/* 1F144 8002E944 2D004490 */  lbu        $a0, 0x2D($v0)
/* 1F148 8002E948 9E56010C */  jal        PlaySound
/* 1F14C 8002E94C 21380000 */   addu      $a3, $zero, $zero
/* 1F150 8002E950 0780023C */  lui        $v0, %hi(D_80075720)
/* 1F154 8002E954 2057428C */  lw         $v0, %lo(D_80075720)($v0)
/* 1F158 8002E958 0780013C */  lui        $at, %hi(D_8007568C)
/* 1F15C 8002E95C 8C5620AC */  sw         $zero, %lo(D_8007568C)($at)
/* 1F160 8002E960 FFFF4224 */  addiu      $v0, $v0, -0x1
/* 1F164 8002E964 0780013C */  lui        $at, %hi(D_80075720)
/* 1F168 8002E968 205722AC */  sw         $v0, %lo(D_80075720)($at)
/* 1F16C 8002E96C 03004104 */  bgez       $v0, .L8002E97C
/* 1F170 8002E970 00000000 */   nop
/* 1F174 8002E974 0780013C */  lui        $at, %hi(D_80075720)
/* 1F178 8002E978 205730AC */  sw         $s0, %lo(D_80075720)($at)
.L8002E97C:
/* 1F17C 8002E97C 0780023C */  lui        $v0, %hi(g_Pad)
/* 1F180 8002E980 7873428C */  lw         $v0, %lo(g_Pad)($v0)
/* 1F184 8002E984 00000000 */  nop
/* 1F188 8002E988 40084230 */  andi       $v0, $v0, 0x840
/* 1F18C 8002E98C 61004010 */  beqz       $v0, .L8002EB14
/* 1F190 8002E990 01001024 */   addiu     $s0, $zero, 0x1
/* 1F194 8002E994 0780033C */  lui        $v1, %hi(D_80075720)
/* 1F198 8002E998 2057638C */  lw         $v1, %lo(D_80075720)($v1)
/* 1F19C 8002E99C 00000000 */  nop
/* 1F1A0 8002E9A0 17007010 */  beq        $v1, $s0, .L8002EA00
/* 1F1A4 8002E9A4 02006228 */   slti      $v0, $v1, 0x2
/* 1F1A8 8002E9A8 05004010 */  beqz       $v0, .L8002E9C0
/* 1F1AC 8002E9AC 02001124 */   addiu     $s1, $zero, 0x2
/* 1F1B0 8002E9B0 09006010 */  beqz       $v1, .L8002E9D8
/* 1F1B4 8002E9B4 21280000 */   addu      $a1, $zero, $zero
/* 1F1B8 8002E9B8 C5BA0008 */  j          .L8002EB14
/* 1F1BC 8002E9BC 00000000 */   nop
.L8002E9C0:
/* 1F1C0 8002E9C0 1C007110 */  beq        $v1, $s1, .L8002EA34
/* 1F1C4 8002E9C4 03000224 */   addiu     $v0, $zero, 0x3
/* 1F1C8 8002E9C8 1E006210 */  beq        $v1, $v0, .L8002EA44
/* 1F1CC 8002E9CC 21280000 */   addu      $a1, $zero, $zero
/* 1F1D0 8002E9D0 C5BA0008 */  j          .L8002EB14
/* 1F1D4 8002E9D4 00000000 */   nop
.L8002E9D8:
/* 1F1D8 8002E9D8 0780023C */  lui        $v0, %hi(g_Spu + 0x2CC)
/* 1F1DC 8002E9DC D461428C */  lw         $v0, %lo(g_Spu + 0x2CC)($v0)
/* 1F1E0 8002E9E0 10000624 */  addiu      $a2, $zero, 0x10
/* 1F1E4 8002E9E4 2E004490 */  lbu        $a0, 0x2E($v0)
/* 1F1E8 8002E9E8 9E56010C */  jal        PlaySound
/* 1F1EC 8002E9EC 21380000 */   addu      $a3, $zero, $zero
/* 1F1F0 8002E9F0 4DB1000C */  jal        func_8002C534
/* 1F1F4 8002E9F4 01000424 */   addiu     $a0, $zero, 0x1
/* 1F1F8 8002E9F8 C5BA0008 */  j          .L8002EB14
/* 1F1FC 8002E9FC 00000000 */   nop
.L8002EA00:
/* 1F200 8002EA00 21280000 */  addu       $a1, $zero, $zero
/* 1F204 8002EA04 0780023C */  lui        $v0, %hi(g_Spu + 0x2CC)
/* 1F208 8002EA08 D461428C */  lw         $v0, %lo(g_Spu + 0x2CC)($v0)
/* 1F20C 8002EA0C 10000624 */  addiu      $a2, $zero, 0x10
/* 1F210 8002EA10 2E004490 */  lbu        $a0, 0x2E($v0)
/* 1F214 8002EA14 9E56010C */  jal        PlaySound
/* 1F218 8002EA18 21380000 */   addu      $a3, $zero, $zero
/* 1F21C 8002EA1C 0780013C */  lui        $at, %hi(D_800757C8)
/* 1F220 8002EA20 C85730AC */  sw         $s0, %lo(D_800757C8)($at)
/* 1F224 8002EA24 0780013C */  lui        $at, %hi(D_80075720)
/* 1F228 8002EA28 205720AC */  sw         $zero, %lo(D_80075720)($at)
/* 1F22C 8002EA2C C5BA0008 */  j          .L8002EB14
/* 1F230 8002EA30 00000000 */   nop
.L8002EA34:
/* 1F234 8002EA34 C5B1000C */  jal        func_8002C714
/* 1F238 8002EA38 21200000 */   addu      $a0, $zero, $zero
/* 1F23C 8002EA3C C5BA0008 */  j          .L8002EB14
/* 1F240 8002EA40 00000000 */   nop
.L8002EA44:
/* 1F244 8002EA44 0780023C */  lui        $v0, %hi(g_Spu + 0x2CC)
/* 1F248 8002EA48 D461428C */  lw         $v0, %lo(g_Spu + 0x2CC)($v0)
/* 1F24C 8002EA4C 10000624 */  addiu      $a2, $zero, 0x10
/* 1F250 8002EA50 2E004490 */  lbu        $a0, 0x2E($v0)
/* 1F254 8002EA54 9E56010C */  jal        PlaySound
/* 1F258 8002EA58 21380000 */   addu      $a3, $zero, $zero
/* 1F25C 8002EA5C 6666023C */  lui        $v0, (0x66666667 >> 16)
/* 1F260 8002EA60 0780043C */  lui        $a0, %hi(g_LevelId)
/* 1F264 8002EA64 6C59848C */  lw         $a0, %lo(g_LevelId)($a0)
/* 1F268 8002EA68 67664234 */  ori        $v0, $v0, (0x66666667 & 0xFFFF)
/* 1F26C 8002EA6C 18008200 */  mult       $a0, $v0
/* 1F270 8002EA70 C3170400 */  sra        $v0, $a0, 31
/* 1F274 8002EA74 10400000 */  mfhi       $t0
/* 1F278 8002EA78 83180800 */  sra        $v1, $t0, 2
/* 1F27C 8002EA7C 23186200 */  subu       $v1, $v1, $v0
/* 1F280 8002EA80 80100300 */  sll        $v0, $v1, 2
/* 1F284 8002EA84 21104300 */  addu       $v0, $v0, $v1
/* 1F288 8002EA88 40100200 */  sll        $v0, $v0, 1
/* 1F28C 8002EA8C 07008214 */  bne        $a0, $v0, .L8002EAAC
/* 1F290 8002EA90 00000000 */   nop
/* 1F294 8002EA94 0780013C */  lui        $at, %hi(D_80075720)
/* 1F298 8002EA98 205730AC */  sw         $s0, %lo(D_80075720)($at)
/* 1F29C 8002EA9C 0780013C */  lui        $at, %hi(D_800757C8)
/* 1F2A0 8002EAA0 C85731AC */  sw         $s1, %lo(D_800757C8)($at)
/* 1F2A4 8002EAA4 C5BA0008 */  j          .L8002EB14
/* 1F2A8 8002EAA8 00000000 */   nop
.L8002EAAC:
/* 1F2AC 8002EAAC 0880043C */  lui        $a0, %hi(g_Spyro + 0x1A4)
/* 1F2B0 8002EAB0 FC8B8424 */  addiu      $a0, $a0, %lo(g_Spyro + 0x1A4)
/* 1F2B4 8002EAB4 BC5D000C */  jal        VecNull
/* 1F2B8 8002EAB8 00000000 */   nop
/* 1F2BC 8002EABC 0780023C */  lui        $v0, %hi(g_IsFlightLevel)
/* 1F2C0 8002EAC0 9056428C */  lw         $v0, %lo(g_IsFlightLevel)($v0)
/* 1F2C4 8002EAC4 0880013C */  lui        $at, %hi(g_Spyro + 0x194)
/* 1F2C8 8002EAC8 EC8B20AC */  sw         $zero, %lo(g_Spyro + 0x194)($at)
/* 1F2CC 8002EACC 0F004010 */  beqz       $v0, .L8002EB0C
/* 1F2D0 8002EAD0 07000224 */   addiu     $v0, $zero, 0x7
/* 1F2D4 8002EAD4 0780033C */  lui        $v1, %hi(g_UpdateMoby)
/* 1F2D8 8002EAD8 3457638C */  lw         $v1, %lo(g_UpdateMoby)($v1)
/* 1F2DC 8002EADC 0780013C */  lui        $at, %hi(g_Gamestate)
/* 1F2E0 8002EAE0 D85722AC */  sw         $v0, %lo(g_Gamestate)($at)
/* 1F2E4 8002EAE4 0780013C */  lui        $at, %hi(D_80075720)
/* 1F2E8 8002EAE8 205720AC */  sw         $zero, %lo(D_80075720)($at)
/* 1F2EC 8002EAEC 0780013C */  lui        $at, %hi(D_8007568C)
/* 1F2F0 8002EAF0 8C5620AC */  sw         $zero, %lo(D_8007568C)($at)
/* 1F2F4 8002EAF4 0780013C */  lui        $at, %hi(D_80075900)
/* 1F2F8 8002EAF8 005930AC */  sw         $s0, %lo(D_80075900)($at)
/* 1F2FC 8002EAFC 09F86000 */  jalr       $v1
/* 1F300 8002EB00 00000000 */   nop
/* 1F304 8002EB04 C5BA0008 */  j          .L8002EB14
/* 1F308 8002EB08 00000000 */   nop
.L8002EB0C:
/* 1F30C 8002EB0C 86B1000C */  jal        func_8002C618
/* 1F310 8002EB10 00000000 */   nop
.L8002EB14:
/* 1F314 8002EB14 2800BF8F */  lw         $ra, 0x28($sp)
/* 1F318 8002EB18 2400B18F */  lw         $s1, 0x24($sp)
/* 1F31C 8002EB1C 2000B08F */  lw         $s0, 0x20($sp)
/* 1F320 8002EB20 3000BD27 */  addiu      $sp, $sp, 0x30
/* 1F324 8002EB24 0800E003 */  jr         $ra
/* 1F328 8002EB28 00000000 */   nop
.size func_8002E12C, . - func_8002E12C
