#ifndef LEVEL_45_PARTICLE_CONFIG_H
#define LEVEL_45_PARTICLE_CONFIG_H

#define LEVEL 45

#define HAS_PARTICLE_0
#define HAS_PARTICLE_1
#define HAS_PARTICLE_2
#define HAS_PARTICLE_9
#define HAS_PARTICLE_10
#define HAS_PARTICLE_11
#define HAS_PARTICLE_12
#define HAS_PARTICLE_26
#define HAS_PARTICLE_27
#define HAS_PARTICLE_33
#define HAS_PARTICLE_66
#define HAS_PARTICLE_71
#define HAS_PARTICLE_72
#define HAS_PARTICLE_77
#define HAS_PARTICLE_78
#define HAS_PARTICLE_79

#endif
