.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 2
dlabel D_level_11_8007AA5C
/* B83824 8007AA5C */ .asciz "%s THE BALLOONIST"
.align 2
.size D_level_11_8007AA5C, . - D_level_11_8007AA5C

.align 2
dlabel D_level_11_8007AA70
/* B83838 8007AA70 */ .asciz "HOP ON, SPYRO!"
.align 2
.size D_level_11_8007AA70, . - D_level_11_8007AA70

.align 2
dlabel D_level_11_8007AA80
/* B83848 8007AA80 */ .asciz "NEED A LIFT?"
.align 2
.size D_level_11_8007AA80, . - D_level_11_8007AA80

.align 2
dlabel D_level_11_8007AA90
/* B83858 8007AA90 */ .asciz "WHERE TO, SPYRO?"
.align 2
.size D_level_11_8007AA90, . - D_level_11_8007AA90

.align 2
dlabel D_level_11_8007AAA4
/* B8386C 8007AAA4 */ .asciz "STAY HERE"
.align 2
.size D_level_11_8007AAA4, . - D_level_11_8007AAA4

.align 2
dlabel D_level_11_8007AAB0
/* B83878 8007AAB0 */ .asciz "ARE YOU READY TO GO?"
.align 2
.size D_level_11_8007AAB0, . - D_level_11_8007AAB0

.align 2
dlabel D_level_11_8007AAC8
/* B83890 8007AAC8 */ .asciz "WOULD YOU LIKE TO GO?"
.align 2
.size D_level_11_8007AAC8, . - D_level_11_8007AAC8


.section .text
/* Generated by spimdisasm 1.27.0 */

glabel func_level_11_8007D070
/* B85E38 8007D070 08FFBD27 */  addiu      $sp, $sp, -0xF8
/* B85E3C 8007D074 E800B2AF */  sw         $s2, 0xE8($sp)
/* B85E40 8007D078 0780123C */  lui        $s2, %hi(D_800777E8)
/* B85E44 8007D07C E8775226 */  addiu      $s2, $s2, %lo(D_800777E8)
/* B85E48 8007D080 F400BFAF */  sw         $ra, 0xF4($sp)
/* B85E4C 8007D084 F000B4AF */  sw         $s4, 0xF0($sp)
/* B85E50 8007D088 EC00B3AF */  sw         $s3, 0xEC($sp)
/* B85E54 8007D08C E400B1AF */  sw         $s1, 0xE4($sp)
/* B85E58 8007D090 E000B0AF */  sw         $s0, 0xE0($sp)
/* B85E5C 8007D094 0000438E */  lw         $v1, 0x0($s2)
/* B85E60 8007D098 00000000 */  nop
/* B85E64 8007D09C 04006228 */  slti       $v0, $v1, 0x4
/* B85E68 8007D0A0 53024010 */  beqz       $v0, .Llevel_11_8007D9F0
/* B85E6C 8007D0A4 02006228 */   slti      $v0, $v1, 0x2
/* B85E70 8007D0A8 46004010 */  beqz       $v0, .Llevel_11_8007D1C4
/* B85E74 8007D0AC 6666023C */   lui       $v0, (0x66666667 >> 16)
/* B85E78 8007D0B0 0780033C */  lui        $v1, %hi(g_LevelId)
/* B85E7C 8007D0B4 6C59638C */  lw         $v1, %lo(g_LevelId)($v1)
/* B85E80 8007D0B8 67664234 */  ori        $v0, $v0, (0x66666667 & 0xFFFF)
/* B85E84 8007D0BC 18006200 */  mult       $v1, $v0
/* B85E88 8007D0C0 3800B027 */  addiu      $s0, $sp, 0x38
/* B85E8C 8007D0C4 0880053C */  lui        $a1, %hi(D_level_11_8007AA5C)
/* B85E90 8007D0C8 5CAAA524 */  addiu      $a1, $a1, %lo(D_level_11_8007AA5C)
/* B85E94 8007D0CC C31F0300 */  sra        $v1, $v1, 31
/* B85E98 8007D0D0 10400000 */  mfhi       $t0
/* B85E9C 8007D0D4 83100800 */  sra        $v0, $t0, 2
/* B85EA0 8007D0D8 23104300 */  subu       $v0, $v0, $v1
/* B85EA4 8007D0DC 80100200 */  sll        $v0, $v0, 2
/* B85EA8 8007D0E0 0780013C */  lui        $at, %hi(D_8006F884 - 0x04)
/* B85EAC 8007D0E4 21082200 */  addu       $at, $at, $v0
/* B85EB0 8007D0E8 80F8268C */  lw         $a2, %lo(D_8006F884 - 0x04)($at)
/* B85EB4 8007D0EC 0780113C */  lui        $s1, %hi(D_80075710)
/* B85EB8 8007D0F0 1057318E */  lw         $s1, %lo(D_80075710)($s1)
/* B85EBC 8007D0F4 F58B010C */  jal        sprintf
/* B85EC0 8007D0F8 21200002 */   addu      $a0, $s0, $zero
/* B85EC4 8007D0FC DB89010C */  jal        strlen
/* B85EC8 8007D100 21200002 */   addu      $a0, $s0, $zero
/* B85ECC 8007D104 21200002 */  addu       $a0, $s0, $zero
/* B85ED0 8007D108 1800A527 */  addiu      $a1, $sp, 0x18
/* B85ED4 8007D10C 2800A627 */  addiu      $a2, $sp, 0x28
/* B85ED8 8007D110 12000724 */  addiu      $a3, $zero, 0x12
/* B85EDC 8007D114 C0100200 */  sll        $v0, $v0, 3
/* B85EE0 8007D118 08010324 */  addiu      $v1, $zero, 0x108
/* B85EE4 8007D11C 23186200 */  subu       $v1, $v1, $v0
/* B85EE8 8007D120 CC000224 */  addiu      $v0, $zero, 0xCC
/* B85EEC 8007D124 1C00A2AF */  sw         $v0, 0x1C($sp)
/* B85EF0 8007D128 00110224 */  addiu      $v0, $zero, 0x1100
/* B85EF4 8007D12C 2000A2AF */  sw         $v0, 0x20($sp)
/* B85EF8 8007D130 10000224 */  addiu      $v0, $zero, 0x10
/* B85EFC 8007D134 2800A2AF */  sw         $v0, 0x28($sp)
/* B85F00 8007D138 01000224 */  addiu      $v0, $zero, 0x1
/* B85F04 8007D13C 2C00A2AF */  sw         $v0, 0x2C($sp)
/* B85F08 8007D140 00140224 */  addiu      $v0, $zero, 0x1400
/* B85F0C 8007D144 3000A2AF */  sw         $v0, 0x30($sp)
/* B85F10 8007D148 0B000224 */  addiu      $v0, $zero, 0xB
/* B85F14 8007D14C 1800A3AF */  sw         $v1, 0x18($sp)
/* B85F18 8007D150 6B60000C */  jal        func_800181AC
/* B85F1C 8007D154 1000A2AF */   sw        $v0, 0x10($sp)
/* B85F20 8007D158 0780023C */  lui        $v0, %hi(D_80075710)
/* B85F24 8007D15C 1057428C */  lw         $v0, %lo(D_80075710)($v0)
/* B85F28 8007D160 A8FF3126 */  addiu      $s1, $s1, -0x58
/* B85F2C 8007D164 2A102202 */  slt        $v0, $s1, $v0
/* B85F30 8007D168 16004014 */  bnez       $v0, .Llevel_11_8007D1C4
/* B85F34 8007D16C 00000000 */   nop
/* B85F38 8007D170 04004526 */  addiu      $a1, $s2, 0x4
/* B85F3C 8007D174 0780043C */  lui        $a0, %hi(D_8006CC78)
/* B85F40 8007D178 78CC8424 */  addiu      $a0, $a0, %lo(D_8006CC78)
/* B85F44 8007D17C 21180000 */  addu       $v1, $zero, $zero
.Llevel_11_8007D180:
/* B85F48 8007D180 0000A28C */  lw         $v0, 0x0($a1)
/* B85F4C 8007D184 00000000 */  nop
/* B85F50 8007D188 80100200 */  sll        $v0, $v0, 2
/* B85F54 8007D18C 21104300 */  addu       $v0, $v0, $v1
/* B85F58 8007D190 FF004230 */  andi       $v0, $v0, 0xFF
/* B85F5C 8007D194 40100200 */  sll        $v0, $v0, 1
/* B85F60 8007D198 21104400 */  addu       $v0, $v0, $a0
/* B85F64 8007D19C 00004294 */  lhu        $v0, 0x0($v0)
/* B85F68 8007D1A0 00000000 */  nop
/* B85F6C 8007D1A4 02120200 */  srl        $v0, $v0, 8
/* B85F70 8007D1A8 460022A2 */  sb         $v0, 0x46($s1)
/* B85F74 8007D1AC 0780023C */  lui        $v0, %hi(D_80075710)
/* B85F78 8007D1B0 1057428C */  lw         $v0, %lo(D_80075710)($v0)
/* B85F7C 8007D1B4 A8FF3126 */  addiu      $s1, $s1, -0x58
/* B85F80 8007D1B8 2A102202 */  slt        $v0, $s1, $v0
/* B85F84 8007D1BC F0FF4010 */  beqz       $v0, .Llevel_11_8007D180
/* B85F88 8007D1C0 0C006324 */   addiu     $v1, $v1, 0xC
.Llevel_11_8007D1C4:
/* B85F8C 8007D1C4 0780133C */  lui        $s3, %hi(D_800777E8)
/* B85F90 8007D1C8 E877738E */  lw         $s3, %lo(D_800777E8)($s3)
/* B85F94 8007D1CC 01000224 */  addiu      $v0, $zero, 0x1
/* B85F98 8007D1D0 F5016216 */  bne        $s3, $v0, .Llevel_11_8007D9A8
/* B85F9C 8007D1D4 00000000 */   nop
/* B85FA0 8007D1D8 0780033C */  lui        $v1, %hi(D_800777F4)
/* B85FA4 8007D1DC F477638C */  lw         $v1, %lo(D_800777F4)($v1)
/* B85FA8 8007D1E0 00000000 */  nop
/* B85FAC 8007D1E4 E2FF6224 */  addiu      $v0, $v1, -0x1E
/* B85FB0 8007D1E8 0300422C */  sltiu      $v0, $v0, 0x3
/* B85FB4 8007D1EC 73004014 */  bnez       $v0, .Llevel_11_8007D3BC
/* B85FB8 8007D1F0 1E000224 */   addiu     $v0, $zero, 0x1E
/* B85FBC 8007D1F4 48000424 */  addiu      $a0, $zero, 0x48
/* B85FC0 8007D1F8 B8010524 */  addiu      $a1, $zero, 0x1B8
/* B85FC4 8007D1FC 1C000624 */  addiu      $a2, $zero, 0x1C
/* B85FC8 8007D200 8361000C */  jal        func_8001860C
/* B85FCC 8007D204 68000724 */   addiu     $a3, $zero, 0x68
/* B85FD0 8007D208 0780033C */  lui        $v1, %hi(D_800777F4)
/* B85FD4 8007D20C F477638C */  lw         $v1, %lo(D_800777F4)($v1)
/* B85FD8 8007D210 2C000224 */  addiu      $v0, $zero, 0x2C
/* B85FDC 8007D214 5C00A2AF */  sw         $v0, 0x5C($sp)
/* B85FE0 8007D218 00110224 */  addiu      $v0, $zero, 0x1100
/* B85FE4 8007D21C 6000A2AF */  sw         $v0, 0x60($sp)
/* B85FE8 8007D220 10000224 */  addiu      $v0, $zero, 0x10
/* B85FEC 8007D224 6800A2AF */  sw         $v0, 0x68($sp)
/* B85FF0 8007D228 00140224 */  addiu      $v0, $zero, 0x1400
/* B85FF4 8007D22C 6C00B3AF */  sw         $s3, 0x6C($sp)
/* B85FF8 8007D230 7000A2AF */  sw         $v0, 0x70($sp)
/* B85FFC 8007D234 0780013C */  lui        $at, %hi(balloonistDialogue)
/* B86000 8007D238 21082300 */  addu       $at, $at, $v1
/* B86004 8007D23C 9CF83090 */  lbu        $s0, %lo(balloonistDialogue)($at)
/* B86008 8007D240 0780013C */  lui        $at, %hi(D_8006F89D)
/* B8600C 8007D244 21082300 */  addu       $at, $at, $v1
/* B86010 8007D248 9DF82290 */  lbu        $v0, %lo(D_8006F89D)($at)
/* B86014 8007D24C 0780123C */  lui        $s2, %hi(D_80075710)
/* B86018 8007D250 1057528E */  lw         $s2, %lo(D_80075710)($s2)
/* B8601C 8007D254 2A100202 */  slt        $v0, $s0, $v0
/* B86020 8007D258 1A004010 */  beqz       $v0, .Llevel_11_8007D2C4
/* B86024 8007D25C 80101000 */   sll       $v0, $s0, 2
/* B86028 8007D260 5E001324 */  addiu      $s3, $zero, 0x5E
/* B8602C 8007D264 0780033C */  lui        $v1, %hi(balloonistDialogueText)
/* B86030 8007D268 C4F86324 */  addiu      $v1, $v1, %lo(balloonistDialogueText)
/* B86034 8007D26C 21884300 */  addu       $s1, $v0, $v1
/* B86038 8007D270 5800A527 */  addiu      $a1, $sp, 0x58
.Llevel_11_8007D274:
/* B8603C 8007D274 6800A627 */  addiu      $a2, $sp, 0x68
/* B86040 8007D278 12000724 */  addiu      $a3, $zero, 0x12
/* B86044 8007D27C 0B000224 */  addiu      $v0, $zero, 0xB
/* B86048 8007D280 5800B3AF */  sw         $s3, 0x58($sp)
/* B8604C 8007D284 1000A2AF */  sw         $v0, 0x10($sp)
/* B86050 8007D288 0000248E */  lw         $a0, 0x0($s1)
/* B86054 8007D28C 6B60000C */  jal        func_800181AC
/* B86058 8007D290 04003126 */   addiu     $s1, $s1, 0x4
/* B8605C 8007D294 5C00A28F */  lw         $v0, 0x5C($sp)
/* B86060 8007D298 0780033C */  lui        $v1, %hi(D_800777F4)
/* B86064 8007D29C F477638C */  lw         $v1, %lo(D_800777F4)($v1)
/* B86068 8007D2A0 12004224 */  addiu      $v0, $v0, 0x12
/* B8606C 8007D2A4 5C00A2AF */  sw         $v0, 0x5C($sp)
/* B86070 8007D2A8 0780013C */  lui        $at, %hi(D_8006F89D)
/* B86074 8007D2AC 21082300 */  addu       $at, $at, $v1
/* B86078 8007D2B0 9DF82290 */  lbu        $v0, %lo(D_8006F89D)($at)
/* B8607C 8007D2B4 01001026 */  addiu      $s0, $s0, 0x1
/* B86080 8007D2B8 2A100202 */  slt        $v0, $s0, $v0
/* B86084 8007D2BC EDFF4014 */  bnez       $v0, .Llevel_11_8007D274
/* B86088 8007D2C0 5800A527 */   addiu     $a1, $sp, 0x58
.Llevel_11_8007D2C4:
/* B8608C 8007D2C4 0780033C */  lui        $v1, %hi(D_800777EC)
/* B86090 8007D2C8 EC77638C */  lw         $v1, %lo(D_800777EC)($v1)
/* B86094 8007D2CC 00000000 */  nop
/* B86098 8007D2D0 50006228 */  slti       $v0, $v1, 0x50
/* B8609C 8007D2D4 0D004010 */  beqz       $v0, .Llevel_11_8007D30C
/* B860A0 8007D2D8 40100300 */   sll       $v0, $v1, 1
/* B860A4 8007D2DC 21104300 */  addu       $v0, $v0, $v1
/* B860A8 8007D2E0 80100200 */  sll        $v0, $v0, 2
/* B860AC 8007D2E4 23104300 */  subu       $v0, $v0, $v1
/* B860B0 8007D2E8 C0100200 */  sll        $v0, $v0, 3
/* B860B4 8007D2EC 0780033C */  lui        $v1, %hi(D_80075710)
/* B860B8 8007D2F0 1057638C */  lw         $v1, %lo(D_80075710)($v1)
/* B860BC 8007D2F4 23104202 */  subu       $v0, $s2, $v0
/* B860C0 8007D2F8 2A184300 */  slt        $v1, $v0, $v1
/* B860C4 8007D2FC 03006014 */  bnez       $v1, .Llevel_11_8007D30C
/* B860C8 8007D300 00000000 */   nop
/* B860CC 8007D304 0780013C */  lui        $at, %hi(D_80075710)
/* B860D0 8007D308 105722AC */  sw         $v0, %lo(D_80075710)($at)
.Llevel_11_8007D30C:
/* B860D4 8007D30C 0780023C */  lui        $v0, %hi(D_80075710)
/* B860D8 8007D310 1057428C */  lw         $v0, %lo(D_80075710)($v0)
/* B860DC 8007D314 A8FF5226 */  addiu      $s2, $s2, -0x58
/* B860E0 8007D318 2A104202 */  slt        $v0, $s2, $v0
/* B860E4 8007D31C 17004014 */  bnez       $v0, .Llevel_11_8007D37C
/* B860E8 8007D320 00000000 */   nop
/* B860EC 8007D324 0780053C */  lui        $a1, %hi(D_800777EC)
/* B860F0 8007D328 EC77A524 */  addiu      $a1, $a1, %lo(D_800777EC)
/* B860F4 8007D32C 0780043C */  lui        $a0, %hi(D_8006CC78)
/* B860F8 8007D330 78CC8424 */  addiu      $a0, $a0, %lo(D_8006CC78)
/* B860FC 8007D334 21180000 */  addu       $v1, $zero, $zero
.Llevel_11_8007D338:
/* B86100 8007D338 0000A28C */  lw         $v0, 0x0($a1)
/* B86104 8007D33C 00000000 */  nop
/* B86108 8007D340 80100200 */  sll        $v0, $v0, 2
/* B8610C 8007D344 21104300 */  addu       $v0, $v0, $v1
/* B86110 8007D348 FF004230 */  andi       $v0, $v0, 0xFF
/* B86114 8007D34C 40100200 */  sll        $v0, $v0, 1
/* B86118 8007D350 21104400 */  addu       $v0, $v0, $a0
/* B8611C 8007D354 00004294 */  lhu        $v0, 0x0($v0)
/* B86120 8007D358 00000000 */  nop
/* B86124 8007D35C 02120200 */  srl        $v0, $v0, 8
/* B86128 8007D360 460042A2 */  sb         $v0, 0x46($s2)
/* B8612C 8007D364 0780023C */  lui        $v0, %hi(D_80075710)
/* B86130 8007D368 1057428C */  lw         $v0, %lo(D_80075710)($v0)
/* B86134 8007D36C A8FF5226 */  addiu      $s2, $s2, -0x58
/* B86138 8007D370 2A104202 */  slt        $v0, $s2, $v0
/* B8613C 8007D374 F0FF4010 */  beqz       $v0, .Llevel_11_8007D338
/* B86140 8007D378 0C006324 */   addiu     $v1, $v1, 0xC
.Llevel_11_8007D37C:
/* B86144 8007D37C 0780053C */  lui        $a1, %hi(D_800777EC)
/* B86148 8007D380 EC77A58C */  lw         $a1, %lo(D_800777EC)($a1)
/* B8614C 8007D384 00000000 */  nop
/* B86150 8007D388 5000A228 */  slti       $v0, $a1, 0x50
/* B86154 8007D38C 86014014 */  bnez       $v0, .Llevel_11_8007D9A8
/* B86158 8007D390 5800A427 */   addiu     $a0, $sp, 0x58
/* B8615C 8007D394 21300000 */  addu       $a2, $zero, $zero
/* B86160 8007D398 9C010224 */  addiu      $v0, $zero, 0x19C
/* B86164 8007D39C 5800A2AF */  sw         $v0, 0x58($sp)
/* B86168 8007D3A0 60000224 */  addiu      $v0, $zero, 0x60
/* B8616C 8007D3A4 5C00A2AF */  sw         $v0, 0x5C($sp)
/* B86170 8007D3A8 00110224 */  addiu      $v0, $zero, 0x1100
/* B86174 8007D3AC 4D61000C */  jal        func_80018534
/* B86178 8007D3B0 6000A2AF */   sw        $v0, 0x60($sp)
/* B8617C 8007D3B4 6AF60108 */  j          .Llevel_11_8007D9A8
/* B86180 8007D3B8 00000000 */   nop
.Llevel_11_8007D3BC:
/* B86184 8007D3BC B9006214 */  bne        $v1, $v0, .Llevel_11_8007D6A4
/* B86188 8007D3C0 E1FF6224 */   addiu     $v0, $v1, -0x1F
/* B8618C 8007D3C4 0780033C */  lui        $v1, %hi(D_800777F8)
/* B86190 8007D3C8 F877638C */  lw         $v1, %lo(D_800777F8)($v1)
/* B86194 8007D3CC 0E000224 */  addiu      $v0, $zero, 0xE
/* B86198 8007D3D0 8800A2AF */  sw         $v0, 0x88($sp)
/* B8619C 8007D3D4 00160224 */  addiu      $v0, $zero, 0x1600
/* B861A0 8007D3D8 9000A2AF */  sw         $v0, 0x90($sp)
/* B861A4 8007D3DC 00140224 */  addiu      $v0, $zero, 0x1400
/* B861A8 8007D3E0 8000A2AF */  sw         $v0, 0x80($sp)
/* B861AC 8007D3E4 F0000224 */  addiu      $v0, $zero, 0xF0
/* B861B0 8007D3E8 7800A2AF */  sw         $v0, 0x78($sp)
/* B861B4 8007D3EC 24000224 */  addiu      $v0, $zero, 0x24
/* B861B8 8007D3F0 8C00B3AF */  sw         $s3, 0x8C($sp)
/* B861BC 8007D3F4 06006014 */  bnez       $v1, .Llevel_11_8007D410
/* B861C0 8007D3F8 7C00A2AF */   sw        $v0, 0x7C($sp)
/* B861C4 8007D3FC 0B000224 */  addiu      $v0, $zero, 0xB
/* B861C8 8007D400 0880043C */  lui        $a0, %hi(D_level_11_8007AA70)
/* B861CC 8007D404 70AA8424 */  addiu      $a0, $a0, %lo(D_level_11_8007AA70)
/* B861D0 8007D408 0DF50108 */  j          .Llevel_11_8007D434
/* B861D4 8007D40C 1000A2AF */   sw        $v0, 0x10($sp)
.Llevel_11_8007D410:
/* B861D8 8007D410 05007314 */  bne        $v1, $s3, .Llevel_11_8007D428
/* B861DC 8007D414 0B000224 */   addiu     $v0, $zero, 0xB
/* B861E0 8007D418 0880043C */  lui        $a0, %hi(D_level_11_8007AA80)
/* B861E4 8007D41C 80AA8424 */  addiu      $a0, $a0, %lo(D_level_11_8007AA80)
/* B861E8 8007D420 0DF50108 */  j          .Llevel_11_8007D434
/* B861EC 8007D424 1000A2AF */   sw        $v0, 0x10($sp)
.Llevel_11_8007D428:
/* B861F0 8007D428 1000A2AF */  sw         $v0, 0x10($sp)
/* B861F4 8007D42C 0880043C */  lui        $a0, %hi(D_level_11_8007AA90)
/* B861F8 8007D430 90AA8424 */  addiu      $a0, $a0, %lo(D_level_11_8007AA90)
.Llevel_11_8007D434:
/* B861FC 8007D434 7800A527 */  addiu      $a1, $sp, 0x78
/* B86200 8007D438 8800A627 */  addiu      $a2, $sp, 0x88
/* B86204 8007D43C 6B60000C */  jal        func_800181AC
/* B86208 8007D440 10000724 */   addiu     $a3, $zero, 0x10
/* B8620C 8007D444 0880043C */  lui        $a0, %hi(D_level_11_8007AAA4)
/* B86210 8007D448 A4AA8424 */  addiu      $a0, $a0, %lo(D_level_11_8007AAA4)
/* B86214 8007D44C 7800A527 */  addiu      $a1, $sp, 0x78
/* B86218 8007D450 8800A627 */  addiu      $a2, $sp, 0x88
/* B8621C 8007D454 10000724 */  addiu      $a3, $zero, 0x10
/* B86220 8007D458 0780033C */  lui        $v1, %hi(D_80075710)
/* B86224 8007D45C 1057638C */  lw         $v1, %lo(D_80075710)($v1)
/* B86228 8007D460 10010224 */  addiu      $v0, $zero, 0x110
/* B8622C 8007D464 7800A2AF */  sw         $v0, 0x78($sp)
/* B86230 8007D468 7C00A28F */  lw         $v0, 0x7C($sp)
/* B86234 8007D46C A8FF7024 */  addiu      $s0, $v1, -0x58
/* B86238 8007D470 14004224 */  addiu      $v0, $v0, 0x14
/* B8623C 8007D474 7C00A2AF */  sw         $v0, 0x7C($sp)
/* B86240 8007D478 0B000224 */  addiu      $v0, $zero, 0xB
/* B86244 8007D47C 6B60000C */  jal        func_800181AC
/* B86248 8007D480 1000A2AF */   sw        $v0, 0x10($sp)
/* B8624C 8007D484 0780043C */  lui        $a0, %hi(D_800777F0)
/* B86250 8007D488 F0778424 */  addiu      $a0, $a0, %lo(D_800777F0)
/* B86254 8007D48C 7C00A28F */  lw         $v0, 0x7C($sp)
/* B86258 8007D490 0000838C */  lw         $v1, 0x0($a0)
/* B8625C 8007D494 0F004224 */  addiu      $v0, $v0, 0xF
/* B86260 8007D498 1C006014 */  bnez       $v1, .Llevel_11_8007D50C
/* B86264 8007D49C 7C00A2AF */   sw        $v0, 0x7C($sp)
/* B86268 8007D4A0 0780023C */  lui        $v0, %hi(D_80075710)
/* B8626C 8007D4A4 1057428C */  lw         $v0, %lo(D_80075710)($v0)
/* B86270 8007D4A8 00000000 */  nop
/* B86274 8007D4AC 2B100202 */  sltu       $v0, $s0, $v0
/* B86278 8007D4B0 17004014 */  bnez       $v0, .Llevel_11_8007D510
/* B8627C 8007D4B4 01001224 */   addiu     $s2, $zero, 0x1
/* B86280 8007D4B8 FCFF8324 */  addiu      $v1, $a0, -0x4
/* B86284 8007D4BC 0780053C */  lui        $a1, %hi(D_8006CC78)
/* B86288 8007D4C0 78CCA524 */  addiu      $a1, $a1, %lo(D_8006CC78)
/* B8628C 8007D4C4 21200000 */  addu       $a0, $zero, $zero
.Llevel_11_8007D4C8:
/* B86290 8007D4C8 0000628C */  lw         $v0, 0x0($v1)
/* B86294 8007D4CC 00000000 */  nop
/* B86298 8007D4D0 80100200 */  sll        $v0, $v0, 2
/* B8629C 8007D4D4 21104400 */  addu       $v0, $v0, $a0
/* B862A0 8007D4D8 FF004230 */  andi       $v0, $v0, 0xFF
/* B862A4 8007D4DC 40100200 */  sll        $v0, $v0, 1
/* B862A8 8007D4E0 21104500 */  addu       $v0, $v0, $a1
/* B862AC 8007D4E4 00004294 */  lhu        $v0, 0x0($v0)
/* B862B0 8007D4E8 00000000 */  nop
/* B862B4 8007D4EC 02120200 */  srl        $v0, $v0, 8
/* B862B8 8007D4F0 460002A2 */  sb         $v0, 0x46($s0)
/* B862BC 8007D4F4 0780023C */  lui        $v0, %hi(D_80075710)
/* B862C0 8007D4F8 1057428C */  lw         $v0, %lo(D_80075710)($v0)
/* B862C4 8007D4FC A8FF1026 */  addiu      $s0, $s0, -0x58
/* B862C8 8007D500 2B100202 */  sltu       $v0, $s0, $v0
/* B862CC 8007D504 F0FF4010 */  beqz       $v0, .Llevel_11_8007D4C8
/* B862D0 8007D508 0C008424 */   addiu     $a0, $a0, 0xC
.Llevel_11_8007D50C:
/* B862D4 8007D50C 01001224 */  addiu      $s2, $zero, 0x1
.Llevel_11_8007D510:
/* B862D8 8007D510 21880000 */  addu       $s1, $zero, $zero
/* B862DC 8007D514 0780143C */  lui        $s4, %hi(D_800777EC)
/* B862E0 8007D518 EC779426 */  addiu      $s4, $s4, %lo(D_800777EC)
/* B862E4 8007D51C 0780133C */  lui        $s3, %hi(D_8006CC78)
/* B862E8 8007D520 78CC7326 */  addiu      $s3, $s3, %lo(D_8006CC78)
/* B862EC 8007D524 6666023C */  lui        $v0, (0x66666667 >> 16)
.Llevel_11_8007D528:
/* B862F0 8007D528 0780033C */  lui        $v1, %hi(g_LevelId)
/* B862F4 8007D52C 6C59638C */  lw         $v1, %lo(g_LevelId)($v1)
/* B862F8 8007D530 67664234 */  ori        $v0, $v0, (0x66666667 & 0xFFFF)
/* B862FC 8007D534 18006200 */  mult       $v1, $v0
/* B86300 8007D538 C31F0300 */  sra        $v1, $v1, 31
/* B86304 8007D53C 10400000 */  mfhi       $t0
/* B86308 8007D540 83100800 */  sra        $v0, $t0, 2
/* B8630C 8007D544 23104300 */  subu       $v0, $v0, $v1
/* B86310 8007D548 FFFF4224 */  addiu      $v0, $v0, -0x1
/* B86314 8007D54C 34005110 */  beq        $v0, $s1, .Llevel_11_8007D620
/* B86318 8007D550 02000224 */   addiu     $v0, $zero, 0x2
/* B8631C 8007D554 0780013C */  lui        $at, %hi(D_800758D0)
/* B86320 8007D558 21083100 */  addu       $at, $at, $s1
/* B86324 8007D55C D0582390 */  lbu        $v1, %lo(D_800758D0)($at)
/* B86328 8007D560 00000000 */  nop
/* B8632C 8007D564 2E006214 */  bne        $v1, $v0, .Llevel_11_8007D620
/* B86330 8007D568 7800A527 */   addiu     $a1, $sp, 0x78
/* B86334 8007D56C 8800A627 */  addiu      $a2, $sp, 0x88
/* B86338 8007D570 10000724 */  addiu      $a3, $zero, 0x10
/* B8633C 8007D574 10010224 */  addiu      $v0, $zero, 0x110
/* B86340 8007D578 7800A2AF */  sw         $v0, 0x78($sp)
/* B86344 8007D57C 0B000224 */  addiu      $v0, $zero, 0xB
/* B86348 8007D580 1000A2AF */  sw         $v0, 0x10($sp)
/* B8634C 8007D584 80101100 */  sll        $v0, $s1, 2
/* B86350 8007D588 0780033C */  lui        $v1, %hi(D_80075710)
/* B86354 8007D58C 1057638C */  lw         $v1, %lo(D_80075710)($v1)
/* B86358 8007D590 0780013C */  lui        $at, %hi(homeworldNameTable)
/* B8635C 8007D594 21082200 */  addu       $at, $at, $v0
/* B86360 8007D598 D4F7248C */  lw         $a0, %lo(homeworldNameTable)($at)
/* B86364 8007D59C 6B60000C */  jal        func_800181AC
/* B86368 8007D5A0 A8FF7024 */   addiu     $s0, $v1, -0x58
/* B8636C 8007D5A4 7C00A28F */  lw         $v0, 0x7C($sp)
/* B86370 8007D5A8 0780033C */  lui        $v1, %hi(D_800777F0)
/* B86374 8007D5AC F077638C */  lw         $v1, %lo(D_800777F0)($v1)
/* B86378 8007D5B0 0F004224 */  addiu      $v0, $v0, 0xF
/* B8637C 8007D5B4 19007214 */  bne        $v1, $s2, .Llevel_11_8007D61C
/* B86380 8007D5B8 7C00A2AF */   sw        $v0, 0x7C($sp)
/* B86384 8007D5BC 0780023C */  lui        $v0, %hi(D_80075710)
/* B86388 8007D5C0 1057428C */  lw         $v0, %lo(D_80075710)($v0)
/* B8638C 8007D5C4 00000000 */  nop
/* B86390 8007D5C8 2B100202 */  sltu       $v0, $s0, $v0
/* B86394 8007D5CC 13004014 */  bnez       $v0, .Llevel_11_8007D61C
/* B86398 8007D5D0 00000000 */   nop
/* B8639C 8007D5D4 21180000 */  addu       $v1, $zero, $zero
.Llevel_11_8007D5D8:
/* B863A0 8007D5D8 0000828E */  lw         $v0, 0x0($s4)
/* B863A4 8007D5DC 00000000 */  nop
/* B863A8 8007D5E0 80100200 */  sll        $v0, $v0, 2
/* B863AC 8007D5E4 21104300 */  addu       $v0, $v0, $v1
/* B863B0 8007D5E8 FF004230 */  andi       $v0, $v0, 0xFF
/* B863B4 8007D5EC 40100200 */  sll        $v0, $v0, 1
/* B863B8 8007D5F0 21105300 */  addu       $v0, $v0, $s3
/* B863BC 8007D5F4 00004294 */  lhu        $v0, 0x0($v0)
/* B863C0 8007D5F8 00000000 */  nop
/* B863C4 8007D5FC 02120200 */  srl        $v0, $v0, 8
/* B863C8 8007D600 460002A2 */  sb         $v0, 0x46($s0)
/* B863CC 8007D604 0780023C */  lui        $v0, %hi(D_80075710)
/* B863D0 8007D608 1057428C */  lw         $v0, %lo(D_80075710)($v0)
/* B863D4 8007D60C A8FF1026 */  addiu      $s0, $s0, -0x58
/* B863D8 8007D610 2B100202 */  sltu       $v0, $s0, $v0
/* B863DC 8007D614 F0FF4010 */  beqz       $v0, .Llevel_11_8007D5D8
/* B863E0 8007D618 0C006324 */   addiu     $v1, $v1, 0xC
.Llevel_11_8007D61C:
/* B863E4 8007D61C 01005226 */  addiu      $s2, $s2, 0x1
.Llevel_11_8007D620:
/* B863E8 8007D620 01003126 */  addiu      $s1, $s1, 0x1
/* B863EC 8007D624 0600222A */  slti       $v0, $s1, 0x6
/* B863F0 8007D628 BFFF4014 */  bnez       $v0, .Llevel_11_8007D528
/* B863F4 8007D62C 6666023C */   lui       $v0, (0x66666667 >> 16)
/* B863F8 8007D630 E0000424 */  addiu      $a0, $zero, 0xE0
/* B863FC 8007D634 D8010524 */  addiu      $a1, $zero, 0x1D8
/* B86400 8007D638 19000624 */  addiu      $a2, $zero, 0x19
/* B86404 8007D63C 00391200 */  sll        $a3, $s2, 4
/* B86408 8007D640 2338F200 */  subu       $a3, $a3, $s2
/* B8640C 8007D644 8361000C */  jal        func_8001860C
/* B86410 8007D648 3300E724 */   addiu     $a3, $a3, 0x33
/* B86414 8007D64C F0000424 */  addiu      $a0, $zero, 0xF0
/* B86418 8007D650 2E000524 */  addiu      $a1, $zero, 0x2E
/* B8641C 8007D654 A0010624 */  addiu      $a2, $zero, 0x1A0
/* B86420 8007D658 1361000C */  jal        func_8001844C
/* B86424 8007D65C 2E000724 */   addiu     $a3, $zero, 0x2E
/* B86428 8007D660 7800A427 */  addiu      $a0, $sp, 0x78
/* B8642C 8007D664 21300000 */  addu       $a2, $zero, $zero
/* B86430 8007D668 0780053C */  lui        $a1, %hi(D_800777EC)
/* B86434 8007D66C EC77A58C */  lw         $a1, %lo(D_800777EC)($a1)
/* B86438 8007D670 0780033C */  lui        $v1, %hi(D_800777F0)
/* B8643C 8007D674 F077638C */  lw         $v1, %lo(D_800777F0)($v1)
/* B86440 8007D678 F4000224 */  addiu      $v0, $zero, 0xF4
/* B86444 8007D67C 7800A2AF */  sw         $v0, 0x78($sp)
/* B86448 8007D680 00110224 */  addiu      $v0, $zero, 0x1100
/* B8644C 8007D684 8000A2AF */  sw         $v0, 0x80($sp)
/* B86450 8007D688 00110300 */  sll        $v0, $v1, 4
/* B86454 8007D68C 23104300 */  subu       $v0, $v0, $v1
/* B86458 8007D690 36004224 */  addiu      $v0, $v0, 0x36
/* B8645C 8007D694 4D61000C */  jal        func_80018534
/* B86460 8007D698 7C00A2AF */   sw        $v0, 0x7C($sp)
/* B86464 8007D69C 6AF60108 */  j          .Llevel_11_8007D9A8
/* B86468 8007D6A0 00000000 */   nop
.Llevel_11_8007D6A4:
/* B8646C 8007D6A4 0200422C */  sltiu      $v0, $v0, 0x2
/* B86470 8007D6A8 BF004010 */  beqz       $v0, .Llevel_11_8007D9A8
/* B86474 8007D6AC 48000424 */   addiu     $a0, $zero, 0x48
/* B86478 8007D6B0 B8010524 */  addiu      $a1, $zero, 0x1B8
/* B8647C 8007D6B4 1C000624 */  addiu      $a2, $zero, 0x1C
/* B86480 8007D6B8 8361000C */  jal        func_8001860C
/* B86484 8007D6BC 66000724 */   addiu     $a3, $zero, 0x66
/* B86488 8007D6C0 64000424 */  addiu      $a0, $zero, 0x64
/* B8648C 8007D6C4 37000524 */  addiu      $a1, $zero, 0x37
/* B86490 8007D6C8 84010624 */  addiu      $a2, $zero, 0x184
/* B86494 8007D6CC 1361000C */  jal        func_8001844C
/* B86498 8007D6D0 37000724 */   addiu     $a3, $zero, 0x37
/* B8649C 8007D6D4 9800B227 */  addiu      $s2, $sp, 0x98
/* B864A0 8007D6D8 21204002 */  addu       $a0, $s2, $zero
/* B864A4 8007D6DC 21300000 */  addu       $a2, $zero, $zero
/* B864A8 8007D6E0 60001124 */  addiu      $s1, $zero, 0x60
/* B864AC 8007D6E4 0780053C */  lui        $a1, %hi(D_800777EC)
/* B864B0 8007D6E8 EC77A58C */  lw         $a1, %lo(D_800777EC)($a1)
/* B864B4 8007D6EC 0780033C */  lui        $v1, %hi(D_800777F0)
/* B864B8 8007D6F0 F077638C */  lw         $v1, %lo(D_800777F0)($v1)
/* B864BC 8007D6F4 00111024 */  addiu      $s0, $zero, 0x1100
/* B864C0 8007D6F8 9800B1AF */  sw         $s1, 0x98($sp)
/* B864C4 8007D6FC A000B0AF */  sw         $s0, 0xA0($sp)
/* B864C8 8007D700 80100300 */  sll        $v0, $v1, 2
/* B864CC 8007D704 21104300 */  addu       $v0, $v0, $v1
/* B864D0 8007D708 80100200 */  sll        $v0, $v0, 2
/* B864D4 8007D70C 23104300 */  subu       $v0, $v0, $v1
/* B864D8 8007D710 43004224 */  addiu      $v0, $v0, 0x43
/* B864DC 8007D714 4D61000C */  jal        func_80018534
/* B864E0 8007D718 9C00A2AF */   sw        $v0, 0x9C($sp)
/* B864E4 8007D71C 0780033C */  lui        $v1, %hi(D_800777F4)
/* B864E8 8007D720 F477638C */  lw         $v1, %lo(D_800777F4)($v1)
/* B864EC 8007D724 10000224 */  addiu      $v0, $zero, 0x10
/* B864F0 8007D728 A800A2AF */  sw         $v0, 0xA8($sp)
/* B864F4 8007D72C 00140224 */  addiu      $v0, $zero, 0x1400
/* B864F8 8007D730 B000A2AF */  sw         $v0, 0xB0($sp)
/* B864FC 8007D734 2C000224 */  addiu      $v0, $zero, 0x2C
/* B86500 8007D738 9C00A2AF */  sw         $v0, 0x9C($sp)
/* B86504 8007D73C 1F000224 */  addiu      $v0, $zero, 0x1F
/* B86508 8007D740 AC00B3AF */  sw         $s3, 0xAC($sp)
/* B8650C 8007D744 A000B0AF */  sw         $s0, 0xA0($sp)
/* B86510 8007D748 06006214 */  bne        $v1, $v0, .Llevel_11_8007D764
/* B86514 8007D74C 9800B1AF */   sw        $s1, 0x98($sp)
/* B86518 8007D750 0B000224 */  addiu      $v0, $zero, 0xB
/* B8651C 8007D754 0880043C */  lui        $a0, %hi(D_level_11_8007AAB0)
/* B86520 8007D758 B0AA8424 */  addiu      $a0, $a0, %lo(D_level_11_8007AAB0)
/* B86524 8007D75C DDF50108 */  j          .Llevel_11_8007D774
/* B86528 8007D760 1000A2AF */   sw        $v0, 0x10($sp)
.Llevel_11_8007D764:
/* B8652C 8007D764 0B000224 */  addiu      $v0, $zero, 0xB
/* B86530 8007D768 1000A2AF */  sw         $v0, 0x10($sp)
/* B86534 8007D76C 0880043C */  lui        $a0, %hi(D_level_11_8007AAC8)
/* B86538 8007D770 C8AA8424 */  addiu      $a0, $a0, %lo(D_level_11_8007AAC8)
.Llevel_11_8007D774:
/* B8653C 8007D774 21284002 */  addu       $a1, $s2, $zero
/* B86540 8007D778 A800A627 */  addiu      $a2, $sp, 0xA8
/* B86544 8007D77C 6B60000C */  jal        func_800181AC
/* B86548 8007D780 12000724 */   addiu     $a3, $zero, 0x12
/* B8654C 8007D784 0880043C */  lui        $a0, %hi(D_level_11_8007AAA4)
/* B86550 8007D788 A4AA8424 */  addiu      $a0, $a0, %lo(D_level_11_8007AAA4)
/* B86554 8007D78C 9800A527 */  addiu      $a1, $sp, 0x98
/* B86558 8007D790 A800A627 */  addiu      $a2, $sp, 0xA8
/* B8655C 8007D794 12000724 */  addiu      $a3, $zero, 0x12
/* B86560 8007D798 0780033C */  lui        $v1, %hi(D_80075710)
/* B86564 8007D79C 1057638C */  lw         $v1, %lo(D_80075710)($v1)
/* B86568 8007D7A0 80000224 */  addiu      $v0, $zero, 0x80
/* B8656C 8007D7A4 9800A2AF */  sw         $v0, 0x98($sp)
/* B86570 8007D7A8 9C00A28F */  lw         $v0, 0x9C($sp)
/* B86574 8007D7AC A8FF7024 */  addiu      $s0, $v1, -0x58
/* B86578 8007D7B0 19004224 */  addiu      $v0, $v0, 0x19
/* B8657C 8007D7B4 9C00A2AF */  sw         $v0, 0x9C($sp)
/* B86580 8007D7B8 0B000224 */  addiu      $v0, $zero, 0xB
/* B86584 8007D7BC 6B60000C */  jal        func_800181AC
/* B86588 8007D7C0 1000A2AF */   sw        $v0, 0x10($sp)
/* B8658C 8007D7C4 0780043C */  lui        $a0, %hi(D_800777F0)
/* B86590 8007D7C8 F0778424 */  addiu      $a0, $a0, %lo(D_800777F0)
/* B86594 8007D7CC 9C00A28F */  lw         $v0, 0x9C($sp)
/* B86598 8007D7D0 0000838C */  lw         $v1, 0x0($a0)
/* B8659C 8007D7D4 13004224 */  addiu      $v0, $v0, 0x13
/* B865A0 8007D7D8 1B006014 */  bnez       $v1, .Llevel_11_8007D848
/* B865A4 8007D7DC 9C00A2AF */   sw        $v0, 0x9C($sp)
/* B865A8 8007D7E0 0780023C */  lui        $v0, %hi(D_80075710)
/* B865AC 8007D7E4 1057428C */  lw         $v0, %lo(D_80075710)($v0)
/* B865B0 8007D7E8 00000000 */  nop
/* B865B4 8007D7EC 2B100202 */  sltu       $v0, $s0, $v0
/* B865B8 8007D7F0 15004014 */  bnez       $v0, .Llevel_11_8007D848
/* B865BC 8007D7F4 FCFF8324 */   addiu     $v1, $a0, -0x4
/* B865C0 8007D7F8 0780053C */  lui        $a1, %hi(D_8006CC78)
/* B865C4 8007D7FC 78CCA524 */  addiu      $a1, $a1, %lo(D_8006CC78)
/* B865C8 8007D800 21200000 */  addu       $a0, $zero, $zero
.Llevel_11_8007D804:
/* B865CC 8007D804 0000628C */  lw         $v0, 0x0($v1)
/* B865D0 8007D808 00000000 */  nop
/* B865D4 8007D80C 80100200 */  sll        $v0, $v0, 2
/* B865D8 8007D810 21104400 */  addu       $v0, $v0, $a0
/* B865DC 8007D814 FF004230 */  andi       $v0, $v0, 0xFF
/* B865E0 8007D818 40100200 */  sll        $v0, $v0, 1
/* B865E4 8007D81C 21104500 */  addu       $v0, $v0, $a1
/* B865E8 8007D820 00004294 */  lhu        $v0, 0x0($v0)
/* B865EC 8007D824 00000000 */  nop
/* B865F0 8007D828 02120200 */  srl        $v0, $v0, 8
/* B865F4 8007D82C 460002A2 */  sb         $v0, 0x46($s0)
/* B865F8 8007D830 0780023C */  lui        $v0, %hi(D_80075710)
/* B865FC 8007D834 1057428C */  lw         $v0, %lo(D_80075710)($v0)
/* B86600 8007D838 A8FF1026 */  addiu      $s0, $s0, -0x58
/* B86604 8007D83C 2B100202 */  sltu       $v0, $s0, $v0
/* B86608 8007D840 F0FF4010 */  beqz       $v0, .Llevel_11_8007D804
/* B8660C 8007D844 0C008424 */   addiu     $a0, $a0, 0xC
.Llevel_11_8007D848:
/* B86610 8007D848 0780033C */  lui        $v1, %hi(D_80075710)
/* B86614 8007D84C 1057638C */  lw         $v1, %lo(D_80075710)($v1)
/* B86618 8007D850 80000224 */  addiu      $v0, $zero, 0x80
/* B8661C 8007D854 9800A2AF */  sw         $v0, 0x98($sp)
/* B86620 8007D858 A8FF7024 */  addiu      $s0, $v1, -0x58
/* B86624 8007D85C 0780033C */  lui        $v1, %hi(D_800777F4)
/* B86628 8007D860 F477638C */  lw         $v1, %lo(D_800777F4)($v1)
/* B8662C 8007D864 1F000224 */  addiu      $v0, $zero, 0x1F
/* B86630 8007D868 0F006214 */  bne        $v1, $v0, .Llevel_11_8007D8A8
/* B86634 8007D86C 6666023C */   lui       $v0, (0x66666667 >> 16)
/* B86638 8007D870 0780033C */  lui        $v1, %hi(g_LevelId)
/* B8663C 8007D874 6C59638C */  lw         $v1, %lo(g_LevelId)($v1)
/* B86640 8007D878 67664234 */  ori        $v0, $v0, (0x66666667 & 0xFFFF)
/* B86644 8007D87C 18006200 */  mult       $v1, $v0
/* B86648 8007D880 C31F0300 */  sra        $v1, $v1, 31
/* B8664C 8007D884 10400000 */  mfhi       $t0
/* B86650 8007D888 83100800 */  sra        $v0, $t0, 2
/* B86654 8007D88C 23104300 */  subu       $v0, $v0, $v1
/* B86658 8007D890 80100200 */  sll        $v0, $v0, 2
/* B8665C 8007D894 0780013C */  lui        $at, %hi(homeworldNameTable)
/* B86660 8007D898 21082200 */  addu       $at, $at, $v0
/* B86664 8007D89C D4F7268C */  lw         $a2, %lo(homeworldNameTable)($at)
/* B86668 8007D8A0 3FF60108 */  j          .Llevel_11_8007D8FC
/* B8666C 8007D8A4 B800A427 */   addiu     $a0, $sp, 0xB8
.Llevel_11_8007D8A8:
/* B86670 8007D8A8 0780053C */  lui        $a1, %hi(D_800758B4)
/* B86674 8007D8AC B458A58C */  lw         $a1, %lo(D_800758B4)($a1)
/* B86678 8007D8B0 67664234 */  ori        $v0, $v0, (0x66666667 & 0xFFFF)
/* B8667C 8007D8B4 1800A200 */  mult       $a1, $v0
/* B86680 8007D8B8 B800A427 */  addiu      $a0, $sp, 0xB8
/* B86684 8007D8BC C3170500 */  sra        $v0, $a1, 31
/* B86688 8007D8C0 10400000 */  mfhi       $t0
/* B8668C 8007D8C4 83180800 */  sra        $v1, $t0, 2
/* B86690 8007D8C8 23186200 */  subu       $v1, $v1, $v0
/* B86694 8007D8CC 80100300 */  sll        $v0, $v1, 2
/* B86698 8007D8D0 21104300 */  addu       $v0, $v0, $v1
/* B8669C 8007D8D4 40100200 */  sll        $v0, $v0, 1
/* B866A0 8007D8D8 2328A200 */  subu       $a1, $a1, $v0
/* B866A4 8007D8DC 40100300 */  sll        $v0, $v1, 1
/* B866A8 8007D8E0 21104300 */  addu       $v0, $v0, $v1
/* B866AC 8007D8E4 40100200 */  sll        $v0, $v0, 1
/* B866B0 8007D8E8 21104500 */  addu       $v0, $v0, $a1
/* B866B4 8007D8EC 80100200 */  sll        $v0, $v0, 2
/* B866B8 8007D8F0 0780013C */  lui        $at, %hi(D_8006F7D8)
/* B866BC 8007D8F4 21082200 */  addu       $at, $at, $v0
/* B866C0 8007D8F8 D8F7268C */  lw         $a2, %lo(D_8006F7D8)($at)
.Llevel_11_8007D8FC:
/* B866C4 8007D8FC 0880053C */  lui        $a1, %hi(D_level_11_8007AAE0)
/* B866C8 8007D900 E0AAA524 */  addiu      $a1, $a1, %lo(D_level_11_8007AAE0)
/* B866CC 8007D904 F58B010C */  jal        sprintf
/* B866D0 8007D908 00000000 */   nop
/* B866D4 8007D90C B800A427 */  addiu      $a0, $sp, 0xB8
/* B866D8 8007D910 9800A527 */  addiu      $a1, $sp, 0x98
/* B866DC 8007D914 A800A627 */  addiu      $a2, $sp, 0xA8
/* B866E0 8007D918 12000724 */  addiu      $a3, $zero, 0x12
/* B866E4 8007D91C 0B000224 */  addiu      $v0, $zero, 0xB
/* B866E8 8007D920 6B60000C */  jal        func_800181AC
/* B866EC 8007D924 1000A2AF */   sw        $v0, 0x10($sp)
/* B866F0 8007D928 0780043C */  lui        $a0, %hi(D_800777F0)
/* B866F4 8007D92C F0778424 */  addiu      $a0, $a0, %lo(D_800777F0)
/* B866F8 8007D930 0000838C */  lw         $v1, 0x0($a0)
/* B866FC 8007D934 01000224 */  addiu      $v0, $zero, 0x1
/* B86700 8007D938 1B006214 */  bne        $v1, $v0, .Llevel_11_8007D9A8
/* B86704 8007D93C 00000000 */   nop
/* B86708 8007D940 0780023C */  lui        $v0, %hi(D_80075710)
/* B8670C 8007D944 1057428C */  lw         $v0, %lo(D_80075710)($v0)
/* B86710 8007D948 00000000 */  nop
/* B86714 8007D94C 2B100202 */  sltu       $v0, $s0, $v0
/* B86718 8007D950 15004014 */  bnez       $v0, .Llevel_11_8007D9A8
/* B8671C 8007D954 FCFF8324 */   addiu     $v1, $a0, -0x4
/* B86720 8007D958 0780053C */  lui        $a1, %hi(D_8006CC78)
/* B86724 8007D95C 78CCA524 */  addiu      $a1, $a1, %lo(D_8006CC78)
/* B86728 8007D960 21200000 */  addu       $a0, $zero, $zero
.Llevel_11_8007D964:
/* B8672C 8007D964 0000628C */  lw         $v0, 0x0($v1)
/* B86730 8007D968 00000000 */  nop
/* B86734 8007D96C 80100200 */  sll        $v0, $v0, 2
/* B86738 8007D970 21104400 */  addu       $v0, $v0, $a0
/* B8673C 8007D974 FF004230 */  andi       $v0, $v0, 0xFF
/* B86740 8007D978 40100200 */  sll        $v0, $v0, 1
/* B86744 8007D97C 21104500 */  addu       $v0, $v0, $a1
/* B86748 8007D980 00004294 */  lhu        $v0, 0x0($v0)
/* B8674C 8007D984 00000000 */  nop
/* B86750 8007D988 02120200 */  srl        $v0, $v0, 8
/* B86754 8007D98C 460002A2 */  sb         $v0, 0x46($s0)
/* B86758 8007D990 0780023C */  lui        $v0, %hi(D_80075710)
/* B8675C 8007D994 1057428C */  lw         $v0, %lo(D_80075710)($v0)
/* B86760 8007D998 A8FF1026 */  addiu      $s0, $s0, -0x58
/* B86764 8007D99C 2B100202 */  sltu       $v0, $s0, $v0
/* B86768 8007D9A0 F0FF4010 */  beqz       $v0, .Llevel_11_8007D964
/* B8676C 8007D9A4 0C008424 */   addiu     $a0, $a0, 0xC
.Llevel_11_8007D9A8:
/* B86770 8007D9A8 7048010C */  jal        func_800521C0
/* B86774 8007D9AC 00000000 */   nop
/* B86778 8007D9B0 A665000C */  jal        func_80019698
/* B8677C 8007D9B4 00000000 */   nop
/* B86780 8007D9B8 0780023C */  lui        $v0, %hi(D_800777E8)
/* B86784 8007D9BC E877428C */  lw         $v0, %lo(D_800777E8)($v0)
/* B86788 8007D9C0 00000000 */  nop
/* B8678C 8007D9C4 02004228 */  slti       $v0, $v0, 0x2
/* B86790 8007D9C8 1C004010 */  beqz       $v0, .Llevel_11_8007DA3C
/* B86794 8007D9CC 00000000 */   nop
/* B86798 8007D9D0 0780013C */  lui        $at, %hi(D_8006FCF4 + 0x2400)
/* B8679C 8007D9D4 F42020AC */  sw         $zero, %lo(D_8006FCF4 + 0x2400)($at)
/* B867A0 8007D9D8 2062000C */  jal        func_80018880
/* B867A4 8007D9DC 00000000 */   nop
/* B867A8 8007D9E0 8B8A000C */  jal        func_80022A2C
/* B867AC 8007D9E4 00000000 */   nop
/* B867B0 8007D9E8 8FF60108 */  j          .Llevel_11_8007DA3C
/* B867B4 8007D9EC 00000000 */   nop
.Llevel_11_8007D9F0:
/* B867B8 8007D9F0 7048010C */  jal        func_800521C0
/* B867BC 8007D9F4 00000000 */   nop
/* B867C0 8007D9F8 0780033C */  lui        $v1, %hi(D_8006FCF4)
/* B867C4 8007D9FC F4FC6324 */  addiu      $v1, $v1, %lo(D_8006FCF4)
/* B867C8 8007DA00 0000628C */  lw         $v0, 0x0($v1)
/* B867CC 8007DA04 00000000 */  nop
/* B867D0 8007DA08 07004010 */  beqz       $v0, .Llevel_11_8007DA28
/* B867D4 8007DA0C 00000000 */   nop
/* B867D8 8007DA10 04006324 */  addiu      $v1, $v1, 0x4
.Llevel_11_8007DA14:
/* B867DC 8007DA14 0000628C */  lw         $v0, 0x0($v1)
/* B867E0 8007DA18 00000000 */  nop
/* B867E4 8007DA1C FDFF4014 */  bnez       $v0, .Llevel_11_8007DA14
/* B867E8 8007DA20 04006324 */   addiu     $v1, $v1, 0x4
/* B867EC 8007DA24 FCFF6324 */  addiu      $v1, $v1, -0x4
.Llevel_11_8007DA28:
/* B867F0 8007DA28 0780023C */  lui        $v0, %hi(D_80077850)
/* B867F4 8007DA2C 5078428C */  lw         $v0, %lo(D_80077850)($v0)
/* B867F8 8007DA30 040060AC */  sw         $zero, 0x4($v1)
/* B867FC 8007DA34 A665000C */  jal        func_80019698
/* B86800 8007DA38 000062AC */   sw        $v0, 0x0($v1)
.Llevel_11_8007DA3C:
/* B86804 8007DA3C 73AE000C */  jal        func_8002B9CC
/* B86808 8007DA40 00000000 */   nop
/* B8680C 8007DA44 F442010C */  jal        func_80050BD0
/* B86810 8007DA48 00000000 */   nop
/* B86814 8007DA4C F25C010C */  jal        func_800573C8
/* B86818 8007DA50 00000000 */   nop
/* B8681C 8007DA54 F400BF8F */  lw         $ra, 0xF4($sp)
/* B86820 8007DA58 F000B48F */  lw         $s4, 0xF0($sp)
/* B86824 8007DA5C EC00B38F */  lw         $s3, 0xEC($sp)
/* B86828 8007DA60 E800B28F */  lw         $s2, 0xE8($sp)
/* B8682C 8007DA64 E400B18F */  lw         $s1, 0xE4($sp)
/* B86830 8007DA68 E000B08F */  lw         $s0, 0xE0($sp)
/* B86834 8007DA6C F800BD27 */  addiu      $sp, $sp, 0xF8
/* B86838 8007DA70 0800E003 */  jr         $ra
/* B8683C 8007DA74 00000000 */   nop
.size func_level_11_8007D070, . - func_level_11_8007D070
