.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata.jtbl
.align 3
dlabel jtbl_80010E88
/* 1688 80010E88 D4EA0380 */ .word .L8003EAD4
/* 168C 80010E8C 1CEB0380 */ .word .L8003EB1C
/* 1690 80010E90 1CEB0380 */ .word .L8003EB1C
/* 1694 80010E94 1CEB0380 */ .word .L8003EB1C
/* 1698 80010E98 BCEA0380 */ .word .L8003EABC
/* 169C 80010E9C 1CEB0380 */ .word .L8003EB1C
/* 16A0 80010EA0 1CEB0380 */ .word .L8003EB1C
/* 16A4 80010EA4 DCEA0380 */ .word .L8003EADC
/* 16A8 80010EA8 BCEA0380 */ .word .L8003EABC
/* 16AC 80010EAC 1CEB0380 */ .word .L8003EB1C
/* 16B0 80010EB0 1CEB0380 */ .word .L8003EB1C
/* 16B4 80010EB4 1CEB0380 */ .word .L8003EB1C
/* 16B8 80010EB8 1CEB0380 */ .word .L8003EB1C
/* 16BC 80010EBC 1CEB0380 */ .word .L8003EB1C
/* 16C0 80010EC0 1CEB0380 */ .word .L8003EB1C
/* 16C4 80010EC4 DCEA0380 */ .word .L8003EADC
/* 16C8 80010EC8 1CEB0380 */ .word .L8003EB1C
/* 16CC 80010ECC 1CEB0380 */ .word .L8003EB1C
/* 16D0 80010ED0 FCEA0380 */ .word .L8003EAFC
/* 16D4 80010ED4 1CEB0380 */ .word .L8003EB1C
/* 16D8 80010ED8 DCEA0380 */ .word .L8003EADC
/* 16DC 80010EDC DCEA0380 */ .word .L8003EADC
/* 16E0 80010EE0 1CEB0380 */ .word .L8003EB1C
/* 16E4 80010EE4 1CEB0380 */ .word .L8003EB1C
/* 16E8 80010EE8 1CEB0380 */ .word .L8003EB1C
/* 16EC 80010EEC BCEA0380 */ .word .L8003EABC
/* 16F0 80010EF0 1CEB0380 */ .word .L8003EB1C
/* 16F4 80010EF4 1CEB0380 */ .word .L8003EB1C
/* 16F8 80010EF8 1CEB0380 */ .word .L8003EB1C
/* 16FC 80010EFC 1CEB0380 */ .word .L8003EB1C
/* 1700 80010F00 1CEB0380 */ .word .L8003EB1C
/* 1704 80010F04 1CEB0380 */ .word .L8003EB1C
/* 1708 80010F08 1CEB0380 */ .word .L8003EB1C
/* 170C 80010F0C 1CEB0380 */ .word .L8003EB1C
/* 1710 80010F10 1CEB0380 */ .word .L8003EB1C
/* 1714 80010F14 1CEB0380 */ .word .L8003EB1C
/* 1718 80010F18 1CEB0380 */ .word .L8003EB1C
/* 171C 80010F1C BCEA0380 */ .word .L8003EABC
.size jtbl_80010E88, . - jtbl_80010E88
.section .rodata.jtbl
.align 3
dlabel jtbl_80010F20
/* 1720 80010F20 40EB0380 */ .word .L8003EB40
/* 1724 80010F24 A0EB0380 */ .word .L8003EBA0
/* 1728 80010F28 A0EB0380 */ .word .L8003EBA0
/* 172C 80010F2C A0EB0380 */ .word .L8003EBA0
/* 1730 80010F30 F4ED0380 */ .word .L8003EDF4
/* 1734 80010F34 10EE0380 */ .word .L8003EE10
/* 1738 80010F38 9CEE0380 */ .word .L8003EE9C
/* 173C 80010F3C 08F30380 */ .word .L8003F308
/* 1740 80010F40 6CFC0380 */ .word .L8003FC6C
/* 1744 80010F44 50EF0380 */ .word .L8003EF50
/* 1748 80010F48 50EF0380 */ .word .L8003EF50
/* 174C 80010F4C 84EF0380 */ .word .L8003EF84
/* 1750 80010F50 D4F10380 */ .word .L8003F1D4
/* 1754 80010F54 00F30380 */ .word .L8003F300
/* 1758 80010F58 C8F30380 */ .word .L8003F3C8
/* 175C 80010F5C 70F50380 */ .word .L8003F570
/* 1760 80010F60 F0EE0380 */ .word .L8003EEF0
/* 1764 80010F64 BCF60380 */ .word .L8003F6BC
/* 1768 80010F68 84F70380 */ .word .L8003F784
/* 176C 80010F6C BCF70380 */ .word .L8003F7BC
/* 1770 80010F70 10F80380 */ .word .L8003F810
/* 1774 80010F74 A0EB0380 */ .word .L8003EBA0
/* 1778 80010F78 E0F90380 */ .word .L8003F9E0
/* 177C 80010F7C 70F50380 */ .word .L8003F570
/* 1780 80010F80 ECF80380 */ .word .L8003F8EC
/* 1784 80010F84 9CF40380 */ .word .L8003F49C
/* 1788 80010F88 3CF90380 */ .word .L8003F93C
/* 178C 80010F8C 20F50380 */ .word .L8003F520
/* 1790 80010F90 E0F90380 */ .word .L8003F9E0
/* 1794 80010F94 B4FA0380 */ .word .L8003FAB4
/* 1798 80010F98 A4FB0380 */ .word .L8003FBA4
/* 179C 80010F9C F4FB0380 */ .word .L8003FBF4
/* 17A0 80010FA0 70F50380 */ .word .L8003F570
/* 17A4 80010FA4 70F50380 */ .word .L8003F570
/* 17A8 80010FA8 70F50380 */ .word .L8003F570
/* 17AC 80010FAC 60FC0380 */ .word .L8003FC60
/* 17B0 80010FB0 84F70380 */ .word .L8003F784
/* 17B4 80010FB4 84F70380 */ .word .L8003F784
/* 17B8 80010FB8 84F70380 */ .word .L8003F784
/* 17BC 80010FBC 84F70380 */ .word .L8003F784
/* 17C0 80010FC0 84F70380 */ .word .L8003F784
/* 17C4 80010FC4 84F70380 */ .word .L8003F784
/* 17C8 80010FC8 84F70380 */ .word .L8003F784
/* 17CC 80010FCC 84F70380 */ .word .L8003F784
/* 17D0 80010FD0 88FC0380 */ .word .L8003FC88
/* 17D4 80010FD4 00000000 */ .word 0x00000000
.size jtbl_80010F20, . - jtbl_80010F20


.section .text
/* Generated by spimdisasm 1.27.0 */

glabel func_8003EA68
/* 2F268 8003EA68 0880023C */  lui        $v0, %hi(g_Spyro + 0x78)
/* 2F26C 8003EA6C D08A428C */  lw         $v0, %lo(g_Spyro + 0x78)($v0)
/* 2F270 8003EA70 B0FFBD27 */  addiu      $sp, $sp, -0x50
/* 2F274 8003EA74 4400B5AF */  sw         $s5, 0x44($sp)
/* 2F278 8003EA78 21A88000 */  addu       $s5, $a0, $zero
/* 2F27C 8003EA7C 4800BFAF */  sw         $ra, 0x48($sp)
/* 2F280 8003EA80 4000B4AF */  sw         $s4, 0x40($sp)
/* 2F284 8003EA84 3C00B3AF */  sw         $s3, 0x3C($sp)
/* 2F288 8003EA88 3800B2AF */  sw         $s2, 0x38($sp)
/* 2F28C 8003EA8C 3400B1AF */  sw         $s1, 0x34($sp)
/* 2F290 8003EA90 F9FF4324 */  addiu      $v1, $v0, -0x7
/* 2F294 8003EA94 2600622C */  sltiu      $v0, $v1, 0x26
/* 2F298 8003EA98 20004010 */  beqz       $v0, .L8003EB1C
/* 2F29C 8003EA9C 3000B0AF */   sw        $s0, 0x30($sp)
/* 2F2A0 8003EAA0 80100300 */  sll        $v0, $v1, 2
/* 2F2A4 8003EAA4 0180013C */  lui        $at, %hi(jtbl_80010E88)
/* 2F2A8 8003EAA8 21082200 */  addu       $at, $at, $v0
/* 2F2AC 8003EAAC 880E228C */  lw         $v0, %lo(jtbl_80010E88)($at)
/* 2F2B0 8003EAB0 00000000 */  nop
/* 2F2B4 8003EAB4 08004000 */  jr         $v0
/* 2F2B8 8003EAB8 00000000 */   nop
.L8003EABC:
/* 2F2BC 8003EABC 0880043C */  lui        $a0, %hi(g_Spyro)
/* 2F2C0 8003EAC0 588A8424 */  addiu      $a0, $a0, %lo(g_Spyro)
/* 2F2C4 8003EAC4 A958010C */  jal        func_800562A4
/* 2F2C8 8003EAC8 02000524 */   addiu     $a1, $zero, 0x2
/* 2F2CC 8003EACC C8FA0008 */  j          .L8003EB20
/* 2F2D0 8003EAD0 2D00A22E */   sltiu     $v0, $s5, 0x2D
.L8003EAD4:
/* 2F2D4 8003EAD4 0880013C */  lui        $at, %hi(g_Spyro + 0x2B)
/* 2F2D8 8003EAD8 838A20A0 */  sb         $zero, %lo(g_Spyro + 0x2B)($at)
.L8003EADC:
/* 2F2DC 8003EADC 0880053C */  lui        $a1, %hi(g_Spyro)
/* 2F2E0 8003EAE0 588AA524 */  addiu      $a1, $a1, %lo(g_Spyro)
/* 2F2E4 8003EAE4 0780023C */  lui        $v0, %hi(g_Spu + 0x2CC)
/* 2F2E8 8003EAE8 D461428C */  lw         $v0, %lo(g_Spu + 0x2CC)($v0)
/* 2F2EC 8003EAEC 00000000 */  nop
/* 2F2F0 8003EAF0 1B004490 */  lbu        $a0, 0x1B($v0)
/* 2F2F4 8003EAF4 C5FA0008 */  j          .L8003EB14
/* 2F2F8 8003EAF8 04000624 */   addiu     $a2, $zero, 0x4
.L8003EAFC:
/* 2F2FC 8003EAFC 0880053C */  lui        $a1, %hi(g_Spyro)
/* 2F300 8003EB00 588AA524 */  addiu      $a1, $a1, %lo(g_Spyro)
/* 2F304 8003EB04 0780023C */  lui        $v0, %hi(g_Spu + 0x2CC)
/* 2F308 8003EB08 D461428C */  lw         $v0, %lo(g_Spu + 0x2CC)($v0)
/* 2F30C 8003EB0C 04000624 */  addiu      $a2, $zero, 0x4
/* 2F310 8003EB10 20004490 */  lbu        $a0, 0x20($v0)
.L8003EB14:
/* 2F314 8003EB14 9E56010C */  jal        PlaySound
/* 2F318 8003EB18 A002A724 */   addiu     $a3, $a1, 0x2A0
.L8003EB1C:
/* 2F31C 8003EB1C 2D00A22E */  sltiu      $v0, $s5, 0x2D
.L8003EB20:
/* 2F320 8003EB20 8B044010 */  beqz       $v0, .L8003FD50
/* 2F324 8003EB24 80101500 */   sll       $v0, $s5, 2
/* 2F328 8003EB28 0180013C */  lui        $at, %hi(jtbl_80010F20)
/* 2F32C 8003EB2C 21082200 */  addu       $at, $at, $v0
/* 2F330 8003EB30 200F228C */  lw         $v0, %lo(jtbl_80010F20)($at)
/* 2F334 8003EB34 00000000 */  nop
/* 2F338 8003EB38 08004000 */  jr         $v0
/* 2F33C 8003EB3C 00000000 */   nop
.L8003EB40:
/* 2F340 8003EB40 0880013C */  lui        $at, %hi(g_Spyro + 0x7C)
/* 2F344 8003EB44 D48A20AC */  sw         $zero, %lo(g_Spyro + 0x7C)($at)
/* 2F348 8003EB48 CB89010C */  jal        rand
/* 2F34C 8003EB4C 00000000 */   nop
/* 2F350 8003EB50 07004230 */  andi       $v0, $v0, 0x7
/* 2F354 8003EB54 0780013C */  lui        $at, %hi(D_80075274)
/* 2F358 8003EB58 21082200 */  addu       $at, $at, $v0
/* 2F35C 8003EB5C 74522390 */  lbu        $v1, %lo(D_80075274)($at)
/* 2F360 8003EB60 0780023C */  lui        $v0, %hi(spyro_AnimationDetails + 0x02)
/* 2F364 8003EB64 A2C44290 */  lbu        $v0, %lo(spyro_AnimationDetails + 0x02)($v0)
/* 2F368 8003EB68 00000000 */  nop
/* 2F36C 8003EB6C 18006200 */  mult       $v1, $v0
/* 2F370 8003EB70 80FF0224 */  addiu      $v0, $zero, -0x80
/* 2F374 8003EB74 0880013C */  lui        $at, %hi(g_Spyro + 0x14C)
/* 2F378 8003EB78 A48B22AC */  sw         $v0, %lo(g_Spyro + 0x14C)($at)
/* 2F37C 8003EB7C 01000224 */  addiu      $v0, $zero, 0x1
/* 2F380 8003EB80 0880013C */  lui        $at, %hi(g_Spyro + 0x15C)
/* 2F384 8003EB84 B48B22AC */  sw         $v0, %lo(g_Spyro + 0x15C)($at)
/* 2F388 8003EB88 12400000 */  mflo       $t0
/* 2F38C 8003EB8C FEFF0225 */  addiu      $v0, $t0, -0x2
/* 2F390 8003EB90 0780013C */  lui        $at, %hi(D_80075788)
/* 2F394 8003EB94 885722A4 */  sh         $v0, %lo(D_80075788)($at)
/* 2F398 8003EB98 54FF0008 */  j          .L8003FD50
/* 2F39C 8003EB9C 00000000 */   nop
.L8003EBA0:
/* 2F3A0 8003EBA0 0880023C */  lui        $v0, %hi(g_Spyro + 0x7C)
/* 2F3A4 8003EBA4 D48A4224 */  addiu      $v0, $v0, %lo(g_Spyro + 0x7C)
/* 2F3A8 8003EBA8 01000624 */  addiu      $a2, $zero, 0x1
/* 2F3AC 8003EBAC 9000448C */  lw         $a0, 0x90($v0)
/* 2F3B0 8003EBB0 0880053C */  lui        $a1, %hi(g_Spyro + 0x110)
/* 2F3B4 8003EBB4 688BA58C */  lw         $a1, %lo(g_Spyro + 0x110)($a1)
/* 2F3B8 8003EBB8 90005024 */  addiu      $s0, $v0, 0x90
/* 2F3BC 8003EBBC AD5A000C */  jal        Atan2
/* 2F3C0 8003EBC0 000040AC */   sw        $zero, 0x0($v0)
/* 2F3C4 8003EBC4 0880033C */  lui        $v1, %hi(g_Spyro + 0x11C)
/* 2F3C8 8003EBC8 748B638C */  lw         $v1, %lo(g_Spyro + 0x11C)($v1)
/* 2F3CC 8003EBCC 00000000 */  nop
/* 2F3D0 8003EBD0 23104300 */  subu       $v0, $v0, $v1
/* 2F3D4 8003EBD4 FF0F5130 */  andi       $s1, $v0, 0xFFF
/* 2F3D8 8003EBD8 FFFB2226 */  addiu      $v0, $s1, -0x401
/* 2F3DC 8003EBDC FF07422C */  sltiu      $v0, $v0, 0x7FF
/* 2F3E0 8003EBE0 05004010 */  beqz       $v0, .L8003EBF8
/* 2F3E4 8003EBE4 21200002 */   addu      $a0, $s0, $zero
/* 2F3E8 8003EBE8 0880013C */  lui        $at, %hi(g_Spyro + 0x118)
/* 2F3EC 8003EBEC 708B20AC */  sw         $zero, %lo(g_Spyro + 0x118)($at)
/* 2F3F0 8003EBF0 03FB0008 */  j          .L8003EC0C
/* 2F3F4 8003EBF4 03000224 */   addiu     $v0, $zero, 0x3
.L8003EBF8:
/* 2F3F8 8003EBF8 7F5C000C */  jal        VecMagnitude
/* 2F3FC 8003EBFC 21280000 */   addu      $a1, $zero, $zero
/* 2F400 8003EC00 0880013C */  lui        $at, %hi(g_Spyro + 0x118)
/* 2F404 8003EC04 708B22AC */  sw         $v0, %lo(g_Spyro + 0x118)($at)
/* 2F408 8003EC08 03000224 */  addiu      $v0, $zero, 0x3
.L8003EC0C:
/* 2F40C 8003EC0C 0B00A216 */  bne        $s5, $v0, .L8003EC3C
/* 2F410 8003EC10 00F40224 */   addiu     $v0, $zero, -0xC00
/* 2F414 8003EC14 0880033C */  lui        $v1, %hi(g_Spyro + 0x118)
/* 2F418 8003EC18 708B6324 */  addiu      $v1, $v1, %lo(g_Spyro + 0x118)
/* 2F41C 8003EC1C 0000628C */  lw         $v0, 0x0($v1)
/* 2F420 8003EC20 00000000 */  nop
/* 2F424 8003EC24 01144228 */  slti       $v0, $v0, 0x1401
/* 2F428 8003EC28 04004014 */  bnez       $v0, .L8003EC3C
/* 2F42C 8003EC2C 00F40224 */   addiu     $v0, $zero, -0xC00
/* 2F430 8003EC30 00140224 */  addiu      $v0, $zero, 0x1400
/* 2F434 8003EC34 000062AC */  sw         $v0, 0x0($v1)
/* 2F438 8003EC38 00F40224 */  addiu      $v0, $zero, -0xC00
.L8003EC3C:
/* 2F43C 8003EC3C 0880013C */  lui        $at, %hi(g_Spyro + 0x14C)
/* 2F440 8003EC40 A48B22AC */  sw         $v0, %lo(g_Spyro + 0x14C)($at)
/* 2F444 8003EC44 6BF8000C */  jal        func_8003E1AC
/* 2F448 8003EC48 00000000 */   nop
/* 2F44C 8003EC4C 0880023C */  lui        $v0, %hi(g_Spyro + 0xB0)
/* 2F450 8003EC50 088B428C */  lw         $v0, %lo(g_Spyro + 0xB0)($v0)
/* 2F454 8003EC54 00000000 */  nop
/* 2F458 8003EC58 52004010 */  beqz       $v0, .L8003EDA4
/* 2F45C 8003EC5C 00000000 */   nop
/* 2F460 8003EC60 0880043C */  lui        $a0, %hi(g_Spyro + 0xA4)
/* 2F464 8003EC64 FC8A848C */  lw         $a0, %lo(g_Spyro + 0xA4)($a0)
/* 2F468 8003EC68 0880053C */  lui        $a1, %hi(g_Spyro + 0xA8)
/* 2F46C 8003EC6C 008BA58C */  lw         $a1, %lo(g_Spyro + 0xA8)($a1)
/* 2F470 8003EC70 AD5A000C */  jal        Atan2
/* 2F474 8003EC74 01000624 */   addiu     $a2, $zero, 0x1
/* 2F478 8003EC78 0880033C */  lui        $v1, %hi(g_Spyro + 0x11C)
/* 2F47C 8003EC7C 748B638C */  lw         $v1, %lo(g_Spyro + 0x11C)($v1)
/* 2F480 8003EC80 00000000 */  nop
/* 2F484 8003EC84 23186200 */  subu       $v1, $v1, $v0
/* 2F488 8003EC88 FF0F7130 */  andi       $s1, $v1, 0xFFF
/* 2F48C 8003EC8C 0108222A */  slti       $v0, $s1, 0x801
/* 2F490 8003EC90 02004014 */  bnez       $v0, .L8003EC9C
/* 2F494 8003EC94 8B2E033C */   lui       $v1, (0x2E8BA2E9 >> 16)
/* 2F498 8003EC98 00F03126 */  addiu      $s1, $s1, -0x1000
.L8003EC9C:
/* 2F49C 8003EC9C 0880023C */  lui        $v0, %hi(g_Spyro + 0xB0)
/* 2F4A0 8003ECA0 088B428C */  lw         $v0, %lo(g_Spyro + 0xB0)($v0)
/* 2F4A4 8003ECA4 E9A26334 */  ori        $v1, $v1, (0x2E8BA2E9 & 0xFFFF)
/* 2F4A8 8003ECA8 00130200 */  sll        $v0, $v0, 12
/* 2F4AC 8003ECAC 18004300 */  mult       $v0, $v1
/* 2F4B0 8003ECB0 02002106 */  bgez       $s1, .L8003ECBC
/* 2F4B4 8003ECB4 00000000 */   nop
/* 2F4B8 8003ECB8 23881100 */  negu       $s1, $s1
.L8003ECBC:
/* 2F4BC 8003ECBC C3170200 */  sra        $v0, $v0, 31
/* 2F4C0 8003ECC0 10400000 */  mfhi       $t0
/* 2F4C4 8003ECC4 83180800 */  sra        $v1, $t0, 2
/* 2F4C8 8003ECC8 23206200 */  subu       $a0, $v1, $v0
/* 2F4CC 8003ECCC 0104222A */  slti       $v0, $s1, 0x401
/* 2F4D0 8003ECD0 0B004014 */  bnez       $v0, .L8003ED00
/* 2F4D4 8003ECD4 00000000 */   nop
/* 2F4D8 8003ECD8 0780023C */  lui        $v0, %hi(D_8006C5CC)
/* 2F4DC 8003ECDC CCC5428C */  lw         $v0, %lo(D_8006C5CC)($v0)
/* 2F4E0 8003ECE0 0780033C */  lui        $v1, %hi(D_8006C5C0)
/* 2F4E4 8003ECE4 C0C5638C */  lw         $v1, %lo(D_8006C5C0)($v1)
/* 2F4E8 8003ECE8 00000000 */  nop
/* 2F4EC 8003ECEC 23104300 */  subu       $v0, $v0, $v1
/* 2F4F0 8003ECF0 18008200 */  mult       $a0, $v0
/* 2F4F4 8003ECF4 00080224 */  addiu      $v0, $zero, 0x800
/* 2F4F8 8003ECF8 47FB0008 */  j          .L8003ED1C
/* 2F4FC 8003ECFC 23885100 */   subu      $s1, $v0, $s1
.L8003ED00:
/* 2F500 8003ED00 0780023C */  lui        $v0, %hi(D_8006C5C4)
/* 2F504 8003ED04 C4C5428C */  lw         $v0, %lo(D_8006C5C4)($v0)
/* 2F508 8003ED08 0780033C */  lui        $v1, %hi(D_8006C5B8)
/* 2F50C 8003ED0C B8C5638C */  lw         $v1, %lo(D_8006C5B8)($v1)
/* 2F510 8003ED10 00000000 */  nop
/* 2F514 8003ED14 23104300 */  subu       $v0, $v0, $v1
/* 2F518 8003ED18 18008200 */  mult       $a0, $v0
.L8003ED1C:
/* 2F51C 8003ED1C 12400000 */  mflo       $t0
/* 2F520 8003ED20 03130800 */  sra        $v0, $t0, 12
/* 2F524 8003ED24 21906200 */  addu       $s2, $v1, $v0
/* 2F528 8003ED28 0780023C */  lui        $v0, %hi(D_8006C5C8)
/* 2F52C 8003ED2C C8C5428C */  lw         $v0, %lo(D_8006C5C8)($v0)
/* 2F530 8003ED30 0780033C */  lui        $v1, %hi(D_8006C5BC)
/* 2F534 8003ED34 BCC5638C */  lw         $v1, %lo(D_8006C5BC)($v1)
/* 2F538 8003ED38 00000000 */  nop
/* 2F53C 8003ED3C 23104300 */  subu       $v0, $v0, $v1
/* 2F540 8003ED40 18008200 */  mult       $a0, $v0
/* 2F544 8003ED44 21202002 */  addu       $a0, $s1, $zero
/* 2F548 8003ED48 12480000 */  mflo       $t1
/* 2F54C 8003ED4C 03130900 */  sra        $v0, $t1, 12
/* 2F550 8003ED50 2C5B000C */  jal        Cos
/* 2F554 8003ED54 21806200 */   addu      $s0, $v1, $v0
/* 2F558 8003ED58 18004202 */  mult       $s2, $v0
/* 2F55C 8003ED5C 21202002 */  addu       $a0, $s1, $zero
/* 2F560 8003ED60 12180000 */  mflo       $v1
/* 2F564 8003ED64 165B000C */  jal        Sin
/* 2F568 8003ED68 03930300 */   sra       $s2, $v1, 12
/* 2F56C 8003ED6C 18000202 */  mult       $s0, $v0
/* 2F570 8003ED70 12180000 */  mflo       $v1
/* 2F574 8003ED74 00000000 */  nop
/* 2F578 8003ED78 00000000 */  nop
/* 2F57C 8003ED7C 18005202 */  mult       $s2, $s2
/* 2F580 8003ED80 12100000 */  mflo       $v0
/* 2F584 8003ED84 03830300 */  sra        $s0, $v1, 12
/* 2F588 8003ED88 00000000 */  nop
/* 2F58C 8003ED8C 18001002 */  mult       $s0, $s0
/* 2F590 8003ED90 12180000 */  mflo       $v1
/* 2F594 8003ED94 8E5E000C */  jal        func_80017A38
/* 2F598 8003ED98 21204300 */   addu      $a0, $v0, $v1
/* 2F59C 8003ED9C 6BFB0008 */  j          .L8003EDAC
/* 2F5A0 8003EDA0 00000000 */   nop
.L8003EDA4:
/* 2F5A4 8003EDA4 0780023C */  lui        $v0, %hi(D_8006C5B8)
/* 2F5A8 8003EDA8 B8C5428C */  lw         $v0, %lo(D_8006C5B8)($v0)
.L8003EDAC:
/* 2F5AC 8003EDAC 0880013C */  lui        $at, %hi(g_Spyro + 0x144)
/* 2F5B0 8003EDB0 9C8B22AC */  sw         $v0, %lo(g_Spyro + 0x144)($at)
/* 2F5B4 8003EDB4 0880033C */  lui        $v1, %hi(g_Spyro + 0x194)
/* 2F5B8 8003EDB8 EC8B638C */  lw         $v1, %lo(g_Spyro + 0x194)($v1)
/* 2F5BC 8003EDBC 01000224 */  addiu      $v0, $zero, 0x1
/* 2F5C0 8003EDC0 0880013C */  lui        $at, %hi(g_Spyro + 0x15C)
/* 2F5C4 8003EDC4 B48B22AC */  sw         $v0, %lo(g_Spyro + 0x15C)($at)
/* 2F5C8 8003EDC8 E1036010 */  beqz       $v1, .L8003FD50
/* 2F5CC 8003EDCC 00000000 */   nop
/* 2F5D0 8003EDD0 0880023C */  lui        $v0, %hi(g_Spyro + 0x206)
/* 2F5D4 8003EDD4 5E8C4290 */  lbu        $v0, %lo(g_Spyro + 0x206)($v0)
/* 2F5D8 8003EDD8 0880013C */  lui        $at, %hi(g_Spyro + 0xC8)
/* 2F5DC 8003EDDC 208B20AC */  sw         $zero, %lo(g_Spyro + 0xC8)($at)
/* 2F5E0 8003EDE0 00110200 */  sll        $v0, $v0, 4
/* 2F5E4 8003EDE4 0880013C */  lui        $at, %hi(g_Spyro + 0xCC)
/* 2F5E8 8003EDE8 248B22AC */  sw         $v0, %lo(g_Spyro + 0xCC)($at)
/* 2F5EC 8003EDEC 54FF0008 */  j          .L8003FD50
/* 2F5F0 8003EDF0 00000000 */   nop
.L8003EDF4:
/* 2F5F4 8003EDF4 00F40224 */  addiu      $v0, $zero, -0xC00
/* 2F5F8 8003EDF8 0880013C */  lui        $at, %hi(g_Spyro + 0x7C)
/* 2F5FC 8003EDFC D48A20AC */  sw         $zero, %lo(g_Spyro + 0x7C)($at)
/* 2F600 8003EE00 0880013C */  lui        $at, %hi(g_Spyro + 0x14C)
/* 2F604 8003EE04 A48B22AC */  sw         $v0, %lo(g_Spyro + 0x14C)($at)
/* 2F608 8003EE08 F6FE0008 */  j          .L8003FBD8
/* 2F60C 8003EE0C 00000000 */   nop
.L8003EE10:
/* 2F610 8003EE10 0880043C */  lui        $a0, %hi(g_Spyro + 0xF4)
/* 2F614 8003EE14 4C8B8424 */  addiu      $a0, $a0, %lo(g_Spyro + 0xF4)
/* 2F618 8003EE18 C05D000C */  jal        VecCopy
/* 2F61C 8003EE1C 18008524 */   addiu     $a1, $a0, 0x18
/* 2F620 8003EE20 C00D0224 */  addiu      $v0, $zero, 0xDC0
/* 2F624 8003EE24 0880013C */  lui        $at, %hi(g_Spyro + 0xF0)
/* 2F628 8003EE28 488B22AC */  sw         $v0, %lo(g_Spyro + 0xF0)($at)
/* 2F62C 8003EE2C 40FF0224 */  addiu      $v0, $zero, -0xC0
/* 2F630 8003EE30 0880013C */  lui        $at, %hi(g_Spyro + 0x14C)
/* 2F634 8003EE34 A48B22AC */  sw         $v0, %lo(g_Spyro + 0x14C)($at)
/* 2F638 8003EE38 0880023C */  lui        $v0, %hi(g_Spyro + 0xFC)
/* 2F63C 8003EE3C 548B428C */  lw         $v0, %lo(g_Spyro + 0xFC)($v0)
/* 2F640 8003EE40 0880033C */  lui        $v1, %hi(g_Spyro + 0x8)
/* 2F644 8003EE44 608A638C */  lw         $v1, %lo(g_Spyro + 0x8)($v1)
/* 2F648 8003EE48 0880013C */  lui        $at, %hi(g_Spyro + 0x7C)
/* 2F64C 8003EE4C D48A20AC */  sw         $zero, %lo(g_Spyro + 0x7C)($at)
/* 2F650 8003EE50 0880013C */  lui        $at, %hi(g_Spyro + 0x154)
/* 2F654 8003EE54 AC8B20AC */  sw         $zero, %lo(g_Spyro + 0x154)($at)
/* 2F658 8003EE58 0880013C */  lui        $at, %hi(g_Spyro + 0x15C)
/* 2F65C 8003EE5C B48B20AC */  sw         $zero, %lo(g_Spyro + 0x15C)($at)
/* 2F660 8003EE60 83110200 */  sra        $v0, $v0, 6
/* 2F664 8003EE64 21186200 */  addu       $v1, $v1, $v0
/* 2F668 8003EE68 0880013C */  lui        $at, %hi(g_Spyro + 0x158)
/* 2F66C 8003EE6C B08B23AC */  sw         $v1, %lo(g_Spyro + 0x158)($at)
/* 2F670 8003EE70 0880033C */  lui        $v1, %hi(g_Spyro + 0x78)
/* 2F674 8003EE74 D08A638C */  lw         $v1, %lo(g_Spyro + 0x78)($v1)
/* 2F678 8003EE78 1D000224 */  addiu      $v0, $zero, 0x1D
/* 2F67C 8003EE7C 04006214 */  bne        $v1, $v0, .L8003EE90
/* 2F680 8003EE80 01000224 */   addiu     $v0, $zero, 0x1
/* 2F684 8003EE84 500482AF */  sw         $v0, %gp_rel(D_800756B4)($gp)
/* 2F688 8003EE88 54FF0008 */  j          .L8003FD50
/* 2F68C 8003EE8C 00000000 */   nop
.L8003EE90:
/* 2F690 8003EE90 500480AF */  sw         $zero, %gp_rel(D_800756B4)($gp)
/* 2F694 8003EE94 54FF0008 */  j          .L8003FD50
/* 2F698 8003EE98 00000000 */   nop
.L8003EE9C:
/* 2F69C 8003EE9C 0880023C */  lui        $v0, %hi(g_Spyro + 0x7C)
/* 2F6A0 8003EEA0 D48A4224 */  addiu      $v0, $v0, %lo(g_Spyro + 0x7C)
/* 2F6A4 8003EEA4 78004424 */  addiu      $a0, $v0, 0x78
/* 2F6A8 8003EEA8 90004524 */  addiu      $a1, $v0, 0x90
/* 2F6AC 8003EEAC C05D000C */  jal        VecCopy
/* 2F6B0 8003EEB0 000040AC */   sw        $zero, 0x0($v0)
/* 2F6B4 8003EEB4 0880023C */  lui        $v0, %hi(g_Spyro + 0x98)
/* 2F6B8 8003EEB8 F08A428C */  lw         $v0, %lo(g_Spyro + 0x98)($v0)
/* 2F6BC 8003EEBC 00000000 */  nop
/* 2F6C0 8003EEC0 84024014 */  bnez       $v0, .L8003F8D4
/* 2F6C4 8003EEC4 40FF0224 */   addiu     $v0, $zero, -0xC0
/* 2F6C8 8003EEC8 0880023C */  lui        $v0, %hi(g_Spyro + 0xB0)
/* 2F6CC 8003EECC 088B428C */  lw         $v0, %lo(g_Spyro + 0xB0)($v0)
/* 2F6D0 8003EED0 00000000 */  nop
/* 2F6D4 8003EED4 20004228 */  slti       $v0, $v0, 0x20
/* 2F6D8 8003EED8 7E024010 */  beqz       $v0, .L8003F8D4
/* 2F6DC 8003EEDC 40FF0224 */   addiu     $v0, $zero, -0xC0
/* 2F6E0 8003EEE0 43FA000C */  jal        func_8003E90C
/* 2F6E4 8003EEE4 00000000 */   nop
/* 2F6E8 8003EEE8 35FE0008 */  j          .L8003F8D4
/* 2F6EC 8003EEEC 40FF0224 */   addiu     $v0, $zero, -0xC0
.L8003EEF0:
/* 2F6F0 8003EEF0 0880023C */  lui        $v0, %hi(g_Spyro + 0x114)
/* 2F6F4 8003EEF4 6C8B428C */  lw         $v0, %lo(g_Spyro + 0x114)($v0)
/* 2F6F8 8003EEF8 0880033C */  lui        $v1, %hi(g_Spyro + 0x98)
/* 2F6FC 8003EEFC F08A638C */  lw         $v1, %lo(g_Spyro + 0x98)($v1)
/* 2F700 8003EF00 0880013C */  lui        $at, %hi(g_Spyro + 0x7C)
/* 2F704 8003EF04 D48A20AC */  sw         $zero, %lo(g_Spyro + 0x7C)($at)
/* 2F708 8003EF08 0880013C */  lui        $at, %hi(g_Spyro + 0xF4)
/* 2F70C 8003EF0C 4C8B20AC */  sw         $zero, %lo(g_Spyro + 0xF4)($at)
/* 2F710 8003EF10 0880013C */  lui        $at, %hi(g_Spyro + 0xF8)
/* 2F714 8003EF14 508B20AC */  sw         $zero, %lo(g_Spyro + 0xF8)($at)
/* 2F718 8003EF18 0880013C */  lui        $at, %hi(g_Spyro + 0xFC)
/* 2F71C 8003EF1C 548B22AC */  sw         $v0, %lo(g_Spyro + 0xFC)($at)
/* 2F720 8003EF20 6C026014 */  bnez       $v1, .L8003F8D4
/* 2F724 8003EF24 40FF0224 */   addiu     $v0, $zero, -0xC0
/* 2F728 8003EF28 0880023C */  lui        $v0, %hi(g_Spyro + 0xB0)
/* 2F72C 8003EF2C 088B428C */  lw         $v0, %lo(g_Spyro + 0xB0)($v0)
/* 2F730 8003EF30 00000000 */  nop
/* 2F734 8003EF34 20004228 */  slti       $v0, $v0, 0x20
/* 2F738 8003EF38 66024010 */  beqz       $v0, .L8003F8D4
/* 2F73C 8003EF3C 40FF0224 */   addiu     $v0, $zero, -0xC0
/* 2F740 8003EF40 43FA000C */  jal        func_8003E90C
/* 2F744 8003EF44 00000000 */   nop
/* 2F748 8003EF48 35FE0008 */  j          .L8003F8D4
/* 2F74C 8003EF4C 40FF0224 */   addiu     $v0, $zero, -0xC0
.L8003EF50:
/* 2F750 8003EF50 0880023C */  lui        $v0, %hi(g_Spyro + 0x7C)
/* 2F754 8003EF54 D48A4224 */  addiu      $v0, $v0, %lo(g_Spyro + 0x7C)
/* 2F758 8003EF58 6C004424 */  addiu      $a0, $v0, 0x6C
/* 2F75C 8003EF5C 90004524 */  addiu      $a1, $v0, 0x90
/* 2F760 8003EF60 C05D000C */  jal        VecCopy
/* 2F764 8003EF64 000040AC */   sw        $zero, 0x0($v0)
/* 2F768 8003EF68 00F40224 */  addiu      $v0, $zero, -0xC00
/* 2F76C 8003EF6C 0880013C */  lui        $at, %hi(g_Spyro + 0x118)
/* 2F770 8003EF70 708B20AC */  sw         $zero, %lo(g_Spyro + 0x118)($at)
/* 2F774 8003EF74 0880013C */  lui        $at, %hi(g_Spyro + 0x14C)
/* 2F778 8003EF78 A48B22AC */  sw         $v0, %lo(g_Spyro + 0x14C)($at)
/* 2F77C 8003EF7C F6FE0008 */  j          .L8003FBD8
/* 2F780 8003EF80 00000000 */   nop
.L8003EF84:
/* 2F784 8003EF84 0880103C */  lui        $s0, %hi(g_Spyro + 0xE8)
/* 2F788 8003EF88 408B1026 */  addiu      $s0, $s0, %lo(g_Spyro + 0xE8)
/* 2F78C 8003EF8C 21200002 */  addu       $a0, $s0, $zero
/* 2F790 8003EF90 C05D000C */  jal        VecCopy
/* 2F794 8003EF94 24000526 */   addiu     $a1, $s0, 0x24
/* 2F798 8003EF98 0880023C */  lui        $v0, %hi(g_Spyro + 0x250)
/* 2F79C 8003EF9C A88C428C */  lw         $v0, %lo(g_Spyro + 0x250)($v0)
/* 2F7A0 8003EFA0 00000000 */  nop
/* 2F7A4 8003EFA4 16004010 */  beqz       $v0, .L8003F000
/* 2F7A8 8003EFA8 01000224 */   addiu     $v0, $zero, 0x1
/* 2F7AC 8003EFAC 0880023C */  lui        $v0, %hi(g_Spyro + 0x7C)
/* 2F7B0 8003EFB0 D48A428C */  lw         $v0, %lo(g_Spyro + 0x7C)($v0)
/* 2F7B4 8003EFB4 00000000 */  nop
/* 2F7B8 8003EFB8 80004230 */  andi       $v0, $v0, 0x80
/* 2F7BC 8003EFBC 10004014 */  bnez       $v0, .L8003F000
/* 2F7C0 8003EFC0 81000224 */   addiu     $v0, $zero, 0x81
/* 2F7C4 8003EFC4 21200002 */  addu       $a0, $s0, $zero
/* 2F7C8 8003EFC8 0880023C */  lui        $v0, %hi(g_Spyro + 0x8)
/* 2F7CC 8003EFCC 608A428C */  lw         $v0, %lo(g_Spyro + 0x8)($v0)
/* 2F7D0 8003EFD0 0880013C */  lui        $at, %hi(g_Spyro + 0x158)
/* 2F7D4 8003EFD4 B08B22AC */  sw         $v0, %lo(g_Spyro + 0x158)($at)
/* 2F7D8 8003EFD8 7F5C000C */  jal        VecMagnitude
/* 2F7DC 8003EFDC 01000524 */   addiu     $a1, $zero, 0x1
/* 2F7E0 8003EFE0 21184000 */  addu       $v1, $v0, $zero
/* 2F7E4 8003EFE4 801F6228 */  slti       $v0, $v1, 0x1F80
/* 2F7E8 8003EFE8 02004010 */  beqz       $v0, .L8003EFF4
/* 2F7EC 8003EFEC 00000000 */   nop
/* 2F7F0 8003EFF0 801F0324 */  addiu      $v1, $zero, 0x1F80
.L8003EFF4:
/* 2F7F4 8003EFF4 0880013C */  lui        $at, %hi(g_Spyro + 0xC8)
/* 2F7F8 8003EFF8 208B23AC */  sw         $v1, %lo(g_Spyro + 0xC8)($at)
/* 2F7FC 8003EFFC 81000224 */  addiu      $v0, $zero, 0x81
.L8003F000:
/* 2F800 8003F000 0880013C */  lui        $at, %hi(g_Spyro + 0x7C)
/* 2F804 8003F004 D48A22AC */  sw         $v0, %lo(g_Spyro + 0x7C)($at)
/* 2F808 8003F008 0880103C */  lui        $s0, %hi(g_Spyro + 0x148)
/* 2F80C 8003F00C A08B1026 */  addiu      $s0, $s0, %lo(g_Spyro + 0x148)
/* 2F810 8003F010 C0FD0224 */  addiu      $v0, $zero, -0x240
/* 2F814 8003F014 000000AE */  sw         $zero, 0x0($s0)
/* 2F818 8003F018 0880013C */  lui        $at, %hi(g_Spyro + 0x14C)
/* 2F81C 8003F01C A48B22AC */  sw         $v0, %lo(g_Spyro + 0x14C)($at)
/* 2F820 8003F020 6BF8000C */  jal        func_8003E1AC
/* 2F824 8003F024 B8FE1126 */   addiu     $s1, $s0, -0x148
/* 2F828 8003F028 2DF8000C */  jal        ApplySlopeGravity
/* 2F82C 8003F02C 00000000 */   nop
/* 2F830 8003F030 21282002 */  addu       $a1, $s1, $zero
/* 2F834 8003F034 04000624 */  addiu      $a2, $zero, 0x4
/* 2F838 8003F038 0780033C */  lui        $v1, %hi(g_Spu + 0x2CC)
/* 2F83C 8003F03C D461638C */  lw         $v1, %lo(g_Spu + 0x2CC)($v1)
/* 2F840 8003F040 01000224 */  addiu      $v0, $zero, 0x1
/* 2F844 8003F044 0880013C */  lui        $at, %hi(g_Spyro + 0x15C)
/* 2F848 8003F048 B48B22AC */  sw         $v0, %lo(g_Spyro + 0x15C)($at)
/* 2F84C 8003F04C 04006490 */  lbu        $a0, 0x4($v1)
/* 2F850 8003F050 9E56010C */  jal        PlaySound
/* 2F854 8003F054 59010726 */   addiu     $a3, $s0, 0x159
/* 2F858 8003F058 0780033C */  lui        $v1, %hi(g_Camera + 0x50)
/* 2F85C 8003F05C 206E6384 */  lh         $v1, %lo(g_Camera + 0x50)($v1)
/* 2F860 8003F060 0880023C */  lui        $v0, %hi(g_Spyro + 0x11C)
/* 2F864 8003F064 748B428C */  lw         $v0, %lo(g_Spyro + 0x11C)($v0)
/* 2F868 8003F068 2C0580AF */  sw         $zero, %gp_rel(D_80075790)($gp)
/* 2F86C 8003F06C 23104300 */  subu       $v0, $v0, $v1
/* 2F870 8003F070 FF0F4330 */  andi       $v1, $v0, 0xFFF
/* 2F874 8003F074 01086228 */  slti       $v0, $v1, 0x801
/* 2F878 8003F078 02004014 */  bnez       $v0, .L8003F084
/* 2F87C 8003F07C 00000000 */   nop
/* 2F880 8003F080 00F06324 */  addiu      $v1, $v1, -0x1000
.L8003F084:
/* 2F884 8003F084 02006104 */  bgez       $v1, .L8003F090
/* 2F888 8003F088 21106000 */   addu      $v0, $v1, $zero
/* 2F88C 8003F08C 23100200 */  negu       $v0, $v0
.L8003F090:
/* 2F890 8003F090 01024228 */  slti       $v0, $v0, 0x201
/* 2F894 8003F094 2E034014 */  bnez       $v0, .L8003FD50
/* 2F898 8003F098 00000000 */   nop
/* 2F89C 8003F09C 0780103C */  lui        $s0, %hi(D_80075828)
/* 2F8A0 8003F0A0 2858108E */  lw         $s0, %lo(D_80075828)($s0)
/* 2F8A4 8003F0A4 0780023C */  lui        $v0, %hi(D_80075890)
/* 2F8A8 8003F0A8 9058428C */  lw         $v0, %lo(D_80075890)($v0)
/* 2F8AC 8003F0AC 00000000 */  nop
/* 2F8B0 8003F0B0 2B100202 */  sltu       $v0, $s0, $v0
/* 2F8B4 8003F0B4 26034010 */  beqz       $v0, .L8003FD50
/* 2F8B8 8003F0B8 30751324 */   addiu     $s3, $zero, 0x7530
/* 2F8BC 8003F0BC 21A02002 */  addu       $s4, $s1, $zero
/* 2F8C0 8003F0C0 0C001126 */  addiu      $s1, $s0, 0xC
.L8003F0C4:
/* 2F8C4 8003F0C4 3C002292 */  lbu        $v0, 0x3C($s1)
/* 2F8C8 8003F0C8 00000000 */  nop
/* 2F8CC 8003F0CC 7F00422C */  sltiu      $v0, $v0, 0x7F
/* 2F8D0 8003F0D0 38004010 */  beqz       $v0, .L8003F1B4
/* 2F8D4 8003F0D4 00000000 */   nop
/* 2F8D8 8003F0D8 FCFF228E */  lw         $v0, -0x4($s1)
/* 2F8DC 8003F0DC 00000000 */  nop
/* 2F8E0 8003F0E0 34004010 */  beqz       $v0, .L8003F1B4
/* 2F8E4 8003F0E4 1000A427 */   addiu     $a0, $sp, 0x10
/* 2F8E8 8003F0E8 21282002 */  addu       $a1, $s1, $zero
/* 2F8EC 8003F0EC E35D000C */  jal        VecSub
/* 2F8F0 8003F0F0 21308002 */   addu      $a2, $s4, $zero
/* 2F8F4 8003F0F4 1000A48F */  lw         $a0, 0x10($sp)
/* 2F8F8 8003F0F8 1400A58F */  lw         $a1, 0x14($sp)
/* 2F8FC 8003F0FC AD5A000C */  jal        Atan2
/* 2F900 8003F100 01000624 */   addiu     $a2, $zero, 0x1
/* 2F904 8003F104 0880033C */  lui        $v1, %hi(g_Spyro + 0x11C)
/* 2F908 8003F108 748B638C */  lw         $v1, %lo(g_Spyro + 0x11C)($v1)
/* 2F90C 8003F10C 00000000 */  nop
/* 2F910 8003F110 23104300 */  subu       $v0, $v0, $v1
/* 2F914 8003F114 FF0F4330 */  andi       $v1, $v0, 0xFFF
/* 2F918 8003F118 01086228 */  slti       $v0, $v1, 0x801
/* 2F91C 8003F11C 02004014 */  bnez       $v0, .L8003F128
/* 2F920 8003F120 00000000 */   nop
/* 2F924 8003F124 00F06324 */  addiu      $v1, $v1, -0x1000
.L8003F128:
/* 2F928 8003F128 02006104 */  bgez       $v1, .L8003F134
/* 2F92C 8003F12C 21906000 */   addu      $s2, $v1, $zero
/* 2F930 8003F130 23901200 */  negu       $s2, $s2
.L8003F134:
/* 2F934 8003F134 0002422A */  slti       $v0, $s2, 0x200
/* 2F938 8003F138 1E004010 */  beqz       $v0, .L8003F1B4
/* 2F93C 8003F13C 00000000 */   nop
/* 2F940 8003F140 1000A48F */  lw         $a0, 0x10($sp)
/* 2F944 8003F144 1400A38F */  lw         $v1, 0x14($sp)
/* 2F948 8003F148 1800A28F */  lw         $v0, 0x18($sp)
/* 2F94C 8003F14C 02008104 */  bgez       $a0, .L8003F158
/* 2F950 8003F150 00000000 */   nop
/* 2F954 8003F154 23200400 */  negu       $a0, $a0
.L8003F158:
/* 2F958 8003F158 02006104 */  bgez       $v1, .L8003F164
/* 2F95C 8003F15C 00000000 */   nop
/* 2F960 8003F160 23180300 */  negu       $v1, $v1
.L8003F164:
/* 2F964 8003F164 21208300 */  addu       $a0, $a0, $v1
/* 2F968 8003F168 02004104 */  bgez       $v0, .L8003F174
/* 2F96C 8003F16C 00000000 */   nop
/* 2F970 8003F170 23100200 */  negu       $v0, $v0
.L8003F174:
/* 2F974 8003F174 21208200 */  addu       $a0, $a0, $v0
/* 2F978 8003F178 00408228 */  slti       $v0, $a0, 0x4000
/* 2F97C 8003F17C 0D004010 */  beqz       $v0, .L8003F1B4
/* 2F980 8003F180 1000A427 */   addiu     $a0, $sp, 0x10
/* 2F984 8003F184 7F5C000C */  jal        VecMagnitude
/* 2F988 8003F188 01000524 */   addiu     $a1, $zero, 0x1
/* 2F98C 8003F18C 21204000 */  addu       $a0, $v0, $zero
/* 2F990 8003F190 00188228 */  slti       $v0, $a0, 0x1800
/* 2F994 8003F194 07004010 */  beqz       $v0, .L8003F1B4
/* 2F998 8003F198 80101200 */   sll       $v0, $s2, 2
/* 2F99C 8003F19C 21208200 */  addu       $a0, $a0, $v0
/* 2F9A0 8003F1A0 2A109300 */  slt        $v0, $a0, $s3
/* 2F9A4 8003F1A4 03004010 */  beqz       $v0, .L8003F1B4
/* 2F9A8 8003F1A8 00000000 */   nop
/* 2F9AC 8003F1AC 21988000 */  addu       $s3, $a0, $zero
/* 2F9B0 8003F1B0 2C0590AF */  sw         $s0, %gp_rel(D_80075790)($gp)
.L8003F1B4:
/* 2F9B4 8003F1B4 0780023C */  lui        $v0, %hi(D_80075890)
/* 2F9B8 8003F1B8 9058428C */  lw         $v0, %lo(D_80075890)($v0)
/* 2F9BC 8003F1BC 58001026 */  addiu      $s0, $s0, 0x58
/* 2F9C0 8003F1C0 2B100202 */  sltu       $v0, $s0, $v0
/* 2F9C4 8003F1C4 BFFF4014 */  bnez       $v0, .L8003F0C4
/* 2F9C8 8003F1C8 58003126 */   addiu     $s1, $s1, 0x58
/* 2F9CC 8003F1CC 54FF0008 */  j          .L8003FD50
/* 2F9D0 8003F1D0 00000000 */   nop
.L8003F1D4:
/* 2F9D4 8003F1D4 CB89010C */  jal        rand
/* 2F9D8 8003F1D8 21880000 */   addu      $s1, $zero, $zero
/* 2F9DC 8003F1DC 3F005230 */  andi       $s2, $v0, 0x3F
/* 2F9E0 8003F1E0 0780133C */  lui        $s3, %hi(D_8006CC78)
/* 2F9E4 8003F1E4 78CC7326 */  addiu      $s3, $s3, %lo(D_8006CC78)
/* 2F9E8 8003F1E8 2000B027 */  addiu      $s0, $sp, 0x20
.L8003F1EC:
/* 2F9EC 8003F1EC 0880043C */  lui        $a0, %hi(g_Spyro + 0x34)
/* 2F9F0 8003F1F0 8C8A8424 */  addiu      $a0, $a0, %lo(g_Spyro + 0x34)
/* 2F9F4 8003F1F4 21280002 */  addu       $a1, $s0, $zero
/* 2F9F8 8003F1F8 40181200 */  sll        $v1, $s2, 1
/* 2F9FC 8003F1FC 21107300 */  addu       $v0, $v1, $s3
/* 2FA00 8003F200 2000A0AF */  sw         $zero, 0x20($sp)
/* 2FA04 8003F204 00004294 */  lhu        $v0, 0x0($v0)
/* 2FA08 8003F208 21300002 */  addu       $a2, $s0, $zero
/* 2FA0C 8003F20C 00140200 */  sll        $v0, $v0, 16
/* 2FA10 8003F210 C3150200 */  sra        $v0, $v0, 23
/* 2FA14 8003F214 2400A2AF */  sw         $v0, 0x24($sp)
/* 2FA18 8003F218 0780013C */  lui        $at, %hi(D_8006CBF8)
/* 2FA1C 8003F21C 21082300 */  addu       $at, $at, $v1
/* 2FA20 8003F220 F8CB2294 */  lhu        $v0, %lo(D_8006CBF8)($at)
/* 2FA24 8003F224 01003126 */  addiu      $s1, $s1, 0x1
/* 2FA28 8003F228 00140200 */  sll        $v0, $v0, 16
/* 2FA2C 8003F22C C3150200 */  sra        $v0, $v0, 23
/* 2FA30 8003F230 125C000C */  jal        VecRotateByMatrix
/* 2FA34 8003F234 2800A2AF */   sw        $v0, 0x28($sp)
/* 2FA38 8003F238 01000424 */  addiu      $a0, $zero, 0x1
/* 2FA3C 8003F23C 21000524 */  addiu      $a1, $zero, 0x21
/* 2FA40 8003F240 21300002 */  addu       $a2, $s0, $zero
/* 2FA44 8003F244 0780023C */  lui        $v0, %hi(D_800758E4)
/* 2FA48 8003F248 E458428C */  lw         $v0, %lo(D_800758E4)($v0)
/* 2FA4C 8003F24C 00000000 */  nop
/* 2FA50 8003F250 09F84000 */  jalr       $v0
/* 2FA54 8003F254 01000724 */   addiu     $a3, $zero, 0x1
/* 2FA58 8003F258 40004226 */  addiu      $v0, $s2, 0x40
/* 2FA5C 8003F25C FF005230 */  andi       $s2, $v0, 0xFF
/* 2FA60 8003F260 0400222A */  slti       $v0, $s1, 0x4
/* 2FA64 8003F264 E1FF4014 */  bnez       $v0, .L8003F1EC
/* 2FA68 8003F268 00000000 */   nop
/* 2FA6C 8003F26C 0880103C */  lui        $s0, %hi(g_Spyro + 0x7C)
/* 2FA70 8003F270 D48A1026 */  addiu      $s0, $s0, %lo(g_Spyro + 0x7C)
/* 2FA74 8003F274 6C001126 */  addiu      $s1, $s0, 0x6C
/* 2FA78 8003F278 21202002 */  addu       $a0, $s1, $zero
/* 2FA7C 8003F27C BC5D000C */  jal        VecNull
/* 2FA80 8003F280 000000AE */   sw        $zero, 0x0($s0)
/* 2FA84 8003F284 78001026 */  addiu      $s0, $s0, 0x78
/* 2FA88 8003F288 21200002 */  addu       $a0, $s0, $zero
/* 2FA8C 8003F28C 21282002 */  addu       $a1, $s1, $zero
/* 2FA90 8003F290 E35D000C */  jal        VecSub
/* 2FA94 8003F294 21300002 */   addu      $a2, $s0, $zero
/* 2FA98 8003F298 21200002 */  addu       $a0, $s0, $zero
/* 2FA9C 8003F29C B25D000C */  jal        VecShiftRight
/* 2FAA0 8003F2A0 02000524 */   addiu     $a1, $zero, 0x2
/* 2FAA4 8003F2A4 00FD0224 */  addiu      $v0, $zero, -0x300
/* 2FAA8 8003F2A8 0880013C */  lui        $at, %hi(g_Spyro + 0x14C)
/* 2FAAC 8003F2AC A48B22AC */  sw         $v0, %lo(g_Spyro + 0x14C)($at)
/* 2FAB0 8003F2B0 0780023C */  lui        $v0, %hi(D_8007584C)
/* 2FAB4 8003F2B4 4C58428C */  lw         $v0, %lo(D_8007584C)($v0)
/* 2FAB8 8003F2B8 01000324 */  addiu      $v1, $zero, 0x1
/* 2FABC 8003F2BC 0880013C */  lui        $at, %hi(g_Spyro + 0x15C)
/* 2FAC0 8003F2C0 B48B23AC */  sw         $v1, %lo(g_Spyro + 0x15C)($at)
/* 2FAC4 8003F2C4 78004228 */  slti       $v0, $v0, 0x78
/* 2FAC8 8003F2C8 03004010 */  beqz       $v0, .L8003F2D8
/* 2FACC 8003F2CC 78000224 */   addiu     $v0, $zero, 0x78
/* 2FAD0 8003F2D0 0780013C */  lui        $at, %hi(D_8007584C)
/* 2FAD4 8003F2D4 4C5822AC */  sw         $v0, %lo(D_8007584C)($at)
.L8003F2D8:
/* 2FAD8 8003F2D8 0780023C */  lui        $v0, %hi(D_800757D0)
/* 2FADC 8003F2DC D057428C */  lw         $v0, %lo(D_800757D0)($v0)
/* 2FAE0 8003F2E0 00000000 */  nop
/* 2FAE4 8003F2E4 0F004228 */  slti       $v0, $v0, 0xF
/* 2FAE8 8003F2E8 99024010 */  beqz       $v0, .L8003FD50
/* 2FAEC 8003F2EC 0F000224 */   addiu     $v0, $zero, 0xF
/* 2FAF0 8003F2F0 0780013C */  lui        $at, %hi(D_800757D0)
/* 2FAF4 8003F2F4 D05722AC */  sw         $v0, %lo(D_800757D0)($at)
/* 2FAF8 8003F2F8 54FF0008 */  j          .L8003FD50
/* 2FAFC 8003F2FC 00000000 */   nop
.L8003F300:
/* 2FB00 8003F300 19FF0008 */  j          .L8003FC64
/* 2FB04 8003F304 00F40224 */   addiu     $v0, $zero, -0xC00
.L8003F308:
/* 2FB08 8003F308 0880103C */  lui        $s0, %hi(g_Spyro + 0x7C)
/* 2FB0C 8003F30C D48A1026 */  addiu      $s0, $s0, %lo(g_Spyro + 0x7C)
/* 2FB10 8003F310 000000AE */  sw         $zero, 0x0($s0)
/* 2FB14 8003F314 78001126 */  addiu      $s1, $s0, 0x78
/* 2FB18 8003F318 BC5D000C */  jal        VecNull
/* 2FB1C 8003F31C 21202002 */   addu      $a0, $s1, $zero
/* 2FB20 8003F320 21202002 */  addu       $a0, $s1, $zero
/* 2FB24 8003F324 21282002 */  addu       $a1, $s1, $zero
/* 2FB28 8003F328 E35D000C */  jal        VecSub
/* 2FB2C 8003F32C 90000626 */   addiu     $a2, $s0, 0x90
/* 2FB30 8003F330 21202002 */  addu       $a0, $s1, $zero
/* 2FB34 8003F334 7F5C000C */  jal        VecMagnitude
/* 2FB38 8003F338 01000524 */   addiu     $a1, $zero, 0x1
/* 2FB3C 8003F33C 21284000 */  addu       $a1, $v0, $zero
/* 2FB40 8003F340 011EA228 */  slti       $v0, $a1, 0x1E01
/* 2FB44 8003F344 03004014 */  bnez       $v0, .L8003F354
/* 2FB48 8003F348 21202002 */   addu      $a0, $s1, $zero
/* 2FB4C 8003F34C 6E5D000C */  jal        VecScaleToLength
/* 2FB50 8003F350 001E0624 */   addiu     $a2, $zero, 0x1E00
.L8003F354:
/* 2FB54 8003F354 0880033C */  lui        $v1, %hi(g_Spyro + 0x9C)
/* 2FB58 8003F358 F48A638C */  lw         $v1, %lo(g_Spyro + 0x9C)($v1)
/* 2FB5C 8003F35C 00FD0224 */  addiu      $v0, $zero, -0x300
/* 2FB60 8003F360 0880013C */  lui        $at, %hi(g_Spyro + 0x14C)
/* 2FB64 8003F364 A48B22AC */  sw         $v0, %lo(g_Spyro + 0x14C)($at)
/* 2FB68 8003F368 04006014 */  bnez       $v1, .L8003F37C
/* 2FB6C 8003F36C 05000424 */   addiu     $a0, $zero, 0x5
/* 2FB70 8003F370 6BF8000C */  jal        func_8003E1AC
/* 2FB74 8003F374 00000000 */   nop
/* 2FB78 8003F378 05000424 */  addiu      $a0, $zero, 0x5
.L8003F37C:
/* 2FB7C 8003F37C 0A000524 */  addiu      $a1, $zero, 0xA
/* 2FB80 8003F380 21300000 */  addu       $a2, $zero, $zero
/* 2FB84 8003F384 0780033C */  lui        $v1, %hi(D_800758E4)
/* 2FB88 8003F388 E458638C */  lw         $v1, %lo(D_800758E4)($v1)
/* 2FB8C 8003F38C 01000224 */  addiu      $v0, $zero, 0x1
/* 2FB90 8003F390 0880013C */  lui        $at, %hi(g_Spyro + 0x15C)
/* 2FB94 8003F394 B48B22AC */  sw         $v0, %lo(g_Spyro + 0x15C)($at)
/* 2FB98 8003F398 09F86000 */  jalr       $v1
/* 2FB9C 8003F39C 21380000 */   addu      $a3, $zero, $zero
/* 2FBA0 8003F3A0 0780023C */  lui        $v0, %hi(D_80075764)
/* 2FBA4 8003F3A4 6457428C */  lw         $v0, %lo(D_80075764)($v0)
/* 2FBA8 8003F3A8 00000000 */  nop
/* 2FBAC 8003F3AC 2D004228 */  slti       $v0, $v0, 0x2D
/* 2FBB0 8003F3B0 67024010 */  beqz       $v0, .L8003FD50
/* 2FBB4 8003F3B4 2D000224 */   addiu     $v0, $zero, 0x2D
/* 2FBB8 8003F3B8 0780013C */  lui        $at, %hi(D_80075764)
/* 2FBBC 8003F3BC 645722AC */  sw         $v0, %lo(D_80075764)($at)
/* 2FBC0 8003F3C0 54FF0008 */  j          .L8003FD50
/* 2FBC4 8003F3C4 00000000 */   nop
.L8003F3C8:
/* 2FBC8 8003F3C8 0880113C */  lui        $s1, %hi(g_Spyro + 0x7C)
/* 2FBCC 8003F3CC D48A3126 */  addiu      $s1, $s1, %lo(g_Spyro + 0x7C)
/* 2FBD0 8003F3D0 000020AE */  sw         $zero, 0x0($s1)
/* 2FBD4 8003F3D4 78003026 */  addiu      $s0, $s1, 0x78
/* 2FBD8 8003F3D8 BC5D000C */  jal        VecNull
/* 2FBDC 8003F3DC 21200002 */   addu      $a0, $s0, $zero
/* 2FBE0 8003F3E0 21200002 */  addu       $a0, $s0, $zero
/* 2FBE4 8003F3E4 21280002 */  addu       $a1, $s0, $zero
/* 2FBE8 8003F3E8 E35D000C */  jal        VecSub
/* 2FBEC 8003F3EC 90002626 */   addiu     $a2, $s1, 0x90
/* 2FBF0 8003F3F0 21200002 */  addu       $a0, $s0, $zero
/* 2FBF4 8003F3F4 7F5C000C */  jal        VecMagnitude
/* 2FBF8 8003F3F8 01000524 */   addiu     $a1, $zero, 0x1
/* 2FBFC 8003F3FC 21284000 */  addu       $a1, $v0, $zero
/* 2FC00 8003F400 011EA228 */  slti       $v0, $a1, 0x1E01
/* 2FC04 8003F404 03004014 */  bnez       $v0, .L8003F414
/* 2FC08 8003F408 21200002 */   addu      $a0, $s0, $zero
/* 2FC0C 8003F40C 6E5D000C */  jal        VecScaleToLength
/* 2FC10 8003F410 001E0624 */   addiu     $a2, $zero, 0x1E00
.L8003F414:
/* 2FC14 8003F414 0880033C */  lui        $v1, %hi(g_Spyro + 0x9C)
/* 2FC18 8003F418 F48A638C */  lw         $v1, %lo(g_Spyro + 0x9C)($v1)
/* 2FC1C 8003F41C 00FD0224 */  addiu      $v0, $zero, -0x300
/* 2FC20 8003F420 0880013C */  lui        $at, %hi(g_Spyro + 0x14C)
/* 2FC24 8003F424 A48B22AC */  sw         $v0, %lo(g_Spyro + 0x14C)($at)
/* 2FC28 8003F428 04006014 */  bnez       $v1, .L8003F43C
/* 2FC2C 8003F42C 05000424 */   addiu     $a0, $zero, 0x5
/* 2FC30 8003F430 6BF8000C */  jal        func_8003E1AC
/* 2FC34 8003F434 00000000 */   nop
/* 2FC38 8003F438 05000424 */  addiu      $a0, $zero, 0x5
.L8003F43C:
/* 2FC3C 8003F43C 0A000524 */  addiu      $a1, $zero, 0xA
/* 2FC40 8003F440 21300000 */  addu       $a2, $zero, $zero
/* 2FC44 8003F444 0780033C */  lui        $v1, %hi(D_800758E4)
/* 2FC48 8003F448 E458638C */  lw         $v1, %lo(D_800758E4)($v1)
/* 2FC4C 8003F44C 01000224 */  addiu      $v0, $zero, 0x1
/* 2FC50 8003F450 0880013C */  lui        $at, %hi(g_Spyro + 0x15C)
/* 2FC54 8003F454 B48B22AC */  sw         $v0, %lo(g_Spyro + 0x15C)($at)
/* 2FC58 8003F458 09F86000 */  jalr       $v1
/* 2FC5C 8003F45C 21380000 */   addu      $a3, $zero, $zero
/* 2FC60 8003F460 0780023C */  lui        $v0, %hi(D_80075904)
/* 2FC64 8003F464 0459428C */  lw         $v0, %lo(D_80075904)($v0)
/* 2FC68 8003F468 00000000 */  nop
/* 2FC6C 8003F46C 0F004228 */  slti       $v0, $v0, 0xF
/* 2FC70 8003F470 03004010 */  beqz       $v0, .L8003F480
/* 2FC74 8003F474 0F000224 */   addiu     $v0, $zero, 0xF
/* 2FC78 8003F478 0780013C */  lui        $at, %hi(D_80075904)
/* 2FC7C 8003F47C 045922AC */  sw         $v0, %lo(D_80075904)($at)
.L8003F480:
/* 2FC80 8003F480 84FF2526 */  addiu      $a1, $s1, -0x7C
/* 2FC84 8003F484 0780023C */  lui        $v0, %hi(g_Spu + 0x2CC)
/* 2FC88 8003F488 D461428C */  lw         $v0, %lo(g_Spu + 0x2CC)($v0)
/* 2FC8C 8003F48C 04000624 */  addiu      $a2, $zero, 0x4
/* 2FC90 8003F490 3B004490 */  lbu        $a0, 0x3B($v0)
/* 2FC94 8003F494 52FF0008 */  j          .L8003FD48
/* 2FC98 8003F498 24022726 */   addiu     $a3, $s1, 0x224
.L8003F49C:
/* 2FC9C 8003F49C 0880103C */  lui        $s0, %hi(g_Spyro + 0x7C)
/* 2FCA0 8003F4A0 D48A1026 */  addiu      $s0, $s0, %lo(g_Spyro + 0x7C)
/* 2FCA4 8003F4A4 78000426 */  addiu      $a0, $s0, 0x78
/* 2FCA8 8003F4A8 BC5D000C */  jal        VecNull
/* 2FCAC 8003F4AC 000000AE */   sw        $zero, 0x0($s0)
/* 2FCB0 8003F4B0 05000424 */  addiu      $a0, $zero, 0x5
/* 2FCB4 8003F4B4 0A000524 */  addiu      $a1, $zero, 0xA
/* 2FCB8 8003F4B8 21300000 */  addu       $a2, $zero, $zero
/* 2FCBC 8003F4BC 0780033C */  lui        $v1, %hi(D_800758E4)
/* 2FCC0 8003F4C0 E458638C */  lw         $v1, %lo(D_800758E4)($v1)
/* 2FCC4 8003F4C4 00F40224 */  addiu      $v0, $zero, -0xC00
/* 2FCC8 8003F4C8 0880013C */  lui        $at, %hi(g_Spyro + 0xFC)
/* 2FCCC 8003F4CC 548B22AC */  sw         $v0, %lo(g_Spyro + 0xFC)($at)
/* 2FCD0 8003F4D0 01000224 */  addiu      $v0, $zero, 0x1
/* 2FCD4 8003F4D4 0880013C */  lui        $at, %hi(g_Spyro + 0x15C)
/* 2FCD8 8003F4D8 B48B22AC */  sw         $v0, %lo(g_Spyro + 0x15C)($at)
/* 2FCDC 8003F4DC 09F86000 */  jalr       $v1
/* 2FCE0 8003F4E0 21380000 */   addu      $a3, $zero, $zero
/* 2FCE4 8003F4E4 0780023C */  lui        $v0, %hi(D_80075904)
/* 2FCE8 8003F4E8 0459428C */  lw         $v0, %lo(D_80075904)($v0)
/* 2FCEC 8003F4EC 00000000 */  nop
/* 2FCF0 8003F4F0 0F004228 */  slti       $v0, $v0, 0xF
/* 2FCF4 8003F4F4 03004010 */  beqz       $v0, .L8003F504
/* 2FCF8 8003F4F8 0F000224 */   addiu     $v0, $zero, 0xF
/* 2FCFC 8003F4FC 0780013C */  lui        $at, %hi(D_80075904)
/* 2FD00 8003F500 045922AC */  sw         $v0, %lo(D_80075904)($at)
.L8003F504:
/* 2FD04 8003F504 84FF0526 */  addiu      $a1, $s0, -0x7C
/* 2FD08 8003F508 0780023C */  lui        $v0, %hi(g_Spu + 0x2CC)
/* 2FD0C 8003F50C D461428C */  lw         $v0, %lo(g_Spu + 0x2CC)($v0)
/* 2FD10 8003F510 04000624 */  addiu      $a2, $zero, 0x4
/* 2FD14 8003F514 3A004490 */  lbu        $a0, 0x3A($v0)
/* 2FD18 8003F518 52FF0008 */  j          .L8003FD48
/* 2FD1C 8003F51C 24020726 */   addiu     $a3, $s0, 0x224
.L8003F520:
/* 2FD20 8003F520 0880023C */  lui        $v0, %hi(g_Spyro + 0x7C)
/* 2FD24 8003F524 D48A4224 */  addiu      $v0, $v0, %lo(g_Spyro + 0x7C)
/* 2FD28 8003F528 78004424 */  addiu      $a0, $v0, 0x78
/* 2FD2C 8003F52C BC5D000C */  jal        VecNull
/* 2FD30 8003F530 000040AC */   sw        $zero, 0x0($v0)
/* 2FD34 8003F534 05000424 */  addiu      $a0, $zero, 0x5
/* 2FD38 8003F538 0A000524 */  addiu      $a1, $zero, 0xA
/* 2FD3C 8003F53C 21300000 */  addu       $a2, $zero, $zero
/* 2FD40 8003F540 0780033C */  lui        $v1, %hi(D_800758E4)
/* 2FD44 8003F544 E458638C */  lw         $v1, %lo(D_800758E4)($v1)
/* 2FD48 8003F548 00FD0224 */  addiu      $v0, $zero, -0x300
/* 2FD4C 8003F54C 0880013C */  lui        $at, %hi(g_Spyro + 0x14C)
/* 2FD50 8003F550 A48B22AC */  sw         $v0, %lo(g_Spyro + 0x14C)($at)
/* 2FD54 8003F554 01000224 */  addiu      $v0, $zero, 0x1
/* 2FD58 8003F558 0880013C */  lui        $at, %hi(g_Spyro + 0x15C)
/* 2FD5C 8003F55C B48B22AC */  sw         $v0, %lo(g_Spyro + 0x15C)($at)
/* 2FD60 8003F560 09F86000 */  jalr       $v1
/* 2FD64 8003F564 21380000 */   addu      $a3, $zero, $zero
/* 2FD68 8003F568 DFFE0008 */  j          .L8003FB7C
/* 2FD6C 8003F56C 00000000 */   nop
.L8003F570:
/* 2FD70 8003F570 0880103C */  lui        $s0, %hi(g_Spyro + 0x78)
/* 2FD74 8003F574 D08A1026 */  addiu      $s0, $s0, %lo(g_Spyro + 0x78)
/* 2FD78 8003F578 0000038E */  lw         $v1, 0x0($s0)
/* 2FD7C 8003F57C 0F000224 */  addiu      $v0, $zero, 0xF
/* 2FD80 8003F580 7C006210 */  beq        $v1, $v0, .L8003F774
/* 2FD84 8003F584 17000224 */   addiu     $v0, $zero, 0x17
/* 2FD88 8003F588 7A006210 */  beq        $v1, $v0, .L8003F774
/* 2FD8C 8003F58C E0FF6224 */   addiu     $v0, $v1, -0x20
/* 2FD90 8003F590 0200422C */  sltiu      $v0, $v0, 0x2
/* 2FD94 8003F594 77004014 */  bnez       $v0, .L8003F774
/* 2FD98 8003F598 22000224 */   addiu     $v0, $zero, 0x22
/* 2FD9C 8003F59C 75006210 */  beq        $v1, $v0, .L8003F774
/* 2FDA0 8003F5A0 01000224 */   addiu     $v0, $zero, 0x1
/* 2FDA4 8003F5A4 0880033C */  lui        $v1, %hi(g_Spyro + 0x114)
/* 2FDA8 8003F5A8 6C8B638C */  lw         $v1, %lo(g_Spyro + 0x114)($v1)
/* 2FDAC 8003F5AC 0880013C */  lui        $at, %hi(g_Spyro + 0x7C)
/* 2FDB0 8003F5B0 D48A20AC */  sw         $zero, %lo(g_Spyro + 0x7C)($at)
/* 2FDB4 8003F5B4 0880013C */  lui        $at, %hi(g_Spyro + 0x150)
/* 2FDB8 8003F5B8 A88B22AC */  sw         $v0, %lo(g_Spyro + 0x150)($at)
/* 2FDBC 8003F5BC 0880013C */  lui        $at, %hi(g_Spyro + 0x148)
/* 2FDC0 8003F5C0 A08B20AC */  sw         $zero, %lo(g_Spyro + 0x148)($at)
/* 2FDC4 8003F5C4 0780013C */  lui        $at, %hi(D_80075960)
/* 2FDC8 8003F5C8 605920AC */  sw         $zero, %lo(D_80075960)($at)
/* 2FDCC 8003F5CC 0780013C */  lui        $at, %hi(D_800758A0)
/* 2FDD0 8003F5D0 A05820AC */  sw         $zero, %lo(D_800758A0)($at)
/* 2FDD4 8003F5D4 0780013C */  lui        $at, %hi(D_80075700)
/* 2FDD8 8003F5D8 005720AC */  sw         $zero, %lo(D_80075700)($at)
/* 2FDDC 8003F5DC 03006018 */  blez       $v1, .L8003F5EC
/* 2FDE0 8003F5E0 7C000426 */   addiu     $a0, $s0, 0x7C
/* 2FDE4 8003F5E4 0880013C */  lui        $at, %hi(g_Spyro + 0x114)
/* 2FDE8 8003F5E8 6C8B20AC */  sw         $zero, %lo(g_Spyro + 0x114)($at)
.L8003F5EC:
/* 2FDEC 8003F5EC 7F5C000C */  jal        VecMagnitude
/* 2FDF0 8003F5F0 21280000 */   addu      $a1, $zero, $zero
/* 2FDF4 8003F5F4 0880013C */  lui        $at, %hi(g_Spyro + 0x118)
/* 2FDF8 8003F5F8 708B22AC */  sw         $v0, %lo(g_Spyro + 0x118)($at)
/* 2FDFC 8003F5FC 01194228 */  slti       $v0, $v0, 0x1901
/* 2FE00 8003F600 03004014 */  bnez       $v0, .L8003F610
/* 2FE04 8003F604 00190224 */   addiu     $v0, $zero, 0x1900
/* 2FE08 8003F608 0880013C */  lui        $at, %hi(g_Spyro + 0x118)
/* 2FE0C 8003F60C 708B22AC */  sw         $v0, %lo(g_Spyro + 0x118)($at)
.L8003F610:
/* 2FE10 8003F610 0880023C */  lui        $v0, %hi(g_Spyro + 0x118)
/* 2FE14 8003F614 708B428C */  lw         $v0, %lo(g_Spyro + 0x118)($v0)
/* 2FE18 8003F618 00000000 */  nop
/* 2FE1C 8003F61C 80074228 */  slti       $v0, $v0, 0x780
/* 2FE20 8003F620 03004010 */  beqz       $v0, .L8003F630
/* 2FE24 8003F624 80070224 */   addiu     $v0, $zero, 0x780
/* 2FE28 8003F628 0880013C */  lui        $at, %hi(g_Spyro + 0x118)
/* 2FE2C 8003F62C 708B22AC */  sw         $v0, %lo(g_Spyro + 0x118)($at)
.L8003F630:
/* 2FE30 8003F630 0000038E */  lw         $v1, 0x0($s0)
/* 2FE34 8003F634 06000224 */  addiu      $v0, $zero, 0x6
/* 2FE38 8003F638 0E006214 */  bne        $v1, $v0, .L8003F674
/* 2FE3C 8003F63C 00000000 */   nop
/* 2FE40 8003F640 0780023C */  lui        $v0, %hi(D_80075690)
/* 2FE44 8003F644 9056428C */  lw         $v0, %lo(D_80075690)($v0)
/* 2FE48 8003F648 00000000 */  nop
/* 2FE4C 8003F64C 09004014 */  bnez       $v0, .L8003F674
/* 2FE50 8003F650 00000000 */   nop
/* 2FE54 8003F654 0880023C */  lui        $v0, %hi(g_Spyro + 0x158)
/* 2FE58 8003F658 B08B428C */  lw         $v0, %lo(g_Spyro + 0x158)($v0)
/* 2FE5C 8003F65C 0880033C */  lui        $v1, %hi(g_Spyro + 0x8)
/* 2FE60 8003F660 608A638C */  lw         $v1, %lo(g_Spyro + 0x8)($v1)
/* 2FE64 8003F664 00000000 */  nop
/* 2FE68 8003F668 2A104300 */  slt        $v0, $v0, $v1
/* 2FE6C 8003F66C 05004010 */  beqz       $v0, .L8003F684
/* 2FE70 8003F670 00000000 */   nop
.L8003F674:
/* 2FE74 8003F674 0880023C */  lui        $v0, %hi(g_Spyro + 0x8)
/* 2FE78 8003F678 608A428C */  lw         $v0, %lo(g_Spyro + 0x8)($v0)
/* 2FE7C 8003F67C 0880013C */  lui        $at, %hi(g_Spyro + 0x158)
/* 2FE80 8003F680 B08B22AC */  sw         $v0, %lo(g_Spyro + 0x158)($at)
.L8003F684:
/* 2FE84 8003F684 0880023C */  lui        $v0, %hi(g_Spyro + 0x120)
/* 2FE88 8003F688 788B428C */  lw         $v0, %lo(g_Spyro + 0x120)($v0)
/* 2FE8C 8003F68C 00000000 */  nop
/* 2FE90 8003F690 01044228 */  slti       $v0, $v0, 0x401
/* 2FE94 8003F694 05004014 */  bnez       $v0, .L8003F6AC
/* 2FE98 8003F698 01000224 */   addiu     $v0, $zero, 0x1
/* 2FE9C 8003F69C 0880013C */  lui        $at, %hi(g_Spyro + 0x254)
/* 2FEA0 8003F6A0 AC8C22AC */  sw         $v0, %lo(g_Spyro + 0x254)($at)
/* 2FEA4 8003F6A4 DBFD0008 */  j          .L8003F76C
/* 2FEA8 8003F6A8 80FF0224 */   addiu     $v0, $zero, -0x80
.L8003F6AC:
/* 2FEAC 8003F6AC 0880013C */  lui        $at, %hi(g_Spyro + 0x254)
/* 2FEB0 8003F6B0 AC8C20AC */  sw         $zero, %lo(g_Spyro + 0x254)($at)
/* 2FEB4 8003F6B4 DBFD0008 */  j          .L8003F76C
/* 2FEB8 8003F6B8 80FF0224 */   addiu     $v0, $zero, -0x80
.L8003F6BC:
/* 2FEBC 8003F6BC 0880053C */  lui        $a1, %hi(g_Spyro + 0x224)
/* 2FEC0 8003F6C0 7C8CA524 */  addiu      $a1, $a1, %lo(g_Spyro + 0x224)
/* 2FEC4 8003F6C4 0000A28C */  lw         $v0, 0x0($a1)
/* 2FEC8 8003F6C8 00000000 */  nop
/* 2FECC 8003F6CC 24004010 */  beqz       $v0, .L8003F760
/* 2FED0 8003F6D0 D0FEA424 */   addiu     $a0, $a1, -0x130
/* 2FED4 8003F6D4 BC5D000C */  jal        VecNull
/* 2FED8 8003F6D8 D0FEA424 */   addiu     $a0, $a1, -0x130
/* 2FEDC 8003F6DC 0880033C */  lui        $v1, %hi(g_Spyro + 0x200)
/* 2FEE0 8003F6E0 588C638C */  lw         $v1, %lo(g_Spyro + 0x200)($v1)
/* 2FEE4 8003F6E4 0880043C */  lui        $a0, %hi(g_Spyro + 0x11C)
/* 2FEE8 8003F6E8 748B848C */  lw         $a0, %lo(g_Spyro + 0x11C)($a0)
/* 2FEEC 8003F6EC 0880023C */  lui        $v0, %hi(g_Spyro + 0x8)
/* 2FEF0 8003F6F0 608A428C */  lw         $v0, %lo(g_Spyro + 0x8)($v0)
/* 2FEF4 8003F6F4 0880013C */  lui        $at, %hi(g_Spyro + 0x158)
/* 2FEF8 8003F6F8 B08B23AC */  sw         $v1, %lo(g_Spyro + 0x158)($at)
/* 2FEFC 8003F6FC 23186200 */  subu       $v1, $v1, $v0
/* 2FF00 8003F700 00F86324 */  addiu      $v1, $v1, -0x800
/* 2FF04 8003F704 C00483AF */  sw         $v1, %gp_rel(D_80075724)($gp)
/* 2FF08 8003F708 801A0300 */  sll        $v1, $v1, 10
/* 2FF0C 8003F70C 831A0300 */  sra        $v1, $v1, 10
/* 2FF10 8003F710 040482AF */  sw         $v0, %gp_rel(D_80075668)($gp)
/* 2FF14 8003F714 0880023C */  lui        $v0, %hi(g_Spyro + 0x224)
/* 2FF18 8003F718 7C8C428C */  lw         $v0, %lo(g_Spyro + 0x224)($v0)
/* 2FF1C 8003F71C 00046324 */  addiu      $v1, $v1, 0x400
/* 2FF20 8003F720 280584AF */  sw         $a0, %gp_rel(D_8007578C)($gp)
/* 2FF24 8003F724 8C0583AF */  sw         $v1, %gp_rel(D_800757F0)($gp)
/* 2FF28 8003F728 46004290 */  lbu        $v0, 0x46($v0)
/* 2FF2C 8003F72C 00000000 */  nop
/* 2FF30 8003F730 00110200 */  sll        $v0, $v0, 4
/* 2FF34 8003F734 23104400 */  subu       $v0, $v0, $a0
/* 2FF38 8003F738 23104300 */  subu       $v0, $v0, $v1
/* 2FF3C 8003F73C FF0F4330 */  andi       $v1, $v0, 0xFFF
/* 2FF40 8003F740 01086228 */  slti       $v0, $v1, 0x801
/* 2FF44 8003F744 8C0583AF */  sw         $v1, %gp_rel(D_800757F0)($gp)
/* 2FF48 8003F748 08004014 */  bnez       $v0, .L8003F76C
/* 2FF4C 8003F74C 80000224 */   addiu     $v0, $zero, 0x80
/* 2FF50 8003F750 00F06224 */  addiu      $v0, $v1, -0x1000
/* 2FF54 8003F754 8C0582AF */  sw         $v0, %gp_rel(D_800757F0)($gp)
/* 2FF58 8003F758 DBFD0008 */  j          .L8003F76C
/* 2FF5C 8003F75C 80000224 */   addiu     $v0, $zero, 0x80
.L8003F760:
/* 2FF60 8003F760 C05D000C */  jal        VecCopy
/* 2FF64 8003F764 E8FEA524 */   addiu     $a1, $a1, -0x118
/* 2FF68 8003F768 80000224 */  addiu      $v0, $zero, 0x80
.L8003F76C:
/* 2FF6C 8003F76C 0880013C */  lui        $at, %hi(g_Spyro + 0x14C)
/* 2FF70 8003F770 A48B22AC */  sw         $v0, %lo(g_Spyro + 0x14C)($at)
.L8003F774:
/* 2FF74 8003F774 0880013C */  lui        $at, %hi(g_Spyro + 0x15C)
/* 2FF78 8003F778 B48B20AC */  sw         $zero, %lo(g_Spyro + 0x15C)($at)
/* 2FF7C 8003F77C 54FF0008 */  j          .L8003FD50
/* 2FF80 8003F780 00000000 */   nop
.L8003F784:
/* 2FF84 8003F784 80101500 */  sll        $v0, $s5, 2
/* 2FF88 8003F788 0880013C */  lui        $at, %hi(g_Spyro + 0x7C)
/* 2FF8C 8003F78C D48A20AC */  sw         $zero, %lo(g_Spyro + 0x7C)($at)
/* 2FF90 8003F790 0780013C */  lui        $at, %hi(spyro_AnimationDetails + 0x02)
/* 2FF94 8003F794 21082200 */  addu       $at, $at, $v0
/* 2FF98 8003F798 A2C42290 */  lbu        $v0, %lo(spyro_AnimationDetails + 0x02)($at)
/* 2FF9C 8003F79C 00F40324 */  addiu      $v1, $zero, -0xC00
/* 2FFA0 8003F7A0 0880013C */  lui        $at, %hi(g_Spyro + 0x14C)
/* 2FFA4 8003F7A4 A48B23AC */  sw         $v1, %lo(g_Spyro + 0x14C)($at)
/* 2FFA8 8003F7A8 00110200 */  sll        $v0, $v0, 4
/* 2FFAC 8003F7AC 0780013C */  lui        $at, %hi(D_80075788)
/* 2FFB0 8003F7B0 885722A4 */  sh         $v0, %lo(D_80075788)($at)
/* 2FFB4 8003F7B4 54FF0008 */  j          .L8003FD50
/* 2FFB8 8003F7B8 00000000 */   nop
.L8003F7BC:
/* 2FFBC 8003F7BC 0880023C */  lui        $v0, %hi(g_Spyro + 0x7C)
/* 2FFC0 8003F7C0 D48A4224 */  addiu      $v0, $v0, %lo(g_Spyro + 0x7C)
/* 2FFC4 8003F7C4 6C004424 */  addiu      $a0, $v0, 0x6C
/* 2FFC8 8003F7C8 90004524 */  addiu      $a1, $v0, 0x90
/* 2FFCC 8003F7CC C05D000C */  jal        VecCopy
/* 2FFD0 8003F7D0 000040AC */   sw        $zero, 0x0($v0)
/* 2FFD4 8003F7D4 0880023C */  lui        $v0, %hi(g_Spyro + 0xF0)
/* 2FFD8 8003F7D8 488B428C */  lw         $v0, %lo(g_Spyro + 0xF0)($v0)
/* 2FFDC 8003F7DC 00000000 */  nop
/* 2FFE0 8003F7E0 03004018 */  blez       $v0, .L8003F7F0
/* 2FFE4 8003F7E4 00FE0224 */   addiu     $v0, $zero, -0x200
/* 2FFE8 8003F7E8 0880013C */  lui        $at, %hi(g_Spyro + 0xF0)
/* 2FFEC 8003F7EC 488B20AC */  sw         $zero, %lo(g_Spyro + 0xF0)($at)
.L8003F7F0:
/* 2FFF0 8003F7F0 0880013C */  lui        $at, %hi(g_Spyro + 0x14C)
/* 2FFF4 8003F7F4 A48B22AC */  sw         $v0, %lo(g_Spyro + 0x14C)($at)
/* 2FFF8 8003F7F8 6BF8000C */  jal        func_8003E1AC
/* 2FFFC 8003F7FC 00000000 */   nop
/* 30000 8003F800 2DF8000C */  jal        ApplySlopeGravity
/* 30004 8003F804 00000000 */   nop
/* 30008 8003F808 DDFD0008 */  j          .L8003F774
/* 3000C 8003F80C 00000000 */   nop
.L8003F810:
/* 30010 8003F810 0880103C */  lui        $s0, %hi(g_Spyro + 0xF4)
/* 30014 8003F814 4C8B1026 */  addiu      $s0, $s0, %lo(g_Spyro + 0xF4)
/* 30018 8003F818 21200002 */  addu       $a0, $s0, $zero
/* 3001C 8003F81C 18001126 */  addiu      $s1, $s0, 0x18
/* 30020 8003F820 C05D000C */  jal        VecCopy
/* 30024 8003F824 21282002 */   addu      $a1, $s1, $zero
/* 30028 8003F828 F4FF1026 */  addiu      $s0, $s0, -0xC
/* 3002C 8003F82C 21200002 */  addu       $a0, $s0, $zero
/* 30030 8003F830 C05D000C */  jal        VecCopy
/* 30034 8003F834 21282002 */   addu      $a1, $s1, $zero
/* 30038 8003F838 0880023C */  lui        $v0, %hi(g_Spyro + 0x250)
/* 3003C 8003F83C A88C428C */  lw         $v0, %lo(g_Spyro + 0x250)($v0)
/* 30040 8003F840 0880013C */  lui        $at, %hi(g_Spyro + 0x148)
/* 30044 8003F844 A08B20AC */  sw         $zero, %lo(g_Spyro + 0x148)($at)
/* 30048 8003F848 1B004010 */  beqz       $v0, .L8003F8B8
/* 3004C 8003F84C 00000000 */   nop
/* 30050 8003F850 0880023C */  lui        $v0, %hi(g_Spyro + 0x7C)
/* 30054 8003F854 D48A428C */  lw         $v0, %lo(g_Spyro + 0x7C)($v0)
/* 30058 8003F858 00000000 */  nop
/* 3005C 8003F85C 80004230 */  andi       $v0, $v0, 0x80
/* 30060 8003F860 0E004014 */  bnez       $v0, .L8003F89C
/* 30064 8003F864 21200002 */   addu      $a0, $s0, $zero
/* 30068 8003F868 0880023C */  lui        $v0, %hi(g_Spyro + 0x8)
/* 3006C 8003F86C 608A428C */  lw         $v0, %lo(g_Spyro + 0x8)($v0)
/* 30070 8003F870 0880013C */  lui        $at, %hi(g_Spyro + 0x158)
/* 30074 8003F874 B08B22AC */  sw         $v0, %lo(g_Spyro + 0x158)($at)
/* 30078 8003F878 7F5C000C */  jal        VecMagnitude
/* 3007C 8003F87C 01000524 */   addiu     $a1, $zero, 0x1
/* 30080 8003F880 21184000 */  addu       $v1, $v0, $zero
/* 30084 8003F884 801F6228 */  slti       $v0, $v1, 0x1F80
/* 30088 8003F888 02004010 */  beqz       $v0, .L8003F894
/* 3008C 8003F88C 00000000 */   nop
/* 30090 8003F890 801F0324 */  addiu      $v1, $zero, 0x1F80
.L8003F894:
/* 30094 8003F894 0880013C */  lui        $at, %hi(g_Spyro + 0xC8)
/* 30098 8003F898 208B23AC */  sw         $v1, %lo(g_Spyro + 0xC8)($at)
.L8003F89C:
/* 3009C 8003F89C 0880033C */  lui        $v1, %hi(g_Spyro + 0x7C)
/* 300A0 8003F8A0 D48A6324 */  addiu      $v1, $v1, %lo(g_Spyro + 0x7C)
/* 300A4 8003F8A4 0000628C */  lw         $v0, 0x0($v1)
/* 300A8 8003F8A8 00000000 */  nop
/* 300AC 8003F8AC 80004234 */  ori        $v0, $v0, 0x80
/* 300B0 8003F8B0 34FE0008 */  j          .L8003F8D0
/* 300B4 8003F8B4 000062AC */   sw        $v0, 0x0($v1)
.L8003F8B8:
/* 300B8 8003F8B8 0880013C */  lui        $at, %hi(g_Spyro + 0x7C)
/* 300BC 8003F8BC D48A20AC */  sw         $zero, %lo(g_Spyro + 0x7C)($at)
/* 300C0 8003F8C0 0880013C */  lui        $at, %hi(g_Spyro + 0xFC)
/* 300C4 8003F8C4 548B20AC */  sw         $zero, %lo(g_Spyro + 0xFC)($at)
/* 300C8 8003F8C8 0880013C */  lui        $at, %hi(g_Spyro + 0xF0)
/* 300CC 8003F8CC 488B20AC */  sw         $zero, %lo(g_Spyro + 0xF0)($at)
.L8003F8D0:
/* 300D0 8003F8D0 C0FD0224 */  addiu      $v0, $zero, -0x240
.L8003F8D4:
/* 300D4 8003F8D4 0880013C */  lui        $at, %hi(g_Spyro + 0x14C)
/* 300D8 8003F8D8 A48B22AC */  sw         $v0, %lo(g_Spyro + 0x14C)($at)
/* 300DC 8003F8DC 0880013C */  lui        $at, %hi(g_Spyro + 0x154)
/* 300E0 8003F8E0 AC8B20AC */  sw         $zero, %lo(g_Spyro + 0x154)($at)
/* 300E4 8003F8E4 DDFD0008 */  j          .L8003F774
/* 300E8 8003F8E8 00000000 */   nop
.L8003F8EC:
/* 300EC 8003F8EC 0880103C */  lui        $s0, %hi(g_Spyro + 0xF4)
/* 300F0 8003F8F0 4C8B1026 */  addiu      $s0, $s0, %lo(g_Spyro + 0xF4)
/* 300F4 8003F8F4 21200002 */  addu       $a0, $s0, $zero
/* 300F8 8003F8F8 18001126 */  addiu      $s1, $s0, 0x18
/* 300FC 8003F8FC C05D000C */  jal        VecCopy
/* 30100 8003F900 21282002 */   addu      $a1, $s1, $zero
/* 30104 8003F904 F4FF0426 */  addiu      $a0, $s0, -0xC
/* 30108 8003F908 C05D000C */  jal        VecCopy
/* 3010C 8003F90C 21282002 */   addu      $a1, $s1, $zero
/* 30110 8003F910 C0000224 */  addiu      $v0, $zero, 0xC0
/* 30114 8003F914 0880013C */  lui        $at, %hi(g_Spyro + 0x148)
/* 30118 8003F918 A08B20AC */  sw         $zero, %lo(g_Spyro + 0x148)($at)
/* 3011C 8003F91C 0880013C */  lui        $at, %hi(g_Spyro + 0x7C)
/* 30120 8003F920 D48A22AC */  sw         $v0, %lo(g_Spyro + 0x7C)($at)
/* 30124 8003F924 0880013C */  lui        $at, %hi(g_Spyro + 0x14C)
/* 30128 8003F928 A48B20AC */  sw         $zero, %lo(g_Spyro + 0x14C)($at)
/* 3012C 8003F92C 0880013C */  lui        $at, %hi(g_Spyro + 0x154)
/* 30130 8003F930 AC8B20AC */  sw         $zero, %lo(g_Spyro + 0x154)($at)
/* 30134 8003F934 54FF0008 */  j          .L8003FD50
/* 30138 8003F938 00000000 */   nop
.L8003F93C:
/* 3013C 8003F93C 0880023C */  lui        $v0, %hi(g_Spyro + 0x7C)
/* 30140 8003F940 D48A4224 */  addiu      $v0, $v0, %lo(g_Spyro + 0x7C)
/* 30144 8003F944 01000624 */  addiu      $a2, $zero, 0x1
/* 30148 8003F948 9000448C */  lw         $a0, 0x90($v0)
/* 3014C 8003F94C 0880053C */  lui        $a1, %hi(g_Spyro + 0x110)
/* 30150 8003F950 688BA58C */  lw         $a1, %lo(g_Spyro + 0x110)($a1)
/* 30154 8003F954 90005024 */  addiu      $s0, $v0, 0x90
/* 30158 8003F958 AD5A000C */  jal        Atan2
/* 3015C 8003F95C 000040AC */   sw        $zero, 0x0($v0)
/* 30160 8003F960 0880033C */  lui        $v1, %hi(g_Spyro + 0x11C)
/* 30164 8003F964 748B638C */  lw         $v1, %lo(g_Spyro + 0x11C)($v1)
/* 30168 8003F968 00000000 */  nop
/* 3016C 8003F96C 23104300 */  subu       $v0, $v0, $v1
/* 30170 8003F970 FF0F4230 */  andi       $v0, $v0, 0xFFF
/* 30174 8003F974 FFFB4224 */  addiu      $v0, $v0, -0x401
/* 30178 8003F978 FF07422C */  sltiu      $v0, $v0, 0x7FF
/* 3017C 8003F97C 05004010 */  beqz       $v0, .L8003F994
/* 30180 8003F980 21200002 */   addu      $a0, $s0, $zero
/* 30184 8003F984 0880013C */  lui        $at, %hi(g_Spyro + 0x118)
/* 30188 8003F988 708B20AC */  sw         $zero, %lo(g_Spyro + 0x118)($at)
/* 3018C 8003F98C 6AFE0008 */  j          .L8003F9A8
/* 30190 8003F990 00F40224 */   addiu     $v0, $zero, -0xC00
.L8003F994:
/* 30194 8003F994 7F5C000C */  jal        VecMagnitude
/* 30198 8003F998 21280000 */   addu      $a1, $zero, $zero
/* 3019C 8003F99C 0880013C */  lui        $at, %hi(g_Spyro + 0x118)
/* 301A0 8003F9A0 708B22AC */  sw         $v0, %lo(g_Spyro + 0x118)($at)
/* 301A4 8003F9A4 00F40224 */  addiu      $v0, $zero, -0xC00
.L8003F9A8:
/* 301A8 8003F9A8 0880013C */  lui        $at, %hi(g_Spyro + 0x14C)
/* 301AC 8003F9AC A48B22AC */  sw         $v0, %lo(g_Spyro + 0x14C)($at)
/* 301B0 8003F9B0 6BF8000C */  jal        func_8003E1AC
/* 301B4 8003F9B4 00000000 */   nop
/* 301B8 8003F9B8 80020224 */  addiu      $v0, $zero, 0x280
/* 301BC 8003F9BC 0880013C */  lui        $at, %hi(g_Spyro + 0x144)
/* 301C0 8003F9C0 9C8B22AC */  sw         $v0, %lo(g_Spyro + 0x144)($at)
/* 301C4 8003F9C4 01000224 */  addiu      $v0, $zero, 0x1
/* 301C8 8003F9C8 0780013C */  lui        $at, %hi(D_800758A0)
/* 301CC 8003F9CC A05820AC */  sw         $zero, %lo(D_800758A0)($at)
/* 301D0 8003F9D0 0880013C */  lui        $at, %hi(g_Spyro + 0x15C)
/* 301D4 8003F9D4 B48B22AC */  sw         $v0, %lo(g_Spyro + 0x15C)($at)
/* 301D8 8003F9D8 54FF0008 */  j          .L8003FD50
/* 301DC 8003F9DC 00000000 */   nop
.L8003F9E0:
/* 301E0 8003F9E0 0880023C */  lui        $v0, %hi(g_Spyro + 0x208)
/* 301E4 8003F9E4 608C428C */  lw         $v0, %lo(g_Spyro + 0x208)($v0)
/* 301E8 8003F9E8 0880033C */  lui        $v1, %hi(g_Spyro + 0x210)
/* 301EC 8003F9EC 688C638C */  lw         $v1, %lo(g_Spyro + 0x210)($v1)
/* 301F0 8003F9F0 80110200 */  sll        $v0, $v0, 6
/* 301F4 8003F9F4 0880013C */  lui        $at, %hi(g_Spyro + 0xF4)
/* 301F8 8003F9F8 4C8B22AC */  sw         $v0, %lo(g_Spyro + 0xF4)($at)
/* 301FC 8003F9FC 0880023C */  lui        $v0, %hi(g_Spyro + 0x20C)
/* 30200 8003FA00 648C428C */  lw         $v0, %lo(g_Spyro + 0x20C)($v0)
/* 30204 8003FA04 0880013C */  lui        $at, %hi(g_Spyro + 0x7C)
/* 30208 8003FA08 D48A20AC */  sw         $zero, %lo(g_Spyro + 0x7C)($at)
/* 3020C 8003FA0C 80110200 */  sll        $v0, $v0, 6
/* 30210 8003FA10 0880013C */  lui        $at, %hi(g_Spyro + 0xF8)
/* 30214 8003FA14 508B22AC */  sw         $v0, %lo(g_Spyro + 0xF8)($at)
/* 30218 8003FA18 03006014 */  bnez       $v1, .L8003FA28
/* 3021C 8003FA1C 80110300 */   sll       $v0, $v1, 6
/* 30220 8003FA20 0880023C */  lui        $v0, %hi(g_Spyro + 0x114)
/* 30224 8003FA24 6C8B428C */  lw         $v0, %lo(g_Spyro + 0x114)($v0)
.L8003FA28:
/* 30228 8003FA28 0880013C */  lui        $at, %hi(g_Spyro + 0xFC)
/* 3022C 8003FA2C 548B22AC */  sw         $v0, %lo(g_Spyro + 0xFC)($at)
/* 30230 8003FA30 0880103C */  lui        $s0, %hi(g_Spyro + 0xF4)
/* 30234 8003FA34 4C8B1026 */  addiu      $s0, $s0, %lo(g_Spyro + 0xF4)
/* 30238 8003FA38 0000048E */  lw         $a0, 0x0($s0)
/* 3023C 8003FA3C 0880053C */  lui        $a1, %hi(g_Spyro + 0xF8)
/* 30240 8003FA40 508BA58C */  lw         $a1, %lo(g_Spyro + 0xF8)($a1)
/* 30244 8003FA44 AD5A000C */  jal        Atan2
/* 30248 8003FA48 01000624 */   addiu     $a2, $zero, 0x1
/* 3024C 8003FA4C 0880033C */  lui        $v1, %hi(g_Spyro + 0x9C)
/* 30250 8003FA50 F48A638C */  lw         $v1, %lo(g_Spyro + 0x9C)($v1)
/* 30254 8003FA54 00FD0224 */  addiu      $v0, $zero, -0x300
/* 30258 8003FA58 0880013C */  lui        $at, %hi(g_Spyro + 0x14C)
/* 3025C 8003FA5C A48B22AC */  sw         $v0, %lo(g_Spyro + 0x14C)($at)
/* 30260 8003FA60 04006014 */  bnez       $v1, .L8003FA74
/* 30264 8003FA64 05000424 */   addiu     $a0, $zero, 0x5
/* 30268 8003FA68 6BF8000C */  jal        func_8003E1AC
/* 3026C 8003FA6C 00000000 */   nop
/* 30270 8003FA70 05000424 */  addiu      $a0, $zero, 0x5
.L8003FA74:
/* 30274 8003FA74 0A000524 */  addiu      $a1, $zero, 0xA
/* 30278 8003FA78 21300000 */  addu       $a2, $zero, $zero
/* 3027C 8003FA7C 0780033C */  lui        $v1, %hi(D_800758E4)
/* 30280 8003FA80 E458638C */  lw         $v1, %lo(D_800758E4)($v1)
/* 30284 8003FA84 01000224 */  addiu      $v0, $zero, 0x1
/* 30288 8003FA88 0880013C */  lui        $at, %hi(g_Spyro + 0x15C)
/* 3028C 8003FA8C B48B22AC */  sw         $v0, %lo(g_Spyro + 0x15C)($at)
/* 30290 8003FA90 09F86000 */  jalr       $v1
/* 30294 8003FA94 21380000 */   addu      $a3, $zero, $zero
/* 30298 8003FA98 0CFF0526 */  addiu      $a1, $s0, -0xF4
/* 3029C 8003FA9C 0780023C */  lui        $v0, %hi(g_Spu + 0x2CC)
/* 302A0 8003FAA0 D461428C */  lw         $v0, %lo(g_Spu + 0x2CC)($v0)
/* 302A4 8003FAA4 00000000 */  nop
/* 302A8 8003FAA8 3B004490 */  lbu        $a0, 0x3B($v0)
/* 302AC 8003FAAC DBFE0008 */  j          .L8003FB6C
/* 302B0 8003FAB0 04000624 */   addiu     $a2, $zero, 0x4
.L8003FAB4:
/* 302B4 8003FAB4 0880103C */  lui        $s0, %hi(g_Spyro + 0x7C)
/* 302B8 8003FAB8 D48A1026 */  addiu      $s0, $s0, %lo(g_Spyro + 0x7C)
/* 302BC 8003FABC 000000AE */  sw         $zero, 0x0($s0)
/* 302C0 8003FAC0 0880033C */  lui        $v1, %hi(g_Spyro + 0x160)
/* 302C4 8003FAC4 B88B638C */  lw         $v1, %lo(g_Spyro + 0x160)($v1)
/* 302C8 8003FAC8 80FF0224 */  addiu      $v0, $zero, -0x80
/* 302CC 8003FACC 0880013C */  lui        $at, %hi(g_Spyro + 0x14C)
/* 302D0 8003FAD0 A48B22AC */  sw         $v0, %lo(g_Spyro + 0x14C)($at)
/* 302D4 8003FAD4 01000224 */  addiu      $v0, $zero, 0x1
/* 302D8 8003FAD8 0880013C */  lui        $at, %hi(g_Spyro + 0x15C)
/* 302DC 8003FADC B48B22AC */  sw         $v0, %lo(g_Spyro + 0x15C)($at)
/* 302E0 8003FAE0 08006014 */  bnez       $v1, .L8003FB04
/* 302E4 8003FAE4 05000424 */   addiu     $a0, $zero, 0x5
/* 302E8 8003FAE8 0A000524 */  addiu      $a1, $zero, 0xA
/* 302EC 8003FAEC 21300000 */  addu       $a2, $zero, $zero
/* 302F0 8003FAF0 0780023C */  lui        $v0, %hi(D_800758E4)
/* 302F4 8003FAF4 E458428C */  lw         $v0, %lo(D_800758E4)($v0)
/* 302F8 8003FAF8 00000000 */  nop
/* 302FC 8003FAFC 09F84000 */  jalr       $v0
/* 30300 8003FB00 21380000 */   addu      $a3, $zero, $zero
.L8003FB04:
/* 30304 8003FB04 0780023C */  lui        $v0, %hi(D_80075728)
/* 30308 8003FB08 2857428C */  lw         $v0, %lo(D_80075728)($v0)
/* 3030C 8003FB0C 00000000 */  nop
/* 30310 8003FB10 80100200 */  sll        $v0, $v0, 2
/* 30314 8003FB14 0780013C */  lui        $at, %hi(D_8006EA34)
/* 30318 8003FB18 21082200 */  addu       $at, $at, $v0
/* 3031C 8003FB1C 34EA248C */  lw         $a0, %lo(D_8006EA34)($at)
/* 30320 8003FB20 0780023C */  lui        $v0, %hi(g_SpawnMoby)
/* 30324 8003FB24 CC58428C */  lw         $v0, %lo(g_SpawnMoby)($v0)
/* 30328 8003FB28 00000000 */  nop
/* 3032C 8003FB2C 09F84000 */  jalr       $v0
/* 30330 8003FB30 21280000 */   addu      $a1, $zero, $zero
/* 30334 8003FB34 84FF1126 */  addiu      $s1, $s0, -0x7C
/* 30338 8003FB38 21282002 */  addu       $a1, $s1, $zero
/* 3033C 8003FB3C 04000624 */  addiu      $a2, $zero, 0x4
/* 30340 8003FB40 0780023C */  lui        $v0, %hi(g_Spu + 0x2CC)
/* 30344 8003FB44 D461428C */  lw         $v0, %lo(g_Spu + 0x2CC)($v0)
/* 30348 8003FB48 24021026 */  addiu      $s0, $s0, 0x224
/* 3034C 8003FB4C 1D004490 */  lbu        $a0, 0x1D($v0)
/* 30350 8003FB50 9E56010C */  jal        PlaySound
/* 30354 8003FB54 21380002 */   addu      $a3, $s0, $zero
/* 30358 8003FB58 21282002 */  addu       $a1, $s1, $zero
/* 3035C 8003FB5C 0780023C */  lui        $v0, %hi(g_Spu + 0x2CC)
/* 30360 8003FB60 D461428C */  lw         $v0, %lo(g_Spu + 0x2CC)($v0)
/* 30364 8003FB64 04000624 */  addiu      $a2, $zero, 0x4
/* 30368 8003FB68 1B004490 */  lbu        $a0, 0x1B($v0)
.L8003FB6C:
/* 3036C 8003FB6C 0880073C */  lui        $a3, %hi(g_Spyro + 0x2A0)
/* 30370 8003FB70 F88CE724 */  addiu      $a3, $a3, %lo(g_Spyro + 0x2A0)
/* 30374 8003FB74 9E56010C */  jal        PlaySound
/* 30378 8003FB78 00000000 */   nop
.L8003FB7C:
/* 3037C 8003FB7C 0780023C */  lui        $v0, %hi(D_80075904)
/* 30380 8003FB80 0459428C */  lw         $v0, %lo(D_80075904)($v0)
/* 30384 8003FB84 00000000 */  nop
/* 30388 8003FB88 0F004228 */  slti       $v0, $v0, 0xF
/* 3038C 8003FB8C 70004010 */  beqz       $v0, .L8003FD50
/* 30390 8003FB90 0F000224 */   addiu     $v0, $zero, 0xF
/* 30394 8003FB94 0780013C */  lui        $at, %hi(D_80075904)
/* 30398 8003FB98 045922AC */  sw         $v0, %lo(D_80075904)($at)
/* 3039C 8003FB9C 54FF0008 */  j          .L8003FD50
/* 303A0 8003FBA0 00000000 */   nop
.L8003FBA4:
/* 303A4 8003FBA4 0880023C */  lui        $v0, %hi(g_Spyro + 0x7C)
/* 303A8 8003FBA8 D48A4224 */  addiu      $v0, $v0, %lo(g_Spyro + 0x7C)
/* 303AC 8003FBAC 6C004424 */  addiu      $a0, $v0, 0x6C
/* 303B0 8003FBB0 90004524 */  addiu      $a1, $v0, 0x90
/* 303B4 8003FBB4 C05D000C */  jal        VecCopy
/* 303B8 8003FBB8 000040AC */   sw        $zero, 0x0($v0)
/* 303BC 8003FBBC 0880033C */  lui        $v1, %hi(g_Spyro + 0x9C)
/* 303C0 8003FBC0 F48A638C */  lw         $v1, %lo(g_Spyro + 0x9C)($v1)
/* 303C4 8003FBC4 00FD0224 */  addiu      $v0, $zero, -0x300
/* 303C8 8003FBC8 0880013C */  lui        $at, %hi(g_Spyro + 0x14C)
/* 303CC 8003FBCC A48B22AC */  sw         $v0, %lo(g_Spyro + 0x14C)($at)
/* 303D0 8003FBD0 04006014 */  bnez       $v1, .L8003FBE4
/* 303D4 8003FBD4 01000224 */   addiu     $v0, $zero, 0x1
.L8003FBD8:
/* 303D8 8003FBD8 6BF8000C */  jal        func_8003E1AC
/* 303DC 8003FBDC 00000000 */   nop
/* 303E0 8003FBE0 01000224 */  addiu      $v0, $zero, 0x1
.L8003FBE4:
/* 303E4 8003FBE4 0880013C */  lui        $at, %hi(g_Spyro + 0x15C)
/* 303E8 8003FBE8 B48B22AC */  sw         $v0, %lo(g_Spyro + 0x15C)($at)
/* 303EC 8003FBEC 54FF0008 */  j          .L8003FD50
/* 303F0 8003FBF0 00000000 */   nop
.L8003FBF4:
/* 303F4 8003FBF4 0880023C */  lui        $v0, %hi(g_Spyro + 0x7C)
/* 303F8 8003FBF8 D48A4224 */  addiu      $v0, $v0, %lo(g_Spyro + 0x7C)
/* 303FC 8003FBFC 6C004424 */  addiu      $a0, $v0, 0x6C
/* 30400 8003FC00 90004524 */  addiu      $a1, $v0, 0x90
/* 30404 8003FC04 C05D000C */  jal        VecCopy
/* 30408 8003FC08 000040AC */   sw        $zero, 0x0($v0)
/* 3040C 8003FC0C 0880033C */  lui        $v1, %hi(g_Spyro + 0x9C)
/* 30410 8003FC10 F48A638C */  lw         $v1, %lo(g_Spyro + 0x9C)($v1)
/* 30414 8003FC14 00FD0224 */  addiu      $v0, $zero, -0x300
/* 30418 8003FC18 0880013C */  lui        $at, %hi(g_Spyro + 0x14C)
/* 3041C 8003FC1C A48B22AC */  sw         $v0, %lo(g_Spyro + 0x14C)($at)
/* 30420 8003FC20 04006014 */  bnez       $v1, .L8003FC34
/* 30424 8003FC24 05000424 */   addiu     $a0, $zero, 0x5
/* 30428 8003FC28 6BF8000C */  jal        func_8003E1AC
/* 3042C 8003FC2C 00000000 */   nop
/* 30430 8003FC30 05000424 */  addiu      $a0, $zero, 0x5
.L8003FC34:
/* 30434 8003FC34 0A000524 */  addiu      $a1, $zero, 0xA
/* 30438 8003FC38 21300000 */  addu       $a2, $zero, $zero
/* 3043C 8003FC3C 0780033C */  lui        $v1, %hi(D_800758E4)
/* 30440 8003FC40 E458638C */  lw         $v1, %lo(D_800758E4)($v1)
/* 30444 8003FC44 01000224 */  addiu      $v0, $zero, 0x1
/* 30448 8003FC48 0880013C */  lui        $at, %hi(g_Spyro + 0x15C)
/* 3044C 8003FC4C B48B22AC */  sw         $v0, %lo(g_Spyro + 0x15C)($at)
/* 30450 8003FC50 09F86000 */  jalr       $v1
/* 30454 8003FC54 21380000 */   addu      $a3, $zero, $zero
/* 30458 8003FC58 54FF0008 */  j          .L8003FD50
/* 3045C 8003FC5C 00000000 */   nop
.L8003FC60:
/* 30460 8003FC60 80FF0224 */  addiu      $v0, $zero, -0x80
.L8003FC64:
/* 30464 8003FC64 0880013C */  lui        $at, %hi(g_Spyro + 0x14C)
/* 30468 8003FC68 A48B22AC */  sw         $v0, %lo(g_Spyro + 0x14C)($at)
.L8003FC6C:
/* 3046C 8003FC6C 01000224 */  addiu      $v0, $zero, 0x1
/* 30470 8003FC70 0880013C */  lui        $at, %hi(g_Spyro + 0x7C)
/* 30474 8003FC74 D48A20AC */  sw         $zero, %lo(g_Spyro + 0x7C)($at)
/* 30478 8003FC78 0880013C */  lui        $at, %hi(g_Spyro + 0x15C)
/* 3047C 8003FC7C B48B22AC */  sw         $v0, %lo(g_Spyro + 0x15C)($at)
/* 30480 8003FC80 54FF0008 */  j          .L8003FD50
/* 30484 8003FC84 00000000 */   nop
.L8003FC88:
/* 30488 8003FC88 0880103C */  lui        $s0, %hi(g_Spyro + 0xE8)
/* 3048C 8003FC8C 408B1026 */  addiu      $s0, $s0, %lo(g_Spyro + 0xE8)
/* 30490 8003FC90 21200002 */  addu       $a0, $s0, $zero
/* 30494 8003FC94 C05D000C */  jal        VecCopy
/* 30498 8003FC98 24000526 */   addiu     $a1, $s0, 0x24
/* 3049C 8003FC9C 0880023C */  lui        $v0, %hi(g_Spyro + 0x7C)
/* 304A0 8003FCA0 D48A428C */  lw         $v0, %lo(g_Spyro + 0x7C)($v0)
/* 304A4 8003FCA4 00000000 */  nop
/* 304A8 8003FCA8 80004230 */  andi       $v0, $v0, 0x80
/* 304AC 8003FCAC 0E004014 */  bnez       $v0, .L8003FCE8
/* 304B0 8003FCB0 21200002 */   addu      $a0, $s0, $zero
/* 304B4 8003FCB4 0880023C */  lui        $v0, %hi(g_Spyro + 0x8)
/* 304B8 8003FCB8 608A428C */  lw         $v0, %lo(g_Spyro + 0x8)($v0)
/* 304BC 8003FCBC 0880013C */  lui        $at, %hi(g_Spyro + 0x158)
/* 304C0 8003FCC0 B08B22AC */  sw         $v0, %lo(g_Spyro + 0x158)($at)
/* 304C4 8003FCC4 7F5C000C */  jal        VecMagnitude
/* 304C8 8003FCC8 01000524 */   addiu     $a1, $zero, 0x1
/* 304CC 8003FCCC 21184000 */  addu       $v1, $v0, $zero
/* 304D0 8003FCD0 801F6228 */  slti       $v0, $v1, 0x1F80
/* 304D4 8003FCD4 02004010 */  beqz       $v0, .L8003FCE0
/* 304D8 8003FCD8 00000000 */   nop
/* 304DC 8003FCDC 801F0324 */  addiu      $v1, $zero, 0x1F80
.L8003FCE0:
/* 304E0 8003FCE0 0880013C */  lui        $at, %hi(g_Spyro + 0xC8)
/* 304E4 8003FCE4 208B23AC */  sw         $v1, %lo(g_Spyro + 0xC8)($at)
.L8003FCE8:
/* 304E8 8003FCE8 0880103C */  lui        $s0, %hi(g_Spyro + 0x7C)
/* 304EC 8003FCEC D48A1026 */  addiu      $s0, $s0, %lo(g_Spyro + 0x7C)
/* 304F0 8003FCF0 C0000224 */  addiu      $v0, $zero, 0xC0
/* 304F4 8003FCF4 000002AE */  sw         $v0, 0x0($s0)
/* 304F8 8003FCF8 C0FD0224 */  addiu      $v0, $zero, -0x240
/* 304FC 8003FCFC 0880013C */  lui        $at, %hi(g_Spyro + 0x148)
/* 30500 8003FD00 A08B20AC */  sw         $zero, %lo(g_Spyro + 0x148)($at)
/* 30504 8003FD04 0880013C */  lui        $at, %hi(g_Spyro + 0x14C)
/* 30508 8003FD08 A48B22AC */  sw         $v0, %lo(g_Spyro + 0x14C)($at)
/* 3050C 8003FD0C 6BF8000C */  jal        func_8003E1AC
/* 30510 8003FD10 00000000 */   nop
/* 30514 8003FD14 2DF8000C */  jal        ApplySlopeGravity
/* 30518 8003FD18 00000000 */   nop
/* 3051C 8003FD1C 84FF0526 */  addiu      $a1, $s0, -0x7C
/* 30520 8003FD20 04000624 */  addiu      $a2, $zero, 0x4
/* 30524 8003FD24 0780033C */  lui        $v1, %hi(g_Spu + 0x2CC)
/* 30528 8003FD28 D461638C */  lw         $v1, %lo(g_Spu + 0x2CC)($v1)
/* 3052C 8003FD2C 01000224 */  addiu      $v0, $zero, 0x1
/* 30530 8003FD30 0880013C */  lui        $at, %hi(g_Spyro + 0x15C)
/* 30534 8003FD34 B48B22AC */  sw         $v0, %lo(g_Spyro + 0x15C)($at)
/* 30538 8003FD38 0780013C */  lui        $at, %hi(D_80075700)
/* 3053C 8003FD3C 005720AC */  sw         $zero, %lo(D_80075700)($at)
/* 30540 8003FD40 05006490 */  lbu        $a0, 0x5($v1)
/* 30544 8003FD44 25020726 */  addiu      $a3, $s0, 0x225
.L8003FD48:
/* 30548 8003FD48 9E56010C */  jal        PlaySound
/* 3054C 8003FD4C 00000000 */   nop
.L8003FD50:
/* 30550 8003FD50 0880023C */  lui        $v0, %hi(g_Spyro + 0x80)
/* 30554 8003FD54 D88A428C */  lw         $v0, %lo(g_Spyro + 0x80)($v0)
/* 30558 8003FD58 0880013C */  lui        $at, %hi(g_Spyro + 0x78)
/* 3055C 8003FD5C D08A35AC */  sw         $s5, %lo(g_Spyro + 0x78)($at)
/* 30560 8003FD60 0880033C */  lui        $v1, %hi(g_Spyro + 0x78)
/* 30564 8003FD64 D08A638C */  lw         $v1, %lo(g_Spyro + 0x78)($v1)
/* 30568 8003FD68 0880013C */  lui        $at, %hi(g_Spyro + 0x80)
/* 3056C 8003FD6C D88A20AC */  sw         $zero, %lo(g_Spyro + 0x80)($at)
/* 30570 8003FD70 0880013C */  lui        $at, %hi(g_Spyro + 0x84)
/* 30574 8003FD74 DC8A22AC */  sw         $v0, %lo(g_Spyro + 0x84)($at)
/* 30578 8003FD78 0780013C */  lui        $at, %hi(spyro_StateDefaultAnimation)
/* 3057C 8003FD7C 21082300 */  addu       $at, $at, $v1
/* 30580 8003FD80 70C42290 */  lbu        $v0, %lo(spyro_StateDefaultAnimation)($at)
/* 30584 8003FD84 00000000 */  nop
/* 30588 8003FD88 80100200 */  sll        $v0, $v0, 2
/* 3058C 8003FD8C 0780013C */  lui        $at, %hi(spyro_AnimationDetails + 0x03)
/* 30590 8003FD90 21082200 */  addu       $at, $at, $v0
/* 30594 8003FD94 A3C42290 */  lbu        $v0, %lo(spyro_AnimationDetails + 0x03)($at)
/* 30598 8003FD98 0880013C */  lui        $at, %hi(g_Spyro + 0x58)
/* 3059C 8003FD9C B08A22AC */  sw         $v0, %lo(g_Spyro + 0x58)($at)
/* 305A0 8003FDA0 4800BF8F */  lw         $ra, 0x48($sp)
/* 305A4 8003FDA4 4400B58F */  lw         $s5, 0x44($sp)
/* 305A8 8003FDA8 4000B48F */  lw         $s4, 0x40($sp)
/* 305AC 8003FDAC 3C00B38F */  lw         $s3, 0x3C($sp)
/* 305B0 8003FDB0 3800B28F */  lw         $s2, 0x38($sp)
/* 305B4 8003FDB4 3400B18F */  lw         $s1, 0x34($sp)
/* 305B8 8003FDB8 3000B08F */  lw         $s0, 0x30($sp)
/* 305BC 8003FDBC 5000BD27 */  addiu      $sp, $sp, 0x50
/* 305C0 8003FDC0 0800E003 */  jr         $ra
/* 305C4 8003FDC4 00000000 */   nop
.size func_8003EA68, . - func_8003EA68
