.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata.jtbl
.align 3
dlabel jtbl_80010E58
/* 1658 80010E58 CCD10380 */ .word .L8003D1CC
/* 165C 80010E5C 00D20380 */ .word .L8003D200
/* 1660 80010E60 00D20380 */ .word .L8003D200
/* 1664 80010E64 7CD20380 */ .word .L8003D27C
/* 1668 80010E68 3CD30380 */ .word .L8003D33C
/* 166C 80010E6C 30D20380 */ .word .L8003D230
/* 1670 80010E70 00D20380 */ .word .L8003D200
/* 1674 80010E74 A4D30380 */ .word .L8003D3A4
/* 1678 80010E78 60D20380 */ .word .L8003D260
/* 167C 80010E7C A4D30380 */ .word .L8003D3A4
/* 1680 80010E80 7CD20380 */ .word .L8003D27C
/* 1684 80010E84 00000000 */ .word 0x00000000
.size jtbl_80010E58, . - jtbl_80010E58


.section .text
/* Generated by spimdisasm 1.27.0 */

glabel func_8003D194
/* 2D994 8003D194 0880033C */  lui        $v1, %hi(g_Spyro + 0x54)
/* 2D998 8003D198 AC8A638C */  lw         $v1, %lo(g_Spyro + 0x54)($v1)
/* 2D99C 8003D19C E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 2D9A0 8003D1A0 1400BFAF */  sw         $ra, 0x14($sp)
/* 2D9A4 8003D1A4 0B00622C */  sltiu      $v0, $v1, 0xB
/* 2D9A8 8003D1A8 7E004010 */  beqz       $v0, .L8003D3A4
/* 2D9AC 8003D1AC 1000B0AF */   sw        $s0, 0x10($sp)
/* 2D9B0 8003D1B0 80100300 */  sll        $v0, $v1, 2
/* 2D9B4 8003D1B4 0180013C */  lui        $at, %hi(jtbl_80010E58)
/* 2D9B8 8003D1B8 21082200 */  addu       $at, $at, $v0
/* 2D9BC 8003D1BC 580E228C */  lw         $v0, %lo(jtbl_80010E58)($at)
/* 2D9C0 8003D1C0 00000000 */  nop
/* 2D9C4 8003D1C4 08004000 */  jr         $v0
/* 2D9C8 8003D1C8 00000000 */   nop
.L8003D1CC:
/* 2D9CC 8003D1CC 0880033C */  lui        $v1, %hi(g_Spyro + 0x78)
/* 2D9D0 8003D1D0 D08A638C */  lw         $v1, %lo(g_Spyro + 0x78)($v1)
/* 2D9D4 8003D1D4 0880023C */  lui        $v0, %hi(g_Spyro + 0x5C)
/* 2D9D8 8003D1D8 B48A428C */  lw         $v0, %lo(g_Spyro + 0x5C)($v0)
/* 2D9DC 8003D1DC 00000000 */  nop
/* 2D9E0 8003D1E0 3A006214 */  bne        $v1, $v0, .L8003D2CC
/* 2D9E4 8003D1E4 00000000 */   nop
/* 2D9E8 8003D1E8 0880043C */  lui        $a0, %hi(g_Spyro + 0x58)
/* 2D9EC 8003D1EC B08A848C */  lw         $a0, %lo(g_Spyro + 0x58)($a0)
/* 2D9F0 8003D1F0 C9F2000C */  jal        func_8003CB24
/* 2D9F4 8003D1F4 00000000 */   nop
/* 2D9F8 8003D1F8 E9F40008 */  j          .L8003D3A4
/* 2D9FC 8003D1FC 00000000 */   nop
.L8003D200:
/* 2DA00 8003D200 0880033C */  lui        $v1, %hi(g_Spyro + 0x24)
/* 2DA04 8003D204 7C8A6324 */  addiu      $v1, $v1, %lo(g_Spyro + 0x24)
/* 2DA08 8003D208 00006290 */  lbu        $v0, 0x0($v1)
/* 2DA0C 8003D20C 00000000 */  nop
/* 2DA10 8003D210 02004224 */  addiu      $v0, $v0, 0x2
/* 2DA14 8003D214 000062A0 */  sb         $v0, 0x0($v1)
/* 2DA18 8003D218 FF004230 */  andi       $v0, $v0, 0xFF
/* 2DA1C 8003D21C 1000422C */  sltiu      $v0, $v0, 0x10
/* 2DA20 8003D220 60004014 */  bnez       $v0, .L8003D3A4
/* 2DA24 8003D224 21200000 */   addu      $a0, $zero, $zero
/* 2DA28 8003D228 99F40008 */  j          .L8003D264
/* 2DA2C 8003D22C 00000000 */   nop
.L8003D230:
/* 2DA30 8003D230 0880033C */  lui        $v1, %hi(g_Spyro + 0x24)
/* 2DA34 8003D234 7C8A6324 */  addiu      $v1, $v1, %lo(g_Spyro + 0x24)
/* 2DA38 8003D238 00006290 */  lbu        $v0, 0x0($v1)
/* 2DA3C 8003D23C 00000000 */  nop
/* 2DA40 8003D240 04004224 */  addiu      $v0, $v0, 0x4
/* 2DA44 8003D244 000062A0 */  sb         $v0, 0x0($v1)
/* 2DA48 8003D248 FF004230 */  andi       $v0, $v0, 0xFF
/* 2DA4C 8003D24C 1000422C */  sltiu      $v0, $v0, 0x10
/* 2DA50 8003D250 54004014 */  bnez       $v0, .L8003D3A4
/* 2DA54 8003D254 21200000 */   addu      $a0, $zero, $zero
/* 2DA58 8003D258 99F40008 */  j          .L8003D264
/* 2DA5C 8003D25C 00000000 */   nop
.L8003D260:
/* 2DA60 8003D260 02000424 */  addiu      $a0, $zero, 0x2
.L8003D264:
/* 2DA64 8003D264 C9F2000C */  jal        func_8003CB24
/* 2DA68 8003D268 00000000 */   nop
.L8003D26C:
/* 2DA6C 8003D26C 0880013C */  lui        $at, %hi(g_Spyro + 0x54)
/* 2DA70 8003D270 AC8A20AC */  sw         $zero, %lo(g_Spyro + 0x54)($at)
/* 2DA74 8003D274 E9F40008 */  j          .L8003D3A4
/* 2DA78 8003D278 00000000 */   nop
.L8003D27C:
/* 2DA7C 8003D27C 0880023C */  lui        $v0, %hi(g_Spyro + 0x5C)
/* 2DA80 8003D280 B48A428C */  lw         $v0, %lo(g_Spyro + 0x5C)($v0)
/* 2DA84 8003D284 0780043C */  lui        $a0, %hi(D_8006BC84)
/* 2DA88 8003D288 84BC8424 */  addiu      $a0, $a0, %lo(D_8006BC84)
/* 2DA8C 8003D28C 40180200 */  sll        $v1, $v0, 1
/* 2DA90 8003D290 21186200 */  addu       $v1, $v1, $v0
/* 2DA94 8003D294 00110300 */  sll        $v0, $v1, 4
/* 2DA98 8003D298 23104300 */  subu       $v0, $v0, $v1
/* 2DA9C 8003D29C 0880033C */  lui        $v1, %hi(g_Spyro + 0x78)
/* 2DAA0 8003D2A0 D08A638C */  lw         $v1, %lo(g_Spyro + 0x78)($v1)
/* 2DAA4 8003D2A4 21104400 */  addu       $v0, $v0, $a0
/* 2DAA8 8003D2A8 21104300 */  addu       $v0, $v0, $v1
/* 2DAAC 8003D2AC 00004390 */  lbu        $v1, 0x0($v0)
/* 2DAB0 8003D2B0 03000224 */  addiu      $v0, $zero, 0x3
/* 2DAB4 8003D2B4 09006210 */  beq        $v1, $v0, .L8003D2DC
/* 2DAB8 8003D2B8 0A000224 */   addiu     $v0, $zero, 0xA
/* 2DABC 8003D2BC 07006210 */  beq        $v1, $v0, .L8003D2DC
/* 2DAC0 8003D2C0 04000224 */   addiu     $v0, $zero, 0x4
/* 2DAC4 8003D2C4 05006210 */  beq        $v1, $v0, .L8003D2DC
/* 2DAC8 8003D2C8 00000000 */   nop
.L8003D2CC:
/* 2DACC 8003D2CC 39F3000C */  jal        func_8003CCE4
/* 2DAD0 8003D2D0 00000000 */   nop
/* 2DAD4 8003D2D4 E9F40008 */  j          .L8003D3A4
/* 2DAD8 8003D2D8 00000000 */   nop
.L8003D2DC:
/* 2DADC 8003D2DC 0880103C */  lui        $s0, %hi(g_Spyro + 0x18)
/* 2DAE0 8003D2E0 708A1026 */  addiu      $s0, $s0, %lo(g_Spyro + 0x18)
/* 2DAE4 8003D2E4 00000292 */  lbu        $v0, 0x0($s0)
/* 2DAE8 8003D2E8 00000000 */  nop
/* 2DAEC 8003D2EC 80100200 */  sll        $v0, $v0, 2
/* 2DAF0 8003D2F0 0780013C */  lui        $at, %hi(spyro_AnimationDetails + 0x03)
/* 2DAF4 8003D2F4 21082200 */  addu       $at, $at, $v0
/* 2DAF8 8003D2F8 A3C42490 */  lbu        $a0, %lo(spyro_AnimationDetails + 0x03)($at)
/* 2DAFC 8003D2FC EEF2000C */  jal        func_8003CBB8
/* 2DB00 8003D300 00000000 */   nop
/* 2DB04 8003D304 27004010 */  beqz       $v0, .L8003D3A4
/* 2DB08 8003D308 1A000224 */   addiu     $v0, $zero, 0x1A
/* 2DB0C 8003D30C 00000392 */  lbu        $v1, 0x0($s0)
/* 2DB10 8003D310 00000000 */  nop
/* 2DB14 8003D314 D5FF6214 */  bne        $v1, $v0, .L8003D26C
/* 2DB18 8003D318 E8FF0526 */   addiu     $a1, $s0, -0x18
/* 2DB1C 8003D31C 0780023C */  lui        $v0, %hi(g_Spu + 0x2CC)
/* 2DB20 8003D320 D461428C */  lw         $v0, %lo(g_Spu + 0x2CC)($v0)
/* 2DB24 8003D324 10000624 */  addiu      $a2, $zero, 0x10
/* 2DB28 8003D328 1B004490 */  lbu        $a0, 0x1B($v0)
/* 2DB2C 8003D32C 9E56010C */  jal        PlaySound
/* 2DB30 8003D330 21380000 */   addu      $a3, $zero, $zero
/* 2DB34 8003D334 9BF40008 */  j          .L8003D26C
/* 2DB38 8003D338 00000000 */   nop
.L8003D33C:
/* 2DB3C 8003D33C 0880043C */  lui        $a0, %hi(g_Spyro + 0x24)
/* 2DB40 8003D340 7C8A8424 */  addiu      $a0, $a0, %lo(g_Spyro + 0x24)
/* 2DB44 8003D344 0880033C */  lui        $v1, %hi(g_Spyro + 0x58)
/* 2DB48 8003D348 B08A638C */  lw         $v1, %lo(g_Spyro + 0x58)($v1)
/* 2DB4C 8003D34C 00008290 */  lbu        $v0, 0x0($a0)
/* 2DB50 8003D350 00000000 */  nop
/* 2DB54 8003D354 21104300 */  addu       $v0, $v0, $v1
/* 2DB58 8003D358 000082A0 */  sb         $v0, 0x0($a0)
/* 2DB5C 8003D35C FF004230 */  andi       $v0, $v0, 0xFF
/* 2DB60 8003D360 1000422C */  sltiu      $v0, $v0, 0x10
/* 2DB64 8003D364 0F004014 */  bnez       $v0, .L8003D3A4
/* 2DB68 8003D368 03000224 */   addiu     $v0, $zero, 0x3
/* 2DB6C 8003D36C 000080A0 */  sb         $zero, 0x0($a0)
/* 2DB70 8003D370 0880033C */  lui        $v1, %hi(g_Spyro + 0x1F)
/* 2DB74 8003D374 778A6390 */  lbu        $v1, %lo(g_Spyro + 0x1F)($v1)
/* 2DB78 8003D378 0880013C */  lui        $at, %hi(g_Spyro + 0x54)
/* 2DB7C 8003D37C AC8A22AC */  sw         $v0, %lo(g_Spyro + 0x54)($at)
/* 2DB80 8003D380 0880023C */  lui        $v0, %hi(g_Spyro + 0x19)
/* 2DB84 8003D384 718A4290 */  lbu        $v0, %lo(g_Spyro + 0x19)($v0)
/* 2DB88 8003D388 01006424 */  addiu      $a0, $v1, 0x1
/* 2DB8C 8003D38C 0880013C */  lui        $at, %hi(g_Spyro + 0x18)
/* 2DB90 8003D390 708A22A0 */  sb         $v0, %lo(g_Spyro + 0x18)($at)
/* 2DB94 8003D394 0880013C */  lui        $at, %hi(g_Spyro + 0x1E)
/* 2DB98 8003D398 768A23A0 */  sb         $v1, %lo(g_Spyro + 0x1E)($at)
/* 2DB9C 8003D39C 0880013C */  lui        $at, %hi(g_Spyro + 0x1F)
/* 2DBA0 8003D3A0 778A24A0 */  sb         $a0, %lo(g_Spyro + 0x1F)($at)
.L8003D3A4:
/* 2DBA4 8003D3A4 1400BF8F */  lw         $ra, 0x14($sp)
/* 2DBA8 8003D3A8 1000B08F */  lw         $s0, 0x10($sp)
/* 2DBAC 8003D3AC 1800BD27 */  addiu      $sp, $sp, 0x18
/* 2DBB0 8003D3B0 0800E003 */  jr         $ra
/* 2DBB4 8003D3B4 00000000 */   nop
.size func_8003D194, . - func_8003D194
