.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata.jtbl
.align 3
dlabel jtbl_credits_8007AA3C
/* 5C97804 8007AA3C 64BC0780 */ .word .L8007BC64_
/* 5C97808 8007AA40 9CBC0780 */ .word .L8007BC9C_
/* 5C9780C 8007AA44 F4BC0780 */ .word .L8007BCF4_
/* 5C97810 8007AA48 C0BD0780 */ .word .L8007BDC0_
/* 5C97814 8007AA4C D0BD0780 */ .word .L8007BDD0_
.size jtbl_credits_8007AA3C, . - jtbl_credits_8007AA3C


.section .text
/* Generated by spimdisasm 1.27.0 */

glabel func_credits_8007AA50
/* 5C97818 8007AA50 78FFBD27 */  addiu      $sp, $sp, -0x88
/* 5C9781C 8007AA54 0780033C */  lui        $v1, %hi(D_80075704)
/* 5C97820 8007AA58 0457638C */  lw         $v1, %lo(D_80075704)($v1)
/* 5C97824 8007AA5C FFFF0224 */  addiu      $v0, $zero, -0x1
/* 5C97828 8007AA60 8400BFAF */  sw         $ra, 0x84($sp)
/* 5C9782C 8007AA64 8000BEAF */  sw         $fp, 0x80($sp)
/* 5C97830 8007AA68 7C00B7AF */  sw         $s7, 0x7C($sp)
/* 5C97834 8007AA6C 7800B6AF */  sw         $s6, 0x78($sp)
/* 5C97838 8007AA70 7400B5AF */  sw         $s5, 0x74($sp)
/* 5C9783C 8007AA74 7000B4AF */  sw         $s4, 0x70($sp)
/* 5C97840 8007AA78 6C00B3AF */  sw         $s3, 0x6C($sp)
/* 5C97844 8007AA7C 6800B2AF */  sw         $s2, 0x68($sp)
/* 5C97848 8007AA80 6400B1AF */  sw         $s1, 0x64($sp)
/* 5C9784C 8007AA84 02016214 */  bne        $v1, $v0, .Lcredits_8007AE90
/* 5C97850 8007AA88 6000B0AF */   sw        $s0, 0x60($sp)
/* 5C97854 8007AA8C 0780023C */  lui        $v0, %hi(D_80075768)
/* 5C97858 8007AA90 6857428C */  lw         $v0, %lo(D_80075768)($v0)
/* 5C9785C 8007AA94 0880053C */  lui        $a1, %hi(func_credits_8007C338)
/* 5C97860 8007AA98 38C3A524 */  addiu      $a1, $a1, %lo(func_credits_8007C338)
/* 5C97864 8007AA9C 1A004014 */  bnez       $v0, .Lcredits_8007AB08
/* 5C97868 8007AAA0 00080624 */   addiu     $a2, $zero, 0x800
/* 5C9786C 8007AAA4 21200000 */  addu       $a0, $zero, $zero
/* 5C97870 8007AAA8 21180000 */  addu       $v1, $zero, $zero
/* 5C97874 8007AAAC 0780013C */  lui        $at, %hi(D_8007589C)
/* 5C97878 8007AAB0 9C5825AC */  sw         $a1, %lo(D_8007589C)($at)
/* 5C9787C 8007AAB4 0780013C */  lui        $at, %hi(D_800756E4)
/* 5C97880 8007AAB8 E45620AC */  sw         $zero, %lo(D_800756E4)($at)
.Lcredits_8007AABC:
/* 5C97884 8007AABC 0780023C */  lui        $v0, %hi(D_8007589C)
/* 5C97888 8007AAC0 9C58428C */  lw         $v0, %lo(D_8007589C)($v0)
/* 5C9788C 8007AAC4 01008424 */  addiu      $a0, $a0, 0x1
/* 5C97890 8007AAC8 21106200 */  addu       $v0, $v1, $v0
/* 5C97894 8007AACC 040040A0 */  sb         $zero, 0x4($v0)
/* 5C97898 8007AAD0 64008228 */  slti       $v0, $a0, 0x64
/* 5C9789C 8007AAD4 F9FF4014 */  bnez       $v0, .Lcredits_8007AABC
/* 5C978A0 8007AAD8 1C006324 */   addiu     $v1, $v1, 0x1C
/* 5C978A4 8007AADC F00AA224 */  addiu      $v0, $a1, 0xAF0
/* 5C978A8 8007AAE0 0780013C */  lui        $at, %hi(D_80075708)
/* 5C978AC 8007AAE4 085722AC */  sw         $v0, %lo(D_80075708)($at)
/* 5C978B0 8007AAE8 0028A224 */  addiu      $v0, $a1, 0x2800
/* 5C978B4 8007AAEC 0780013C */  lui        $at, %hi(D_80075768)
/* 5C978B8 8007AAF0 685722AC */  sw         $v0, %lo(D_80075768)($at)
/* 5C978BC 8007AAF4 0880013C */  lui        $at, %hi(D_800785D8)
/* 5C978C0 8007AAF8 D88522AC */  sw         $v0, %lo(D_800785D8)($at)
/* 5C978C4 8007AAFC 0880013C */  lui        $at, %hi(D_800785DC)
/* 5C978C8 8007AB00 DC8522AC */  sw         $v0, %lo(D_800785DC)($at)
/* 5C978CC 8007AB04 00080624 */  addiu      $a2, $zero, 0x800
.Lcredits_8007AB08:
/* 5C978D0 8007AB08 0780123C */  lui        $s2, %hi(D_80076B90)
/* 5C978D4 8007AB0C 906B5226 */  addiu      $s2, $s2, %lo(D_80076B90)
/* 5C978D8 8007AB10 0880103C */  lui        $s0, %hi(D_800785DC)
/* 5C978DC 8007AB14 DC851026 */  addiu      $s0, $s0, %lo(D_800785DC)
/* 5C978E0 8007AB18 0000448E */  lw         $a0, 0x0($s2)
/* 5C978E4 8007AB1C 0780023C */  lui        $v0, %hi(D_800757AC)
/* 5C978E8 8007AB20 AC57428C */  lw         $v0, %lo(D_800757AC)($v0)
/* 5C978EC 8007AB24 0000058E */  lw         $a1, 0x0($s0)
/* 5C978F0 8007AB28 C0100200 */  sll        $v0, $v0, 3
/* 5C978F4 8007AB2C 0880013C */  lui        $at, %hi(g_WadHeader + 0x290)
/* 5C978F8 8007AB30 21082200 */  addu       $at, $at, $v0
/* 5C978FC 8007AB34 60A9278C */  lw         $a3, %lo(g_WadHeader + 0x290)($at)
/* 5C97900 8007AB38 58021324 */  addiu      $s3, $zero, 0x258
/* 5C97904 8007AB3C 4059000C */  jal        CDLoadSync
/* 5C97908 8007AB40 1000B3AF */   sw        $s3, 0x10($sp)
/* 5C9790C 8007AB44 0780113C */  lui        $s1, %hi(g_LevelHeader)
/* 5C97910 8007AB48 006C3126 */  addiu      $s1, $s1, %lo(g_LevelHeader)
/* 5C97914 8007AB4C 21202002 */  addu       $a0, $s1, $zero
/* 5C97918 8007AB50 0000058E */  lw         $a1, 0x0($s0)
/* 5C9791C 8007AB54 565A000C */  jal        Memcpy
/* 5C97920 8007AB58 D0010624 */   addiu     $a2, $zero, 0x1D0
/* 5C97924 8007AB5C 0000448E */  lw         $a0, 0x0($s2)
/* 5C97928 8007AB60 0780023C */  lui        $v0, %hi(D_800757AC)
/* 5C9792C 8007AB64 AC57428C */  lw         $v0, %lo(D_800757AC)($v0)
/* 5C97930 8007AB68 0000058E */  lw         $a1, 0x0($s0)
/* 5C97934 8007AB6C 0000238E */  lw         $v1, 0x0($s1)
/* 5C97938 8007AB70 C0100200 */  sll        $v0, $v0, 3
/* 5C9793C 8007AB74 0880013C */  lui        $at, %hi(g_WadHeader + 0x290)
/* 5C97940 8007AB78 21082200 */  addu       $at, $at, $v0
/* 5C97944 8007AB7C 60A9278C */  lw         $a3, %lo(g_WadHeader + 0x290)($at)
/* 5C97948 8007AB80 0600063C */  lui        $a2, (0x60000 >> 16)
/* 5C9794C 8007AB84 1000B3AF */  sw         $s3, 0x10($sp)
/* 5C97950 8007AB88 4059000C */  jal        CDLoadSync
/* 5C97954 8007AB8C 21386700 */   addu      $a3, $v1, $a3
/* 5C97958 8007AB90 1800A427 */  addiu      $a0, $sp, 0x18
/* 5C9795C 8007AB94 0000058E */  lw         $a1, 0x0($s0)
/* 5C97960 8007AB98 00020224 */  addiu      $v0, $zero, 0x200
/* 5C97964 8007AB9C 1800A2A7 */  sh         $v0, 0x18($sp)
/* 5C97968 8007ABA0 1C00A2A7 */  sh         $v0, 0x1C($sp)
/* 5C9796C 8007ABA4 80010224 */  addiu      $v0, $zero, 0x180
/* 5C97970 8007ABA8 1A00A0A7 */  sh         $zero, 0x1A($sp)
/* 5C97974 8007ABAC 8A7E010C */  jal        LoadImage
/* 5C97978 8007ABB0 1E00A2A7 */   sh        $v0, 0x1E($sp)
/* 5C9797C 8007ABB4 FAFF073C */  lui        $a3, (0xFFFA0000 >> 16)
/* 5C97980 8007ABB8 0000448E */  lw         $a0, 0x0($s2)
/* 5C97984 8007ABBC 0000058E */  lw         $a1, 0x0($s0)
/* 5C97988 8007ABC0 0780023C */  lui        $v0, %hi(D_800757AC)
/* 5C9798C 8007ABC4 AC57428C */  lw         $v0, %lo(D_800757AC)($v0)
/* 5C97990 8007ABC8 0780063C */  lui        $a2, %hi(g_LevelHeader + 0x4)
/* 5C97994 8007ABCC 046CC68C */  lw         $a2, %lo(g_LevelHeader + 0x4)($a2)
/* 5C97998 8007ABD0 0000238E */  lw         $v1, 0x0($s1)
/* 5C9799C 8007ABD4 C0100200 */  sll        $v0, $v0, 3
/* 5C979A0 8007ABD8 2130C700 */  addu       $a2, $a2, $a3
/* 5C979A4 8007ABDC 0880013C */  lui        $at, %hi(g_WadHeader + 0x290)
/* 5C979A8 8007ABE0 21082200 */  addu       $at, $at, $v0
/* 5C979AC 8007ABE4 60A9228C */  lw         $v0, %lo(g_WadHeader + 0x290)($at)
/* 5C979B0 8007ABE8 0600073C */  lui        $a3, (0x60000 >> 16)
/* 5C979B4 8007ABEC 1000B3AF */  sw         $s3, 0x10($sp)
/* 5C979B8 8007ABF0 21186200 */  addu       $v1, $v1, $v0
/* 5C979BC 8007ABF4 4059000C */  jal        CDLoadSync
/* 5C979C0 8007ABF8 21386700 */   addu      $a3, $v1, $a3
/* 5C979C4 8007ABFC C972010C */  jal        SpuSetTransferStartAddr
/* 5C979C8 8007AC00 10100424 */   addiu     $a0, $zero, 0x1010
/* 5C979CC 8007AC04 0700053C */  lui        $a1, (0x7EFF0 >> 16)
/* 5C979D0 8007AC08 0000048E */  lw         $a0, 0x0($s0)
/* 5C979D4 8007AC0C B172010C */  jal        SpuWrite
/* 5C979D8 8007AC10 F0EFA534 */   ori       $a1, $a1, (0x7EFF0 & 0xFFFF)
.Lcredits_8007AC14:
/* 5C979DC 8007AC14 EC72010C */  jal        SpuIsTransferCompleted
/* 5C979E0 8007AC18 21200000 */   addu      $a0, $zero, $zero
/* 5C979E4 8007AC1C FDFF4010 */  beqz       $v0, .Lcredits_8007AC14
/* 5C979E8 8007AC20 58021224 */   addiu     $s2, $zero, 0x258
/* 5C979EC 8007AC24 0780113C */  lui        $s1, %hi(D_80076B90)
/* 5C979F0 8007AC28 906B3126 */  addiu      $s1, $s1, %lo(D_80076B90)
/* 5C979F4 8007AC2C 0880103C */  lui        $s0, %hi(D_800785DC)
/* 5C979F8 8007AC30 DC851026 */  addiu      $s0, $s0, %lo(D_800785DC)
/* 5C979FC 8007AC34 0000248E */  lw         $a0, 0x0($s1)
/* 5C97A00 8007AC38 0000058E */  lw         $a1, 0x0($s0)
/* 5C97A04 8007AC3C 0780023C */  lui        $v0, %hi(D_800757AC)
/* 5C97A08 8007AC40 AC57428C */  lw         $v0, %lo(D_800757AC)($v0)
/* 5C97A0C 8007AC44 0780063C */  lui        $a2, %hi(g_LevelHeader + 0xC)
/* 5C97A10 8007AC48 0C6CC68C */  lw         $a2, %lo(g_LevelHeader + 0xC)($a2)
/* 5C97A14 8007AC4C 0780033C */  lui        $v1, %hi(g_LevelHeader + 0x8)
/* 5C97A18 8007AC50 086C638C */  lw         $v1, %lo(g_LevelHeader + 0x8)($v1)
/* 5C97A1C 8007AC54 C0100200 */  sll        $v0, $v0, 3
/* 5C97A20 8007AC58 0880013C */  lui        $at, %hi(g_WadHeader + 0x290)
/* 5C97A24 8007AC5C 21082200 */  addu       $at, $at, $v0
/* 5C97A28 8007AC60 60A9278C */  lw         $a3, %lo(g_WadHeader + 0x290)($at)
/* 5C97A2C 8007AC64 1000B2AF */  sw         $s2, 0x10($sp)
/* 5C97A30 8007AC68 4059000C */  jal        CDLoadSync
/* 5C97A34 8007AC6C 21386700 */   addu      $a3, $v1, $a3
/* 5C97A38 8007AC70 0000048E */  lw         $a0, 0x0($s0)
/* 5C97A3C 8007AC74 564B000C */  jal        func_80012D58
/* 5C97A40 8007AC78 01000524 */   addiu     $a1, $zero, 0x1
/* 5C97A44 8007AC7C 0000248E */  lw         $a0, 0x0($s1)
/* 5C97A48 8007AC80 0880013C */  lui        $at, %hi(D_800785E0)
/* 5C97A4C 8007AC84 E08522AC */  sw         $v0, %lo(D_800785E0)($at)
/* 5C97A50 8007AC88 0880023C */  lui        $v0, %hi(D_800785E0)
/* 5C97A54 8007AC8C E085428C */  lw         $v0, %lo(D_800785E0)($v0)
/* 5C97A58 8007AC90 0780033C */  lui        $v1, %hi(g_LevelHeader + 0x18)
/* 5C97A5C 8007AC94 186C638C */  lw         $v1, %lo(g_LevelHeader + 0x18)($v1)
/* 5C97A60 8007AC98 0880013C */  lui        $at, %hi(D_800785E4)
/* 5C97A64 8007AC9C E48522AC */  sw         $v0, %lo(D_800785E4)($at)
/* 5C97A68 8007ACA0 0880053C */  lui        $a1, %hi(D_800785E4)
/* 5C97A6C 8007ACA4 E485A58C */  lw         $a1, %lo(D_800785E4)($a1)
/* 5C97A70 8007ACA8 0780023C */  lui        $v0, %hi(g_LevelHeader + 0x1C)
/* 5C97A74 8007ACAC 1C6C428C */  lw         $v0, %lo(g_LevelHeader + 0x1C)($v0)
/* 5C97A78 8007ACB0 07800A3C */  lui        $t2, %hi(D_80077780)
/* 5C97A7C 8007ACB4 80774A25 */  addiu      $t2, $t2, %lo(D_80077780)
/* 5C97A80 8007ACB8 0880093C */  lui        $t1, %hi(D_80078A40)
/* 5C97A84 8007ACBC 408A2925 */  addiu      $t1, $t1, %lo(D_80078A40)
/* 5C97A88 8007ACC0 0000478D */  lw         $a3, 0x0($t2)
/* 5C97A8C 8007ACC4 0400488D */  lw         $t0, 0x4($t2)
/* 5C97A90 8007ACC8 000027AD */  sw         $a3, 0x0($t1)
/* 5C97A94 8007ACCC 040028AD */  sw         $t0, 0x4($t1)
/* 5C97A98 8007ACD0 0800478D */  lw         $a3, 0x8($t2)
/* 5C97A9C 8007ACD4 0C00488D */  lw         $t0, 0xC($t2)
/* 5C97AA0 8007ACD8 080027AD */  sw         $a3, 0x8($t1)
/* 5C97AA4 8007ACDC 0C0028AD */  sw         $t0, 0xC($t1)
/* 5C97AA8 8007ACE0 1000478D */  lw         $a3, 0x10($t2)
/* 5C97AAC 8007ACE4 00000000 */  nop
/* 5C97AB0 8007ACE8 100027AD */  sw         $a3, 0x10($t1)
/* 5C97AB4 8007ACEC 0880013C */  lui        $at, %hi(D_80078600)
/* 5C97AB8 8007ACF0 008623AC */  sw         $v1, %lo(D_80078600)($at)
/* 5C97ABC 8007ACF4 0880013C */  lui        $at, %hi(D_80078604)
/* 5C97AC0 8007ACF8 048622AC */  sw         $v0, %lo(D_80078604)($at)
/* 5C97AC4 8007ACFC 0780023C */  lui        $v0, %hi(D_800757AC)
/* 5C97AC8 8007AD00 AC57428C */  lw         $v0, %lo(D_800757AC)($v0)
/* 5C97ACC 8007AD04 0880063C */  lui        $a2, %hi(D_80078604)
/* 5C97AD0 8007AD08 0486C68C */  lw         $a2, %lo(D_80078604)($a2)
/* 5C97AD4 8007AD0C C0100200 */  sll        $v0, $v0, 3
/* 5C97AD8 8007AD10 0880013C */  lui        $at, %hi(g_WadHeader + 0x290)
/* 5C97ADC 8007AD14 21082200 */  addu       $at, $at, $v0
/* 5C97AE0 8007AD18 60A9278C */  lw         $a3, %lo(g_WadHeader + 0x290)($at)
/* 5C97AE4 8007AD1C 0780013C */  lui        $at, %hi(D_800758BC)
/* 5C97AE8 8007AD20 BC5820AC */  sw         $zero, %lo(D_800758BC)($at)
/* 5C97AEC 8007AD24 1000B2AF */  sw         $s2, 0x10($sp)
/* 5C97AF0 8007AD28 4059000C */  jal        CDLoadSync
/* 5C97AF4 8007AD2C 21386700 */   addu      $a3, $v1, $a3
/* 5C97AF8 8007AD30 21200000 */  addu       $a0, $zero, $zero
/* 5C97AFC 8007AD34 0880083C */  lui        $t0, %hi(D_800785E4)
/* 5C97B00 8007AD38 E485088D */  lw         $t0, %lo(D_800785E4)($t0)
/* 5C97B04 8007AD3C 0780023C */  lui        $v0, %hi(D_800778F0)
/* 5C97B08 8007AD40 F0784224 */  addiu      $v0, $v0, %lo(D_800778F0)
/* 5C97B0C 8007AD44 0780013C */  lui        $at, %hi(g_Spu + 0x2C8)
/* 5C97B10 8007AD48 D06122AC */  sw         $v0, %lo(g_Spu + 0x2C8)($at)
/* 5C97B14 8007AD4C 0780033C */  lui        $v1, %hi(g_Spu + 0x2C8)
/* 5C97B18 8007AD50 D061638C */  lw         $v1, %lo(g_Spu + 0x2C8)($v1)
/* 5C97B1C 8007AD54 10100224 */  addiu      $v0, $zero, 0x1010
/* 5C97B20 8007AD58 000062AC */  sw         $v0, 0x0($v1)
/* 5C97B24 8007AD5C 0780033C */  lui        $v1, %hi(g_Spu + 0x2C8)
/* 5C97B28 8007AD60 D061638C */  lw         $v1, %lo(g_Spu + 0x2C8)($v1)
/* 5C97B2C 8007AD64 FFFF0224 */  addiu      $v0, $zero, -0x1
/* 5C97B30 8007AD68 040062AC */  sw         $v0, 0x4($v1)
/* 5C97B34 8007AD6C 0780033C */  lui        $v1, %hi(g_Spu + 0x2C8)
/* 5C97B38 8007AD70 D061638C */  lw         $v1, %lo(g_Spu + 0x2C8)($v1)
/* 5C97B3C 8007AD74 50000224 */  addiu      $v0, $zero, 0x50
/* 5C97B40 8007AD78 080062A4 */  sh         $v0, 0x8($v1)
/* 5C97B44 8007AD7C 0780033C */  lui        $v1, %hi(g_Spu + 0x2C8)
/* 5C97B48 8007AD80 D061638C */  lw         $v1, %lo(g_Spu + 0x2C8)($v1)
/* 5C97B4C 8007AD84 59060224 */  addiu      $v0, $zero, 0x659
/* 5C97B50 8007AD88 0A0062A4 */  sh         $v0, 0xA($v1)
/* 5C97B54 8007AD8C 0780023C */  lui        $v0, %hi(g_Spu + 0x2C8)
/* 5C97B58 8007AD90 D061428C */  lw         $v0, %lo(g_Spu + 0x2C8)($v0)
/* 5C97B5C 8007AD94 21280000 */  addu       $a1, $zero, $zero
/* 5C97B60 8007AD98 0C0040A4 */  sh         $zero, 0xC($v0)
/* 5C97B64 8007AD9C 0780023C */  lui        $v0, %hi(g_Spu + 0x2C8)
/* 5C97B68 8007ADA0 D061428C */  lw         $v0, %lo(g_Spu + 0x2C8)($v0)
/* 5C97B6C 8007ADA4 10000624 */  addiu      $a2, $zero, 0x10
/* 5C97B70 8007ADA8 0E0040A4 */  sh         $zero, 0xE($v0)
/* 5C97B74 8007ADAC 0780023C */  lui        $v0, %hi(g_Spu + 0x2C8)
/* 5C97B78 8007ADB0 D061428C */  lw         $v0, %lo(g_Spu + 0x2C8)($v0)
/* 5C97B7C 8007ADB4 0780013C */  lui        $at, %hi(D_800757BC)
/* 5C97B80 8007ADB8 BC5728AC */  sw         $t0, %lo(D_800757BC)($at)
/* 5C97B84 8007ADBC 100040AC */  sw         $zero, 0x10($v0)
/* 5C97B88 8007ADC0 01000224 */  addiu      $v0, $zero, 0x1
/* 5C97B8C 8007ADC4 0780013C */  lui        $at, %hi(g_Spu + 0x2D4)
/* 5C97B90 8007ADC8 DC6122AC */  sw         $v0, %lo(g_Spu + 0x2D4)($at)
/* 5C97B94 8007ADCC FF3F0224 */  addiu      $v0, $zero, 0x3FFF
/* 5C97B98 8007ADD0 0780013C */  lui        $at, %hi(g_Spu + 0x2E0)
/* 5C97B9C 8007ADD4 E86122A4 */  sh         $v0, %lo(g_Spu + 0x2E0)($at)
/* 5C97BA0 8007ADD8 0780013C */  lui        $at, %hi(g_Spu + 0x2E2)
/* 5C97BA4 8007ADDC EA6122A4 */  sh         $v0, %lo(g_Spu + 0x2E2)($at)
/* 5C97BA8 8007ADE0 9E56010C */  jal        PlaySound
/* 5C97BAC 8007ADE4 21380000 */   addu      $a3, $zero, $zero
/* 5C97BB0 8007ADE8 0780033C */  lui        $v1, %hi(D_800757BC)
/* 5C97BB4 8007ADEC BC57638C */  lw         $v1, %lo(D_800757BC)($v1)
/* 5C97BB8 8007ADF0 0880023C */  lui        $v0, %hi(D_800785E4)
/* 5C97BBC 8007ADF4 E485428C */  lw         $v0, %lo(D_800785E4)($v0)
/* 5C97BC0 8007ADF8 0400638C */  lw         $v1, 0x4($v1)
/* 5C97BC4 8007ADFC 0780043C */  lui        $a0, %hi(D_80075708)
/* 5C97BC8 8007AE00 0857848C */  lw         $a0, %lo(D_80075708)($a0)
/* 5C97BCC 8007AE04 21104300 */  addu       $v0, $v0, $v1
/* 5C97BD0 8007AE08 0C004524 */  addiu      $a1, $v0, 0xC
/* 5C97BD4 8007AE0C 0780013C */  lui        $at, %hi(D_800757EC)
/* 5C97BD8 8007AE10 EC5722AC */  sw         $v0, %lo(D_800757EC)($at)
/* 5C97BDC 8007AE14 0000468C */  lw         $a2, 0x0($v0)
/* 5C97BE0 8007AE18 0400438C */  lw         $v1, 0x4($v0)
/* 5C97BE4 8007AE1C 0800428C */  lw         $v0, 0x8($v0)
/* 5C97BE8 8007AE20 F4FFC624 */  addiu      $a2, $a2, -0xC
/* 5C97BEC 8007AE24 0780013C */  lui        $at, %hi(D_800757DC)
/* 5C97BF0 8007AE28 DC5722AC */  sw         $v0, %lo(D_800757DC)($at)
/* 5C97BF4 8007AE2C 21108300 */  addu       $v0, $a0, $v1
/* 5C97BF8 8007AE30 565A000C */  jal        Memcpy
/* 5C97BFC 8007AE34 F4FF5024 */   addiu     $s0, $v0, -0xC
/* 5C97C00 8007AE38 0780053C */  lui        $a1, %hi(D_800757DC)
/* 5C97C04 8007AE3C DC57A58C */  lw         $a1, %lo(D_800757DC)($a1)
/* 5C97C08 8007AE40 00000000 */  nop
/* 5C97C0C 8007AE44 0B00A018 */  blez       $a1, .Lcredits_8007AE74
/* 5C97C10 8007AE48 21200000 */   addu      $a0, $zero, $zero
/* 5C97C14 8007AE4C 0780033C */  lui        $v1, %hi(D_80075708)
/* 5C97C18 8007AE50 0857638C */  lw         $v1, %lo(D_80075708)($v1)
.Lcredits_8007AE54:
/* 5C97C1C 8007AE54 00000000 */  nop
/* 5C97C20 8007AE58 0000628C */  lw         $v0, 0x0($v1)
/* 5C97C24 8007AE5C 01008424 */  addiu      $a0, $a0, 0x1
/* 5C97C28 8007AE60 21100202 */  addu       $v0, $s0, $v0
/* 5C97C2C 8007AE64 000062AC */  sw         $v0, 0x0($v1)
/* 5C97C30 8007AE68 2A108500 */  slt        $v0, $a0, $a1
/* 5C97C34 8007AE6C F9FF4014 */  bnez       $v0, .Lcredits_8007AE54
/* 5C97C38 8007AE70 0C006324 */   addiu     $v1, $v1, 0xC
.Lcredits_8007AE74:
/* 5C97C3C 8007AE74 0780023C */  lui        $v0, %hi(D_800757AC)
/* 5C97C40 8007AE78 AC57428C */  lw         $v0, %lo(D_800757AC)($v0)
/* 5C97C44 8007AE7C 0780013C */  lui        $at, %hi(D_80075704)
/* 5C97C48 8007AE80 045720AC */  sw         $zero, %lo(D_80075704)($at)
/* 5C97C4C 8007AE84 01004224 */  addiu      $v0, $v0, 0x1
/* 5C97C50 8007AE88 0780013C */  lui        $at, %hi(D_800757AC)
/* 5C97C54 8007AE8C AC5722AC */  sw         $v0, %lo(D_800757AC)($at)
.Lcredits_8007AE90:
/* 5C97C58 8007AE90 0780053C */  lui        $a1, %hi(D_800757BC)
/* 5C97C5C 8007AE94 BC57A58C */  lw         $a1, %lo(D_800757BC)($a1)
/* 5C97C60 8007AE98 00000000 */  nop
/* 5C97C64 8007AE9C 7200A010 */  beqz       $a1, .Lcredits_8007B068
/* 5C97C68 8007AEA0 00000000 */   nop
/* 5C97C6C 8007AEA4 0780063C */  lui        $a2, %hi(D_80075704)
/* 5C97C70 8007AEA8 0457C68C */  lw         $a2, %lo(D_80075704)($a2)
/* 5C97C74 8007AEAC 00000000 */  nop
/* 5C97C78 8007AEB0 6D00C004 */  bltz       $a2, .Lcredits_8007B068
/* 5C97C7C 8007AEB4 00000000 */   nop
/* 5C97C80 8007AEB8 0000A38C */  lw         $v1, 0x0($a1)
/* 5C97C84 8007AEBC 0780023C */  lui        $v0, %hi(g_DeltaTime)
/* 5C97C88 8007AEC0 CC56428C */  lw         $v0, %lo(g_DeltaTime)($v0)
/* 5C97C8C 8007AEC4 0800A48C */  lw         $a0, 0x8($a1)
/* 5C97C90 8007AEC8 21186200 */  addu       $v1, $v1, $v0
/* 5C97C94 8007AECC 40200400 */  sll        $a0, $a0, 1
/* 5C97C98 8007AED0 2A106400 */  slt        $v0, $v1, $a0
/* 5C97C9C 8007AED4 61004010 */  beqz       $v0, .Lcredits_8007B05C
/* 5C97CA0 8007AED8 0000A3AC */   sw        $v1, 0x0($a1)
/* 5C97CA4 8007AEDC 20006228 */  slti       $v0, $v1, 0x20
/* 5C97CA8 8007AEE0 05004014 */  bnez       $v0, .Lcredits_8007AEF8
/* 5C97CAC 8007AEE4 00000000 */   nop
/* 5C97CB0 8007AEE8 23188300 */  subu       $v1, $a0, $v1
/* 5C97CB4 8007AEEC 20006228 */  slti       $v0, $v1, 0x20
/* 5C97CB8 8007AEF0 08004010 */  beqz       $v0, .Lcredits_8007AF14
/* 5C97CBC 8007AEF4 00000000 */   nop
.Lcredits_8007AEF8:
/* 5C97CC0 8007AEF8 43180300 */  sra        $v1, $v1, 1
/* 5C97CC4 8007AEFC 10000224 */  addiu      $v0, $zero, 0x10
/* 5C97CC8 8007AF00 23104300 */  subu       $v0, $v0, $v1
/* 5C97CCC 8007AF04 0780013C */  lui        $at, %hi(D_80075918)
/* 5C97CD0 8007AF08 185922AC */  sw         $v0, %lo(D_80075918)($at)
/* 5C97CD4 8007AF0C C7EB0108 */  j          .Lcredits_8007AF1C
/* 5C97CD8 8007AF10 00000000 */   nop
.Lcredits_8007AF14:
/* 5C97CDC 8007AF14 0780013C */  lui        $at, %hi(D_80075918)
/* 5C97CE0 8007AF18 185920AC */  sw         $zero, %lo(D_80075918)($at)
.Lcredits_8007AF1C:
/* 5C97CE4 8007AF1C 0780023C */  lui        $v0, %hi(D_80075918)
/* 5C97CE8 8007AF20 1859428C */  lw         $v0, %lo(D_80075918)($v0)
/* 5C97CEC 8007AF24 00000000 */  nop
/* 5C97CF0 8007AF28 10004228 */  slti       $v0, $v0, 0x10
/* 5C97CF4 8007AF2C 03004014 */  bnez       $v0, .Lcredits_8007AF3C
/* 5C97CF8 8007AF30 0F000224 */   addiu     $v0, $zero, 0xF
/* 5C97CFC 8007AF34 0780013C */  lui        $at, %hi(D_80075918)
/* 5C97D00 8007AF38 185922AC */  sw         $v0, %lo(D_80075918)($at)
.Lcredits_8007AF3C:
/* 5C97D04 8007AF3C 0780023C */  lui        $v0, %hi(D_80075918)
/* 5C97D08 8007AF40 1859428C */  lw         $v0, %lo(D_80075918)($v0)
/* 5C97D0C 8007AF44 00000000 */  nop
/* 5C97D10 8007AF48 03004104 */  bgez       $v0, .Lcredits_8007AF58
/* 5C97D14 8007AF4C 00000000 */   nop
/* 5C97D18 8007AF50 0780013C */  lui        $at, %hi(D_80075918)
/* 5C97D1C 8007AF54 185920AC */  sw         $zero, %lo(D_80075918)($at)
.Lcredits_8007AF58:
/* 5C97D20 8007AF58 0780043C */  lui        $a0, %hi(D_800757BC)
/* 5C97D24 8007AF5C BC57848C */  lw         $a0, %lo(D_800757BC)($a0)
/* 5C97D28 8007AF60 00000000 */  nop
/* 5C97D2C 8007AF64 0000838C */  lw         $v1, 0x0($a0)
/* 5C97D30 8007AF68 00000000 */  nop
/* 5C97D34 8007AF6C 43180300 */  sra        $v1, $v1, 1
/* 5C97D38 8007AF70 40100300 */  sll        $v0, $v1, 1
/* 5C97D3C 8007AF74 21104300 */  addu       $v0, $v0, $v1
/* 5C97D40 8007AF78 C0100200 */  sll        $v0, $v0, 3
/* 5C97D44 8007AF7C 21104400 */  addu       $v0, $v0, $a0
/* 5C97D48 8007AF80 0C00428C */  lw         $v0, 0xC($v0)
/* 5C97D4C 8007AF84 0780013C */  lui        $at, %hi(g_Camera + 0x28)
/* 5C97D50 8007AF88 F86D22AC */  sw         $v0, %lo(g_Camera + 0x28)($at)
/* 5C97D54 8007AF8C 0000838C */  lw         $v1, 0x0($a0)
/* 5C97D58 8007AF90 00000000 */  nop
/* 5C97D5C 8007AF94 43180300 */  sra        $v1, $v1, 1
/* 5C97D60 8007AF98 40100300 */  sll        $v0, $v1, 1
/* 5C97D64 8007AF9C 21104300 */  addu       $v0, $v0, $v1
/* 5C97D68 8007AFA0 C0100200 */  sll        $v0, $v0, 3
/* 5C97D6C 8007AFA4 21108200 */  addu       $v0, $a0, $v0
/* 5C97D70 8007AFA8 1000428C */  lw         $v0, 0x10($v0)
/* 5C97D74 8007AFAC 0780013C */  lui        $at, %hi(g_Camera + 0x2C)
/* 5C97D78 8007AFB0 FC6D22AC */  sw         $v0, %lo(g_Camera + 0x2C)($at)
/* 5C97D7C 8007AFB4 0000838C */  lw         $v1, 0x0($a0)
/* 5C97D80 8007AFB8 00000000 */  nop
/* 5C97D84 8007AFBC 43180300 */  sra        $v1, $v1, 1
/* 5C97D88 8007AFC0 40100300 */  sll        $v0, $v1, 1
/* 5C97D8C 8007AFC4 21104300 */  addu       $v0, $v0, $v1
/* 5C97D90 8007AFC8 C0100200 */  sll        $v0, $v0, 3
/* 5C97D94 8007AFCC 21108200 */  addu       $v0, $a0, $v0
/* 5C97D98 8007AFD0 1400428C */  lw         $v0, 0x14($v0)
/* 5C97D9C 8007AFD4 0780013C */  lui        $at, %hi(g_Camera + 0x30)
/* 5C97DA0 8007AFD8 006E22AC */  sw         $v0, %lo(g_Camera + 0x30)($at)
/* 5C97DA4 8007AFDC 0000838C */  lw         $v1, 0x0($a0)
/* 5C97DA8 8007AFE0 00000000 */  nop
/* 5C97DAC 8007AFE4 43180300 */  sra        $v1, $v1, 1
/* 5C97DB0 8007AFE8 40100300 */  sll        $v0, $v1, 1
/* 5C97DB4 8007AFEC 21104300 */  addu       $v0, $v0, $v1
/* 5C97DB8 8007AFF0 C0100200 */  sll        $v0, $v0, 3
/* 5C97DBC 8007AFF4 21108200 */  addu       $v0, $a0, $v0
/* 5C97DC0 8007AFF8 1800428C */  lw         $v0, 0x18($v0)
/* 5C97DC4 8007AFFC 0780013C */  lui        $at, %hi(g_Camera + 0x4C)
/* 5C97DC8 8007B000 1C6E22A4 */  sh         $v0, %lo(g_Camera + 0x4C)($at)
/* 5C97DCC 8007B004 0000838C */  lw         $v1, 0x0($a0)
/* 5C97DD0 8007B008 00000000 */  nop
/* 5C97DD4 8007B00C 43180300 */  sra        $v1, $v1, 1
/* 5C97DD8 8007B010 40100300 */  sll        $v0, $v1, 1
/* 5C97DDC 8007B014 21104300 */  addu       $v0, $v0, $v1
/* 5C97DE0 8007B018 C0100200 */  sll        $v0, $v0, 3
/* 5C97DE4 8007B01C 21108200 */  addu       $v0, $a0, $v0
/* 5C97DE8 8007B020 1C00428C */  lw         $v0, 0x1C($v0)
/* 5C97DEC 8007B024 0780013C */  lui        $at, %hi(g_Camera + 0x4E)
/* 5C97DF0 8007B028 1E6E22A4 */  sh         $v0, %lo(g_Camera + 0x4E)($at)
/* 5C97DF4 8007B02C 0000838C */  lw         $v1, 0x0($a0)
/* 5C97DF8 8007B030 00000000 */  nop
/* 5C97DFC 8007B034 43180300 */  sra        $v1, $v1, 1
/* 5C97E00 8007B038 40100300 */  sll        $v0, $v1, 1
/* 5C97E04 8007B03C 21104300 */  addu       $v0, $v0, $v1
/* 5C97E08 8007B040 C0100200 */  sll        $v0, $v0, 3
/* 5C97E0C 8007B044 21208200 */  addu       $a0, $a0, $v0
/* 5C97E10 8007B048 2000828C */  lw         $v0, 0x20($a0)
/* 5C97E14 8007B04C 0780013C */  lui        $at, %hi(g_Camera + 0x50)
/* 5C97E18 8007B050 206E22A4 */  sh         $v0, %lo(g_Camera + 0x50)($at)
/* 5C97E1C 8007B054 1AEC0108 */  j          .Lcredits_8007B068
/* 5C97E20 8007B058 00000000 */   nop
.Lcredits_8007B05C:
/* 5C97E24 8007B05C 0100C224 */  addiu      $v0, $a2, 0x1
/* 5C97E28 8007B060 0780013C */  lui        $at, %hi(D_80075704)
/* 5C97E2C 8007B064 045722AC */  sw         $v0, %lo(D_80075704)($at)
.Lcredits_8007B068:
/* 5C97E30 8007B068 0780023C */  lui        $v0, %hi(D_800756E4)
/* 5C97E34 8007B06C E456428C */  lw         $v0, %lo(D_800756E4)($v0)
/* 5C97E38 8007B070 00000000 */  nop
/* 5C97E3C 8007B074 2F004014 */  bnez       $v0, .Lcredits_8007B134
/* 5C97E40 8007B078 00000000 */   nop
/* 5C97E44 8007B07C 0780023C */  lui        $v0, %hi(D_80075968)
/* 5C97E48 8007B080 6859428C */  lw         $v0, %lo(D_80075968)($v0)
/* 5C97E4C 8007B084 0780033C */  lui        $v1, %hi(D_800757DC)
/* 5C97E50 8007B088 DC57638C */  lw         $v1, %lo(D_800757DC)($v1)
/* 5C97E54 8007B08C 00000000 */  nop
/* 5C97E58 8007B090 2A104300 */  slt        $v0, $v0, $v1
/* 5C97E5C 8007B094 25004014 */  bnez       $v0, .Lcredits_8007B12C
/* 5C97E60 8007B098 00000000 */   nop
/* 5C97E64 8007B09C 0780033C */  lui        $v1, %hi(g_Spu + 0x2C8)
/* 5C97E68 8007B0A0 D061638C */  lw         $v1, %lo(g_Spu + 0x2C8)($v1)
/* 5C97E6C 8007B0A4 00000000 */  nop
/* 5C97E70 8007B0A8 08006294 */  lhu        $v0, 0x8($v1)
/* 5C97E74 8007B0AC 00000000 */  nop
/* 5C97E78 8007B0B0 F6FF4224 */  addiu      $v0, $v0, -0xA
/* 5C97E7C 8007B0B4 080062A4 */  sh         $v0, 0x8($v1)
/* 5C97E80 8007B0B8 0780023C */  lui        $v0, %hi(D_800756F8)
/* 5C97E84 8007B0BC F856428C */  lw         $v0, %lo(D_800756F8)($v0)
/* 5C97E88 8007B0C0 0780053C */  lui        $a1, %hi(g_Spu + 0x2C8)
/* 5C97E8C 8007B0C4 D061A58C */  lw         $a1, %lo(g_Spu + 0x2C8)($a1)
/* 5C97E90 8007B0C8 0780033C */  lui        $v1, %hi(g_DeltaTime)
/* 5C97E94 8007B0CC CC56638C */  lw         $v1, %lo(g_DeltaTime)($v1)
/* 5C97E98 8007B0D0 0800A484 */  lh         $a0, 0x8($a1)
/* 5C97E9C 8007B0D4 21104300 */  addu       $v0, $v0, $v1
/* 5C97EA0 8007B0D8 0780013C */  lui        $at, %hi(D_800756F8)
/* 5C97EA4 8007B0DC F85622AC */  sw         $v0, %lo(D_800756F8)($at)
/* 5C97EA8 8007B0E0 02008104 */  bgez       $a0, .Lcredits_8007B0EC
/* 5C97EAC 8007B0E4 00000000 */   nop
/* 5C97EB0 8007B0E8 0800A0A4 */  sh         $zero, 0x8($a1)
.Lcredits_8007B0EC:
/* 5C97EB4 8007B0EC 0780023C */  lui        $v0, %hi(D_800756F8)
/* 5C97EB8 8007B0F0 F856428C */  lw         $v0, %lo(D_800756F8)($v0)
/* 5C97EBC 8007B0F4 0780013C */  lui        $at, %hi(D_80075918)
/* 5C97EC0 8007B0F8 185922AC */  sw         $v0, %lo(D_80075918)($at)
/* 5C97EC4 8007B0FC 10004228 */  slti       $v0, $v0, 0x10
/* 5C97EC8 8007B100 03004014 */  bnez       $v0, .Lcredits_8007B110
/* 5C97ECC 8007B104 0F000224 */   addiu     $v0, $zero, 0xF
/* 5C97ED0 8007B108 0780013C */  lui        $at, %hi(D_80075918)
/* 5C97ED4 8007B10C 185922AC */  sw         $v0, %lo(D_80075918)($at)
.Lcredits_8007B110:
/* 5C97ED8 8007B110 0780033C */  lui        $v1, %hi(D_80075918)
/* 5C97EDC 8007B114 1859638C */  lw         $v1, %lo(D_80075918)($v1)
/* 5C97EE0 8007B118 0F000224 */  addiu      $v0, $zero, 0xF
/* 5C97EE4 8007B11C 03006214 */  bne        $v1, $v0, .Lcredits_8007B12C
/* 5C97EE8 8007B120 63000224 */   addiu     $v0, $zero, 0x63
/* 5C97EEC 8007B124 0780013C */  lui        $at, %hi(D_80075704)
/* 5C97EF0 8007B128 045722AC */  sw         $v0, %lo(D_80075704)($at)
.Lcredits_8007B12C:
/* 5C97EF4 8007B12C 0780023C */  lui        $v0, %hi(D_800756E4)
/* 5C97EF8 8007B130 E456428C */  lw         $v0, %lo(D_800756E4)($v0)
.Lcredits_8007B134:
/* 5C97EFC 8007B134 00000000 */  nop
/* 5C97F00 8007B138 0C00401C */  bgtz       $v0, .Lcredits_8007B16C
/* 5C97F04 8007B13C 00000000 */   nop
/* 5C97F08 8007B140 0780033C */  lui        $v1, %hi(D_800757DC)
/* 5C97F0C 8007B144 DC57638C */  lw         $v1, %lo(D_800757DC)($v1)
/* 5C97F10 8007B148 00000000 */  nop
/* 5C97F14 8007B14C A5026018 */  blez       $v1, .Lcredits_8007BBE4
/* 5C97F18 8007B150 00000000 */   nop
/* 5C97F1C 8007B154 0780023C */  lui        $v0, %hi(D_80075968)
/* 5C97F20 8007B158 6859428C */  lw         $v0, %lo(D_80075968)($v0)
/* 5C97F24 8007B15C 00000000 */  nop
/* 5C97F28 8007B160 2A104300 */  slt        $v0, $v0, $v1
/* 5C97F2C 8007B164 9F024010 */  beqz       $v0, .Lcredits_8007BBE4
/* 5C97F30 8007B168 00000000 */   nop
.Lcredits_8007B16C:
/* 5C97F34 8007B16C 07801E3C */  lui        $fp, %hi(D_80075878)
/* 5C97F38 8007B170 7858DE8F */  lw         $fp, %lo(D_80075878)($fp)
/* 5C97F3C 8007B174 3063010C */  jal        SpecularUpdate
/* 5C97F40 8007B178 03000424 */   addiu     $a0, $zero, 0x3
/* 5C97F44 8007B17C 0780153C */  lui        $s5, %hi(D_80075968)
/* 5C97F48 8007B180 6859B58E */  lw         $s5, %lo(D_80075968)($s5)
/* 5C97F4C 8007B184 00000000 */  nop
/* 5C97F50 8007B188 2A10D503 */  slt        $v0, $fp, $s5
/* 5C97F54 8007B18C A6014014 */  bnez       $v0, .Lcredits_8007B828
/* 5C97F58 8007B190 01001424 */   addiu     $s4, $zero, 0x1
/* 5C97F5C 8007B194 40101500 */  sll        $v0, $s5, 1
/* 5C97F60 8007B198 21105500 */  addu       $v0, $v0, $s5
/* 5C97F64 8007B19C 80B80200 */  sll        $s7, $v0, 2
.Lcredits_8007B1A0:
/* 5C97F68 8007B1A0 FFFF1324 */  addiu      $s3, $zero, -0x1
/* 5C97F6C 8007B1A4 0780043C */  lui        $a0, %hi(D_80075708)
/* 5C97F70 8007B1A8 0857848C */  lw         $a0, %lo(D_80075708)($a0)
/* 5C97F74 8007B1AC 02000524 */  addiu      $a1, $zero, 0x2
/* 5C97F78 8007B1B0 21209700 */  addu       $a0, $a0, $s7
/* 5C97F7C 8007B1B4 E4DF000C */  jal        func_80037F90
/* 5C97F80 8007B1B8 06008424 */   addiu     $a0, $a0, 0x6
/* 5C97F84 8007B1BC 10004010 */  beqz       $v0, .Lcredits_8007B200
/* 5C97F88 8007B1C0 00000000 */   nop
/* 5C97F8C 8007B1C4 0780023C */  lui        $v0, %hi(D_80075708)
/* 5C97F90 8007B1C8 0857428C */  lw         $v0, %lo(D_80075708)($v0)
/* 5C97F94 8007B1CC 00000000 */  nop
/* 5C97F98 8007B1D0 2110E202 */  addu       $v0, $s7, $v0
/* 5C97F9C 8007B1D4 08004484 */  lh         $a0, 0x8($v0)
/* 5C97FA0 8007B1D8 02000324 */  addiu      $v1, $zero, 0x2
/* 5C97FA4 8007B1DC 08008014 */  bnez       $a0, .Lcredits_8007B200
/* 5C97FA8 8007B1E0 0A0043A4 */   sh        $v1, 0xA($v0)
/* 5C97FAC 8007B1E4 0780023C */  lui        $v0, %hi(D_80075968)
/* 5C97FB0 8007B1E8 6859428C */  lw         $v0, %lo(D_80075968)($v0)
/* 5C97FB4 8007B1EC 00000000 */  nop
/* 5C97FB8 8007B1F0 0300A216 */  bne        $s5, $v0, .Lcredits_8007B200
/* 5C97FBC 8007B1F4 0100A226 */   addiu     $v0, $s5, 0x1
/* 5C97FC0 8007B1F8 0780013C */  lui        $at, %hi(D_80075968)
/* 5C97FC4 8007B1FC 685922AC */  sw         $v0, %lo(D_80075968)($at)
.Lcredits_8007B200:
/* 5C97FC8 8007B200 0780043C */  lui        $a0, %hi(D_80075708)
/* 5C97FCC 8007B204 0857848C */  lw         $a0, %lo(D_80075708)($a0)
/* 5C97FD0 8007B208 00000000 */  nop
/* 5C97FD4 8007B20C 0A008284 */  lh         $v0, 0xA($a0)
/* 5C97FD8 8007B210 00000000 */  nop
/* 5C97FDC 8007B214 03004014 */  bnez       $v0, .Lcredits_8007B224
/* 5C97FE0 8007B218 21209700 */   addu      $a0, $a0, $s7
/* 5C97FE4 8007B21C 9EEC0108 */  j          .Lcredits_8007B278
/* 5C97FE8 8007B220 21980000 */   addu      $s3, $zero, $zero
.Lcredits_8007B224:
/* 5C97FEC 8007B224 08008424 */  addiu      $a0, $a0, 0x8
/* 5C97FF0 8007B228 E4DF000C */  jal        func_80037F90
/* 5C97FF4 8007B22C 02000524 */   addiu     $a1, $zero, 0x2
/* 5C97FF8 8007B230 12004010 */  beqz       $v0, .Lcredits_8007B27C
/* 5C97FFC 8007B234 FFFF0224 */   addiu     $v0, $zero, -0x1
/* 5C98000 8007B238 0780023C */  lui        $v0, %hi(D_80075708)
/* 5C98004 8007B23C 0857428C */  lw         $v0, %lo(D_80075708)($v0)
/* 5C98008 8007B240 00000000 */  nop
/* 5C9800C 8007B244 2110E202 */  addu       $v0, $s7, $v0
/* 5C98010 8007B248 16004284 */  lh         $v0, 0x16($v0)
/* 5C98014 8007B24C 00000000 */  nop
/* 5C98018 8007B250 0A004014 */  bnez       $v0, .Lcredits_8007B27C
/* 5C9801C 8007B254 FFFF0224 */   addiu     $v0, $zero, -0x1
/* 5C98020 8007B258 0780023C */  lui        $v0, %hi(D_800757DC)
/* 5C98024 8007B25C DC57428C */  lw         $v0, %lo(D_800757DC)($v0)
/* 5C98028 8007B260 00000000 */  nop
/* 5C9802C 8007B264 FFFF4224 */  addiu      $v0, $v0, -0x1
/* 5C98030 8007B268 2A10A202 */  slt        $v0, $s5, $v0
/* 5C98034 8007B26C 03004010 */  beqz       $v0, .Lcredits_8007B27C
/* 5C98038 8007B270 FFFF0224 */   addiu     $v0, $zero, -0x1
/* 5C9803C 8007B274 0100B326 */  addiu      $s3, $s5, 0x1
.Lcredits_8007B278:
/* 5C98040 8007B278 FFFF0224 */  addiu      $v0, $zero, -0x1
.Lcredits_8007B27C:
/* 5C98044 8007B27C 66016212 */  beq        $s3, $v0, .Lcredits_8007B818
/* 5C98048 8007B280 21380000 */   addu      $a3, $zero, $zero
/* 5C9804C 8007B284 21400000 */  addu       $t0, $zero, $zero
/* 5C98050 8007B288 40101300 */  sll        $v0, $s3, 1
/* 5C98054 8007B28C 21105300 */  addu       $v0, $v0, $s3
/* 5C98058 8007B290 0780033C */  lui        $v1, %hi(D_80075708)
/* 5C9805C 8007B294 0857638C */  lw         $v1, %lo(D_80075708)($v1)
/* 5C98060 8007B298 80100200 */  sll        $v0, $v0, 2
/* 5C98064 8007B29C 21204300 */  addu       $a0, $v0, $v1
/* 5C98068 8007B2A0 01000224 */  addiu      $v0, $zero, 0x1
/* 5C9806C 8007B2A4 0A0082A4 */  sh         $v0, 0xA($a0)
/* 5C98070 8007B2A8 0780023C */  lui        $v0, %hi(D_80075878)
/* 5C98074 8007B2AC 7858428C */  lw         $v0, %lo(D_80075878)($v0)
/* 5C98078 8007B2B0 00000000 */  nop
/* 5C9807C 8007B2B4 2A105300 */  slt        $v0, $v0, $s3
/* 5C98080 8007B2B8 03004010 */  beqz       $v0, .Lcredits_8007B2C8
/* 5C98084 8007B2BC 10000924 */   addiu     $t1, $zero, 0x10
/* 5C98088 8007B2C0 0780013C */  lui        $at, %hi(D_80075878)
/* 5C9808C 8007B2C4 785833AC */  sw         $s3, %lo(D_80075878)($at)
.Lcredits_8007B2C8:
/* 5C98090 8007B2C8 0780023C */  lui        $v0, %hi(D_80075878)
/* 5C98094 8007B2CC 7858428C */  lw         $v0, %lo(D_80075878)($v0)
/* 5C98098 8007B2D0 0780033C */  lui        $v1, %hi(D_800757DC)
/* 5C9809C 8007B2D4 DC57638C */  lw         $v1, %lo(D_800757DC)($v1)
/* 5C980A0 8007B2D8 00000000 */  nop
/* 5C980A4 8007B2DC 2A106200 */  slt        $v0, $v1, $v0
/* 5C980A8 8007B2E0 03004010 */  beqz       $v0, .Lcredits_8007B2F0
/* 5C980AC 8007B2E4 00010224 */   addiu     $v0, $zero, 0x100
/* 5C980B0 8007B2E8 0780013C */  lui        $at, %hi(D_80075878)
/* 5C980B4 8007B2EC 785823AC */  sw         $v1, %lo(D_80075878)($at)
.Lcredits_8007B2F0:
/* 5C980B8 8007B2F0 2000A2AF */  sw         $v0, 0x20($sp)
/* 5C980BC 8007B2F4 04008384 */  lh         $v1, 0x4($a0)
/* 5C980C0 8007B2F8 B3120224 */  addiu      $v0, $zero, 0x12B3
/* 5C980C4 8007B2FC 2800A2AF */  sw         $v0, 0x28($sp)
/* 5C980C8 8007B300 0E000224 */  addiu      $v0, $zero, 0xE
/* 5C980CC 8007B304 3000A2AF */  sw         $v0, 0x30($sp)
/* 5C980D0 8007B308 01000224 */  addiu      $v0, $zero, 0x1
/* 5C980D4 8007B30C 3400A2AF */  sw         $v0, 0x34($sp)
/* 5C980D8 8007B310 00160224 */  addiu      $v0, $zero, 0x1600
/* 5C980DC 8007B314 3800A2AF */  sw         $v0, 0x38($sp)
/* 5C980E0 8007B318 2400A3AF */  sw         $v1, 0x24($sp)
/* 5C980E4 8007B31C 0000868C */  lw         $a2, 0x0($a0)
/* 5C980E8 8007B320 00000000 */  nop
/* 5C980EC 8007B324 0000C390 */  lbu        $v1, 0x0($a2)
/* 5C980F0 8007B328 00000000 */  nop
/* 5C980F4 8007B32C B7006010 */  beqz       $v1, .Lcredits_8007B60C
/* 5C980F8 8007B330 00010A24 */   addiu     $t2, $zero, 0x100
.Lcredits_8007B334:
/* 5C980FC 8007B334 FF006330 */  andi       $v1, $v1, 0xFF
/* 5C98100 8007B338 20000224 */  addiu      $v0, $zero, 0x20
/* 5C98104 8007B33C A3006210 */  beq        $v1, $v0, .Lcredits_8007B5CC
/* 5C98108 8007B340 00000000 */   nop
.Lcredits_8007B344:
/* 5C9810C 8007B344 0780053C */  lui        $a1, %hi(D_800756E4)
/* 5C98110 8007B348 E456A58C */  lw         $a1, %lo(D_800756E4)($a1)
/* 5C98114 8007B34C 2188E000 */  addu       $s1, $a3, $zero
/* 5C98118 8007B350 2A102502 */  slt        $v0, $s1, $a1
/* 5C9811C 8007B354 19004010 */  beqz       $v0, .Lcredits_8007B3BC
/* 5C98120 8007B358 C0101100 */   sll       $v0, $s1, 3
/* 5C98124 8007B35C 0780043C */  lui        $a0, %hi(D_8007589C)
/* 5C98128 8007B360 9C58848C */  lw         $a0, %lo(D_8007589C)($a0)
/* 5C9812C 8007B364 23105100 */  subu       $v0, $v0, $s1
/* 5C98130 8007B368 80100200 */  sll        $v0, $v0, 2
/* 5C98134 8007B36C 21184400 */  addu       $v1, $v0, $a0
.Lcredits_8007B370:
/* 5C98138 8007B370 04006290 */  lbu        $v0, 0x4($v1)
/* 5C9813C 8007B374 00000000 */  nop
/* 5C98140 8007B378 05004010 */  beqz       $v0, .Lcredits_8007B390
/* 5C98144 8007B37C 00000000 */   nop
/* 5C98148 8007B380 01003126 */  addiu      $s1, $s1, 0x1
/* 5C9814C 8007B384 2A102502 */  slt        $v0, $s1, $a1
/* 5C98150 8007B388 F9FF4014 */  bnez       $v0, .Lcredits_8007B370
/* 5C98154 8007B38C 1C006324 */   addiu     $v1, $v1, 0x1C
.Lcredits_8007B390:
/* 5C98158 8007B390 0780023C */  lui        $v0, %hi(D_800756E4)
/* 5C9815C 8007B394 E456428C */  lw         $v0, %lo(D_800756E4)($v0)
/* 5C98160 8007B398 00000000 */  nop
/* 5C98164 8007B39C 2A102202 */  slt        $v0, $s1, $v0
/* 5C98168 8007B3A0 06004010 */  beqz       $v0, .Lcredits_8007B3BC
/* 5C9816C 8007B3A4 C0101100 */   sll       $v0, $s1, 3
/* 5C98170 8007B3A8 21382002 */  addu       $a3, $s1, $zero
/* 5C98174 8007B3AC 23104700 */  subu       $v0, $v0, $a3
/* 5C98178 8007B3B0 80100200 */  sll        $v0, $v0, 2
/* 5C9817C 8007B3B4 FAEC0108 */  j          .Lcredits_8007B3E8
/* 5C98180 8007B3B8 21208200 */   addu      $a0, $a0, $v0
.Lcredits_8007B3BC:
/* 5C98184 8007B3BC 0780023C */  lui        $v0, %hi(D_800756E4)
/* 5C98188 8007B3C0 E456428C */  lw         $v0, %lo(D_800756E4)($v0)
/* 5C9818C 8007B3C4 0780043C */  lui        $a0, %hi(D_8007589C)
/* 5C98190 8007B3C8 9C58848C */  lw         $a0, %lo(D_8007589C)($a0)
/* 5C98194 8007B3CC C0180200 */  sll        $v1, $v0, 3
/* 5C98198 8007B3D0 23186200 */  subu       $v1, $v1, $v0
/* 5C9819C 8007B3D4 80180300 */  sll        $v1, $v1, 2
/* 5C981A0 8007B3D8 21208300 */  addu       $a0, $a0, $v1
/* 5C981A4 8007B3DC 01004224 */  addiu      $v0, $v0, 0x1
/* 5C981A8 8007B3E0 0780013C */  lui        $at, %hi(D_800756E4)
/* 5C981AC 8007B3E4 E45622AC */  sw         $v0, %lo(D_800756E4)($at)
.Lcredits_8007B3E8:
/* 5C981B0 8007B3E8 0000C390 */  lbu        $v1, 0x0($a2)
/* 5C981B4 8007B3EC 00000000 */  nop
/* 5C981B8 8007B3F0 BFFF6224 */  addiu      $v0, $v1, -0x41
/* 5C981BC 8007B3F4 1A00422C */  sltiu      $v0, $v0, 0x1A
/* 5C981C0 8007B3F8 02004010 */  beqz       $v0, .Lcredits_8007B404
/* 5C981C4 8007B3FC 9FFF6224 */   addiu     $v0, $v1, -0x61
/* 5C981C8 8007B400 01001424 */  addiu      $s4, $zero, 0x1
.Lcredits_8007B404:
/* 5C981CC 8007B404 1A00422C */  sltiu      $v0, $v0, 0x1A
/* 5C981D0 8007B408 02004010 */  beqz       $v0, .Lcredits_8007B414
/* 5C981D4 8007B40C 01000224 */   addiu     $v0, $zero, 0x1
/* 5C981D8 8007B410 21A00000 */  addu       $s4, $zero, $zero
.Lcredits_8007B414:
/* 5C981DC 8007B414 040082A0 */  sb         $v0, 0x4($a0)
/* 5C981E0 8007B418 0780023C */  lui        $v0, %hi(D_800756E4)
/* 5C981E4 8007B41C E456428C */  lw         $v0, %lo(D_800756E4)($v0)
/* 5C981E8 8007B420 00000000 */  nop
/* 5C981EC 8007B424 65004228 */  slti       $v0, $v0, 0x65
/* 5C981F0 8007B428 03004014 */  bnez       $v0, .Lcredits_8007B438
/* 5C981F4 8007B42C 180093A4 */   sh        $s3, 0x18($a0)
/* 5C981F8 8007B430 5B8E010C */  jal        exit
/* 5C981FC 8007B434 21200000 */   addu      $a0, $zero, $zero
.Lcredits_8007B438:
/* 5C98200 8007B438 2000A28F */  lw         $v0, 0x20($sp)
/* 5C98204 8007B43C 00000000 */  nop
/* 5C98208 8007B440 120082A4 */  sh         $v0, 0x12($a0)
/* 5C9820C 8007B444 2400A28F */  lw         $v0, 0x24($sp)
/* 5C98210 8007B448 00000000 */  nop
/* 5C98214 8007B44C 140082A4 */  sh         $v0, 0x14($a0)
/* 5C98218 8007B450 2800A28F */  lw         $v0, 0x28($sp)
/* 5C9821C 8007B454 09008016 */  bnez       $s4, .Lcredits_8007B47C
/* 5C98220 8007B458 160082A4 */   sh        $v0, 0x16($a0)
/* 5C98224 8007B45C 3400A28F */  lw         $v0, 0x34($sp)
/* 5C98228 8007B460 14008394 */  lhu        $v1, 0x14($a0)
/* 5C9822C 8007B464 00000000 */  nop
/* 5C98230 8007B468 21186200 */  addu       $v1, $v1, $v0
/* 5C98234 8007B46C 140083A4 */  sh         $v1, 0x14($a0)
/* 5C98238 8007B470 3800A28F */  lw         $v0, 0x38($sp)
/* 5C9823C 8007B474 00000000 */  nop
/* 5C98240 8007B478 160082A4 */  sh         $v0, 0x16($a0)
.Lcredits_8007B47C:
/* 5C98244 8007B47C 0000C390 */  lbu        $v1, 0x0($a2)
/* 5C98248 8007B480 00000000 */  nop
/* 5C9824C 8007B484 D0FF6224 */  addiu      $v0, $v1, -0x30
/* 5C98250 8007B488 0A00422C */  sltiu      $v0, $v0, 0xA
/* 5C98254 8007B48C 03004010 */  beqz       $v0, .Lcredits_8007B49C
/* 5C98258 8007B490 D4006224 */   addiu     $v0, $v1, 0xD4
/* 5C9825C 8007B494 64ED0108 */  j          .Lcredits_8007B590
/* 5C98260 8007B498 1A0082A4 */   sh        $v0, 0x1A($a0)
.Lcredits_8007B49C:
/* 5C98264 8007B49C BFFF6224 */  addiu      $v0, $v1, -0x41
/* 5C98268 8007B4A0 1A00422C */  sltiu      $v0, $v0, 0x1A
/* 5C9826C 8007B4A4 03004010 */  beqz       $v0, .Lcredits_8007B4B4
/* 5C98270 8007B4A8 69016224 */   addiu     $v0, $v1, 0x169
/* 5C98274 8007B4AC 64ED0108 */  j          .Lcredits_8007B590
/* 5C98278 8007B4B0 1A0082A4 */   sh        $v0, 0x1A($a0)
.Lcredits_8007B4B4:
/* 5C9827C 8007B4B4 9FFF6224 */  addiu      $v0, $v1, -0x61
/* 5C98280 8007B4B8 1A00422C */  sltiu      $v0, $v0, 0x1A
/* 5C98284 8007B4BC 03004010 */  beqz       $v0, .Lcredits_8007B4CC
/* 5C98288 8007B4C0 49016224 */   addiu     $v0, $v1, 0x149
/* 5C9828C 8007B4C4 64ED0108 */  j          .Lcredits_8007B590
/* 5C98290 8007B4C8 1A0082A4 */   sh        $v0, 0x1A($a0)
.Lcredits_8007B4CC:
/* 5C98294 8007B4CC FF006330 */  andi       $v1, $v1, 0xFF
/* 5C98298 8007B4D0 21000224 */  addiu      $v0, $zero, 0x21
/* 5C9829C 8007B4D4 04006214 */  bne        $v1, $v0, .Lcredits_8007B4E8
/* 5C982A0 8007B4D8 2C000224 */   addiu     $v0, $zero, 0x2C
/* 5C982A4 8007B4DC 4B000224 */  addiu      $v0, $zero, 0x4B
/* 5C982A8 8007B4E0 64ED0108 */  j          .Lcredits_8007B590
/* 5C982AC 8007B4E4 1A0082A4 */   sh        $v0, 0x1A($a0)
.Lcredits_8007B4E8:
/* 5C982B0 8007B4E8 04006214 */  bne        $v1, $v0, .Lcredits_8007B4FC
/* 5C982B4 8007B4EC 2E000224 */   addiu     $v0, $zero, 0x2E
/* 5C982B8 8007B4F0 4C000224 */  addiu      $v0, $zero, 0x4C
/* 5C982BC 8007B4F4 64ED0108 */  j          .Lcredits_8007B590
/* 5C982C0 8007B4F8 1A0082A4 */   sh        $v0, 0x1A($a0)
.Lcredits_8007B4FC:
/* 5C982C4 8007B4FC 04006214 */  bne        $v1, $v0, .Lcredits_8007B510
/* 5C982C8 8007B500 2D000224 */   addiu     $v0, $zero, 0x2D
/* 5C982CC 8007B504 47010224 */  addiu      $v0, $zero, 0x147
/* 5C982D0 8007B508 64ED0108 */  j          .Lcredits_8007B590
/* 5C982D4 8007B50C 1A0082A4 */   sh        $v0, 0x1A($a0)
.Lcredits_8007B510:
/* 5C982D8 8007B510 04006214 */  bne        $v1, $v0, .Lcredits_8007B524
/* 5C982DC 8007B514 3A000224 */   addiu     $v0, $zero, 0x3A
/* 5C982E0 8007B518 15010224 */  addiu      $v0, $zero, 0x115
/* 5C982E4 8007B51C 64ED0108 */  j          .Lcredits_8007B590
/* 5C982E8 8007B520 1A0082A4 */   sh        $v0, 0x1A($a0)
.Lcredits_8007B524:
/* 5C982EC 8007B524 0E006214 */  bne        $v1, $v0, .Lcredits_8007B560
/* 5C982F0 8007B528 5555033C */   lui       $v1, (0x55555556 >> 16)
/* 5C982F4 8007B52C 16008394 */  lhu        $v1, 0x16($a0)
/* 5C982F8 8007B530 47010224 */  addiu      $v0, $zero, 0x147
/* 5C982FC 8007B534 1A0082A4 */  sh         $v0, 0x1A($a0)
/* 5C98300 8007B538 78056324 */  addiu      $v1, $v1, 0x578
/* 5C98304 8007B53C 03000015 */  bnez       $t0, .Lcredits_8007B54C
/* 5C98308 8007B540 160083A4 */   sh        $v1, 0x16($a0)
/* 5C9830C 8007B544 D1EC0108 */  j          .Lcredits_8007B344
/* 5C98310 8007B548 01000824 */   addiu     $t0, $zero, 0x1
.Lcredits_8007B54C:
/* 5C98314 8007B54C 14008294 */  lhu        $v0, 0x14($a0)
/* 5C98318 8007B550 21400000 */  addu       $t0, $zero, $zero
/* 5C9831C 8007B554 FAFF4224 */  addiu      $v0, $v0, -0x6
/* 5C98320 8007B558 64ED0108 */  j          .Lcredits_8007B590
/* 5C98324 8007B55C 140082A4 */   sh        $v0, 0x14($a0)
.Lcredits_8007B560:
/* 5C98328 8007B560 4C000224 */  addiu      $v0, $zero, 0x4C
/* 5C9832C 8007B564 1A0082A4 */  sh         $v0, 0x1A($a0)
/* 5C98330 8007B568 3000A28F */  lw         $v0, 0x30($sp)
/* 5C98334 8007B56C 56556334 */  ori        $v1, $v1, (0x55555556 & 0xFFFF)
/* 5C98338 8007B570 40100200 */  sll        $v0, $v0, 1
/* 5C9833C 8007B574 18004300 */  mult       $v0, $v1
/* 5C98340 8007B578 C3170200 */  sra        $v0, $v0, 31
/* 5C98344 8007B57C 14008394 */  lhu        $v1, 0x14($a0)
/* 5C98348 8007B580 10580000 */  mfhi       $t3
/* 5C9834C 8007B584 23106201 */  subu       $v0, $t3, $v0
/* 5C98350 8007B588 23186200 */  subu       $v1, $v1, $v0
/* 5C98354 8007B58C 140083A4 */  sh         $v1, 0x14($a0)
.Lcredits_8007B590:
/* 5C98358 8007B590 04008012 */  beqz       $s4, .Lcredits_8007B5A4
/* 5C9835C 8007B594 00000000 */   nop
/* 5C98360 8007B598 2000A28F */  lw         $v0, 0x20($sp)
/* 5C98364 8007B59C 6DED0108 */  j          .Lcredits_8007B5B4
/* 5C98368 8007B5A0 21104900 */   addu      $v0, $v0, $t1
.Lcredits_8007B5A4:
/* 5C9836C 8007B5A4 2000A28F */  lw         $v0, 0x20($sp)
/* 5C98370 8007B5A8 3000A38F */  lw         $v1, 0x30($sp)
/* 5C98374 8007B5AC 00000000 */  nop
/* 5C98378 8007B5B0 21104300 */  addu       $v0, $v0, $v1
.Lcredits_8007B5B4:
/* 5C9837C 8007B5B4 2000A2AF */  sw         $v0, 0x20($sp)
/* 5C98380 8007B5B8 0000C290 */  lbu        $v0, 0x0($a2)
/* 5C98384 8007B5BC 00000000 */  nop
/* 5C98388 8007B5C0 D0FF4224 */  addiu      $v0, $v0, -0x30
/* 5C9838C 8007B5C4 7EED0108 */  j          .Lcredits_8007B5F8
/* 5C98390 8007B5C8 0A00542C */   sltiu     $s4, $v0, 0xA
.Lcredits_8007B5CC:
/* 5C98394 8007B5CC 3000A28F */  lw         $v0, 0x30($sp)
/* 5C98398 8007B5D0 00000000 */  nop
/* 5C9839C 8007B5D4 40180200 */  sll        $v1, $v0, 1
/* 5C983A0 8007B5D8 21186200 */  addu       $v1, $v1, $v0
/* 5C983A4 8007B5DC 02006104 */  bgez       $v1, .Lcredits_8007B5E8
/* 5C983A8 8007B5E0 01001424 */   addiu     $s4, $zero, 0x1
/* 5C983AC 8007B5E4 03006324 */  addiu      $v1, $v1, 0x3
.Lcredits_8007B5E8:
/* 5C983B0 8007B5E8 2000A28F */  lw         $v0, 0x20($sp)
/* 5C983B4 8007B5EC 83180300 */  sra        $v1, $v1, 2
/* 5C983B8 8007B5F0 21104300 */  addu       $v0, $v0, $v1
/* 5C983BC 8007B5F4 2000A2AF */  sw         $v0, 0x20($sp)
.Lcredits_8007B5F8:
/* 5C983C0 8007B5F8 0100C624 */  addiu      $a2, $a2, 0x1
/* 5C983C4 8007B5FC 0000C390 */  lbu        $v1, 0x0($a2)
/* 5C983C8 8007B600 00000000 */  nop
/* 5C983CC 8007B604 4BFF6014 */  bnez       $v1, .Lcredits_8007B334
/* 5C983D0 8007B608 00000000 */   nop
.Lcredits_8007B60C:
/* 5C983D4 8007B60C 2000A28F */  lw         $v0, 0x20($sp)
/* 5C983D8 8007B610 21880000 */  addu       $s1, $zero, $zero
/* 5C983DC 8007B614 23104A00 */  subu       $v0, $v0, $t2
/* 5C983E0 8007B618 43B00200 */  sra        $s6, $v0, 1
/* 5C983E4 8007B61C 0780023C */  lui        $v0, %hi(D_800756E4)
/* 5C983E8 8007B620 E456428C */  lw         $v0, %lo(D_800756E4)($v0)
/* 5C983EC 8007B624 00000000 */  nop
/* 5C983F0 8007B628 7B004018 */  blez       $v0, .Lcredits_8007B818
/* 5C983F4 8007B62C 1E001224 */   addiu     $s2, $zero, 0x1E
/* 5C983F8 8007B630 21800000 */  addu       $s0, $zero, $zero
.Lcredits_8007B634:
/* 5C983FC 8007B634 0780023C */  lui        $v0, %hi(D_8007589C)
/* 5C98400 8007B638 9C58428C */  lw         $v0, %lo(D_8007589C)($v0)
/* 5C98404 8007B63C 00000000 */  nop
/* 5C98408 8007B640 21380202 */  addu       $a3, $s0, $v0
/* 5C9840C 8007B644 1800E284 */  lh         $v0, 0x18($a3)
/* 5C98410 8007B648 00000000 */  nop
/* 5C98414 8007B64C 6C005314 */  bne        $v0, $s3, .Lcredits_8007B800
/* 5C98418 8007B650 0F000524 */   addiu     $a1, $zero, 0xF
/* 5C9841C 8007B654 1200E694 */  lhu        $a2, 0x12($a3)
/* 5C98420 8007B658 00000000 */  nop
/* 5C98424 8007B65C 2330D600 */  subu       $a2, $a2, $s6
/* 5C98428 8007B660 00140600 */  sll        $v0, $a2, 16
/* 5C9842C 8007B664 03140200 */  sra        $v0, $v0, 16
/* 5C98430 8007B668 00FF4224 */  addiu      $v0, $v0, -0x100
/* 5C98434 8007B66C 40180200 */  sll        $v1, $v0, 1
/* 5C98438 8007B670 21186200 */  addu       $v1, $v1, $v0
/* 5C9843C 8007B674 23180300 */  negu       $v1, $v1
/* 5C98440 8007B678 1A007200 */  div        $zero, $v1, $s2
/* 5C98444 8007B67C 02004016 */  bnez       $s2, .Lcredits_8007B688
/* 5C98448 8007B680 00000000 */   nop
/* 5C9844C 8007B684 0D000700 */  break      7
.Lcredits_8007B688:
/* 5C98450 8007B688 FFFF0124 */  addiu      $at, $zero, -0x1
/* 5C98454 8007B68C 04004116 */  bne        $s2, $at, .Lcredits_8007B6A0
/* 5C98458 8007B690 0080013C */   lui       $at, (0x80000000 >> 16)
/* 5C9845C 8007B694 02006114 */  bne        $v1, $at, .Lcredits_8007B6A0
/* 5C98460 8007B698 00000000 */   nop
/* 5C98464 8007B69C 0D000600 */  break      6
.Lcredits_8007B6A0:
/* 5C98468 8007B6A0 12180000 */  mflo       $v1
/* 5C9846C 8007B6A4 1600E284 */  lh         $v0, 0x16($a3)
/* 5C98470 8007B6A8 00000000 */  nop
/* 5C98474 8007B6AC 40100200 */  sll        $v0, $v0, 1
/* 5C98478 8007B6B0 23100200 */  negu       $v0, $v0
/* 5C9847C 8007B6B4 1A005200 */  div        $zero, $v0, $s2
/* 5C98480 8007B6B8 02004016 */  bnez       $s2, .Lcredits_8007B6C4
/* 5C98484 8007B6BC 00000000 */   nop
/* 5C98488 8007B6C0 0D000700 */  break      7
.Lcredits_8007B6C4:
/* 5C9848C 8007B6C4 FFFF0124 */  addiu      $at, $zero, -0x1
/* 5C98490 8007B6C8 04004116 */  bne        $s2, $at, .Lcredits_8007B6DC
/* 5C98494 8007B6CC 0080013C */   lui       $at, (0x80000000 >> 16)
/* 5C98498 8007B6D0 02004114 */  bne        $v0, $at, .Lcredits_8007B6DC
/* 5C9849C 8007B6D4 00000000 */   nop
/* 5C984A0 8007B6D8 0D000600 */  break      6
.Lcredits_8007B6DC:
/* 5C984A4 8007B6DC 12100000 */  mflo       $v0
/* 5C984A8 8007B6E0 00000000 */  nop
/* 5C984AC 8007B6E4 00000000 */  nop
/* 5C984B0 8007B6E8 18007200 */  mult       $v1, $s2
/* 5C984B4 8007B6EC 12480000 */  mflo       $t1
/* 5C984B8 8007B6F0 00000000 */  nop
/* 5C984BC 8007B6F4 00000000 */  nop
/* 5C984C0 8007B6F8 18005200 */  mult       $v0, $s2
/* 5C984C4 8007B6FC 1200E6A4 */  sh         $a2, 0x12($a3)
/* 5C984C8 8007B700 04000424 */  addiu      $a0, $zero, 0x4
/* 5C984CC 8007B704 0C00E3A4 */  sh         $v1, 0xC($a3)
/* 5C984D0 8007B708 1000E2A4 */  sh         $v0, 0x10($a3)
/* 5C984D4 8007B70C 1600E294 */  lhu        $v0, 0x16($a3)
/* 5C984D8 8007B710 2330C900 */  subu       $a2, $a2, $t1
/* 5C984DC 8007B714 1200E6A4 */  sh         $a2, 0x12($a3)
/* 5C984E0 8007B718 12400000 */  mflo       $t0
/* 5C984E4 8007B71C 23104800 */  subu       $v0, $v0, $t0
/* 5C984E8 8007B720 C4DF000C */  jal        RandRangeSigned
/* 5C984EC 8007B724 1600E2A4 */   sh        $v0, 0x16($a3)
/* 5C984F0 8007B728 04000424 */  addiu      $a0, $zero, 0x4
/* 5C984F4 8007B72C 0780033C */  lui        $v1, %hi(D_8007589C)
/* 5C984F8 8007B730 9C58638C */  lw         $v1, %lo(D_8007589C)($v1)
/* 5C984FC 8007B734 0F000524 */  addiu      $a1, $zero, 0xF
/* 5C98500 8007B738 21180302 */  addu       $v1, $s0, $v1
/* 5C98504 8007B73C C4DF000C */  jal        RandRangeSigned
/* 5C98508 8007B740 080062A0 */   sb        $v0, 0x8($v1)
/* 5C9850C 8007B744 04000424 */  addiu      $a0, $zero, 0x4
/* 5C98510 8007B748 0780033C */  lui        $v1, %hi(D_8007589C)
/* 5C98514 8007B74C 9C58638C */  lw         $v1, %lo(D_8007589C)($v1)
/* 5C98518 8007B750 0F000524 */  addiu      $a1, $zero, 0xF
/* 5C9851C 8007B754 21180302 */  addu       $v1, $s0, $v1
/* 5C98520 8007B758 C4DF000C */  jal        RandRangeSigned
/* 5C98524 8007B75C 090062A0 */   sb        $v0, 0x9($v1)
/* 5C98528 8007B760 0780033C */  lui        $v1, %hi(D_8007589C)
/* 5C9852C 8007B764 9C58638C */  lw         $v1, %lo(D_8007589C)($v1)
/* 5C98530 8007B768 00000000 */  nop
/* 5C98534 8007B76C 21180302 */  addu       $v1, $s0, $v1
/* 5C98538 8007B770 0A0062A0 */  sb         $v0, 0xA($v1)
/* 5C9853C 8007B774 0780033C */  lui        $v1, %hi(D_8007589C)
/* 5C98540 8007B778 9C58638C */  lw         $v1, %lo(D_8007589C)($v1)
/* 5C98544 8007B77C 00000000 */  nop
/* 5C98548 8007B780 21180302 */  addu       $v1, $s0, $v1
/* 5C9854C 8007B784 08006290 */  lbu        $v0, 0x8($v1)
/* 5C98550 8007B788 00000000 */  nop
/* 5C98554 8007B78C 23100200 */  negu       $v0, $v0
/* 5C98558 8007B790 18005200 */  mult       $v0, $s2
/* 5C9855C 8007B794 12400000 */  mflo       $t0
/* 5C98560 8007B798 050068A0 */  sb         $t0, 0x5($v1)
/* 5C98564 8007B79C 0780033C */  lui        $v1, %hi(D_8007589C)
/* 5C98568 8007B7A0 9C58638C */  lw         $v1, %lo(D_8007589C)($v1)
/* 5C9856C 8007B7A4 00000000 */  nop
/* 5C98570 8007B7A8 21180302 */  addu       $v1, $s0, $v1
/* 5C98574 8007B7AC 09006290 */  lbu        $v0, 0x9($v1)
/* 5C98578 8007B7B0 00000000 */  nop
/* 5C9857C 8007B7B4 23100200 */  negu       $v0, $v0
/* 5C98580 8007B7B8 18005200 */  mult       $v0, $s2
/* 5C98584 8007B7BC 12400000 */  mflo       $t0
/* 5C98588 8007B7C0 060068A0 */  sb         $t0, 0x6($v1)
/* 5C9858C 8007B7C4 0780033C */  lui        $v1, %hi(D_8007589C)
/* 5C98590 8007B7C8 9C58638C */  lw         $v1, %lo(D_8007589C)($v1)
/* 5C98594 8007B7CC 00000000 */  nop
/* 5C98598 8007B7D0 21180302 */  addu       $v1, $s0, $v1
/* 5C9859C 8007B7D4 0A006290 */  lbu        $v0, 0xA($v1)
/* 5C985A0 8007B7D8 00000000 */  nop
/* 5C985A4 8007B7DC 23100200 */  negu       $v0, $v0
/* 5C985A8 8007B7E0 18005200 */  mult       $v0, $s2
/* 5C985AC 8007B7E4 12400000 */  mflo       $t0
/* 5C985B0 8007B7E8 070068A0 */  sb         $t0, 0x7($v1)
/* 5C985B4 8007B7EC 0780023C */  lui        $v0, %hi(D_8007589C)
/* 5C985B8 8007B7F0 9C58428C */  lw         $v0, %lo(D_8007589C)($v0)
/* 5C985BC 8007B7F4 00000000 */  nop
/* 5C985C0 8007B7F8 21100202 */  addu       $v0, $s0, $v0
/* 5C985C4 8007B7FC 0B0052A0 */  sb         $s2, 0xB($v0)
.Lcredits_8007B800:
/* 5C985C8 8007B800 0780023C */  lui        $v0, %hi(D_800756E4)
/* 5C985CC 8007B804 E456428C */  lw         $v0, %lo(D_800756E4)($v0)
/* 5C985D0 8007B808 01003126 */  addiu      $s1, $s1, 0x1
/* 5C985D4 8007B80C 2A102202 */  slt        $v0, $s1, $v0
/* 5C985D8 8007B810 88FF4014 */  bnez       $v0, .Lcredits_8007B634
/* 5C985DC 8007B814 1C001026 */   addiu     $s0, $s0, 0x1C
.Lcredits_8007B818:
/* 5C985E0 8007B818 0100B526 */  addiu      $s5, $s5, 0x1
/* 5C985E4 8007B81C 2A10D503 */  slt        $v0, $fp, $s5
/* 5C985E8 8007B820 5FFE4010 */  beqz       $v0, .Lcredits_8007B1A0
/* 5C985EC 8007B824 0C00F726 */   addiu     $s7, $s7, 0xC
.Lcredits_8007B828:
/* 5C985F0 8007B828 0780023C */  lui        $v0, %hi(D_800756E4)
/* 5C985F4 8007B82C E456428C */  lw         $v0, %lo(D_800756E4)($v0)
/* 5C985F8 8007B830 00000000 */  nop
/* 5C985FC 8007B834 26004018 */  blez       $v0, .Lcredits_8007B8D0
/* 5C98600 8007B838 21880000 */   addu      $s1, $zero, $zero
/* 5C98604 8007B83C 02000824 */  addiu      $t0, $zero, 0x2
/* 5C98608 8007B840 03000724 */  addiu      $a3, $zero, 0x3
/* 5C9860C 8007B844 04000624 */  addiu      $a2, $zero, 0x4
/* 5C98610 8007B848 21280000 */  addu       $a1, $zero, $zero
.Lcredits_8007B84C:
/* 5C98614 8007B84C 0780023C */  lui        $v0, %hi(D_8007589C)
/* 5C98618 8007B850 9C58428C */  lw         $v0, %lo(D_8007589C)($v0)
/* 5C9861C 8007B854 00000000 */  nop
/* 5C98620 8007B858 2120A200 */  addu       $a0, $a1, $v0
/* 5C98624 8007B85C 18008384 */  lh         $v1, 0x18($a0)
/* 5C98628 8007B860 00000000 */  nop
/* 5C9862C 8007B864 40100300 */  sll        $v0, $v1, 1
/* 5C98630 8007B868 21104300 */  addu       $v0, $v0, $v1
/* 5C98634 8007B86C 0780033C */  lui        $v1, %hi(D_80075708)
/* 5C98638 8007B870 0857638C */  lw         $v1, %lo(D_80075708)($v1)
/* 5C9863C 8007B874 80100200 */  sll        $v0, $v0, 2
/* 5C98640 8007B878 21104300 */  addu       $v0, $v0, $v1
/* 5C98644 8007B87C 0A004384 */  lh         $v1, 0xA($v0)
/* 5C98648 8007B880 00000000 */  nop
/* 5C9864C 8007B884 0A006814 */  bne        $v1, $t0, .Lcredits_8007B8B0
/* 5C98650 8007B888 00000000 */   nop
/* 5C98654 8007B88C 04008290 */  lbu        $v0, 0x4($a0)
/* 5C98658 8007B890 00000000 */  nop
/* 5C9865C 8007B894 03004314 */  bne        $v0, $v1, .Lcredits_8007B8A4
/* 5C98660 8007B898 00000000 */   nop
/* 5C98664 8007B89C 2CEE0108 */  j          .Lcredits_8007B8B0
/* 5C98668 8007B8A0 040087A0 */   sb        $a3, 0x4($a0)
.Lcredits_8007B8A4:
/* 5C9866C 8007B8A4 02004614 */  bne        $v0, $a2, .Lcredits_8007B8B0
/* 5C98670 8007B8A8 00000000 */   nop
/* 5C98674 8007B8AC 040080A0 */  sb         $zero, 0x4($a0)
.Lcredits_8007B8B0:
/* 5C98678 8007B8B0 0780023C */  lui        $v0, %hi(D_800756E4)
/* 5C9867C 8007B8B4 E456428C */  lw         $v0, %lo(D_800756E4)($v0)
/* 5C98680 8007B8B8 01003126 */  addiu      $s1, $s1, 0x1
/* 5C98684 8007B8BC 2A102202 */  slt        $v0, $s1, $v0
/* 5C98688 8007B8C0 E2FF4014 */  bnez       $v0, .Lcredits_8007B84C
/* 5C9868C 8007B8C4 1C00A524 */   addiu     $a1, $a1, 0x1C
/* 5C98690 8007B8C8 0780023C */  lui        $v0, %hi(D_800756E4)
/* 5C98694 8007B8CC E456428C */  lw         $v0, %lo(D_800756E4)($v0)
.Lcredits_8007B8D0:
/* 5C98698 8007B8D0 00000000 */  nop
/* 5C9869C 8007B8D4 A5004018 */  blez       $v0, .Lcredits_8007BB6C
/* 5C986A0 8007B8D8 21880000 */   addu      $s1, $zero, $zero
/* 5C986A4 8007B8DC 21800000 */  addu       $s0, $zero, $zero
.Lcredits_8007B8E0:
/* 5C986A8 8007B8E0 0780023C */  lui        $v0, %hi(D_8007589C)
/* 5C986AC 8007B8E4 9C58428C */  lw         $v0, %lo(D_8007589C)($v0)
/* 5C986B0 8007B8E8 00000000 */  nop
/* 5C986B4 8007B8EC 21300202 */  addu       $a2, $s0, $v0
/* 5C986B8 8007B8F0 0400C390 */  lbu        $v1, 0x4($a2)
/* 5C986BC 8007B8F4 01000224 */  addiu      $v0, $zero, 0x1
/* 5C986C0 8007B8F8 05006210 */  beq        $v1, $v0, .Lcredits_8007B910
/* 5C986C4 8007B8FC 03000224 */   addiu     $v0, $zero, 0x3
/* 5C986C8 8007B900 5C006210 */  beq        $v1, $v0, .Lcredits_8007BA74
/* 5C986CC 8007B904 00000000 */   nop
/* 5C986D0 8007B908 D5EE0108 */  j          .Lcredits_8007BB54
/* 5C986D4 8007B90C 00000000 */   nop
.Lcredits_8007B910:
/* 5C986D8 8007B910 1200C294 */  lhu        $v0, 0x12($a2)
/* 5C986DC 8007B914 0C00C494 */  lhu        $a0, 0xC($a2)
/* 5C986E0 8007B918 0500C390 */  lbu        $v1, 0x5($a2)
/* 5C986E4 8007B91C 0800C590 */  lbu        $a1, 0x8($a2)
/* 5C986E8 8007B920 21104400 */  addu       $v0, $v0, $a0
/* 5C986EC 8007B924 1200C2A4 */  sh         $v0, 0x12($a2)
/* 5C986F0 8007B928 1600C294 */  lhu        $v0, 0x16($a2)
/* 5C986F4 8007B92C 21186500 */  addu       $v1, $v1, $a1
/* 5C986F8 8007B930 0500C3A0 */  sb         $v1, 0x5($a2)
/* 5C986FC 8007B934 1000C394 */  lhu        $v1, 0x10($a2)
/* 5C98700 8007B938 0780043C */  lui        $a0, %hi(D_8007589C)
/* 5C98704 8007B93C 9C58848C */  lw         $a0, %lo(D_8007589C)($a0)
/* 5C98708 8007B940 21104300 */  addu       $v0, $v0, $v1
/* 5C9870C 8007B944 21200402 */  addu       $a0, $s0, $a0
/* 5C98710 8007B948 1600C2A4 */  sh         $v0, 0x16($a2)
/* 5C98714 8007B94C 06008290 */  lbu        $v0, 0x6($a0)
/* 5C98718 8007B950 09008390 */  lbu        $v1, 0x9($a0)
/* 5C9871C 8007B954 00000000 */  nop
/* 5C98720 8007B958 21104300 */  addu       $v0, $v0, $v1
/* 5C98724 8007B95C 060082A0 */  sb         $v0, 0x6($a0)
/* 5C98728 8007B960 0780043C */  lui        $a0, %hi(D_8007589C)
/* 5C9872C 8007B964 9C58848C */  lw         $a0, %lo(D_8007589C)($a0)
/* 5C98730 8007B968 00000000 */  nop
/* 5C98734 8007B96C 21200402 */  addu       $a0, $s0, $a0
/* 5C98738 8007B970 07008290 */  lbu        $v0, 0x7($a0)
/* 5C9873C 8007B974 0A008390 */  lbu        $v1, 0xA($a0)
/* 5C98740 8007B978 00000000 */  nop
/* 5C98744 8007B97C 21104300 */  addu       $v0, $v0, $v1
/* 5C98748 8007B980 070082A0 */  sb         $v0, 0x7($a0)
/* 5C9874C 8007B984 0780033C */  lui        $v1, %hi(D_8007589C)
/* 5C98750 8007B988 9C58638C */  lw         $v1, %lo(D_8007589C)($v1)
/* 5C98754 8007B98C 00000000 */  nop
/* 5C98758 8007B990 21180302 */  addu       $v1, $s0, $v1
/* 5C9875C 8007B994 0B006290 */  lbu        $v0, 0xB($v1)
/* 5C98760 8007B998 00000000 */  nop
/* 5C98764 8007B99C FFFF4224 */  addiu      $v0, $v0, -0x1
/* 5C98768 8007B9A0 0B0062A0 */  sb         $v0, 0xB($v1)
/* 5C9876C 8007B9A4 FF004230 */  andi       $v0, $v0, 0xFF
/* 5C98770 8007B9A8 6A004014 */  bnez       $v0, .Lcredits_8007BB54
/* 5C98774 8007B9AC 03000424 */   addiu     $a0, $zero, 0x3
/* 5C98778 8007B9B0 0B000524 */  addiu      $a1, $zero, 0xB
/* 5C9877C 8007B9B4 0780033C */  lui        $v1, %hi(D_8007589C)
/* 5C98780 8007B9B8 9C58638C */  lw         $v1, %lo(D_8007589C)($v1)
/* 5C98784 8007B9BC 02000224 */  addiu      $v0, $zero, 0x2
/* 5C98788 8007B9C0 21180302 */  addu       $v1, $s0, $v1
/* 5C9878C 8007B9C4 C4DF000C */  jal        RandRangeSigned
/* 5C98790 8007B9C8 040062A0 */   sb        $v0, 0x4($v1)
/* 5C98794 8007B9CC 06000424 */  addiu      $a0, $zero, 0x6
/* 5C98798 8007B9D0 0780033C */  lui        $v1, %hi(D_8007589C)
/* 5C9879C 8007B9D4 9C58638C */  lw         $v1, %lo(D_8007589C)($v1)
/* 5C987A0 8007B9D8 0A000524 */  addiu      $a1, $zero, 0xA
/* 5C987A4 8007B9DC 21180302 */  addu       $v1, $s0, $v1
/* 5C987A8 8007B9E0 A8DF000C */  jal        RandRange
/* 5C987AC 8007B9E4 0C0062A4 */   sh        $v0, 0xC($v1)
/* 5C987B0 8007B9E8 DDFF0424 */  addiu      $a0, $zero, -0x23
/* 5C987B4 8007B9EC 23000524 */  addiu      $a1, $zero, 0x23
/* 5C987B8 8007B9F0 0780033C */  lui        $v1, %hi(D_8007589C)
/* 5C987BC 8007B9F4 9C58638C */  lw         $v1, %lo(D_8007589C)($v1)
/* 5C987C0 8007B9F8 23100200 */  negu       $v0, $v0
/* 5C987C4 8007B9FC 21180302 */  addu       $v1, $s0, $v1
/* 5C987C8 8007BA00 A8DF000C */  jal        RandRange
/* 5C987CC 8007BA04 0E0062A4 */   sh        $v0, 0xE($v1)
/* 5C987D0 8007BA08 04000424 */  addiu      $a0, $zero, 0x4
/* 5C987D4 8007BA0C 0780033C */  lui        $v1, %hi(D_8007589C)
/* 5C987D8 8007BA10 9C58638C */  lw         $v1, %lo(D_8007589C)($v1)
/* 5C987DC 8007BA14 09000524 */  addiu      $a1, $zero, 0x9
/* 5C987E0 8007BA18 21180302 */  addu       $v1, $s0, $v1
/* 5C987E4 8007BA1C C4DF000C */  jal        RandRangeSigned
/* 5C987E8 8007BA20 100062A4 */   sh        $v0, 0x10($v1)
/* 5C987EC 8007BA24 04000424 */  addiu      $a0, $zero, 0x4
/* 5C987F0 8007BA28 0780033C */  lui        $v1, %hi(D_8007589C)
/* 5C987F4 8007BA2C 9C58638C */  lw         $v1, %lo(D_8007589C)($v1)
/* 5C987F8 8007BA30 09000524 */  addiu      $a1, $zero, 0x9
/* 5C987FC 8007BA34 21180302 */  addu       $v1, $s0, $v1
/* 5C98800 8007BA38 C4DF000C */  jal        RandRangeSigned
/* 5C98804 8007BA3C 080062A0 */   sb        $v0, 0x8($v1)
/* 5C98808 8007BA40 04000424 */  addiu      $a0, $zero, 0x4
/* 5C9880C 8007BA44 0780033C */  lui        $v1, %hi(D_8007589C)
/* 5C98810 8007BA48 9C58638C */  lw         $v1, %lo(D_8007589C)($v1)
/* 5C98814 8007BA4C 09000524 */  addiu      $a1, $zero, 0x9
/* 5C98818 8007BA50 21180302 */  addu       $v1, $s0, $v1
/* 5C9881C 8007BA54 C4DF000C */  jal        RandRangeSigned
/* 5C98820 8007BA58 090062A0 */   sb        $v0, 0x9($v1)
/* 5C98824 8007BA5C 0780033C */  lui        $v1, %hi(D_8007589C)
/* 5C98828 8007BA60 9C58638C */  lw         $v1, %lo(D_8007589C)($v1)
/* 5C9882C 8007BA64 00000000 */  nop
/* 5C98830 8007BA68 21180302 */  addu       $v1, $s0, $v1
/* 5C98834 8007BA6C D5EE0108 */  j          .Lcredits_8007BB54
/* 5C98838 8007BA70 0A0062A0 */   sb        $v0, 0xA($v1)
.Lcredits_8007BA74:
/* 5C9883C 8007BA74 1200C294 */  lhu        $v0, 0x12($a2)
/* 5C98840 8007BA78 0C00C494 */  lhu        $a0, 0xC($a2)
/* 5C98844 8007BA7C 1400C394 */  lhu        $v1, 0x14($a2)
/* 5C98848 8007BA80 0E00C594 */  lhu        $a1, 0xE($a2)
/* 5C9884C 8007BA84 21104400 */  addu       $v0, $v0, $a0
/* 5C98850 8007BA88 1200C2A4 */  sh         $v0, 0x12($a2)
/* 5C98854 8007BA8C 1600C294 */  lhu        $v0, 0x16($a2)
/* 5C98858 8007BA90 1000C494 */  lhu        $a0, 0x10($a2)
/* 5C9885C 8007BA94 21186500 */  addu       $v1, $v1, $a1
/* 5C98860 8007BA98 1400C3A4 */  sh         $v1, 0x14($a2)
/* 5C98864 8007BA9C 0500C390 */  lbu        $v1, 0x5($a2)
/* 5C98868 8007BAA0 0800C590 */  lbu        $a1, 0x8($a2)
/* 5C9886C 8007BAA4 21104400 */  addu       $v0, $v0, $a0
/* 5C98870 8007BAA8 1600C2A4 */  sh         $v0, 0x16($a2)
/* 5C98874 8007BAAC 0E00C294 */  lhu        $v0, 0xE($a2)
/* 5C98878 8007BAB0 21186500 */  addu       $v1, $v1, $a1
/* 5C9887C 8007BAB4 0500C3A0 */  sb         $v1, 0x5($a2)
/* 5C98880 8007BAB8 0780043C */  lui        $a0, %hi(D_8007589C)
/* 5C98884 8007BABC 9C58848C */  lw         $a0, %lo(D_8007589C)($a0)
/* 5C98888 8007BAC0 01004224 */  addiu      $v0, $v0, 0x1
/* 5C9888C 8007BAC4 21200402 */  addu       $a0, $s0, $a0
/* 5C98890 8007BAC8 0E00C2A4 */  sh         $v0, 0xE($a2)
/* 5C98894 8007BACC 06008290 */  lbu        $v0, 0x6($a0)
/* 5C98898 8007BAD0 09008390 */  lbu        $v1, 0x9($a0)
/* 5C9889C 8007BAD4 00000000 */  nop
/* 5C988A0 8007BAD8 21104300 */  addu       $v0, $v0, $v1
/* 5C988A4 8007BADC 060082A0 */  sb         $v0, 0x6($a0)
/* 5C988A8 8007BAE0 0780043C */  lui        $a0, %hi(D_8007589C)
/* 5C988AC 8007BAE4 9C58848C */  lw         $a0, %lo(D_8007589C)($a0)
/* 5C988B0 8007BAE8 00000000 */  nop
/* 5C988B4 8007BAEC 21200402 */  addu       $a0, $s0, $a0
/* 5C988B8 8007BAF0 07008290 */  lbu        $v0, 0x7($a0)
/* 5C988BC 8007BAF4 0A008390 */  lbu        $v1, 0xA($a0)
/* 5C988C0 8007BAF8 00000000 */  nop
/* 5C988C4 8007BAFC 21104300 */  addu       $v0, $v0, $v1
/* 5C988C8 8007BB00 070082A0 */  sb         $v0, 0x7($a0)
/* 5C988CC 8007BB04 0780023C */  lui        $v0, %hi(D_8007589C)
/* 5C988D0 8007BB08 9C58428C */  lw         $v0, %lo(D_8007589C)($v0)
/* 5C988D4 8007BB0C 00000000 */  nop
/* 5C988D8 8007BB10 21180202 */  addu       $v1, $s0, $v0
/* 5C988DC 8007BB14 0E006284 */  lh         $v0, 0xE($v1)
/* 5C988E0 8007BB18 00000000 */  nop
/* 5C988E4 8007BB1C 15004228 */  slti       $v0, $v0, 0x15
/* 5C988E8 8007BB20 02004014 */  bnez       $v0, .Lcredits_8007BB2C
/* 5C988EC 8007BB24 14000224 */   addiu     $v0, $zero, 0x14
/* 5C988F0 8007BB28 0E0062A4 */  sh         $v0, 0xE($v1)
.Lcredits_8007BB2C:
/* 5C988F4 8007BB2C 0780023C */  lui        $v0, %hi(D_8007589C)
/* 5C988F8 8007BB30 9C58428C */  lw         $v0, %lo(D_8007589C)($v0)
/* 5C988FC 8007BB34 00000000 */  nop
/* 5C98900 8007BB38 21180202 */  addu       $v1, $s0, $v0
/* 5C98904 8007BB3C 14006284 */  lh         $v0, 0x14($v1)
/* 5C98908 8007BB40 00000000 */  nop
/* 5C9890C 8007BB44 19014228 */  slti       $v0, $v0, 0x119
/* 5C98910 8007BB48 02004014 */  bnez       $v0, .Lcredits_8007BB54
/* 5C98914 8007BB4C 04000224 */   addiu     $v0, $zero, 0x4
/* 5C98918 8007BB50 040062A0 */  sb         $v0, 0x4($v1)
.Lcredits_8007BB54:
/* 5C9891C 8007BB54 0780023C */  lui        $v0, %hi(D_800756E4)
/* 5C98920 8007BB58 E456428C */  lw         $v0, %lo(D_800756E4)($v0)
/* 5C98924 8007BB5C 01003126 */  addiu      $s1, $s1, 0x1
/* 5C98928 8007BB60 2A102202 */  slt        $v0, $s1, $v0
/* 5C9892C 8007BB64 5EFF4014 */  bnez       $v0, .Lcredits_8007B8E0
/* 5C98930 8007BB68 1C001026 */   addiu     $s0, $s0, 0x1C
.Lcredits_8007BB6C:
/* 5C98934 8007BB6C 0780033C */  lui        $v1, %hi(D_800756E4)
/* 5C98938 8007BB70 E456638C */  lw         $v1, %lo(D_800756E4)($v1)
/* 5C9893C 8007BB74 00000000 */  nop
/* 5C98940 8007BB78 1A006018 */  blez       $v1, .Lcredits_8007BBE4
/* 5C98944 8007BB7C C0100300 */   sll       $v0, $v1, 3
/* 5C98948 8007BB80 23104300 */  subu       $v0, $v0, $v1
/* 5C9894C 8007BB84 0780033C */  lui        $v1, %hi(D_8007589C)
/* 5C98950 8007BB88 9C58638C */  lw         $v1, %lo(D_8007589C)($v1)
/* 5C98954 8007BB8C 80100200 */  sll        $v0, $v0, 2
/* 5C98958 8007BB90 21104300 */  addu       $v0, $v0, $v1
/* 5C9895C 8007BB94 E8FF4290 */  lbu        $v0, -0x18($v0)
/* 5C98960 8007BB98 00000000 */  nop
/* 5C98964 8007BB9C 11004014 */  bnez       $v0, .Lcredits_8007BBE4
/* 5C98968 8007BBA0 00000000 */   nop
/* 5C9896C 8007BBA4 21206000 */  addu       $a0, $v1, $zero
.Lcredits_8007BBA8:
/* 5C98970 8007BBA8 0780023C */  lui        $v0, %hi(D_800756E4)
/* 5C98974 8007BBAC E456428C */  lw         $v0, %lo(D_800756E4)($v0)
/* 5C98978 8007BBB0 00000000 */  nop
/* 5C9897C 8007BBB4 FFFF4324 */  addiu      $v1, $v0, -0x1
/* 5C98980 8007BBB8 0780013C */  lui        $at, %hi(D_800756E4)
/* 5C98984 8007BBBC E45623AC */  sw         $v1, %lo(D_800756E4)($at)
/* 5C98988 8007BBC0 08006018 */  blez       $v1, .Lcredits_8007BBE4
/* 5C9898C 8007BBC4 C0100300 */   sll       $v0, $v1, 3
/* 5C98990 8007BBC8 23104300 */  subu       $v0, $v0, $v1
/* 5C98994 8007BBCC 80100200 */  sll        $v0, $v0, 2
/* 5C98998 8007BBD0 21104400 */  addu       $v0, $v0, $a0
/* 5C9899C 8007BBD4 E8FF4290 */  lbu        $v0, -0x18($v0)
/* 5C989A0 8007BBD8 00000000 */  nop
/* 5C989A4 8007BBDC F2FF4010 */  beqz       $v0, .Lcredits_8007BBA8
/* 5C989A8 8007BBE0 00000000 */   nop
.Lcredits_8007BBE4:
/* 5C989AC 8007BBE4 0780033C */  lui        $v1, %hi(D_80075704)
/* 5C989B0 8007BBE8 0457638C */  lw         $v1, %lo(D_80075704)($v1)
/* 5C989B4 8007BBEC FFFF0224 */  addiu      $v0, $zero, -0x1
/* 5C989B8 8007BBF0 EA006210 */  beq        $v1, $v0, .Lcredits_8007BF9C
/* 5C989BC 8007BBF4 00000000 */   nop
/* 5C989C0 8007BBF8 12006018 */  blez       $v1, .Lcredits_8007BC44
/* 5C989C4 8007BBFC 0500622C */   sltiu     $v0, $v1, 0x5
/* 5C989C8 8007BC00 F958000C */  jal        CDLoadTime
/* 5C989CC 8007BC04 00000000 */   nop
/* 5C989D0 8007BC08 0780023C */  lui        $v0, %hi(D_80076BB8)
/* 5C989D4 8007BC0C B86B4224 */  addiu      $v0, $v0, %lo(D_80076BB8)
/* 5C989D8 8007BC10 0000428C */  lw         $v0, 0x0($v0)
/* 5C989DC 8007BC14 00000000 */  nop
/* 5C989E0 8007BC18 E0004014 */  bnez       $v0, .Lcredits_8007BF9C
/* 5C989E4 8007BC1C 01000424 */   addiu     $a0, $zero, 0x1
/* 5C989E8 8007BC20 F68E010C */  jal        CdSync
/* 5C989EC 8007BC24 21280000 */   addu      $a1, $zero, $zero
/* 5C989F0 8007BC28 02000324 */  addiu      $v1, $zero, 0x2
/* 5C989F4 8007BC2C DB004314 */  bne        $v0, $v1, .Lcredits_8007BF9C
/* 5C989F8 8007BC30 00000000 */   nop
/* 5C989FC 8007BC34 0780033C */  lui        $v1, %hi(D_80075704)
/* 5C98A00 8007BC38 0457638C */  lw         $v1, %lo(D_80075704)($v1)
/* 5C98A04 8007BC3C 00000000 */  nop
/* 5C98A08 8007BC40 0500622C */  sltiu      $v0, $v1, 0x5
.Lcredits_8007BC44:
/* 5C98A0C 8007BC44 D5004010 */  beqz       $v0, .Lcredits_8007BF9C
/* 5C98A10 8007BC48 80100300 */   sll       $v0, $v1, 2
/* 5C98A14 8007BC4C 0880013C */  lui        $at, %hi(jtbl_credits_8007AA3C)
/* 5C98A18 8007BC50 21082200 */  addu       $at, $at, $v0
/* 5C98A1C 8007BC54 3CAA228C */  lw         $v0, %lo(jtbl_credits_8007AA3C)($at)
/* 5C98A20 8007BC58 00000000 */  nop
/* 5C98A24 8007BC5C 08004000 */  jr         $v0
/* 5C98A28 8007BC60 00000000 */   nop
.L8007BC64_:
/* 5C98A2C 8007BC64 00080624 */  addiu      $a2, $zero, 0x800
/* 5C98A30 8007BC68 0780043C */  lui        $a0, %hi(D_80076B90)
/* 5C98A34 8007BC6C 906B848C */  lw         $a0, %lo(D_80076B90)($a0)
/* 5C98A38 8007BC70 0780023C */  lui        $v0, %hi(D_800757AC)
/* 5C98A3C 8007BC74 AC57428C */  lw         $v0, %lo(D_800757AC)($v0)
/* 5C98A40 8007BC78 0780053C */  lui        $a1, %hi(D_800757EC)
/* 5C98A44 8007BC7C EC57A58C */  lw         $a1, %lo(D_800757EC)($a1)
/* 5C98A48 8007BC80 C0100200 */  sll        $v0, $v0, 3
/* 5C98A4C 8007BC84 0880013C */  lui        $at, %hi(g_WadHeader + 0x290)
/* 5C98A50 8007BC88 21082200 */  addu       $at, $at, $v0
/* 5C98A54 8007BC8C 60A9278C */  lw         $a3, %lo(g_WadHeader + 0x290)($at)
/* 5C98A58 8007BC90 58020224 */  addiu      $v0, $zero, 0x258
/* 5C98A5C 8007BC94 66EF0108 */  j          .Lcredits_8007BD98
/* 5C98A60 8007BC98 1000A2AF */   sw        $v0, 0x10($sp)
.L8007BC9C_:
/* 5C98A64 8007BC9C 0780103C */  lui        $s0, %hi(g_LevelHeader)
/* 5C98A68 8007BCA0 006C1026 */  addiu      $s0, $s0, %lo(g_LevelHeader)
/* 5C98A6C 8007BCA4 21200002 */  addu       $a0, $s0, $zero
/* 5C98A70 8007BCA8 0780053C */  lui        $a1, %hi(D_800757EC)
/* 5C98A74 8007BCAC EC57A58C */  lw         $a1, %lo(D_800757EC)($a1)
/* 5C98A78 8007BCB0 565A000C */  jal        Memcpy
/* 5C98A7C 8007BCB4 D0010624 */   addiu     $a2, $zero, 0x1D0
/* 5C98A80 8007BCB8 0200063C */  lui        $a2, (0x20000 >> 16)
/* 5C98A84 8007BCBC 0780043C */  lui        $a0, %hi(D_80076B90)
/* 5C98A88 8007BCC0 906B848C */  lw         $a0, %lo(D_80076B90)($a0)
/* 5C98A8C 8007BCC4 0780053C */  lui        $a1, %hi(D_800757EC)
/* 5C98A90 8007BCC8 EC57A58C */  lw         $a1, %lo(D_800757EC)($a1)
/* 5C98A94 8007BCCC 0780023C */  lui        $v0, %hi(D_800757AC)
/* 5C98A98 8007BCD0 AC57428C */  lw         $v0, %lo(D_800757AC)($v0)
/* 5C98A9C 8007BCD4 0000038E */  lw         $v1, 0x0($s0)
/* 5C98AA0 8007BCD8 C0100200 */  sll        $v0, $v0, 3
/* 5C98AA4 8007BCDC 0880013C */  lui        $at, %hi(g_WadHeader + 0x290)
/* 5C98AA8 8007BCE0 21082200 */  addu       $at, $at, $v0
/* 5C98AAC 8007BCE4 60A9278C */  lw         $a3, %lo(g_WadHeader + 0x290)($at)
/* 5C98AB0 8007BCE8 58020224 */  addiu      $v0, $zero, 0x258
/* 5C98AB4 8007BCEC 65EF0108 */  j          .Lcredits_8007BD94
/* 5C98AB8 8007BCF0 1000A2AF */   sw        $v0, 0x10($sp)
.L8007BCF4_:
/* 5C98ABC 8007BCF4 21200000 */  addu       $a0, $zero, $zero
/* 5C98AC0 8007BCF8 00020324 */  addiu      $v1, $zero, 0x200
/* 5C98AC4 8007BCFC 80010224 */  addiu      $v0, $zero, 0x180
/* 5C98AC8 8007BD00 2200A2A7 */  sh         $v0, 0x22($sp)
/* 5C98ACC 8007BD04 80000224 */  addiu      $v0, $zero, 0x80
/* 5C98AD0 8007BD08 2000A3A7 */  sh         $v1, 0x20($sp)
/* 5C98AD4 8007BD0C 2400A3A7 */  sh         $v1, 0x24($sp)
/* 5C98AD8 8007BD10 D97D010C */  jal        DrawSync
/* 5C98ADC 8007BD14 2600A2A7 */   sh        $v0, 0x26($sp)
/* 5C98AE0 8007BD18 0780053C */  lui        $a1, %hi(D_800757EC)
/* 5C98AE4 8007BD1C EC57A58C */  lw         $a1, %lo(D_800757EC)($a1)
/* 5C98AE8 8007BD20 8A7E010C */  jal        LoadImage
/* 5C98AEC 8007BD24 2000A427 */   addiu     $a0, $sp, 0x20
/* 5C98AF0 8007BD28 D97D010C */  jal        DrawSync
/* 5C98AF4 8007BD2C 21200000 */   addu      $a0, $zero, $zero
/* 5C98AF8 8007BD30 0400033C */  lui        $v1, (0x40000 >> 16)
/* 5C98AFC 8007BD34 0780053C */  lui        $a1, %hi(D_800757EC)
/* 5C98B00 8007BD38 EC57A58C */  lw         $a1, %lo(D_800757EC)($a1)
/* 5C98B04 8007BD3C 0780043C */  lui        $a0, %hi(D_80076B90)
/* 5C98B08 8007BD40 906B848C */  lw         $a0, %lo(D_80076B90)($a0)
/* 5C98B0C 8007BD44 0780023C */  lui        $v0, %hi(g_LevelHeader + 0x1C)
/* 5C98B10 8007BD48 1C6C428C */  lw         $v0, %lo(g_LevelHeader + 0x1C)($v0)
/* 5C98B14 8007BD4C 0780063C */  lui        $a2, %hi(g_LevelHeader + 0xC)
/* 5C98B18 8007BD50 0C6CC68C */  lw         $a2, %lo(g_LevelHeader + 0xC)($a2)
/* 5C98B1C 8007BD54 21104300 */  addu       $v0, $v0, $v1
/* 5C98B20 8007BD58 2130C200 */  addu       $a2, $a2, $v0
/* 5C98B24 8007BD5C 0780023C */  lui        $v0, %hi(D_800757AC)
/* 5C98B28 8007BD60 AC57428C */  lw         $v0, %lo(D_800757AC)($v0)
/* 5C98B2C 8007BD64 0780033C */  lui        $v1, %hi(g_LevelHeader)
/* 5C98B30 8007BD68 006C638C */  lw         $v1, %lo(g_LevelHeader)($v1)
/* 5C98B34 8007BD6C 0780013C */  lui        $at, %hi(D_80075958)
/* 5C98B38 8007BD70 585926AC */  sw         $a2, %lo(D_80075958)($at)
/* 5C98B3C 8007BD74 C0100200 */  sll        $v0, $v0, 3
/* 5C98B40 8007BD78 0880013C */  lui        $at, %hi(g_WadHeader + 0x290)
/* 5C98B44 8007BD7C 21082200 */  addu       $at, $at, $v0
/* 5C98B48 8007BD80 60A9278C */  lw         $a3, %lo(g_WadHeader + 0x290)($at)
/* 5C98B4C 8007BD84 58020224 */  addiu      $v0, $zero, 0x258
/* 5C98B50 8007BD88 1000A2AF */  sw         $v0, 0x10($sp)
/* 5C98B54 8007BD8C 21186700 */  addu       $v1, $v1, $a3
/* 5C98B58 8007BD90 0200073C */  lui        $a3, (0x20000 >> 16)
.Lcredits_8007BD94:
/* 5C98B5C 8007BD94 21386700 */  addu       $a3, $v1, $a3
.Lcredits_8007BD98:
/* 5C98B60 8007BD98 A659000C */  jal        CDLoadAsync
/* 5C98B64 8007BD9C 00000000 */   nop
/* 5C98B68 8007BDA0 0780023C */  lui        $v0, %hi(D_80075704)
/* 5C98B6C 8007BDA4 0457428C */  lw         $v0, %lo(D_80075704)($v0)
/* 5C98B70 8007BDA8 00000000 */  nop
/* 5C98B74 8007BDAC 01004224 */  addiu      $v0, $v0, 0x1
/* 5C98B78 8007BDB0 0780013C */  lui        $at, %hi(D_80075704)
/* 5C98B7C 8007BDB4 045722AC */  sw         $v0, %lo(D_80075704)($at)
/* 5C98B80 8007BDB8 E7EF0108 */  j          .Lcredits_8007BF9C
/* 5C98B84 8007BDBC 00000000 */   nop
.L8007BDC0_:
/* 5C98B88 8007BDC0 0780013C */  lui        $at, %hi(D_8007576C)
/* 5C98B8C 8007BDC4 6C5720AC */  sw         $zero, %lo(D_8007576C)($at)
/* 5C98B90 8007BDC8 E7EF0108 */  j          .Lcredits_8007BF9C
/* 5C98B94 8007BDCC 00000000 */   nop
.L8007BDD0_:
/* 5C98B98 8007BDD0 00021124 */  addiu      $s1, $zero, 0x200
/* 5C98B9C 8007BDD4 80001224 */  addiu      $s2, $zero, 0x80
/* 5C98BA0 8007BDD8 0780033C */  lui        $v1, %hi(D_80075768)
/* 5C98BA4 8007BDDC 6857638C */  lw         $v1, %lo(D_80075768)($v1)
/* 5C98BA8 8007BDE0 00010224 */  addiu      $v0, $zero, 0x100
/* 5C98BAC 8007BDE4 2800B1A7 */  sh         $s1, 0x28($sp)
/* 5C98BB0 8007BDE8 2A00B2A7 */  sh         $s2, 0x2A($sp)
/* 5C98BB4 8007BDEC 2C00B1A7 */  sh         $s1, 0x2C($sp)
/* 5C98BB8 8007BDF0 2E00A2A7 */  sh         $v0, 0x2E($sp)
/* 5C98BBC 8007BDF4 0880013C */  lui        $at, %hi(D_800785D8)
/* 5C98BC0 8007BDF8 D88523AC */  sw         $v1, %lo(D_800785D8)($at)
/* 5C98BC4 8007BDFC 0880013C */  lui        $at, %hi(D_800785DC)
/* 5C98BC8 8007BE00 DC8523AC */  sw         $v1, %lo(D_800785DC)($at)
/* 5C98BCC 8007BE04 D97D010C */  jal        DrawSync
/* 5C98BD0 8007BE08 21200000 */   addu      $a0, $zero, $zero
/* 5C98BD4 8007BE0C 2800B027 */  addiu      $s0, $sp, 0x28
/* 5C98BD8 8007BE10 0780053C */  lui        $a1, %hi(D_800757EC)
/* 5C98BDC 8007BE14 EC57A58C */  lw         $a1, %lo(D_800757EC)($a1)
/* 5C98BE0 8007BE18 8A7E010C */  jal        LoadImage
/* 5C98BE4 8007BE1C 21200002 */   addu      $a0, $s0, $zero
/* 5C98BE8 8007BE20 21200002 */  addu       $a0, $s0, $zero
/* 5C98BEC 8007BE24 00020524 */  addiu      $a1, $zero, 0x200
/* 5C98BF0 8007BE28 21300000 */  addu       $a2, $zero, $zero
/* 5C98BF4 8007BE2C 80010224 */  addiu      $v0, $zero, 0x180
/* 5C98BF8 8007BE30 2800B1A7 */  sh         $s1, 0x28($sp)
/* 5C98BFC 8007BE34 2A00A2A7 */  sh         $v0, 0x2A($sp)
/* 5C98C00 8007BE38 2C00B1A7 */  sh         $s1, 0x2C($sp)
/* 5C98C04 8007BE3C BC7E010C */  jal        MoveImage
/* 5C98C08 8007BE40 2E00B2A7 */   sh        $s2, 0x2E($sp)
/* 5C98C0C 8007BE44 D97D010C */  jal        DrawSync
/* 5C98C10 8007BE48 21200000 */   addu      $a0, $zero, $zero
/* 5C98C14 8007BE4C 0400103C */  lui        $s0, (0x40000 >> 16)
/* 5C98C18 8007BE50 0780043C */  lui        $a0, %hi(D_80075768)
/* 5C98C1C 8007BE54 6857848C */  lw         $a0, %lo(D_80075768)($a0)
/* 5C98C20 8007BE58 0780053C */  lui        $a1, %hi(D_800757EC)
/* 5C98C24 8007BE5C EC57A58C */  lw         $a1, %lo(D_800757EC)($a1)
/* 5C98C28 8007BE60 0780063C */  lui        $a2, %hi(D_80075958)
/* 5C98C2C 8007BE64 5859C68C */  lw         $a2, %lo(D_80075958)($a2)
/* 5C98C30 8007BE68 2128B000 */  addu       $a1, $a1, $s0
/* 5C98C34 8007BE6C 565A000C */  jal        Memcpy
/* 5C98C38 8007BE70 2330D000 */   subu      $a2, $a2, $s0
/* 5C98C3C 8007BE74 0780023C */  lui        $v0, %hi(D_80075768)
/* 5C98C40 8007BE78 6857428C */  lw         $v0, %lo(D_80075768)($v0)
/* 5C98C44 8007BE7C 0780033C */  lui        $v1, %hi(D_80075958)
/* 5C98C48 8007BE80 5859638C */  lw         $v1, %lo(D_80075958)($v1)
/* 5C98C4C 8007BE84 0880043C */  lui        $a0, %hi(D_800785DC)
/* 5C98C50 8007BE88 DC85848C */  lw         $a0, %lo(D_800785DC)($a0)
/* 5C98C54 8007BE8C 21104300 */  addu       $v0, $v0, $v1
/* 5C98C58 8007BE90 23105000 */  subu       $v0, $v0, $s0
/* 5C98C5C 8007BE94 0780013C */  lui        $at, %hi(D_800757EC)
/* 5C98C60 8007BE98 EC5722AC */  sw         $v0, %lo(D_800757EC)($at)
/* 5C98C64 8007BE9C 564B000C */  jal        func_80012D58
/* 5C98C68 8007BEA0 01000524 */   addiu     $a1, $zero, 0x1
/* 5C98C6C 8007BEA4 6666033C */  lui        $v1, (0x66666667 >> 16)
/* 5C98C70 8007BEA8 0780043C */  lui        $a0, %hi(D_800757AC)
/* 5C98C74 8007BEAC AC57848C */  lw         $a0, %lo(D_800757AC)($a0)
/* 5C98C78 8007BEB0 67666334 */  ori        $v1, $v1, (0x66666667 & 0xFFFF)
/* 5C98C7C 8007BEB4 0880013C */  lui        $at, %hi(D_800785E0)
/* 5C98C80 8007BEB8 E08522AC */  sw         $v0, %lo(D_800785E0)($at)
/* 5C98C84 8007BEBC 18008300 */  mult       $a0, $v1
/* 5C98C88 8007BEC0 0880023C */  lui        $v0, %hi(D_800785DC)
/* 5C98C8C 8007BEC4 DC85428C */  lw         $v0, %lo(D_800785DC)($v0)
/* 5C98C90 8007BEC8 0780073C */  lui        $a3, %hi(D_80077780)
/* 5C98C94 8007BECC 8077E724 */  addiu      $a3, $a3, %lo(D_80077780)
/* 5C98C98 8007BED0 0880063C */  lui        $a2, %hi(D_80078A40)
/* 5C98C9C 8007BED4 408AC624 */  addiu      $a2, $a2, %lo(D_80078A40)
/* 5C98CA0 8007BED8 0000E38C */  lw         $v1, 0x0($a3)
/* 5C98CA4 8007BEDC 0400E58C */  lw         $a1, 0x4($a3)
/* 5C98CA8 8007BEE0 0000C3AC */  sw         $v1, 0x0($a2)
/* 5C98CAC 8007BEE4 0400C5AC */  sw         $a1, 0x4($a2)
/* 5C98CB0 8007BEE8 0800E38C */  lw         $v1, 0x8($a3)
/* 5C98CB4 8007BEEC 0C00E58C */  lw         $a1, 0xC($a3)
/* 5C98CB8 8007BEF0 0800C3AC */  sw         $v1, 0x8($a2)
/* 5C98CBC 8007BEF4 0C00C5AC */  sw         $a1, 0xC($a2)
/* 5C98CC0 8007BEF8 1000E38C */  lw         $v1, 0x10($a3)
/* 5C98CC4 8007BEFC 00000000 */  nop
/* 5C98CC8 8007BF00 1000C3AC */  sw         $v1, 0x10($a2)
/* 5C98CCC 8007BF04 0780033C */  lui        $v1, %hi(g_LevelHeader + 0xC)
/* 5C98CD0 8007BF08 0C6C638C */  lw         $v1, %lo(g_LevelHeader + 0xC)($v1)
/* 5C98CD4 8007BF0C 0780053C */  lui        $a1, %hi(g_LevelHeader + 0x1C)
/* 5C98CD8 8007BF10 1C6CA58C */  lw         $a1, %lo(g_LevelHeader + 0x1C)($a1)
/* 5C98CDC 8007BF14 0780063C */  lui        $a2, %hi(g_LevelHeader + 0x18)
/* 5C98CE0 8007BF18 186CC68C */  lw         $a2, %lo(g_LevelHeader + 0x18)($a2)
/* 5C98CE4 8007BF1C 21104300 */  addu       $v0, $v0, $v1
/* 5C98CE8 8007BF20 0880013C */  lui        $at, %hi(D_800785E4)
/* 5C98CEC 8007BF24 E48522AC */  sw         $v0, %lo(D_800785E4)($at)
/* 5C98CF0 8007BF28 0780013C */  lui        $at, %hi(D_800757BC)
/* 5C98CF4 8007BF2C BC5722AC */  sw         $v0, %lo(D_800757BC)($at)
/* 5C98CF8 8007BF30 C3170400 */  sra        $v0, $a0, 31
/* 5C98CFC 8007BF34 0880013C */  lui        $at, %hi(D_80078604)
/* 5C98D00 8007BF38 048625AC */  sw         $a1, %lo(D_80078604)($at)
/* 5C98D04 8007BF3C 0880013C */  lui        $at, %hi(D_80078600)
/* 5C98D08 8007BF40 008626AC */  sw         $a2, %lo(D_80078600)($at)
/* 5C98D0C 8007BF44 10580000 */  mfhi       $t3
/* 5C98D10 8007BF48 83180B00 */  sra        $v1, $t3, 2
/* 5C98D14 8007BF4C 23186200 */  subu       $v1, $v1, $v0
/* 5C98D18 8007BF50 80100300 */  sll        $v0, $v1, 2
/* 5C98D1C 8007BF54 21104300 */  addu       $v0, $v0, $v1
/* 5C98D20 8007BF58 40100200 */  sll        $v0, $v0, 1
/* 5C98D24 8007BF5C 23208200 */  subu       $a0, $a0, $v0
/* 5C98D28 8007BF60 09008428 */  slti       $a0, $a0, 0x9
/* 5C98D2C 8007BF64 05008010 */  beqz       $a0, .Lcredits_8007BF7C
/* 5C98D30 8007BF68 03000224 */   addiu     $v0, $zero, 0x3
/* 5C98D34 8007BF6C 0780013C */  lui        $at, %hi(D_80075704)
/* 5C98D38 8007BF70 045720AC */  sw         $zero, %lo(D_80075704)($at)
/* 5C98D3C 8007BF74 E1EF0108 */  j          .Lcredits_8007BF84
/* 5C98D40 8007BF78 00000000 */   nop
.Lcredits_8007BF7C:
/* 5C98D44 8007BF7C 0780013C */  lui        $at, %hi(D_80075704)
/* 5C98D48 8007BF80 045722AC */  sw         $v0, %lo(D_80075704)($at)
.Lcredits_8007BF84:
/* 5C98D4C 8007BF84 0780023C */  lui        $v0, %hi(D_800757AC)
/* 5C98D50 8007BF88 AC57428C */  lw         $v0, %lo(D_800757AC)($v0)
/* 5C98D54 8007BF8C 00000000 */  nop
/* 5C98D58 8007BF90 01004224 */  addiu      $v0, $v0, 0x1
/* 5C98D5C 8007BF94 0780013C */  lui        $at, %hi(D_800757AC)
/* 5C98D60 8007BF98 AC5722AC */  sw         $v0, %lo(D_800757AC)($at)
.Lcredits_8007BF9C:
/* 5C98D64 8007BF9C 8400BF8F */  lw         $ra, 0x84($sp)
/* 5C98D68 8007BFA0 8000BE8F */  lw         $fp, 0x80($sp)
/* 5C98D6C 8007BFA4 7C00B78F */  lw         $s7, 0x7C($sp)
/* 5C98D70 8007BFA8 7800B68F */  lw         $s6, 0x78($sp)
/* 5C98D74 8007BFAC 7400B58F */  lw         $s5, 0x74($sp)
/* 5C98D78 8007BFB0 7000B48F */  lw         $s4, 0x70($sp)
/* 5C98D7C 8007BFB4 6C00B38F */  lw         $s3, 0x6C($sp)
/* 5C98D80 8007BFB8 6800B28F */  lw         $s2, 0x68($sp)
/* 5C98D84 8007BFBC 6400B18F */  lw         $s1, 0x64($sp)
/* 5C98D88 8007BFC0 6000B08F */  lw         $s0, 0x60($sp)
/* 5C98D8C 8007BFC4 8800BD27 */  addiu      $sp, $sp, 0x88
/* 5C98D90 8007BFC8 0800E003 */  jr         $ra
/* 5C98D94 8007BFCC 00000000 */   nop
.size func_credits_8007AA50, . - func_credits_8007AA50
