#ifndef LEVEL_31_PARTICLE_CONFIG_H
#define LEVEL_31_PARTICLE_CONFIG_H

#define LEVEL 31

#define HAS_PARTICLE_0
#define HAS_PARTICLE_1
#define HAS_PARTICLE_2
#define HAS_PARTICLE_4
#define HAS_PARTICLE_5
#define HAS_PARTICLE_8
#define HAS_PARTICLE_9
#define HAS_PARTICLE_10
#define HAS_PARTICLE_11
#define HAS_PARTICLE_12
#define HAS_PARTICLE_16
#define HAS_PARTICLE_17
#define HAS_PARTICLE_21
#define HAS_PARTICLE_22
#define HAS_PARTICLE_24
#define HAS_PARTICLE_33
#define HAS_PARTICLE_66
#define HAS_PARTICLE_70
#define HAS_PARTICLE_71
#define HAS_PARTICLE_72
#define HAS_PARTICLE_76
#define HAS_PARTICLE_77
#define HAS_PARTICLE_78
#define HAS_PARTICLE_79
#define HAS_PARTICLE_80

#endif
