.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 2
dlabel D_level_35_8007AA3C
/* 33DF804 8007AA3C */ .asciz "......"
.align 2
.size D_level_35_8007AA3C, . - D_level_35_8007AA3C

.align 2
dlabel D_level_35_8007AA44
/* 33DF80C 8007AA44 */ .asciz "%d %02d.%02d"
.align 2
.size D_level_35_8007AA44, . - D_level_35_8007AA44

.align 2
dlabel D_level_35_8007AA54
/* 33DF81C 8007AA54 */ .asciz "%d.%02d"
.align 2
.size D_level_35_8007AA54, . - D_level_35_8007AA54

.align 2
dlabel D_level_35_8007AA5C
/* 33DF824 8007AA5C */ .asciz "."
.align 2
.size D_level_35_8007AA5C, . - D_level_35_8007AA5C


.section .text
/* Generated by spimdisasm 1.27.0 */

glabel func_level_35_8007B4B0
/* 33E0278 8007B4B0 C0FFBD27 */  addiu      $sp, $sp, -0x40
/* 33E027C 8007B4B4 2C00B1AF */  sw         $s1, 0x2C($sp)
/* 33E0280 8007B4B8 2188A000 */  addu       $s1, $a1, $zero
/* 33E0284 8007B4BC 3400B3AF */  sw         $s3, 0x34($sp)
/* 33E0288 8007B4C0 2198C000 */  addu       $s3, $a2, $zero
/* 33E028C 8007B4C4 3800BFAF */  sw         $ra, 0x38($sp)
/* 33E0290 8007B4C8 3000B2AF */  sw         $s2, 0x30($sp)
/* 33E0294 8007B4CC 0E008104 */  bgez       $a0, .Llevel_35_8007B508
/* 33E0298 8007B4D0 2800B0AF */   sw        $s0, 0x28($sp)
/* 33E029C 8007B4D4 0880043C */  lui        $a0, %hi(D_level_35_8007AA3C)
/* 33E02A0 8007B4D8 3CAA8424 */  addiu      $a0, $a0, %lo(D_level_35_8007AA3C)
/* 33E02A4 8007B4DC 12000624 */  addiu      $a2, $zero, 0x12
/* 33E02A8 8007B4E0 21386002 */  addu       $a3, $s3, $zero
/* 33E02AC 8007B4E4 0000A28C */  lw         $v0, 0x0($a1)
/* 33E02B0 8007B4E8 0400A38C */  lw         $v1, 0x4($a1)
/* 33E02B4 8007B4EC CAFF4224 */  addiu      $v0, $v0, -0x36
/* 33E02B8 8007B4F0 FBFF6324 */  addiu      $v1, $v1, -0x5
/* 33E02BC 8007B4F4 0000A2AC */  sw         $v0, 0x0($a1)
/* 33E02C0 8007B4F8 F95F000C */  jal        func_80017FE4
/* 33E02C4 8007B4FC 0400A3AC */   sw        $v1, 0x4($a1)
/* 33E02C8 8007B500 9BED0108 */  j          .Llevel_35_8007B66C
/* 33E02CC 8007B504 06000224 */   addiu     $v0, $zero, 0x6
.Llevel_35_8007B508:
/* 33E02D0 8007B508 4E1B023C */  lui        $v0, (0x1B4E81B5 >> 16)
/* 33E02D4 8007B50C B5814234 */  ori        $v0, $v0, (0x1B4E81B5 & 0xFFFF)
/* 33E02D8 8007B510 18008200 */  mult       $a0, $v0
/* 33E02DC 8007B514 10480000 */  mfhi       $t1
/* 33E02E0 8007B518 AA2A023C */  lui        $v0, (0x2AAAAAAB >> 16)
/* 33E02E4 8007B51C ABAA4234 */  ori        $v0, $v0, (0x2AAAAAAB & 0xFFFF)
/* 33E02E8 8007B520 18008200 */  mult       $a0, $v0
/* 33E02EC 8007B524 10280000 */  mfhi       $a1
/* 33E02F0 8007B528 8274023C */  lui        $v0, (0x7482296B >> 16)
/* 33E02F4 8007B52C 6B294234 */  ori        $v0, $v0, (0x7482296B & 0xFFFF)
/* 33E02F8 8007B530 18008200 */  mult       $a0, $v0
/* 33E02FC 8007B534 C31F0400 */  sra        $v1, $a0, 31
/* 33E0300 8007B538 83210900 */  sra        $a0, $t1, 6
/* 33E0304 8007B53C 23208300 */  subu       $a0, $a0, $v1
/* 33E0308 8007B540 21388000 */  addu       $a3, $a0, $zero
/* 33E030C 8007B544 2328A300 */  subu       $a1, $a1, $v1
/* 33E0310 8007B548 40100700 */  sll        $v0, $a3, 1
/* 33E0314 8007B54C 21104700 */  addu       $v0, $v0, $a3
/* 33E0318 8007B550 C0100200 */  sll        $v0, $v0, 3
/* 33E031C 8007B554 21104700 */  addu       $v0, $v0, $a3
/* 33E0320 8007B558 80100200 */  sll        $v0, $v0, 2
/* 33E0324 8007B55C 2338A200 */  subu       $a3, $a1, $v0
/* 33E0328 8007B560 10300000 */  mfhi       $a2
/* 33E032C 8007B564 83130600 */  sra        $v0, $a2, 14
/* 33E0330 8007B568 23804300 */  subu       $s0, $v0, $v1
/* 33E0334 8007B56C 00111000 */  sll        $v0, $s0, 4
/* 33E0338 8007B570 23105000 */  subu       $v0, $v0, $s0
/* 33E033C 8007B574 80100200 */  sll        $v0, $v0, 2
/* 33E0340 8007B578 0A000012 */  beqz       $s0, .Llevel_35_8007B5A4
/* 33E0344 8007B57C 23108200 */   subu      $v0, $a0, $v0
/* 33E0348 8007B580 1000A7AF */  sw         $a3, 0x10($sp)
/* 33E034C 8007B584 1800A427 */  addiu      $a0, $sp, 0x18
/* 33E0350 8007B588 0880053C */  lui        $a1, %hi(D_level_35_8007AA44)
/* 33E0354 8007B58C 44AAA524 */  addiu      $a1, $a1, %lo(D_level_35_8007AA44)
/* 33E0358 8007B590 21300002 */  addu       $a2, $s0, $zero
/* 33E035C 8007B594 F58B010C */  jal        sprintf
/* 33E0360 8007B598 21384000 */   addu      $a3, $v0, $zero
/* 33E0364 8007B59C 6EED0108 */  j          .Llevel_35_8007B5B8
/* 33E0368 8007B5A0 00000000 */   nop
.Llevel_35_8007B5A4:
/* 33E036C 8007B5A4 1800A427 */  addiu      $a0, $sp, 0x18
/* 33E0370 8007B5A8 0880053C */  lui        $a1, %hi(D_level_35_8007AA54)
/* 33E0374 8007B5AC 54AAA524 */  addiu      $a1, $a1, %lo(D_level_35_8007AA54)
/* 33E0378 8007B5B0 F58B010C */  jal        sprintf
/* 33E037C 8007B5B4 21304000 */   addu      $a2, $v0, $zero
.Llevel_35_8007B5B8:
/* 33E0380 8007B5B8 DB89010C */  jal        strlen
/* 33E0384 8007B5BC 1800A427 */   addiu     $a0, $sp, 0x18
/* 33E0388 8007B5C0 21904000 */  addu       $s2, $v0, $zero
/* 33E038C 8007B5C4 1800A427 */  addiu      $a0, $sp, 0x18
/* 33E0390 8007B5C8 21282002 */  addu       $a1, $s1, $zero
/* 33E0394 8007B5CC 12000624 */  addiu      $a2, $zero, 0x12
/* 33E0398 8007B5D0 21386002 */  addu       $a3, $s3, $zero
/* 33E039C 8007B5D4 C0101200 */  sll        $v0, $s2, 3
/* 33E03A0 8007B5D8 0000238E */  lw         $v1, 0x0($s1)
/* 33E03A4 8007B5DC 21105200 */  addu       $v0, $v0, $s2
/* 33E03A8 8007B5E0 23186200 */  subu       $v1, $v1, $v0
/* 33E03AC 8007B5E4 F95F000C */  jal        func_80017FE4
/* 33E03B0 8007B5E8 000023AE */   sw        $v1, 0x0($s1)
/* 33E03B4 8007B5EC 1E000012 */  beqz       $s0, .Llevel_35_8007B668
/* 33E03B8 8007B5F0 21282002 */   addu      $a1, $s1, $zero
/* 33E03BC 8007B5F4 0880103C */  lui        $s0, %hi(D_level_35_8007AA5C)
/* 33E03C0 8007B5F8 5CAA1026 */  addiu      $s0, $s0, %lo(D_level_35_8007AA5C)
/* 33E03C4 8007B5FC 21200002 */  addu       $a0, $s0, $zero
/* 33E03C8 8007B600 12000624 */  addiu      $a2, $zero, 0x12
/* 33E03CC 8007B604 21386002 */  addu       $a3, $s3, $zero
/* 33E03D0 8007B608 0000228E */  lw         $v0, 0x0($s1)
/* 33E03D4 8007B60C 01005226 */  addiu      $s2, $s2, 0x1
/* 33E03D8 8007B610 94FF4224 */  addiu      $v0, $v0, -0x6C
/* 33E03DC 8007B614 000022AE */  sw         $v0, 0x0($s1)
/* 33E03E0 8007B618 0400228E */  lw         $v0, 0x4($s1)
/* 33E03E4 8007B61C 0800238E */  lw         $v1, 0x8($s1)
/* 33E03E8 8007B620 01004224 */  addiu      $v0, $v0, 0x1
/* 33E03EC 8007B624 040022AE */  sw         $v0, 0x4($s1)
/* 33E03F0 8007B628 40100300 */  sll        $v0, $v1, 1
/* 33E03F4 8007B62C 21104300 */  addu       $v0, $v0, $v1
/* 33E03F8 8007B630 43100200 */  sra        $v0, $v0, 1
/* 33E03FC 8007B634 F95F000C */  jal        func_80017FE4
/* 33E0400 8007B638 080022AE */   sw        $v0, 0x8($s1)
/* 33E0404 8007B63C 21200002 */  addu       $a0, $s0, $zero
/* 33E0408 8007B640 21282002 */  addu       $a1, $s1, $zero
/* 33E040C 8007B644 12000624 */  addiu      $a2, $zero, 0x12
/* 33E0410 8007B648 21386002 */  addu       $a3, $s3, $zero
/* 33E0414 8007B64C 0000A28C */  lw         $v0, 0x0($a1)
/* 33E0418 8007B650 0400A38C */  lw         $v1, 0x4($a1)
/* 33E041C 8007B654 EEFF4224 */  addiu      $v0, $v0, -0x12
/* 33E0420 8007B658 F8FF6324 */  addiu      $v1, $v1, -0x8
/* 33E0424 8007B65C 0000A2AC */  sw         $v0, 0x0($a1)
/* 33E0428 8007B660 F95F000C */  jal        func_80017FE4
/* 33E042C 8007B664 0400A3AC */   sw        $v1, 0x4($a1)
.Llevel_35_8007B668:
/* 33E0430 8007B668 21104002 */  addu       $v0, $s2, $zero
.Llevel_35_8007B66C:
/* 33E0434 8007B66C 3800BF8F */  lw         $ra, 0x38($sp)
/* 33E0438 8007B670 3400B38F */  lw         $s3, 0x34($sp)
/* 33E043C 8007B674 3000B28F */  lw         $s2, 0x30($sp)
/* 33E0440 8007B678 2C00B18F */  lw         $s1, 0x2C($sp)
/* 33E0444 8007B67C 2800B08F */  lw         $s0, 0x28($sp)
/* 33E0448 8007B680 4000BD27 */  addiu      $sp, $sp, 0x40
/* 33E044C 8007B684 0800E003 */  jr         $ra
/* 33E0450 8007B688 00000000 */   nop
.size func_level_35_8007B4B0, . - func_level_35_8007B4B0
